### ISSUE TITLE
Invalid build warning: Cannot build selected target ABI...

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#1002]
#### Chaquopy version

14.0.2

#### Relevant parts of your build.gradle file

```groovy
ndk {
    abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
}

python {
    version "3.8"

    pip {
        options "--extra-index-url", rootProject.projectDir.toString() + "/wheels"
    }

    pyc {
        stdlib true
        pip true
        src true
    }
}
```

#### Describe your issue

I get warnings saying that it can't build selected target ABI, but everything works as expected
![image](https://github.com/chaquo/chaquopy/assets/67378443/f99c170e-73e3-4db7-938a-45fbb919cb82)

**Comment by mhsmith** [comment]
This message doesn't come from Chaquopy, so it must be caused by something else in your build.gradle file. Are you using the [`splits`](https://developer.android.com/build/configure-apk-splits#configure-abi-split) feature?

**Comment by IsakTheHacker** [comment]
Not using splits, just build variants as described in the  [Chaquopy FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size)

**Comment by mhsmith** [comment]
OK, can you upload your project to GitHub, or a simplified version that reproduces the same problem?

**Comment by mhsmith** [comment]
If you still need help, please upload your project as mentioned above, and I'll reopen the issue.
