### ISSUE TITLE
PermissionError: [WinError 5] when renaming arm64-v8a\tensorboard -> common\tensorboard

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#1006]
_Originally posted by @basaris in https://github.com/chaquo/chaquopy/issues/374#issuecomment-1781332793_

-----
            
When I am trying to pip install tensorflow in my react-native app, it crashes and an error like this occurs:

Traceback (most recent call last):
  File "C:\Users\bill\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bill\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 366, in <module>
    PipInstall().main()
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 60, in main
    self.move_pure([ri.tree for ri in req_infos if ri.is_pure], abi, abi_trees[abi])
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 179, in move_pure
    self.move_to_common(abi, path)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 206, in move_to_common
    renames(abi_filename, common_filename)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 53, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 217, in call
    raise attempt.get()
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 252, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\six.py", line 703, in reraise
    raise value
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 204, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 303, in renames
    os.renames(src, dst)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python38\lib\os.py", line 270, in renames
    rename(old, new)
PermissionError: [WinError 5] ��� ����������� � ��������: 'C:\\Users\\bill\\Desktop\\react-native\\MapAdapt\\android\\app\\build\\pip\\debug\\arm64-v8a\\tensorboard' -> 'C:\\Users\\bill\\Desktop\\react-native\\MapAdapt\\android\\app\\build\\pip\\debug\\common\\tensorboard'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/bill/AppData/Local/Programs/Python/Python38/python.exe'' finished with non-zero exit value 1

Any idea why it crashes? Any help? When I pip install other libraries like numpy or scipy it loads fine. Please help.

**Comment by mhsmith** [comment]
Please post the Chaquopy-related parts of your top-level and module-level build.gradle files.

The full TensorFlow package is quite large and not very convenient for mobile use, so one possible workaround is to use tflite_runtime instead, as mentioned in the [FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size).

**Comment by basaris** [comment]
Top level build.gradle:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.chaquo.python:gradle:14.0.2")
    }
    
}

module-level build.gradle:

pply plugin: "com.android.application"
apply plugin: "com.facebook.react"
apply plugin: "com.chaquo.python"


react {

}



def enableProguardInReleaseBuilds = false


def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.mapadapt"
    defaultConfig {
        applicationId "com.mapadapt"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            version "3.8"
        }
        python {
            buildPython "C:/Users/bill/AppData/Local/Programs/Python/Python38/python.exe"
        }
        python {
            pip {
                // install "numpy"
                // install "tqdm"
                install "tensorflow"
                // install "pathlib"
                // install "dill"
                // install "natsort"
                // install "scipy"
                // install "scikit-learn"
                // install "librosa"

            }
        }
    }
    sourceSets {
        main {
            python.srcDir "src/main/python"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

**Comment by mhsmith** [comment]
On Windows, a PermissionError when renaming usually means the file is open. I've seen similar issues before involving anti-virus software automatically scanning every new file, but the `retrying` decorator has always been good enough to work around them until now.

Try excluding the `app\build` directory from your anti-virus's real-time scanning.

**Comment by mhsmith** [comment]
I hope you managed to solve your problem. If you have any more issues in this area, please post a comment, and I'll reopen the issue.
