### ISSUE TITLE
Failed to install numpy from BellsAnalyzer==1.0.1

### ISSUE THREAD

**Issue by alirezarabiei7239** [chaquo/chaquopy#1008]
#### Chaquopy version
14.0.2

 Complete output (2 lines):
    
    meson-python: error: Could not find ninja version 1.8.2 or newer.
    ----------------------------------------
ERROR: Failed to install numpy from https://files.pythonhosted.org/packages/78/23/f78fd8311e0f710fe1d065d50b92ce0057fe877b8ed7fd41b28ad6865bfc/numpy-1.26.1.tar.gz#sha256=c8c6c72d4a9f831f328efb1312642a1cafafaa88981d9ab76368d50d07d93cbe (from BellsAnalyzer==1.0.1->-r requirements.txt (line 3)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by IsakTheHacker** [comment]
For Python 3.8, the newest precompiled numpy wheel is for version `1.19.5`. If you are using Python 3.9 or Python 3.10, the newest version of numpy they support is `1.23.3`. Try those numpy versions instead!

**Comment by mhsmith** [comment]
There's no package called BellsAnalyzer on PyPI, and from this fragment of the log, it's unclear why it's attempting to install this version of NumPy. If you still need help, please post:

* The COMPLETE build log (click the “Build: failed” caption to the left of the message)
* The `pip` section of your build.gradle file
* Your requirements.txt file

**Comment by mhsmith** [comment]
If this is still a problem, please post the requested information, and I'll reopen the issue.
