### ISSUE TITLE
how to install numpy 1.23.3 in python 3.8

### ISSUE THREAD

**Issue by MoonLight1202** [chaquo/chaquopy#1013]
python {
            pip {
                install "numpy" 
                install "seaborn"

            }
}
 And I encountered an error: seaborn 0.13.0 has requirement numpy!=1.24.0,>=1.20, but you'll have numpy 1.19.5 which is incompatible. I using python 3.8, and when i install numpy, it will only download version 1.19.5, if I change it to install "numpy==1.23.3" then it gives the error Failed to install numpy==1.23.3 from https://files.pythonhosted.org/packages/0a/88/f4f0c7a982efdf7bf22f283acf6009b29a9cc5835b684a49f8d3a4adb22f/numpy-1.23.3.tar.gz#sha256=51bf49c0cd1d52be0a240aa66f3458afc4b95d8993d2d04f0d91fa60c10af6cd.
 
 Why is that, I need help

**Comment by MoonLight1202** [comment]
@mhsmith can you help me

**Comment by mhsmith** [comment]
We don't have this exact version of NumPy, but we do have a version within that range. See https://github.com/chaquo/chaquopy/issues/570#issuecomment-989319467 for instructions.
