### ISSUE TITLE
[Help] pyjnius java_method equivalent

### ISSUE THREAD

**Issue by aronkahrs-us** [chaquo/chaquopy#1020]
Hello! I don't know if this is the best place to make this question, if not please tell me, but i'm trying to use kivy plyer with chaquopy, i nearly have it i just need to convert `@java_method('(Landroid/hardware/SensorEvent;)V')` to chaquopy, I tied using `java.method` but I cannot get it working, I know it´s probably something really stupid, but i'm stuck.

Basicaly this is what i need to rewrite using chaquopy:
```
@java_method('(Landroid/hardware/SensorEvent;)V')
    def onSensorChanged(self, event):
        self.values = event.values[:3]
```

**Comment by mhsmith** [comment]
I assume you're trying to implement the SensorEventListener interface. You can do this with a dynamic proxy, as shown [here](https://chaquo.com/chaquopy/doc/current/python.html#dynamic-proxy). There's no need to decorate each method.
