### ISSUE TITLE
Failed to build "tokenizers" library.

### ISSUE THREAD

**Issue by Serkali-sudo** [chaquo/chaquopy#1028]
#### Chaquopy version
14.0.2

#### Relevant parts of my build.gradle file
```gradle
python {
    pip {
        install "setuptools-rust"
        install "diffusers==0.16.0"
        install "accelerate==0.20.0"
        install "transformers==4.28.1"
    }
    version "3.8"
}
 ```

So transformers library requires a python library called "tokenizers" which uses rust compiler. 
I have already installed rust compiler. I also verified that "tokenizers" library works okay in a regular pycharm project.

So when i build my android app with this python libraries installed while building tokenizers library it gives:
```
error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module --crate-type cdylib --` failed with code 101

ERROR: Command errored out with exit status 1:
warning: GNU compiler is not supported for this target
error: failed to run custom build command for `esaxx-rs v0.1.10`
```

I have already tried to install different versions of tokenizers but none of them were neither wasnt compatible with transformers or giving the error. Also i tried tokenizer library .whl locally but it still didnt worked.

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/607#issuecomment-1643676510, and please post any further comments in that issue.
