### ISSUE TITLE
Does Chaquopy supports turtle graphics

### ISSUE THREAD

**Issue by surajsahani** [chaquo/chaquopy#1032]
I am trying to build graphics in android, and not sure if chaquopy supports any graphics lib for android

**Comment by mhsmith** [comment]
The standard library `turtle` is based on `tkinter`, which we don't currently support (#1023).

Chaquopy is a relatively low-level library which doesn't provide any graphics API in itself. But [BeeWare](https://beeware.org/), which is based on Chaquopy, includes the Toga GUI library, which has a [Canvas](https://toga.readthedocs.io/en/stable/reference/api/widgets/canvas.html) API similar to HTML5. This would allow you to write graphics code in Python, while being portable to other desktop and mobile platforms.
