### ISSUE TITLE
Add support for the RISC-V architecture

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#1033]
Android is getting [RISC-V support](https://opensource.googleblog.com/2023/10/android-and-risc-v-what-you-need-to-know.html). Maybe this is something we should look into supporting in Chaquopy? Google is expected to release build tools, compilers, toolchains and such for this new architecture sometime in 2024.

**Comment by mhsmith** [comment]
Each additional ABI is a significant amount of work, so I don't think we'll do this unless Android starts to see a significant amount of real-world usage on RISC-V. 

If in the future anyone thinks this has now happened, please post a comment below, and I'll consider reopening the issue.
