### ISSUE TITLE
scikit-image for Python 3.9 or later

### ISSUE THREAD

**Issue by rek** [chaquo/chaquopy#1035]
Currently looks like only 3.8 is supported: https://chaquo.com/pypi-7.0/scikit-image/

When trying to use this with a newer python it is trying to compile and failing on the numpy dep:
```
  ...
  running build_ext
  INFO: No module named 'numpy.distutils.disabledcompiler' in numpy.distutils; trying from distutils
  INFO: customize DisabledCompiler
  error: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install scikit-image==0.18.3
```

**Comment by mhsmith** [comment]
Thanks – it just so happens that I'll be looking at filling in the gaps in Python 3.9-3.11 packages later this week.

**Comment by rek** [comment]
Oh excellent, looking forward to it :)

**Comment by mhsmith** [comment]
If anyone else needs this package for Python 3.9 or later, please click the thumbs up button above, and subscribe to this issue to receive updates.

**Comment by mhsmith** [comment]
`scikit-image` version 0.18.3 is now in the public repository for Python 3.9 and 3.10. If anyone needs a newer version, see #1042.
