### ISSUE TITLE
while installing ultralytics libray it is giving error for opencv version

### ISSUE THREAD

**Issue by Dev180399** [chaquo/chaquopy#1037]
i have created yolo model using Yolov5 and i want to run it on android using chaquopy but i am getting problem while installing ultralytics libray where it is giving error for opencv version, i have python 3.8 attached kindly help with setting up and running yolo model in python script android

**Comment by mhsmith** [comment]
Please post the full build log, and the relevant parts of your build.gradle file.

**Comment by Dev180399** [comment]
I have added the necessary Screenshot an you please look into it

**Comment by mhsmith** [comment]
Our available package versions can be seen [here](https://chaquo.com/pypi-7.0/) and [here](https://chaquo.com/pypi-13.1/). If you try older versions of ultralytics, you may be able to find one which is compatible with them. 

However, since `ultralytics` is apparently less than 2 years old, `tensorflow` may be a problem, since we haven't updated that in over 3 years.

**Comment by Dev180399** [comment]
As suggested, we have removed tensorflow and added link from pypi-13.1 which has resolved error for matplotlib but got another error which is attached below

ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.8 /media/hitesh-gupta/Realtrial/HLD/CameraX-master/app/build/generated/python/bp/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpiil32vc5
       cwd: /tmp/pip-install-c9rptpw0/opencv-python
  Complete output (88 lines):
 
 
  --------------------------------------------------------------------------------
  ERROR: Command errored out with exit status 1:

  -- Trying 'Ninja' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
 
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
 
  Not searching for unused variables given on the command line.
 
  CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja' generator - failure
  --------------------------------------------------------------------------------
 
 
 
  --------------------------------------------------------------------------------
  -- Trying 'Unix Makefiles' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
 
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
 
  Not searching for unused variables given on the command line.
 
  CMake Error at /tmp/pip-build-env-8o_3ttaj/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:49 (message):
    Could not find compiler set in environment variable CC:
 
    Chaquopy_cannot_compile_native_code.
  Call Stack (most recent call first):
    CMakeLists.txt:3 (ENABLE_LANGUAGE)
 
 
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Unix Makefiles' generator - failure
  --------------------------------------------------------------------------------
 
                  ********************************************************************************
                  scikit-build could not get a working generator for your system. Aborting build.
 
                  Building Linux wheels for Python 3.8 requires a compiler (e.g gcc).
  But scikit-build does *NOT* know how to install it on ubuntu
 
  To build compliant wheels, consider using the manylinux system described in PEP-513.
  Get it with "dockcross/manylinux-x64" docker image:
 
    https://github.com/dockcross/dockcross#readme
 
  For more details, please refer to scikit-build documentation:
 
    http://scikit-build.readthedocs.io/en/latest/generators.html#linux
 
                  ********************************************************************************
  ----------------------------------------
ERROR: Failed to install opencv-python>=4.6.0 from https://files.pythonhosted.org/packages/c0/52/9fe76a56e01078a612812b40764a7b138f528b503f7653996c6cfadfa8ec/opencv-python-4.8.1.78.tar.gz#sha256=cc7adbbcd1112877a39274106cb2752e04984bc01a031162952e97450d6117f6 (from ultralytics).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command '/usr/local/bin/python3.8'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
![Screenshot from 2023-12-11 11-41-15](https://github.com/chaquo/chaquopy/assets/143414438/8906d77f-9613-475c-a139-aff3fb641674)

**Comment by mhsmith** [comment]
Like I said, you should try older versions of ultralytics to see if they're compatible with the package versions we have. But since ultralytics itself depends on tensorflow, it's possible that none of its versions will work. Unfortunately updating tensorflow is extremely difficult, and we're not planning to do it in the near future.

**Comment by Dev180399** [comment]
i have been able to install ultralytics as well as tensorflow along with other libraries but i am now getting this error while loading yolo model in python file
![Uploading Screenshot 2023-12-11 at 6.14.34 PM.png…]()

**Comment by Dev180399** [comment]
<img width="490" alt="Screenshot 2023-12-11 at 6 14 34 PM" src="https://github.com/chaquo/chaquopy/assets/143414438/c8b96730-e3aa-4584-8901-4480da002a5f">

**Comment by mhsmith** [comment]
Well, it means exactly what it says: it's doing something that requires it to be on the main thread, so you should run it on the main thread and not inside an AsyncTask.

In future, please don't post screenshots of text. Instead, copy and paste the text, and surround it with triple backticks as shown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
