### ISSUE TITLE
[Request]: kivy 

### ISSUE THREAD

**Issue by jhay06** [chaquo/chaquopy#1045]
i know this is just a stupid request because there is existing tool to use kivy which is python-for-android , just want to request this since tensorflow is existing in chaquopy but on python-for-android it is not existing . adding this will add build option to kivy , dev can choose if they want to build kivy app with python-for-android or build it with chaquopy

**Comment by mhsmith** [comment]
Sorry, we have no plans to work on this in the near future, but please subscribe to #408 for any updates.
