### ISSUE TITLE
sudo support to chaquopy

### ISSUE THREAD

**Issue by claudiosx** [chaquo/chaquopy#105]

**Comment by claudiosx** [comment]
I have a fully rooted smartphone, I would like to access the device like  /dev /ttyACM0 with chaquopy. I sent the above code, which confirms that the phone is rooted,  But chaquopy runs in user mode. how can I do?

//java  code
import android.util.Log;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public static boolean canRunRootCommands()
   {
      boolean retval = false;
      Process suProcess;

      try
      {
         suProcess = Runtime.getRuntime().exec("su");

         DataOutputStream os = new DataOutputStream(suProcess.getOutputStream());
         DataInputStream osRes = new DataInputStream(suProcess.getInputStream());

         if (null != os && null != osRes)
         {
            // Getting the id of the current user to check if this is root
            os.writeBytes("id\n");
            os.flush();

            String currUid = osRes.readLine();
            boolean exitSu = false;
            if (null == currUid)
            {
               retval = false;
               exitSu = false;
               Log.d("ROOT", "Can't get root access or denied by user");
            }
            else if (true == currUid.contains("uid=0"))
            {
               retval = true;
               exitSu = true;
               Log.d("ROOT", "Root access granted");
            }
            else
            {
               retval = false;
               exitSu = true;
               Log.d("ROOT", "Root access rejected: " + currUid);
            }

            if (exitSu)
            {
               os.writeBytes("exit\n");
               os.flush();
            }
         }
      }
      catch (Exception e)
      {
         // Can't get root !
         // Probably broken pipe exception on trying to write to output stream (os) after su failed, meaning that the device is not rooted

         retval = false;
         Log.d("ROOT", "Root access rejected [" + e.getClass().getName() + "] : " + e.getMessage());
      }

      return retval;
   }


// This is TASK class 

 public static abstract class Task extends SCiActivity.Task {

        protected Python py = Python.getInstance();
        private PyObject sys;
        private PyObject stdin, stdout, stderr;
        private PyObject realStdin, realStdout, realStderr;

        public static final int STDIN_DISABLED = 0x0, STDIN_ENABLED = 0x1;

        public Task(Application app) { this(app, STDIN_ENABLED); }

        public Task(Application app, int flags) {
            super(app);

            canRunRootCommands();

**Comment by mhsmith** [comment]
What do you mean by "chaquopy runs in user mode"? All I can see here is Java code calling a Java function `canRunRootCommands`. That doesn't involve Chaquopy at all.

Related: #99.

**Comment by claudiosx** [comment]
I would like Chaquopy to run with root privileges.

**Comment by mhsmith** [comment]
If you mean you want the app process itself to run as root, that's not a Chaquopy question, and I don't know the answer. You should ask it in some forum related to Android rooting.

Or if you mean something else, please give details.
