### ISSUE TITLE
src directory missing when building chaquopy-llvm

### ISSUE THREAD

**Issue by Peter9897** [chaquo/chaquopy#1056]
I want to build a wheel for llvmlite, but that requieres chaquopy-llvm to be built. The version i want to use needs a newer version of chaquopy-llvm, so i tried to build that aswell. After hours of adapting the patches to the newer version (why did they have to change all file paths???) the build failed with `Unknown triple 'llvm'`, which was is raised by the build.sh.  It tries to get a triple `triple=$(basename $AR | sed 's/-ar$//')` to determine what to build for. I manually set the triple to "ARM", because i want to build for android abi. However after that the build fails with CMake being unable to find the /src folder, that indeed doesnt exist. All the folders where created before, as i can see in the log output, but then suddenly it doesnt exist anymore. Why is that, how can i fix that, or will there be newer versions prebuilt available soon?

**Comment by mhsmith** [comment]
I can't answer this question unless you give the actual error message.

However, by coincidence I tried to build the current version of chaquopy-llvm myself today, and it looks like I got a bit further. See #1057, which requires the current build-wheel version from the master branch. If you make any more progress, please post it there.
