### ISSUE TITLE
 No such file or directory: '/android_asset/chaquopy/requirements-common.zip/names/dist.male.first'

### ISSUE THREAD

**Issue by haneenhassen** [chaquo/chaquopy#106]
I need use this library from python 
pip {
                    //librarys
                    install "names"
                    install "pillow"
                    install "nltk"
                    install "tokenizer"
                    install "corpus"
                    install "data"
                    install "python-docx"
                }

this output in Build

BUILD SUCCESSFUL in 11s

and in Run
This is the error:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pythonmath, PID: 31277
    java.lang.RuntimeException: Unable to resume activity {com.example.pythonmath/pythonactivity.main.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/android_asset/chaquopy/requirements-common.zip/names/dist.male.first'
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6339)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/android_asset/chaquopy/requirements-common.zip/names/dist.male.first'
        at <python>.names.get_name(__init__.py:24)
        at <python>.names.get_first_name(__init__.py:35)
        at <python>.pythonactivity.main.generateQuestion2(main.py:107)
        at <python>.pythonactivity.main.onResume(main.py:309)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject._chaquopyCall(PyObject.java:222)
        at pythonactivity.main.MainActivity.onResume(MainActivity.java:42)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
        at android.app.Activity.performResume(Activity.java:6793)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3527)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6339) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945) 

I  trying Build > Clean Project in case Gradle
and trying Updated Android Studio. 

but Still not work

**Comment by mhsmith** [comment]
Please see the [documentation on resource files](https://chaquo.com/chaquopy/doc/current/android.html#resource-files). In this case, you'll probably want to use `extractPackages "names"`.

**Comment by haneenhassen** [comment]
Thanks you very much

**Comment by haneenhassen** [comment]
The app is giving some new errors

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pythonmath, PID: 4970
    java.lang.RuntimeException: Unable to resume activity {com.example.pythonmath/pythonactivity.main.MainActivity}: com.chaquo.python.PyException: LookupError: 
    **********************************************************************
      Resource [93mpunkt[0m not found.
      Please use the NLTK Downloader to obtain the resource:
    
      [31m>>> import nltk
      >>> nltk.download('punkt')
      [0m
      For more information see: https://www.nltk.org/data.html
    
      Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m
    
      Searched in:
        - '/data/user/0/com.example.pythonmath/files/nltk_data'
        - '/usr/local/nltk_data'
        - '/usr/local/share/nltk_data'
        - '/usr/local/lib/nltk_data'
        - '/usr/share/nltk_data'
        - '/usr/local/share/nltk_data'
        - '/usr/lib/nltk_data'
        - '/usr/local/lib/nltk_data'
        - '/root/nltk_data'
        - ''
    **********************************************************************
    
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6339)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: com.chaquo.python.PyException: LookupError: 

i am insert 
  import nltk   
  nltk.download('punkt')

And download the 'punkt' from here  
http://www.nltk.org/nltk_data/?fbclid=IwAR2DnRdmFZh0uNtirtYEUBTPPhuJDjiiHdjab09Xju7AUpUGYRK-YspJ-zw

and  Unzipping in /Home/nltk_data

but Still not work

**Comment by mhsmith** [comment]
Please see [this question](https://stackoverflow.com/questions/50906501) on StackOverflow.

**Comment by haneenhassen** [comment]
I am try this but still not working

**Comment by mhsmith** [comment]
Please show your current code, and any errors it produces.

**Comment by haneenhassen** [comment]
[image: Screenshot from 2019-05-01 16-19-20.png]
[image: Screenshot from 2019-05-01 16-11-48.png]

**Comment by mhsmith** [comment]
Your images aren't visible on GitHub. Better to copy and paste the text.

**Comment by haneenhassen** [comment]
#this my code 

from com.example.pythonmath import R

from java import static_proxy, Override, jvoid, method
from android.os import Bundle
from android.support.v7.app import AppCompatActivity
from android.support.v4.app import FragmentActivity
from android.view import View


from com.chaquo.python import Python
import os
import time
import re
import random
from os.path import abspath, join, dirname
import names


import nltk

download_dir = "{}/nltk".format(Python.getPlatform().getApplication().getFilesDir())
if not os.path.exists(download_dir):
    os.mkdir(download_dir)
nltk.download('punkt', download_dir=download_dir)

import nltk.tokenize
import nltk.corpus
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize

from random import randint
import nltk.data
import docx



class MainActivity(static_proxy(AppCompatActivity)):

    global str, t, str3
    global label


    @Override(jvoid, [Bundle])
    def onCreate(self, state):


        AppCompatActivity.onCreate(self, state)
        self.setContentView(R.layout.activity_main)


        label =self.findViewById(R.id.label)
        label.setText("Python Activity!")

        t=[0,1]
        str3=""

    @method(jvoid, [View])
    def generateQuestion2(self):


        item = ['Beg', 'Pen', 'Book', 'Box', 'Chocolate', 'Biscuit', 'Car', 'Press', 'Mango', 'Banana', 'Doll', 'Flower', 'Bread', 'Watch', 'apple', 'apricot', 'avocado', 'banana', 'blackcurrant', 'blackberry', 'blueberry', 'cherry', 'coconut', 'fig', 'toy', 'kiwi(fruit)', 'lemon', 'lime', 'lychee', 'mango', 'nectarine', 'orange', 'papaya', 'peach', 'pear', 'pineapple', 'plum', 'quince', 'raspberry', 'strawberry', 'watermelon']
        z = (random.choice(item))
        addition = ['originally', 'in the first', 'in the beginning', 'earlier', 'to begin with', 'primitively', 'at first', 'initially', 'incipiently']
        az1 = (random.choice(addition))
        __title__ = 'names'
        __version__ = '0.2'
        __author__ = 'Trey Hunner'
        __license__ = 'MIT'

        full_path = lambda filename: abspath(join(dirname(__file__), filename))

        FILES = {
            'first:male': full_path('dist.male.first'),
            'first:female': full_path('dist.female.first'),
            'last': full_path('dist.all.last'),
        }


        def multiwordReplace(text, wordDic):
           
            rc = re.compile('|'.join(map(re.escape, wordDic)))

            def translate(match):
                return wordDic[match.group(0)]

            return rc.sub(translate, text)


        p1 = random.randint(1, 9)
        p2 = random.randint(10, 50)
        q = str(p1)
        x = str(p2)


        def get_name(filename):
            selected = random.random() * 90
            with open(filename) as name_file:
                for line in name_file:
                    name, _, cummulative, _ = line.split()
                    if float(cummulative) > selected:
                        return name


        def get_first_name(gender=None):
            if gender not in ('male', 'female'):
                gender = random.choice(('male', 'female'))
            return get_name(FILES['first:%s' % gender]).capitalize()


        def get_last_name():
            return get_name(FILES['last']).capitalize()


        def get_full_name(gender=None):
            return u"%s %s" % (get_first_name(gender), get_last_name())

        tn = (names.get_first_name())
        p = (names.get_first_name())

        str1 = "John had some marbles. Jim gave him 3 more. Now John has 8 marbles. How many marbles did John have to begin with?"
       
        wordDic = {'John': tn,'marbles': z,'Jim': p,'3': q,'8': x,'to begin with' : az1}
     
        str2 = multiwordReplace(str1, wordDic)
        str3 = (str2)
      
        output = ""

        from com.chaquo.python import Python
        download_dir = "{}/nltk".format(Python.getPlatform().getApplication().getFilesDir())
        if not os.path.exists(download_dir):
            os.mkdir(download_dir)
        nltk.download('punkt', download_dir=download_dir)


        tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
     
        tokenized = tokenizer.tokenize(str3)

       
        words = word_tokenize(str3)

        # Identify the parts of speech
        tagged = nltk.pos_tag(words)



        for i in range(0, len(words)):
            replacements = []

            for syn in wordnet.synsets(words[i]):

                if tagged[i][1] == 'NNP' or tagged[i][1] == 'DT':
                    break

                # The tokenizer returns strings like NNP, VBP etc
                # but the wordnet synonyms has tags like .n.
                # So we extract the first character from NNP ie n
                # then we check if the dictionary word has a .n. or not
                word_type = tagged[i][1][0].lower()
                if syn.name().find("." + word_type + "."):
                    # extract the word only
                    r = syn.name()[0:syn.name().find(".")]
                    replacements.append(r)

            if len(replacements) > 0:
            
                replacement = replacements[randint(0, len(replacements) - 1)]
                output = output + " " + replacement
            else:
             
                output = output + " " + words[i]

        strr = str3
        tn = [int(s) for s in strr.split() if s.isdigit()]
        t[0] = tn[0]
        t[1] = tn[1]
        label.setText(strr+"nony1")

        return strr

    @method(jvoid, [View])
    def generateQuestion(self):


        item = ['Bag', 'Pen', 'Book', 'Box', 'Chocolate', 'Biscuit', 'Car', 'Tickets', 'Mango', 'Banana', 'Doll', 'Flower', 'Bread', 'Watch', 'apple', 'toy', 'avocado', 'Butterfly', 'blackcurrant', 'blackberry', 'blueberry', 'cherry', 'coconut', '', 'toy', 'kiwi(fruit)', 'lemon', 'lime', 'lychee', 'mango', 'Bird', 'orange', 'Ball', 'peach', 'pear', 'pineapple', 'Tomato', 'Lemon', 'raspberry', 'strawberry', 'watermelon']
        z = (random.choice(item))
        addition = ['originally', 'in the first', 'in the beginning', 'earlier', 'to begin with', 'primitively', 'at first', 'initially', 'incipiently']
        az1 = (random.choice(addition))
        __title__ = 'names'
        __version__ = '0.2'
        __author__ = 'Trey Hunner'
        __license__ = 'MIT'

        full_path = lambda filename: abspath(join(dirname(__file__), filename))

        FILES = {
            'first:male': full_path('dist.male.first'),
            'first:female': full_path('dist.female.first'),
            'last': full_path('dist.all.last'),
        }


        def multiwordReplace(text, wordDic):
           
            rc = re.compile('|'.join(map(re.escape, wordDic)))

            def translate(match):
                return wordDic[match.group(0)]

            return rc.sub(translate, text)


        p1 = random.randint(1, 9)
        p2 = random.randint(10, 50)
        q = str(p1)
        x = str(p2)


        def get_name(filename):
            selected = random.random() * 90
            with open(filename) as name_file:
                for line in name_file:
                    name, _, cummulative, _ = line.split()
                    if float(cummulative) > selected:
                        return name


        def get_first_name(gender=None):
            if gender not in ('male', 'female'):
                gender = random.choice(('male', 'female'))
            return get_name(FILES['first:%s' % gender]).capitalize()


        def get_last_name():
            return get_name(FILES['last']).capitalize()


        def get_full_name(gender=None):
            return u"%s %s" % (get_first_name(gender), get_last_name())


        tn = (names.get_first_name())
        p = (names.get_first_name())
        
        wordDic = {
            'John': tn,
            'marbles': z,
            'Jim': p,
            '3': q,
            '8': x,
            'to begin with' : az1}
  
        str2 = multiwordReplace(str1, wordDic)
        str3 = (str2)

        output = ""
        tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

        tokenized = tokenizer.tokenize(str3)

        # Get the list of words from the entire text
        words = word_tokenize(str3)

        # Identify the parts of speech
        tagged = nltk.pos_tag(words)



        for i in range(0, len(words)):
            replacements = []

    
            for syn in wordnet.synsets(words[i]):

          
                if tagged[i][1] == 'NNP' or tagged[i][1] == 'DT':
                    break

          
                word_type = tagged[i][1][0].lower()
                if syn.name().find("." + word_type + "."):
               r = syn.name()[0:syn.name().find(".")]
                    replacements.append(r)

            if len(replacements) > 0:
                replacement = replacements[randint(0, len(replacements) - 1)]
                output = output + " " + replacement
            else:
                output = output + " " + words[i]

        strr = str3
        tn = [int(s) for s in strr.split() if s.isdigit()]
        t[0] = tn[0]
        t[1] = tn[1]
        label.setText(strr+"nony2")

        return strr

    @Override(jvoid,[])
    def onResume(self):
        AppCompatActivity.onResume(self)


        All_Questions= [ MainActivity.generateQuestion2(self) ,MainActivity.generateQuestion(self)]
        question = (random.choice(All_Questions))
        str3 =question

        label.setText(str3+"nony")




 #and this is  errors it produces


E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pythonmath, PID: 5639
    java.lang.RuntimeException: Unable to resume activity {com.example.pythonmath/pythonactivity.main.MainActivity}: com.chaquo.python.PyException: LookupError: 
    **********************************************************************
      Resource [93mpunkt[0m not found.
      Please use the NLTK Downloader to obtain the resource:
    
      [31m>>> import nltk
      >>> nltk.download('punkt')
      [0m
      For more information see: https://www.nltk.org/data.html
    
      Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m
    
      Searched in:
        - '/data/user/0/com.example.pythonmath/files/nltk_data'
        - '/usr/local/nltk_data'
        - '/usr/local/share/nltk_data'
        - '/usr/local/lib/nltk_data'
        - '/usr/share/nltk_data'
        - '/usr/local/share/nltk_data'
        - '/usr/lib/nltk_data'
        - '/usr/local/lib/nltk_data'
        - ''
    **********************************************************************
    
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6339)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: com.chaquo.python.PyException: LookupError: 
    **********************************************************************
      Resource [93mpunkt[0m not found.
      Please use the NLTK Downloader to obtain the resource:
    
      [31m>>> import nltk
      >>> nltk.download('punkt')
      [0m
      For more information see: https://www.nltk.org/data.html
    
      Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m
    
      Searched in:
        - '/data/user/0/com.example.pythonmath/files/nltk_data'
        - '/usr/local/nltk_data'
        - '/usr/local/share/nltk_data'
        - '/usr/local/lib/nltk_data'
        - '/usr/share/nltk_data'
        - '/usr/local/share/nltk_data'
        - '/usr/lib/nltk_data'
        - '/usr/local/lib/nltk_data'
        - ''
    **********************************************************************
    
        at <python>.nltk.data.find(data.py:701)
        at <python>.nltk.data._open(data.py:995)
        at <python>.nltk.data.load(data.py:870)
        at <python>.pythonactivity.main.generateQuestion2(main.py:143)
        at <python>.pythonactivity.main.onResume(main.py:331)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject._chaquopyCall(PyObject.java:222)
        at pythonactivity.main.MainActivity.onResume(MainActivity.java:42)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
        at android.app.Activity.performResume(Activity.java:6793)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3527)
        	... 10 more

**Comment by mhsmith** [comment]
You're downloading to `files/nltk`, but it's searching in `files/nltk_data`. Either change the name of the directory to match what it expects, or set the `NLTK_DATA` environment variable as I explain in the StackOverflow link.

**Comment by mhsmith** [comment]
Chaquopy 4.0.0 and newer sets the `HOME` environment variable to your app's files directory, and nltk will automatically create an `nltk_data` subdirectory there. So there's no longer any need to use the `NLTK_DATA` environment variable, or the `download_dir` parameter.

**Comment by haneenhassen** [comment]
thank you this problem is done

Intent Math = new Intent(this, wordproblem.main.WordActivity.class);
startActivityForResult(Math, RESULT_OK);


please I'am want call the python file as like ActivityForResult
how code of function  ActivityForResult  write

@Override (jvoid,[])
def onActivityResult(self, requestCode, resultCode,dataIntent):
    AppCompatActivity.onActivityResult(requestCode, resultCode, dataIntent)

    if(resultCode == RESULT_OK):
        messageReturn =
dataIntent.getStringExtra(str(WordActivity.objt.answer(self)))

**Comment by mhsmith** [comment]
Please create new issues for unrelated questions. We can continue in #110.
