### ISSUE TITLE
Could not resolve all files for configuration ':classpath'.

### ISSUE THREAD

**Issue by zhangxiaoxuan39** [chaquo/chaquopy#1065]
The language I used is kts, and when configuring the new chaquo version 15.0.1, according to the usage instructions sent on the official website, chaquo{} cannot appear alone and an error is reported "Unresolved reference: chaquopy ", and "sync", error "Could not resolve all files for configuration ':classpath'.> Could not find gradle - 15.0.1. Jar (com) chaquo) python: gradle: 15.0.1).Searched in the following locations:”

![image](https://github.com/chaquo/chaquopy/assets/68416359/83030b4a-6c1b-4d32-b09a-13ef5562dd13)

**Comment by zhangxiaoxuan39** [comment]
chaquo{} cannot appear alone and an error is reported "Unresolved reference: chaquopy

**Comment by mhsmith** [comment]
Read the instructions more carefully – they tell you where to add the `mavenCentral` repository. If the URL in your error message is a mirror of Maven Central, maybe it hasn't updated with the new Chaquopy version yet.

**Comment by mhsmith** [comment]
The URL in your message now works fine.
