### ISSUE TITLE
How can I open binaized files with chaquopy Java API ?

### ISSUE THREAD

**Issue by rigoeramirez** [chaquo/chaquopy#107]
I'm working on an app that uses scikit learn on a server to generate a model, this model is persisted on a (.sav) file . I want to recober this model on my android app with the chaquopy Java API to apply the predict() with local data generated on the device.

**Comment by mhsmith** [comment]
I assume the part you're having trouble with is building the model file into the app and accessing it at runtime. 

Start by looking at the section on [resource files](https://chaquo.com/chaquopy/doc/current/android.html#resource-files) in the documentation. If you prefer to write as much as possible in Java, you should be able to translate those examples into Java using the [Java API examples](https://chaquo.com/chaquopy/doc/current/java.html).

Or alternatively, you could package the model file as an APK asset and extract it to a temporary file using standard Android APIs.
