### ISSUE TITLE
[question] How read python print output from service?

### ISSUE THREAD

**Issue by ObscurusGrassator** [chaquo/chaquopy#1079]
How read python print() output of nfinite python script from android (background) service please?
You have only example for activity with viewModel.
Or another (callback) option, how to call multiple times java method from python script.
( I am not python and java developer. Please get me real example please :-) . )
Thanks.

**Comment by mhsmith** [comment]
> How read python print() output of nfinite python script from android (background) service please?
> You have only example for activity with viewModel.

The most important parts of the example are:
* console.py, which defines a ConsoleOutputStream class that can wrap stdout
* PythonConsoleActivity.java, which creates the class, though this could be done just as easily in Java

If you want to do something with the output other than passing it to a Java method, then you can adapt ConsoleOutputStream to do whatever you want.

> Or another (callback) option, how to call multiple times java method from python script.

I don't understand what you mean. If you want to call a method multiple times, then just call it multiple times. In fact, that's exactly what ConsoleOutputStream does already – it calls a Java method every time something is written to the stream.

**Comment by mhsmith** [comment]
If you need more help, then please give more details of exactly what you're trying to achieve.

**Comment by ObscurusGrassator** [comment]
I write, I saw existed example PythonConsoleActivity.java, but I do not know, how use in android service without ConsoleActivity and ViewModelProviders. But for now this question is not important for my (pyaudio). I cloce this question and I will open it later maybe.
