### ISSUE TITLE
Chaquopy bundles seemingly unneeded native assets

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#1080]
I have configured my project to build separate APKs for every architecture, however when examining an arm64 APK it seems like Chaquopy has bundled *some* assets for all architectures.
![image](https://github.com/chaquo/chaquopy/assets/67378443/b6a3fac9-f724-4fb9-86ab-f1592875e2ba)
Why are the selected files bundled? Are they safe to remove using `packagingOptions` in build.gradle?

**Comment by mhsmith** [comment]
> I have configured my project to build separate APKs for every architecture, 

How exactly have you done this? Please post the relevant sections of your build.gradle file.

**Comment by mhsmith** [comment]
If this is still a problem, please post the requested information, and I'll reopen the issue.

**Comment by IsakTheHacker** [comment]
I'm sorry for creating issues and then not following up with more information. I think something is wrong about my abi split configuration and maybe it is also related to the other issue with the target abi warnings. When I have time to take a proper look, I will of course post all the configuration. But as a temporary fix, would it be safe to removed the selected bundles assets manually from the final APK if it is just supporting the arm64-v8a ABI, as described above?

**Comment by mhsmith** [comment]
It would be safe from Chaquopy's point of view, but I don't know if it would invalidate the APK's signature.

The recommended way to build separate APKs for each ABI is described in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size).

**Comment by IsakTheHacker** [comment]
Thank you, that workaround will work just fine for now. I'm excluding the assets based on the method I mentioned in the first message so signatures shouldn't be an issue I think.

And yes, I am indeed using the recommended strategy for building separate APKs for each ABI (since it says in the manual that AABs don't automatically split the ABIs properly?). However, I have chaquopy in a separate library module so the ABI split configuration is specified there and in the app module if that makes sense.

**Comment by mhsmith** [comment]
Yes, the FAQ method probably won't work if you're using a library module, because it'll put all the ABIs in the library, and then has no way of knowing which ones to remove in the app itself.
