### ISSUE TITLE
why doesn't it recognize libraries? in android studio,java

### ISSUE THREAD

**Issue by Melkon2008** [chaquo/chaquopy#1088]
![Screenshot 2024-02-02 201709](https://github.com/chaquo/chaquopy/assets/144586504/545cef73-e5f0-495b-92cb-a3ee3a539037)

**Comment by mhsmith** [comment]
See the [FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#no-python-interpreter-configured-for-the-module), and in future please read the issue template before creating an issue.
