### ISSUE TITLE
ANR error when instantiate a class

### ISSUE THREAD

**Issue by husaynirfan1** [chaquo/chaquopy#1089]
I got an anr error when starting a class. The class consist of importing few modules. No problem with syntax to access the class through Java in Android as I tried different simple modules in the same directory. I am using Chaquopy 14, running using gradle 8.0. Below is the stacktrace from logcat.
~~~
ANR in com.AlMawaddah.FilQurba (com.AlMawaddah.FilQurba/.Base.MainActivity)
                                                  PID: 16773
                                                  Reason: Input dispatching timed out (9bcc855 com.AlMawaddah.FilQurba/com.AlMawaddah.FilQurba.Base.MainActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false))

CPU usage from 69ms to 606ms later (2024-02-03 02:03:53.764 to 2024-02-03 02:03:54.302):
                                                   120% 16773/com.AlMawaddah.FilQurba: 105% user + 15% kernel / faults: 1260 minor 63 major
                                                    100% 16773/waddah.FilQurba: 100% user + 0% kernel
~~~

**Comment by mhsmith** [comment]
Some Python imports will inevitably take a long time to complete. If you want to make sure that doesn't cause an ANR, you can do it in a background thread.

On the other hand, if the import *never* completes, then you might have some other problem. You can narrow it down by adding some `print` statements to the Python code and checking the logcat to see how far it gets.
