### ISSUE TITLE
Video stream using chaquopy

### ISSUE THREAD

**Issue by fadi0332** [chaquo/chaquopy#109]
Hi there! 
I am trying to open a camera using my python class code (cv2.VideoCapture(0)) ,but the activity fails to launch it and displays an blank screen instead .I searched alot but could not get an answer.

**Comment by mhsmith** [comment]
Are the OpenCV calls throwing an exception, or are they returning an image? Either way, please give details.

**Comment by fadi0332** [comment]
There are 3 errors in logcat :
1)AtomicFileUtils:readFileUtils file not exist :android. Until. AtomicFile@49ccbd8
2)E/MemoryLeakMonitorManager:MemoryLeakMonitor.jar is not exist!
3)E/Minkin:Could not get cmap table size!

**Comment by mhsmith** [comment]
But your actual OpenCV calls: how are they returning? You might need to add some logging code to find this out. Everything you print to the Python stdout or stderr will go to logcat.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information
