### ISSUE TITLE
lxml version is deprecated

### ISSUE THREAD

**Issue by SWindes** [chaquo/chaquopy#1092]
Similiar issue to this one https://github.com/chaquo/chaquopy/issues/535. However it requires version 4.9.1 of lxml now.

**Comment by mhsmith** [comment]
If you'd like to try building a newer version of this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the new version to the public repository.

If anyone else needs a new version of this package, please click the thumbs up button above, and post a comment explaining why you need it.
