### ISSUE TITLE
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'curses'

### ISSUE THREAD

**Issue by nini22P** [chaquo/chaquopy#1093]
#### Chaquopy version
15.0.1

#### Relevant parts of your code
```
val python = Python.getInstance()
python.getModule("nsz").callAttr("D", path)
```

#### Describe your issue
Error when using `nsz` library 
```
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'curses'
```

**Comment by mhsmith** [comment]
Chaquopy does not include the `curses` module, because an Android app has no console on which it could be run.
