### ISSUE TITLE
Support pytorch version 1.11

### ISSUE THREAD

**Issue by FishConsole** [chaquo/chaquopy#1105]
We're building an Android-based flask application using chaquopy, and now we're all set, But when we tried to provide AI support for flask, After checking, we found that this is because chaquopy only provides pytorch's 1.8.x library, The 1.8.x pytorch library no longer exists on pypi, which is an underlying problem that we can't solve. We hope you will be compatible with pytorch 1.11.x. Thank you

我们正在使用chaquopy构建安卓端可以运行的flask应用，现在一切准备就绪，但是我们在尝试对flask提供AI支持时发现无法安装pytorch，经过排查我们发现这是由于chaquopy只提供pytorch了1.8.x的库，而1.8.x的pytorch库在pypi上由于版本过低已经不存在了，这是一个底层的问题，我们无法解决，我们希望贵方可以兼容pytorch1.11.x，感谢你们

**Comment by mhsmith** [comment]
Sorry, we won't be able to update PyTorch in the near future. For updates, please subscribe to #606.

**Comment by FishConsole** [comment]
Y U I J  -  自动回复邮件已经收到了,但是现在我有些事,没法回你.你等我一会儿,我看到就回.
