### ISSUE TITLE
Error: Found 0 armeabi-v7a ZIPs in /home/meow/chaquopy/maven/com/chaquo/target/3.12.1-0

### ISSUE THREAD

**Issue by krecicki** [chaquo/chaquopy#1109]
I am building a python wheel for android.

The error I am getting is 

```
Error: Found 0 armeabi-v7a ZIPs in /home/meow/chaquopy/maven/com/chaquo/target/3.12.1-0
```

I am running the line

```
./build-wheel.py --python 3.12 --abi armeabi-v7a packages/package
```

**Comment by mhsmith** [comment]
For Python 3.12 and later we only support the 64-bit ABIs, `arm64-v8a` and `x86_64`. I'll update the README to make this clear.
