### ISSUE TITLE
two activity 

### ISSUE THREAD

**Issue by haneenhassen** [chaquo/chaquopy#111]
hello 

this code in python file

```
@Override(jvoid, [Bundle])
    def onCreate(self, state):
        AppCompatActivity.onCreate(self, state)
        self.setContentView(R.layout.activity_exercise_choose)
```

and this is call of python file

```
case "Problem word":
                Intent Math = new Intent(this,wordproblem.divided.WordActivity.class);
                startActivityForResult(Math, RESULT_OK);
                break;
```

problem happen is show to Activity 

![Screenshot_2019-06-05_044210](https://user-images.githubusercontent.com/49983834/58926961-29800c80-874d-11e9-83d0-370c56e61b65.jpg) 
this activity run from java code 
![Screenshot_2019-06-05_044204](https://user-images.githubusercontent.com/49983834/58926957-284edf80-874d-11e9-8b67-0081ab274628.jpg)
and this run from python file

I'am need show one activity 

how do this ??

**Comment by mhsmith** [comment]
I'm sorry, I don't understand your question. Please explain more clearly.
