### ISSUE TITLE
HELP me plz....TT :  ModuleNotFoundError: No module named 'com'

### ISSUE THREAD

**Issue by lawiparadise** [chaquo/chaquopy#1118]
I just follow demo app(https://github.com/chaquo/chaquopy) and success
Chaquopy is so nice project!!

and I saw "from com.chaquo.python.demo import R" in src/main/python/chaquopy/demo/ui_demo.py
![image](https://github.com/chaquo/chaquopy/assets/12179624/4fcdb8c6-3bf3-447d-a17f-5383bdf184e3)

so I make a new android project, and success to running chaquopy app(gradle success, matplotlib success)

and I want to add my package(com.example.cloiblockcoding) to src/main/python/plot2.py
"from com.example.cloiblockcoding.activity.PlotActivity import aa"
(aa is kotlin function)
![image](https://github.com/chaquo/chaquopy/assets/12179624/1f26c067-ec6a-4fd4-a435-13cecc62138d)

but it give me a error
![image](https://github.com/chaquo/chaquopy/assets/12179624/e7746736-a469-466c-937b-094ca3975cf2)

so I tried to copy demo apps build.grade.kts code etc and paste it to my project
but it cannot fix my bug...

I already find documentation,, but I cannot fix it

why my plot2.py cannot import my package name and kotlin function???
which part of code can make it recognize to my python code import my package name and kotlin code?

Please help me..
I searched issue with keyworkds "no module name" but I cannot find,,.  sorry..

thank you!!

**Comment by lawiparadise** [comment]
oh, i got it

from com.example.cloiblockcoding.activity import MainActivity

this code working,,

sorry to bother

**Comment by mhsmith** [comment]
> from com.example.cloiblockcoding.activity.PlotActivity import aa
> (aa is kotlin function)

You can't import individual functions, only classes. See [the documentation](https://chaquo.com/chaquopy/doc/current/python.html#import-hook) for more details.
