### ISSUE TITLE
is the pip version causing this problem?

### ISSUE THREAD

**Issue by dnecra** [chaquo/chaquopy#1120]
Chaquopy version: 15.0.1

Windows, Android studio, Python 3.10.9

#### Relevant parts of your code
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517): started
  Building wheel for cryptography (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ednecra\AndroidStudioProjects\Switch\app\build\python\env\debug\Scripts\python.exe' 
   
   .
   .
   .
     If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
  To update pip, run:
  
      pip install --upgrade pip
  
  and then retry package installation.

#### Describe your issue
i want to run tinytuya script on android using chaquopy
the script running but when its downloading the tintytuya requirements, the pip install cryptography>=3.1 giving error

**Comment by mhsmith** [comment]
We currently only support `cryptography` on Python 3.8-3.10. To set the Python version of your app, see [these instructions](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

If that isn't it, please post the FULL build log; you can display it by clicking the “Build: failed” caption to the left of the error.

**Comment by dnecra** [comment]
Downgraded python to 3.10 and now cryptography installed and script running great. Thank you !!!
