### ISSUE TITLE
Can't install pymupdf

### ISSUE THREAD

**Issue by Burhan7777** [chaquo/chaquopy#1124]
This is the error:
 ERROR: Command errored out with exit status 1:
     command: /Users/peerzadaburhan/AndroidStudioProjects/RedPdfPro/app/build/python/env/debug/bin/python /Users/peerzadaburhan/AndroidStudioProjects/RedPdfPro/app/build/python/env/debug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/tmpc80sna36
         cwd: /private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf
    Complete output (251 lines):
    pymupdf/setup.py: ### Starting.
    pymupdf/setup.py: __name__: 'setup'
    pymupdf/setup.py: platform.platform(): 'macOS-13.1-arm64-arm-64bit'
    pymupdf/setup.py: platform.python_version(): '3.12.2'
    pymupdf/setup.py: sys.executable: '/Users/peerzadaburhan/AndroidStudioProjects/RedPdfPro/app/build/python/env/debug/bin/python'
    pymupdf/setup.py: CPU bits: 64 sys.maxsize=9223372036854775807
    pymupdf/setup.py: __file__: '/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf/setup.py'
    pymupdf/setup.py: os.getcwd(): '/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf'
    pymupdf/setup.py: sys.argv (3):
    pymupdf/setup.py:     0: '/Users/peerzadaburhan/AndroidStudioProjects/RedPdfPro/app/build/python/env/debug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py'
    pymupdf/setup.py:     1: 'prepare_metadata_for_build_wheel'
    pymupdf/setup.py:     2: '/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/tmpc80sna36'
    pymupdf/setup.py: os.environ (30):
    pymupdf/setup.py:     AR: 'Chaquopy_cannot_compile_native_code'
    pymupdf/setup.py:     AS: 'Chaquopy_cannot_compile_native_code'
    pymupdf/setup.py:     CC: 'Chaquopy_cannot_compile_native_code'
    pymupdf/setup.py:     COMMAND_MODE: 'unix2003'
    pymupdf/setup.py:     CXX: 'Chaquopy_cannot_compile_native_code'
    pymupdf/setup.py:     HOME: '/Users/peerzadaburhan'
    pymupdf/setup.py:     HOMEBREW_CELLAR: '/opt/homebrew/Cellar'
    pymupdf/setup.py:     HOMEBREW_PREFIX: '/opt/homebrew'
    pymupdf/setup.py:     HOMEBREW_REPOSITORY: '/opt/homebrew'
    pymupdf/setup.py:     INFOPATH: '/opt/homebrew/share/info:'
    pymupdf/setup.py:     LC_CTYPE: 'UTF-8'
    pymupdf/setup.py:     LD: 'Chaquopy_cannot_compile_native_code'
    pymupdf/setup.py:     LOGNAME: 'peerzadaburhan'
    pymupdf/setup.py:     MANPATH: '/opt/homebrew/share/man::'
    pymupdf/setup.py:     OLDPWD: '/'
    pymupdf/setup.py:     PATH: '/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-build-env-3fipihiz/overlay/bin:/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-build-env-3fipihiz/normal/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/Users/peerzadaburhan/.npm-global/lib/node_modules/@aws-amplify/cli/:/Users/peerzadaburhan/node_modules/@aws-amplify/cli/:/Users/peerzadaburhan/.amplify/bin/'
    pymupdf/setup.py:     PEP517_BACKEND_PATH: '/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf'
    pymupdf/setup.py:     PEP517_BUILD_BACKEND: 'setup'
    pymupdf/setup.py:     PIP_CONFIG_FILE: '/dev/null'
    pymupdf/setup.py:     PIP_REQ_TRACKER: '/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-req-tracker-5ort05pu'
    pymupdf/setup.py:     PYTHONNOUSERSITE: '1'
    pymupdf/setup.py:     PYTHONPATH: '/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-build-env-3fipihiz/site'
    pymupdf/setup.py:     SHELL: '/bin/zsh'
    pymupdf/setup.py:     SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.WJLxV6uSL4/Listeners'
    pymupdf/setup.py:     TMPDIR: '/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/'
    pymupdf/setup.py:     USER: 'peerzadaburhan'
    pymupdf/setup.py:     XPC_FLAGS: '0x0'
    pymupdf/setup.py:     XPC_SERVICE_NAME: '0'
    pymupdf/setup.py:     __CFBundleIdentifier: 'com.google.android.studio'
    pymupdf/setup.py:     __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0'
    pipcl.py: build_wheel():  wheel_directory='/private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-modern-metadata-qkoij2e3' config_settings=None metadata_directory=None
    pipcl.py: _call_fn_build(): calling self.fn_build=<function build at 0x1062df740>
    pymupdf/setup.py: get_mupdf_internal(): out='dir' location=None sha=None
    pymupdf/setup.py: Download location='https://mupdf.com/downloads/archive/mupdf-1.24.0-source.tar.gz' local_tgz='mupdf-1.24.0-source.tar.gz' name='mupdf-1.24.0-source'
    pymupdf/setup.py: Downloading from location='https://mupdf.com/downloads/archive/mupdf-1.24.0-source.tar.gz' to local_tgz='mupdf-1.24.0-source.tar.gz'.
    pymupdf/setup.py: Extracting mupdf-1.24.0-source.tar.gz
    pymupdf/setup.py: Setting XCFLAGS and XCXXFLAGS to predefine TOFU_CJK_EXT.
    pymupdf/setup.py: Building MuPDF by running: cd /private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf/mupdf-1.24.0-source && XCFLAGS=-DTOFU_CJK_EXT XCXXFLAGS=-DTOFU_CJK_EXT /Users/peerzadaburhan/AndroidStudioProjects/RedPdfPro/app/build/python/env/debug/bin/python ./scripts/mupdfwrap.py -d build/PyMuPDF-arm64-shared-tesseract-release -b all && echo /private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf/mupdf-1.24.0-source/build/PyMuPDF-arm64-shared-tesseract-release: && ls -l /private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf/mupdf-1.24.0-source/build/PyMuPDF-arm64-shared-tesseract-release
    (+0.1s): -b: __main__.py:1514:build: Setting compiler to os.environ["CXX"]='Chaquopy_cannot_compile_native_code'.
    (+0.1s): -b: m: __main__.py:1603:build: Building libmupdf.so ...
    (+0.1s): -b: m: __main__.py:1208:_get_m_command: Setting -j to  multiprocessing.cpu_count()=8
    (+0.1s): -b: m: __main__.py:1605:build: running: cd /private/var/folders/ld/1c9mlp857gg017f1j29mm82c0000gn/T/pip-install-z3pq3qf2/pymupdf/mupdf-1.24.0-source && make -j 8 HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes shared=yes HAVE_LEPTONICA=yes HAVE_TESSERACT=yes build=release build_prefix=PyMuPDF-arm64-shared-tesseract-
    (+0.5s): -b: m: __main__.py:1605:build: (+0.1s): -b: m: __main__.py:1605:build: mkdir -p build/PyMuPDF-arm64-shared-tesseract-release/source/fitz/ ; xcrun cc -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -DTOFU_CJK_EXT -Iinclude -MMD -MP -o build/PyMuPDF-arm64-shared-tesseract-release/source/fitz/archive.o -c source/fitz/archive.c -Wall -Wsign-compare -Wdeclaration-after-statement -fPIC -Ithirdparty/freetype/include -Iscripts/freetype -Ithirdparty/gumbo-parser/src -Ithirdparty/harfbuzz/src -Ithirdparty/libjpeg -Iscripts/libjpeg -Ithirdparty/lcms2/include -DHAVE_LCMS2MT -Ithirdparty/mujs -Ithirdparty/zlib -Ithirdparty/jbig2dec -Ithirdparty/openjpeg/src/lib/openjp2 -DOPJ_STATIC -DOPJ_HAVE_INTTYPES_H -DOPJ_HAVE_STDINT_H -DHAVE_LEPTONICA -Ithirdparty/leptonica/src -DHAVE_TESSERACT -Ithirdparty/tesseract/include -Iscripts/tesseract -Ithirdparty/extract/include -Ithirdparty/extract/src

This is my gradle:

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.chaquo.python")
}

android {
    namespace = "com.pzbdownloaders.redpdfpro"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.pzbdownloaders.redpdfpro"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
        ndk {
            // On Apple silicon, you can omit x86_64.
            abiFilters += "arm64-v8a"
        }
        chaquopy {
            defaultConfig {
                version = "3.8"
                buildPython("/opt/homebrew/bin/python3")
                pip {
                    install("requests")
                    install("datetime")
                    install("pypdf")
                    install("pypdf[image]")
                    install("PYPDF2")
                    install("pillow")
                    install("pymupdf")
                }
            }
            productFlavors {

            }
            sourceSets { }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.3"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {

    implementation("androidx.core:core-ktx:1.9.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
    implementation("androidx.activity:activity-compose:1.8.2")
    implementation(platform("androidx.compose:compose-bom:2023.03.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2023.03.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")

    //NAVIGATION
    implementation("androidx.navigation:navigation-compose:2.7.7")

    //MATERIAL 3
    implementation("androidx.compose.material3:material3:1.2.1")

}

I tried with different pymupdf versions . None of them work

**Comment by mhsmith** [comment]
See #423, and in future please search for existing issues before creating new ones.
