### ISSUE TITLE
Demo Building: SSL and native code compilation

### ISSUE THREAD

**Issue by the7threvival** [chaquo/chaquopy#113]
Hello Malcolm,

I have not sure if the following issue is a bug or something I am missing. It seems it cannot find the SSl module? Any clarification would be appreciated. Here is the Build Output:

""""""""""""""""""""""""""''''''''''''''''''''''''''''' OUTPUT """"""""""""""""""""""""""''''''''''''''''''''''''''''' 
Executing tasks: [assemble]

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-2.1, https://chaquo.com/pypi-6.2
Collecting Pygments==2.2.0
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygments/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygments/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygments/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygments/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pygments/
  Could not fetch URL https://pypi.org/simple/pygments/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pygments/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-2.1/pygments/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-2.1/pygments/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-2.1/pygments/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-2.1/pygments/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-2.1/pygments/
  Could not fetch URL https://chaquo.com/pypi-2.1/pygments/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-2.1/pygments/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-6.2/pygments/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-6.2/pygments/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-6.2/pygments/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-6.2/pygments/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /pypi-6.2/pygments/
  Could not fetch URL https://chaquo.com/pypi-6.2/pygments/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-6.2/pygments/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement Pygments==2.2.0 (from versions: )
No matching distribution found for Pygments==2.2.0
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> buildPython failed (org.gradle.process.internal.ExecException: Process 'command 'py'' finished with non-zero exit value 1). For full details, open the 'Build' window and switch to text mode with the 'Toggle view' button on the left.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
6 actionable tasks: 1 executed, 5 up-to-date

**Comment by mhsmith** [comment]
What version of Python are you using for the build?

I assume you're using the official Python builds from python.org, installed with the default settings, and you're not using the [buildPython](https://chaquo.com/chaquopy/doc/current/android.html#development) setting? If any of that isn't the case, then please give details.

The most plausible explanation I've found for this error is that there may be other copies of the OpenSSL DLLs on your PATH which are incompatible with your Python version. [This answer](https://stackoverflow.com/a/54932141) has a suggestion for fixing that.

In any case, you should be able to get a more detailed error message by running `py` at the Windows command prompt and then typing `import ssl`.

**Comment by the7threvival** [comment]
I have not added the buildPython line so I imagine it must be using Python 3.7? I have various versions on my computer but I believe it should be using that one. If it runs using `py -3` or `py` then it is probably running Python 3.7.3

Yes, all of that should be the case.

It's funny that you mention that solution. That is exactly what I was about to try. 

After running `import ssl` in Python, I got;
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\212760773\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.`

Running conda install openssl, removed the above error but did not fix the issue.

After installing OpenSSL 1.1.1c from https://slproweb.com/products/Win32OpenSSL.html, that seems to have **fixed** the issue! It downloads from pypi.org but still fails from chaquo.com because it cannot verify the certificate. Prob not a problem on your side.

**Comment by the7threvival** [comment]
Now I am getting an issue when installing murmurhash. Here is a sample of the output:

running build_ext
  building 'murmurhash.mrmr' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
ERROR: Failed to install murmurhash==0.28.0 from https://files.pythonhosted.org/packages/5e/31/c8c1ecafa44db30579c8c457ac7a0f819e8b1dbc3e58308394fff5ff9ba7/murmurhash-0.28.0.tar.gz.

""""""""""""""""""""""""""'''''''''''''''''''''''''''''  """"""""""""""""""""""""""'''''''''''''''''''''''''''''

I am running your chaquopy-master project directly downloaded from the repo btw. So the settings are unchanged.

**Comment by mhsmith** [comment]
> It downloads from pypi.org but still fails from chaquo.com because it cannot verify the certificate.

What's the error message? You won't be able to build the demo app without access to chaquo.com, because that's where the Android murmurhash builds are stored.

> If it runs using `py -3` or `py` then it is probably running Python 3.7.3

Yes, by default it runs using `py -3`. But is that how you launched your interactive Python to run `import ssl`? I didn't think the `py` command could be used to launch an Anaconda Python installation (e.g. see [here](https://github.com/ContinuumIO/anaconda-issues/issues/149)). If you're unsure what copy of Python is running in an interactive session, then you can check `sys.executable`.

You might want to try reinstalling an official Python build from python.org.

**Comment by the7threvival** [comment]
""""""""""""""""""""""""""'''''''''''''''''''''''''''''NEW ERRROR MESSAGE""""""""""""""""""""""""""'''''''''''''''''''''''''''''

Executing tasks: [:app:assembleDebug]

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-2.1, https://chaquo.com/pypi-6.2
Collecting Pygments==2.2.0
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/pygments/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/pygments/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/pygments/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/pygments/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/pygments/
  Could not fetch URL https://chaquo.com/pypi-2.1/pygments/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-2.1/pygments/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/pygments/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/pygments/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/pygments/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/pygments/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/pygments/
  Could not fetch URL https://chaquo.com/pypi-6.2/pygments/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-6.2/pygments/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting MarkupSafe==1.0
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/markupsafe/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/markupsafe/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/markupsafe/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/markupsafe/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/markupsafe/
  Could not fetch URL https://chaquo.com/pypi-2.1/markupsafe/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-2.1/markupsafe/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/markupsafe/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/markupsafe/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/markupsafe/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/markupsafe/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/markupsafe/
  Could not fetch URL https://chaquo.com/pypi-6.2/markupsafe/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-6.2/markupsafe/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
Collecting murmurhash==0.28.0
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/murmurhash/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/murmurhash/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/murmurhash/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/murmurhash/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/murmurhash/
  Could not fetch URL https://chaquo.com/pypi-2.1/murmurhash/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-2.1/murmurhash/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/murmurhash/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/murmurhash/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/murmurhash/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/murmurhash/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/murmurhash/
  Could not fetch URL https://chaquo.com/pypi-6.2/murmurhash/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-6.2/murmurhash/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Using cached https://files.pythonhosted.org/packages/5e/31/c8c1ecafa44db30579c8c457ac7a0f819e8b1dbc3e58308394fff5ff9ba7/murmurhash-0.28.0.tar.gz
Collecting certifi==2018.01.18
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/certifi/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/certifi/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/certifi/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/certifi/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/certifi/
  Could not fetch URL https://chaquo.com/pypi-2.1/certifi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-2.1/certifi/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/certifi/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/certifi/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/certifi/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/certifi/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/certifi/
  Could not fetch URL https://chaquo.com/pypi-6.2/certifi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-6.2/certifi/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Using cached https://files.pythonhosted.org/packages/fa/53/0a5562e2b96749e99a3d55d8c7df91c9e4d8c39a9da1f1a49ac9e4f4b39f/certifi-2018.1.18-py2.py3-none-any.whl
Collecting setuptools==40.4.3
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/setuptools/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/setuptools/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/setuptools/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/setuptools/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-2.1/setuptools/
  Could not fetch URL https://chaquo.com/pypi-2.1/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-2.1/setuptools/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/setuptools/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/setuptools/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/setuptools/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/setuptools/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /pypi-6.2/setuptools/
  Could not fetch URL https://chaquo.com/pypi-6.2/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-6.2/setuptools/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Using cached https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl
Building wheels for collected packages: murmurhash
  Running setup.py bdist_wheel for murmurhash: started
  Running setup.py bdist_wheel for murmurhash: finished with status 'error'
  Complete output from command C:\Users\212760773\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\212760~1\\AppData\\Local\\Temp\\pip-install-re289775\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\212760~1\AppData\Local\Temp\pip-wheel-gednf7f0 --python-tag py3:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\murmurhash
  copying murmurhash\about.py -> build\lib.win-amd64-3.6\murmurhash
  copying murmurhash\__init__.py -> build\lib.win-amd64-3.6\murmurhash
  creating build\lib.win-amd64-3.6\murmurhash\tests
  copying murmurhash\tests\test_import.py -> build\lib.win-amd64-3.6\murmurhash\tests
  copying murmurhash\tests\__init__.py -> build\lib.win-amd64-3.6\murmurhash\tests
  copying murmurhash\mrmr.pyx -> build\lib.win-amd64-3.6\murmurhash
  copying murmurhash\mrmr.pxd -> build\lib.win-amd64-3.6\murmurhash
  copying murmurhash\__init__.pxd -> build\lib.win-amd64-3.6\murmurhash
  Command "C:\Users\212760773\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\212760~1\\AppData\\Local\\Temp\\pip-install-re289775\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\212760~1\AppData\Local\Temp\pip-wheel-gednf7f0 --python-tag py3" failed with error code 1 in C:\Users\212760~1\AppData\Local\Temp\pip-install-re289775\murmurhash\  creating build\lib.win-amd64-3.6\murmurhash\include

  creating build\lib.win-amd64-3.6\murmurhash\include\murmurhash
  copying murmurhash\include\murmurhash\MurmurHash2.h -> build\lib.win-amd64-3.6\murmurhash\include\murmurhash
  copying murmurhash\include\murmurhash\MurmurHash3.h -> build\lib.win-amd64-3.6\murmurhash\include\murmurhash
  running build_ext
  building 'murmurhash.mrmr' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
ERROR: Failed to install murmurhash==0.28.0 from https://files.pythonhosted.org/packages/5e/31/c8c1ecafa44db30579c8c457ac7a0f819e8b1dbc3e58308394fff5ff9ba7/murmurhash-0.28.0.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> buildPython failed (org.gradle.process.internal.ExecException: Process 'command 'C:\Users\212760773\AppData\Local\Programs\Python\Python36\python.exe'' finished with non-zero exit value 1). For full details, open the 'Build' window and switch to text mode with the 'Toggle view' button on the left.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s
6 actionable tasks: 1 executed, 5 up-to-date

**Comment by the7threvival** [comment]
py launcher can run Anaconda Python. And the one I ran in the command prompt was that one. 

I have 3.6, which I installed directly from python.org. I tried changing the buildPython line to use that executable but the same problem happens. 

I am also behind a corporate firewall if that helps.
And this popped up, don't know if it is related or not:

>Cannot load module file 'C:/Users/212760773/Desktop/Code/chaquopy-master/demo.iml': File C:\Users\212760773\Desktop\Code\chaquopy-master\demo.iml does not exist. Would you like to remove module 'demo' from the project?

**Comment by mhsmith** [comment]
The default executable location for the python.org installer is `C:\Users\<username>\AppData\Local\Programs\Python\Python<version>\python.exe`. Is that what you used with `buildPython`?

In my installation, `Python37\DLLs` contains `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll`, whereas `Python36\DLLs` evidently has both of these built into `_ssl.pyd`, which is 2 MB larger. So if your Python 3.6 installation is like this, I don't think it should be affected by any DLLs anywhere else.

The only other thing I can think of is this advice from https://slproweb.com/products/Win32OpenSSL.html:

> Users should install BOTH the 1.0.2 series (LTS) and the 1.1.1 (LTS) series for maximum application compatibility.

**Comment by the7threvival** [comment]
That's right.

That is how my DLL folder is as well. 
When I comment out murmurhash and its extraction, i can build the build the app. But will that limit the amount of packages I can import for my own purposes if I can't download any from chaquo.com?

Also, how do I get your domain validation certificate? It seems that is what is missing?

**Comment by the7threvival** [comment]
I got it to work eventually.. I had to remove **all** proxy use on my side (from gradle.properties and environment variables) and connect to an unsecured network. And then it worked! Thanks for the help.

**Comment by mhsmith** [comment]
Strange, I wonder if there might be something wrong with your proxy. And yet you were obviously able to download the Chaquopy Gradle plugin, and I assume you could also visit chaquo.com in a web browser, and all of those things are covered by the same certificate as the Python package repository.

If you ever work out an explanation for this, please do let me know.

**Comment by the7threvival** [comment]
I ended up getting it to work without these workarounds as well. I am not sure how I was able to download the Chaquopy plugin if it also resides on chaquo.com. Maybe the servers were different somehow. I did have issues when visiting chaquo.com on a web browser as my company's proxy did not trust it and it did not show the correct certificate being given to it. 

What I ended doing was getting this app called SSLDetective+ on iOS AppStore and using that to look at the certificate from your website as I could not see it on my computer. I then looked up the root certificate it was pointing to, it's different to the pypi.org one, and downloaded it. After installing it on my machine, everything seems to work with no issues now! I can't even replicate the issue anymore lol. Link for the certificate: https://www.tbs-certificates.co.uk/FAQ/en/racine-USERTrustRSACertificationAuthority.html

**Comment by mhsmith** [comment]
Thanks for the information. That is indeed the correct root certificate, and as you can see it says it's been trusted by Firefox since 2015, and other web browsers should be similar. So it looks like there must have been some problem with your company's IT setup.

**Comment by mhsmith** [comment]
For the original error ("Can't connect to HTTPS URL because the SSL module is not available"), see #450.
