### ISSUE TITLE
11.0.0: python submodule password

### ISSUE THREAD

**Issue by linyv** [chaquo/chaquopy#1130]
#### Chaquopy version

11.0.0
#### Describe your issue

I checked out 11.0.0 version and want to build chaquopy libs. When I run git submodule init && git submodule update:
gitolite@chaquo.com's password:
Is it a private repository？

**Comment by mhsmith** [comment]
The repository `gitolite@chaquo.com:cpython`listed in the .gitmodules file for 11.0.0 is now at https://github.com/chaquo/cpython.

Why do you want to use version 11.0.0? It's [over two years old](https://chaquo.com/chaquopy/doc/current/changelog.html), so I recommend using the current version instead.

And why do you want to build it yourself? If you want to use an older version you can just follow the instructions in the [documentation](https://chaquo.com/chaquopy/documentation/).

**Comment by linyv** [comment]
Thanks. Now I solved the problem.

> Why do you want to use version 11.0.0?
Because I used it in my project from two years ago and I will try to update it.

> And why do you want to build it yourself?
Becuase I encrypted my python code, so I need to  modify the python interpreter and rebuild it again.
