### ISSUE TITLE
Can't install numpy >= 1.20 on Python 3.8

### ISSUE THREAD

**Issue by nathaniacalista01** [chaquo/chaquopy#1133]
#### Relevant parts of your build.gradle file
```
plugins {
    id("com.android.application")
    kotlin("android")
    id("androidx.navigation.safeargs.kotlin")
    id("com.chaquo.python")
}

android {
    namespace = "com.example.sioptik"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.sioptik"
        minSdk = 29
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64", "x86", "armeabi-v7a")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        compose = true
        viewBinding = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

chaquopy{
    defaultConfig{
        buildPython("Path/Programs/Python/Python311/python.exe")
        pip{
            install("numpy==1.23.3")
//            install("opencv-python")
//            install("pupil_apriltags")
        }
    }
    sourceSets{
        getByName("main"){
            srcDir("src/main/python")
        }
    }

}
```
#### Describe your issue
I try to pip install a version of numpy, but I get this warning and error
  WARN: Could not locate executable g77
  WARN: Could not locate executable f77
  WARN: Could not locate executable ifort
  WARN: Could not locate executable ifl
  WARN: Could not locate executable f90
  WARN: Could not locate executable DF
  WARN: Could not locate executable efl
  WARN: Could not locate executable gfortran
  WARN: Could not locate executable f95
  WARN: Could not locate executable g95
  WARN: Could not locate executable efort
  WARN: Could not locate executable efc
  WARN: Could not locate executable flang
  WARN: don't know how to compile Fortran code on platform 'nt'
  error: CCompiler.compile: Chaquopy cannot compile native code

**Comment by mhsmith** [comment]
The current version of Chaquopy defaults to Python 3.8, but we don't have NumPy 1.23.3 for that version of Python.

* To see which NumPy versions are available for which Python versions, see [the repository](https://chaquo.com/pypi-13.1/numpy/).
* To change your app's Python version, see [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

**Comment by nathaniacalista01** [comment]
> The current version of Chaquopy defaults to Python 3.8, but we don't have NumPy 1.23.3 for that version of Python.
> 
> * To see which NumPy versions are available for which Python versions, see [the repository](https://chaquo.com/pypi-13.1/numpy/).
> * To change your app's Python version, see [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

May I know which version of NumPy supported by Chaquopy? I saw this version the link that you have referred, so I think this NumPy 1.23.3 is supported

![image](https://github.com/chaquo/chaquopy/assets/91357043/1b462e3e-11be-4753-aba2-43690f0dfa96)

**Comment by mhsmith** [comment]
The "cp" part of the filename identifies the Python version.

**Comment by nathaniacalista01** [comment]
I've tried to downgrade my Python version and install the compatible version of numpy, but it still get an error

**Comment by mhsmith** [comment]
As you can see from the repository, NumPy 1.20.3 is available for Python 3.9, and NumPy 1.23.3 for Python 3.9-3.11.

If you still can't install it, please post the`chaquopy` section of your build.gradle file, and the full build log.

**Comment by nathaniacalista01** [comment]
Yup I still get an error and for more context, I need to use numpy that is >= 1.20, therefore I use a higher version of Python (not 3.8). This is my chaquopy section 
```
chaquopy {
    defaultConfig {
        version = "3.11"
        buildPython("C:/Users/ASUS/AppData/Local/Programs/Python/Python311/python.exe")
        pip{
            install("numpy==1.23.3")
            install("opencv-python")
            install("pupil_apriltags")
        }
    }
}
```

And now I don't get any error, but it is still loading until now (already 30 minutes) 
![image](https://github.com/chaquo/chaquopy/assets/91357043/05d9e27b-2c7c-44a7-a3ad-e7ae4f7d1437)

**Comment by mhsmith** [comment]
Unfortunately we don't have OpenCV for Python 3.9 or later yet (#779). However, we do have a newer NumPy version for Python 3.8 in a separate repository: see https://github.com/chaquo/chaquopy/issues/559#issuecomment-989318791.

**Comment by nathaniacalista01** [comment]
Thanks! it works like a charm for me
