### ISSUE TITLE
No module name numpy.typing

### ISSUE THREAD

**Issue by nathaniacalista01** [chaquo/chaquopy#1134]
#### Chaquopy version
Chaquopy version 15

#### Devices or emulators where the issue happens
I use an android device

#### Relevant parts of your code
Basicly, I have an android project that read AprilTag. I try to read AprilTag by using pupil_apriltags library and I did it in python. Then, I pass the image that was taken by device's camera to the Python code. 

```
from pupil_apriltags import Detector
import cv2

def main(image_path):
    img = image_path
    at_detector = Detector(
        families="tag16h5 tag25h9 tag36h11 tagCircle21h7 tagCircle49h12 tagCustom48h12 tagStandard41h12 tagStandard52h13",
        nthreads=1,

    )
    img = cv2.imread(image_path)
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    tags = at_detector.detect(
        gray_img, estimate_tag_pose=False, camera_params=None, tag_size=None
    )
    for detection in tags:
        corners = detection.corners.astype(np.int32)
        cv2.rectangle(img, tuple(corners[0]), tuple(corners[2]), (0, 0, 255), 5)
    for tag in tags:
        (ptA, ptB, ptC, ptD) = tag.corners
        ptA = (int(ptA[0]), int(ptA[1]))
        ptB = (int(ptB[0]), int(ptB[1]))
        ptC = (int(ptC[0]), int(ptC[1]))
        ptD = (int(ptD[0]), int(ptD[1]))

        cv2.line(image, ptA, ptB, (0, 255, 0), 2)
        cv2.line(image, ptB, ptC, (0, 255, 0), 2)
        cv2.line(image, ptC, ptD, (0, 255, 0), 2)
        cv2.line(image, ptD, ptA, (0, 255, 0), 2)
    output_path = os.path.join(script_dir, "apriltag.jpg")
    cv2.imwrite(output_path, image)
    return output_path
```

#### Describe your issue
I get an error like this : 
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'numpy.typing'

However, when I try to run the Python code only (not using chaquopy), I successfully run my code. Anyone can help me? Thanks

**Comment by mhsmith** [comment]
I assume this is the reason why you needed `numpy >= 1.20`, so let's keep all discussion about that in #1133.
