### ISSUE TITLE
jarray to numpy performance

### ISSUE THREAD

**Issue by jvallsgm** [chaquo/chaquopy#1136]
#### Chaquopy version
15.0.1

#### Devices or emulators where the issue happens
SM-A515F and others

#### Relevant parts of your code
x1_arr = np.array(x1)
x2_arr = np.array(x2)

`x1` and `x2` are jarrays

#### Describe your issue
On some phones, the conversion from jarray to numpy is very slow. To convert two 1-D jarrays with 15000 elements (float) can take about 60 seconds. 

Looking through the documentation and logged issues, I haven't seen an alternative to the one I use. The jarrays are 1-dimensional. 

Is there an alternative to get better conversion performance?

Thanks.

**Comment by mhsmith** [comment]
Fast conversion between Java and NumPy arrays is only possible if their data types match exactly. For example, a Java `float` corresponds to a NumPy `float32`.

**Comment by jvallsgm** [comment]
Thanks for your answer, with `dtype=np.float32` it improves performance by 10%. The problem is that it is still slow, because the app can't take around 50 seconds to convert a 15000 element jarray to numpy. 
Thanks!

**Comment by mhsmith** [comment]
Like I said, are you certain that x1 and x2 are actually jarrays? What's the output of `print(type(x1), type(x2))`?

And are you certain that it's these specific lines of code that are taking a long time?

If you need more help, it would be useful if you posted more of the context of the code, including the details of how the arrays are passed from Java.

**Comment by jvallsgm** [comment]
I think yes, both are jarrays: 
x1 type:  <class 'java.jarray('Ljava/lang/Double;')'>
x2 type:  <class 'java.jarray('Ljava/lang/Double;')'>

From java, arrays are passed like this:
![imagen](https://github.com/chaquo/chaquopy/assets/38186227/14fe298c-458f-43e8-a31a-7fb8b1e146a7)


Thanks

**Comment by mhsmith** [comment]
That's an array of "boxed" Doubles (capital D in Java), not primitive doubles (lower-case D in Java). In Kotlin, the method you want may be [`toDoubleArray`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/to-double-array.html).

Also, a double is a float64, not a float32. But if you fix the first problem, you can probably just remove the `dtype` argument and NumPy will determine it automatically.
