### ISSUE TITLE
Call Python library directly in Java/Kotlin code

### ISSUE THREAD

**Issue by JackEblan** [chaquo/chaquopy#1138]
Is there a way that I can use Python Libraries directly to my Java/Kotlin code without using a Python script and place them to python sourceSet to connect from those?

**Comment by mhsmith** [comment]
Anything in your Python [source directory](https://chaquo.com/chaquopy/doc/current/android.html#android-source) or [requirements](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements) can be accessed from Java/Kotlin by calling [getModule](https://chaquo.com/chaquopy/doc/current/java.html).

If you need more help, please give a specific example.

**Comment by JackEblan** [comment]
Does pip in build.gradle.kts includes the modules in the APK?
