### ISSUE TITLE
scikit-learn version upgrade

### ISSUE THREAD

**Issue by Wafflemannauto** [chaquo/chaquopy#114]
Hi,
You are currently providing scikit-learn version 0.19.1 which is more than one year old.
It would be great if you could additionally provide the newest version of scikit-learn (0.21.2) aswell, since then quite a lot of critical fixes were done.

Thanks for your work anyway!

**Comment by mhsmith** [comment]
OK, we'll look into it.

**Comment by mhsmith** [comment]
Also mentioned in #108.

**Comment by mhsmith** [comment]
scikit-learn version 0.21.2 is now available.
