### ISSUE TITLE
_rust.so is linked against unknown library 'libgcc_s.so.1'

### ISSUE THREAD

**Issue by hongpingwei** [chaquo/chaquopy#1142]
adding 'cryptography-39.0.2.dist-info/top_level.txt'
adding 'cryptography-39.0.2.dist-info/RECORD'
removing build/bdist.linux_aarch64/wheel
build-wheel: mkdir -p /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel
build-wheel: unzip -d /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel -q /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/src/dist/cryptography-39.0.2-cp310-cp310-linux_aarch64.whl
build-wheel: Processing native binaries
build-wheel: mv /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_openssl.abi3.so /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_openssl.so
build-wheel: chmod +w /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_openssl.so
build-wheel: /root/android-sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --strip-unneeded /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_openssl.so
build-wheel: patchelf --remove-rpath /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_openssl.so
build-wheel: mv /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_rust.abi3.so /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_rust.so
build-wheel: chmod +w /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_rust.so
build-wheel: /root/android-sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --strip-unneeded /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_rust.so
build-wheel: Error: /root/chaquopy/server/pypi/packages/cryptography/build/39.0.2/cp310-cp310-android_21_arm64_v8a/fix_wheel/cryptography/hazmat/bindings/_rust.so is linked against unknown library 'libgcc_s.so.1'.
(build-wheel) [root@ecs-weichain pypi]#

**Comment by hongpingwei** [comment]
(base) [root@ecs-weichain ~]# find . / -name libgcc_s.so.1                             
./miniconda3/lib/libgcc_s.so.1
./miniconda3/pkgs/libgcc-ng-11.2.0-h1234567_1/lib/libgcc_s.so.1
./miniconda3/envs/build-wheel/lib/libgcc_s.so.1
/root/miniconda3/lib/libgcc_s.so.1
/root/miniconda3/pkgs/libgcc-ng-11.2.0-h1234567_1/lib/libgcc_s.so.1
/root/miniconda3/envs/build-wheel/lib/libgcc_s.so.1
/usr/lib64/libgcc_s.so.1
(base) [root@ecs-weichain ~]# 

who libgcc_s.so.1 should I   ln -sf to _rust.so   ,  Thanks!

**Comment by mhsmith** [comment]
Sorry, I don't have time to assist in building Rust packages at the moment. But there are some pre-built wheels for Cryptography 39 linked from https://github.com/chaquo/chaquopy/issues/657#issuecomment-1478676407. I haven't tested these wheels myself, so you should only use them for sensitive work if you trust @emanuele-f.

When creating issues in the future, please provide more context , including:
* What you're trying to achieve
* What command you ran
* The content of the recipe you're using
