### ISSUE TITLE
python.exe failted to start

### ISSUE THREAD

**Issue by gitathrun** [chaquo/chaquopy#115]
My system is Windows, and my native python is 2.7. Most of the time, I use anaconda created virtual environment for development, which is python 3.5.

But when I change the Python directory in app level build.gradle, it shows the commnd faild to start.

Then I download python 3.6 and installed natively, pass the directory path to the gradle, it works. is there any permission issue about the python.exe execution?

**Comment by mhsmith** [comment]
Please provide your `buildPython` setting, and the full error message.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information.
