### ISSUE TITLE
BuildPythonException: Unable to create process using 'C:\Users\Vi\AppData\Local\Programs\Python\Python310\python.exe

### ISSUE THREAD

**Issue by Vimal1993** [chaquo/chaquopy#1151]
Unable to create process using 'C:\Users\Vi\AppData\Local\Programs\Python\Python310\python.exe -m chaquopy.pip_install --target F:\project\Vi\app\build\python\pip\debug --android-abis arm64-v8a armeabi-v7a --min-api-level 21 --req Pillow -- --disable-pip-version-check --extra-index-url https://chaquo.com/pypi-13.1 --implementation cp --python-version 3.8.18 --abi cp38 --no-compile'

#### Chaquopy version
com.chaquo.python:gradle:15.0.1

#### Relevant parts of your code
 python {
            pip {
                install 'Pillow'
            }
        }

**Comment by mhsmith** [comment]
Since your app uses Python 3.8 (which is the default in this version of Chaquopy), try downloading Python 3.8 from python.org and installing it with the default settings.

If that doesn't help, please post the full build log.

**Comment by Vimal1993** [comment]
python {
            version "3.12"
 }
        
python {
            pip {
                install 'pillow'
                install 'rembg'
            }
 }

chaquopy {
    defaultConfig {
        buildPython("C:/Users/Vi/AppData/Local/Programs/Python/Python312/python.exe")
        buildPython("C:/Windows/py.exe", "-3.12")
    }
}

![image](https://github.com/chaquo/chaquopy/assets/66515550/6917d3eb-42e8-475d-bd40-6aee4c6cf245)

**Comment by mhsmith** [comment]
See #216, and in future please search the existing issues before asking for help.
