### ISSUE TITLE
user execjs exception Could not find an available JavaScript runtime.

### ISSUE THREAD

**Issue by yangfeng1994** [chaquo/chaquopy#1158]
User com. chaquo. Python: gradle: 14.0.2
Install "PyExecJS"
Use execjs. compile() to display Could not find an available JavaScript runtime How should I solve this problem?

**Comment by mhsmith** [comment]
This package's [PyPI page](https://pypi.org/project/PyExecJS/) says it's no longer maintained, and it hasn't been updated in 6 years, so I suggest you look for an alternative. However, it might be difficult to find one that works on Android, unless there's a pure-Python JavaScript interpreter available.
