### ISSUE TITLE
SentencePiece failt to install

### ISSUE THREAD

**Issue by gitathrun** [chaquo/chaquopy#116]
I try to use pip install in gradle for package "sentencepiece", but it shows:
```
Failed to install sentencepiece from https://files.pythonhosted.org/packages/fd/45/6d0eb609d5cd81df094aab71a867b2ab6b315ffd592e78fb94a625c4d6aa/sentencepiece-0.1.3.tar.gz.
```
Any specific reason for this?

**Comment by mhsmith** [comment]
This is a compiled package so we'd have to build it for Android. It's not a priority at the moment, but we would probably be willing to add it in return for a small payment: please [email us](https://chaquo.com/chaquopy/contact/) if you're interested in this.

If anyone else wants it too, please subscribe to this issue and add a thumbs up to the original post.

**Comment by gitathrun** [comment]
Thanks for the reply, I will consider your advice.

**Comment by mhsmith** [comment]
Let's leave the issue open so it's more visible to other users.

**Comment by gitathrun** [comment]
Oh, since this issue is re-opened, may I ask is there a price standard for a Python library? 

Or the price is changing accordingly?

**Comment by mhsmith** [comment]
There's no standard price: it depends on the complexity of the library. Please [email us](https://chaquo.com/chaquopy/contact/) to discuss your needs.

**Comment by mhsmith** [comment]
SentencePiece version 0.1.95 is now available.
