### ISSUE TITLE
exec and eval with local_var

### ISSUE THREAD

**Issue by anonyein** [chaquo/chaquopy#1163]
Ready check
#### Chaquopy version

15.0.1
#### Describe your issue

I want the Scripts more flexibility, and don't want to write python script before the apk built
1. how to realize the function of exec / eval with local_var and can be used outside the exec sandbox (https://github.com/chaquo/chaquopy/issues/1119)
2. how does [chaquopy](https://github.com/chaquo/chaquopy) treat with the HashMap or Set by fromJava, I could not creat PyObject of just "{}"
Could you help me?

**Comment by mhsmith** [comment]
> how to realize the function of exec / eval with local_var and can be used outside the exec sandbox (https://github.com/chaquo/chaquopy/issues/1119)

You can modify the example in #1119 to keep a reference to the variable dictionary:

```kt
val vars = py.builtins.callAttr("dict")
py.builtins.callAttr("eval", "1+4", vars)
```

> how does [chaquopy](https://github.com/chaquo/chaquopy) treat with the HashMap or Set by fromJava, I could not creat PyObject of just "{}"

Chaquopy doesn't currently support accessing Java Maps or Sets with Python syntax (#1048), so they will appear as generic Java objects. You can access them by calling their Java methods directly.

I don't really understand your example, so please provide a complete code sample if you need more help.

**Comment by anonyein** [comment]
> > how to realize the function of exec / eval with local_var and can be used outside the exec sandbox (#1119)
> 
> You can modify the example in #1119 to keep a reference to the variable dictionary:
> 
> ```kotlin
> val vars = py.builtins.callAttr("dict")
> py.builtins.callAttr("eval", "1+4", vars)
> ```
> 
> > how does [chaquopy](https://github.com/chaquo/chaquopy) treat with the HashMap or Set by fromJava, I could not creat PyObject of just "{}"
> 
> Chaquopy doesn't currently support accessing Java Maps or Sets with Python syntax (#1048), so they will appear as generic Java objects. You can access them by calling their Java methods directly.
> 
> I don't really understand your example, so please provide a complete code sample if you need more help.

I did it by using "exec" and "eval" with globals "{}" in one py file of directory "/python". Thanks for your help!!
