### ISSUE TITLE
error in downloading the sklearn

### ISSUE THREAD

**Issue by Ahmedmohamy** [chaquo/chaquopy#1164]
#### Chaquopy version
15.0.1

#### Relevant parts of your build.gradle file

```
import com.chaquo.python.BUILD_PYTHON_ADVICE
import com.chaquo.python.PythonPlugin
import com.chaquo.python.pythonVersionInfo

plugins {
    id("com.android.application")
    id("com.google.gms.google-services")
    id("com.chaquo.python")
}

android {
    namespace = "com.example.chatbot"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.chatbot"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            // On Apple silicon, you can omit x86_64.
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    dependencies {
        implementation("androidx.appcompat:appcompat:1.6.1")
        implementation("com.google.android.material:material:1.11.0")
        implementation("androidx.constraintlayout:constraintlayout:2.1.4")
        implementation("com.google.firebase:firebase-auth:23.0.0")
        testImplementation("junit:junit:4.13.2")
        androidTestImplementation("androidx.test.ext:junit:1.1.5")
        androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    }
}

chaquopy {
    productFlavors { }
    sourceSets { }

    defaultConfig {
        version = "3.12"
        buildPython("C:/Program Files/Python312/python.exe")
            pip{
                install("pandas")
                install("numpy")
                install("fuzzywuzzy")
                install("scikit-learn==1.0.2")
            }



    }

    sourceSets.getByName("main") {
        setSrcDirs(listOf("src/main/python"))
    }

}
```

#### Describe your issue

please help me as there are always errors when downloading the sklean library i tried alot of things and i dont know what to do now

**Comment by mhsmith** [comment]
We only support certain combinations of Python version and scikit-learn version – see [the repository](https://chaquo.com/pypi-13.1/scikit-learn/) for a full list. "cp" indicates the Python version, so you'll have change the `version` setting to reduce your app's Python version to 3.10 or older.

**Comment by Ahmedmohamy** [comment]
Yes i changed the version to 3.8 but there are still alot of problems regarding errors in the python script in android studio and its connection and stuff in the libraries and i dont know what to do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mhsmith** [comment]
Please read my previous comment again carefully. You'll need to change not only the Python version, but also the scikit-learn version.

If you still need help after that, please post your current `chaquopy` section, and the full build log.

**Comment by Ahmedmohamy** [comment]
If i sent you my codes, can you help me?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mhsmith** [comment]
Please try to solve the problem yourself first, and if you still need help, post the things I mentioned on the GitHub issue.

**Comment by Ahmedmohamy** [comment]
I have spent weeks trying to but there is something in the logic that doesnt add up

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mhsmith** [comment]
OK, but I can't do anything about vague comments like that. If you still need help, please post your current `chaquopy` section, and the full build log.
