### ISSUE TITLE
Is it possible to deepcopy a PyObject?

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#1165]
Is it possible to take a PyObject and make a deepcopy of it so there also exists 2 copies on the Python side?

**Comment by mhsmith** [comment]
You can use the standard Python [`copy`](https://docs.python.org/3/library/copy.html) functions, which can be accessed from Java or Kotlin using `getModule`.

**Comment by IsakTheHacker** [comment]
Thank you, I will try that
