### ISSUE TITLE
Version update of the scipy package

### ISSUE THREAD

**Issue by louis-van-der-stam** [chaquo/chaquopy#1166]
We are trying to make an Android app around a python project. The python project uses a newer version of scipy than what the platform provides. We are using scipy.integrate.simpson and in the Android environment switched to using scipy.integrate.simps  (simps not simpson). The results with the latest version are slightly different and cause bigger errors later in the process due to accumulation of errors/differences.

I looked at building the wheel for scipy, but it seems like it is quite complex...

Currently we use the python 3.8 environment, due to the unavailability of a scipy version in a 3.10 environment.

Are there any plans to build a package of a recent version of scipy for python 3.10?

**Comment by mhsmith** [comment]
As you can see from [the repository](https://chaquo.com/pypi-13.1/scipy/), the newest SciPy we provide for Python 3.10 is version 1.8.1. This is a couple of years old, but it appears that `scipy.integrate.simpson` was [added in version 1.6.0](https://docs.scipy.org/doc/scipy/release/1.6.0-notes.html#scipy-integrate-improvements), so it should work for you.

If you have any other need for a new version of SciPy, please post the details in #1040.
