### ISSUE TITLE
AttributeError: 'HalfBinomialLoss' object has no attribute 'get_init_raw_predictions'

### ISSUE THREAD

**Issue by FishWaterUnder** [chaquo/chaquopy#1167]
#### Chaquopy version

Version 3.9

#### Devices or emulators where the issue happens

TECHNO KI5K phone
#### Relevant parts of your code

```
import numpy as np
import pandas as pd
from os.path import dirname, join
from landmarkers import landmarkers
import pickle
import sklearn

def henllo(lk):
    filename = join(dirname(__file__), "bicep_Curls.pk1")
    with open(filename, 'rb') as f:
        model = pickle.load(f)

    row =[lk.get(i) for i in range(lk.size())]
    X = pd.DataFrame([row], columns = landmarkers)
    bodylang_class = model.predict(X)[0]
    print(bodylang_class)
```

#### Describe your issue

I tried to run a machine learning algorithm using a pickle file but it gave me this error

`JNI DETECTED ERROR IN APPLICATION: JNI GetObjectClass called with pending exception java.lang.IllegalStateException: com.chaquo.python.PyException: AttributeError: 'HalfBinomialLoss' object has no attribute 'get_init_raw_predictions'`

I followed this person in #160 but theirs work I believe when my doesn't

**Comment by mhsmith** [comment]
If you search for this error, you'll find https://github.com/scikit-learn/scikit-learn/issues/14076, which says:

> While models saved using one version of scikit-learn might load in other versions, this is entirely unsupported and inadvisable.

So you'll have to either:

* Regenerate the model with the same version of scikit-learn as you're using with your app; or
* Make your app use a different scikit-learn version which is closer to the version that generated the model. Unfortunately there are only a [few versions available](](https://chaquo.com/pypi-13.1/scikit-learn/).

**Comment by mhsmith** [comment]
There may still be a Chaquopy bug here, because it should have produced a regular Java exception rather than a JNI error. But I have no other reports of this happening, so in order to look into it, I would need a complete and self-contained example.

**Comment by FishWaterUnder** [comment]
Thank You! It worked
