### ISSUE TITLE
UnsatisfiedLinkError when using PyApplication

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#117]
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1016)
  at java.lang.System.loadLibrary (System.java:1657)
  **at com.chaquo.python.android.AndroidPlatform.loadNativeLibs (AndroidPlatform.java:228)
  at com.chaquo.python.android.AndroidPlatform.getPath (AndroidPlatform.java:107)
  at com.chaquo.python.Python.start (Python.java:50)
  at com.chaquo.python.android.PyApplication.onCreate (PyApplication.java:16)
  at com.testdemo.App.onCreate (App.java:45)**
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1125)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6062)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1764)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by mhsmith** [comment]
What device, and what Android version?

And does the app work on other devices?

**Comment by chaocharleswang** [comment]
I found the error on the following two devices:
Xiaomi MI 9 SE (grus), Android 9
Samsung Galaxy S7 edge (hero2lte), Android 8.0

**Comment by mhsmith** [comment]
And does the same app work on other devices or emulators? If so, which ones?

**Comment by mhsmith** [comment]
One other idea: I notice that both of these devices support arm64-v8a. armeabi-v7a apps should certainly work on arm64 devices, but it might be worth enabling arm64-v8a in `abiFilters` to see if it makes a difference.

**Comment by chaocharleswang** [comment]
Do I need to change it to the following one:

    flavorDimensions "abi"
    productFlavors {
        arm {
            dimension "abi"
            ndk { abiFilters "armeabi-v7a", "arm64-v8a" }
        }
        x86 {
            dimension "abi"
            ndk { abiFilters "x86", "x86_64" }
        }
    }

**Comment by mhsmith** [comment]
First I'd just try adding `arm64-v8a` to your existing `abiFilters`. The flavor dimension is only needed if you want to reduce the size of your publicly-released app by not including the x86 ABIs.

Does the same app work on other devices or emulators? If so, which ones?

**Comment by chaocharleswang** [comment]
It works on my following devices:
HUAWEI FRD-L04 (Android 7.0, API 24)
Google Pixel (Android 9, API 28)
Samsung SM-T713 (Android 7.0, API 24)

But not work for the following ones:
Huawei P30 Pro (HWVOG), Android 9
Xiaomi MI 9 SE (grus), Android 9

**Comment by chaocharleswang** [comment]
Updated:
defaultConfig {
	    ndk {
	       abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
	    }
	}

However, the error still exists.

It works on my following devices:
HUAWEI FRD-L04 (Android 7.0, API 24)
Google Pixel (Android 9, API 28)
Samsung SM-T713 (Android 7.0, API 24)

But not work for the following ones:
Huawei P30 Pro (HWVOG), Android 9
Xiaomi MI 9 SE (grus), Android 9
Samsung Galaxy S7 edge (hero2lte), Android 8.0
Samsung Galaxy A40 (a40), Android 9

**Comment by mhsmith** [comment]
Are you getting these crash reports from Google Play? If so, can you give a link to your app so I can have a look at it?

If you're able to reproduce the crash with one of your own devices, are there any other relevant messages in the logcat?

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information.

**Comment by mhsmith** [comment]
Hi,

Did you ever manage to solve this problem?

**Comment by mhsmith** [comment]
@chaocharleswang Did you ever manage to solve this problem?

**Comment by mhsmith** [comment]
> But not work for the following ones:
> Huawei P30 Pro (HWVOG), Android 9
> Xiaomi MI 9 SE (grus), Android 9
> Samsung Galaxy S7 edge (hero2lte), Android 8.0
> Samsung Galaxy A40 (a40), Android 9

Are these your own devices, or were they all Google Play crash reports?

**Comment by mhsmith** [comment]
This may be caused by changing `abiFilters` in your build.gradle file. The removed ABIs will no longer be built, but I've had reports that some of their libraries can still be included in the APK. This could cause a 64-bit device to run the app as a 64-bit process even though it doesn't have a full set of 64-bit libraries.

You should be able to resolve this by running Build > Clean Project in Android Studio.
