### ISSUE TITLE
cryptography for Python 3.11 or later

### ISSUE THREAD

**Issue by pay748** [chaquo/chaquopy#1175]
Is it possible to add python 3.11 build wheel support to the cryptography library? I need to use some asyncio low level socket methods (sock_recvfrom, sock_recvfrom_into, sock_sendto) they were added in python3.11, they are not available on python3.10. Anyway thanks for your work.Especially after discovering chaquo, it feels like opening the door to a new world. There is nothing cooler than being able to develop android apps with hybrid development using python. Thanks anyway for your work.This is really an amazing and great project!
[Low-level asynchronous socket methods added in python version 3.11](https://docs.python.org/zh-cn/3.11/library/asyncio-eventloop.html#working-with-socket-objects-directly)

**Comment by mhsmith** [comment]
Thanks, that's great to hear.

[`cryptography` 3.4.8](https://pypi.org/project/cryptography/3.4.8/#files) came out in August 2021, before Python 3.11, and even before a stable release of Python 3.10. However, we have [already built it for Android](https://chaquo.com/pypi-13.1/cryptography/) on Python 3.10, so it's possible it could be built for Python 3.11 as well.  If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md), and see the special notes in the cryptography [meta.yaml file](https://github.com/chaquo/chaquopy/blob/master/server/pypi/packages/cryptography/meta.yaml).

Ideally we would move to a newer version of `cryptography` which supports Python 3.11 officially, but that's currently blocked by #657.
