### ISSUE TITLE
Failed to install qreader python package

### ISSUE THREAD

**Issue by inzimamulhaq09** [chaquo/chaquopy#1177]
I'm working on a project in which I'm using the qreader package(it detects and decodes multiple QR codes in an image) in Python which works fine on both Python 3.8 and 3.12 while I work with it in notebooks.
As it has dependencies on various other packages, that's why it fails when I try to use it in Android with Chaquopy.
It requires ultralytics, seaborn, opencv-python, scipy, torch, torchvision, numpy and some other libraries, some of these get installed but it fails while installing seaboarn and opencv-python.
Chaquopy works with an older version of qreader, but unfortunately, that older version of qreader only detects a single QR code in an image, which is not enough for my project.

**Comment by mhsmith** [comment]
Please post:

* The `python` or `chaquopy` sections of your build.gradle file.
* The full build log: you can display it by clicking the “Build: failed” caption to the left of the error message.

**Comment by mhsmith** [comment]
If you still need help, please post the requested information, and I'll reopen the issue.
