### ISSUE TITLE
Tensorflow TypeError only in android

### ISSUE THREAD

**Issue by 298068845** [chaquo/chaquopy#1178]
#### Chaquopy version

10.0.1

#### Relevant parts of your build.gradle file

python 3.8.7

In Android Studio 4.1.3
I want to read image with this code:

tf.compat.v1.disable_eager_execution()
gt_connets = tf.io.read_file(filename)

app will throw error:
TypeError: list indices must be integers or slices, not str

I can use this code in pc to read image without error,every one tell me the "filename" type is String

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/1069#issuecomment-1882655659, and in future please search the existing issues before creating new ones.
