### ISSUE TITLE
Unable to Install llama-index package on chaquopy

### ISSUE THREAD

**Issue by pmr99** [chaquo/chaquopy#1187]
I am able to successfully run a simple python script that loads on an emulator but once I use a function that leverages llama-index, it fails. Tried adding the package to gradle as well. 

#### Chaquopy version

id("com.chaquo.python") version "15.0.1

#### Relevant parts of your build.gradle file

```
chaquopy {
    defaultConfig {
        version = "3.8"
        pip {
            // A requirement specifier, with or without a version number:
            install("pip")
            install("setuptools")
            //install("pydantic==1.10.2")
            install("llama-index")
        }
    }
    sourceSets {
        getByName("main") {
            srcDir("kotlin/data/python")
        }
    }

}

android {
    namespace = "com.google.ai.sample"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.google.ai.sample"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        ndk {
            // On Apple silicon, you can omit x86_64.
            abiFilters += listOf("arm64-v8a", "x86_64")
        }

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }
```
<img width="1379" alt="Screenshot 2024-06-22 at 12 02 35 PM" src="https://github.com/chaquo/chaquopy/assets/65054576/c4e15361-7d30-4b33-b3cd-07a374eff096">

**Comment by mhsmith** [comment]
This build.gradle file can't even be built, so the app you're testing must be a different version.

The reason it can't be built is that `llama-index` depends on at least two binary packages that we don't yet support:

* #1017 – This can be worked around by forcing version 1, as I see you've already tried.
* #828 – I don't know of any workaround for this. Please subscribe to the other issue for updates.
