### ISSUE TITLE
Please add ChatterBot package

### ISSUE THREAD

**Issue by sundaramgupta** [chaquo/chaquopy#119]

**Comment by mhsmith** [comment]
The blocker appears to be the requirement `spacy<2.2,>=2.1`. I'll add an updated version of spacy to our repository and get back to you.

**Comment by mhsmith** [comment]
Unfortunately we can't provide this version of spacy, for the reason explained in #121. However, you can avoid the dependency by using a slightly older version of ChatterBot:

```
pip {
    install "ChatterBot==1.0.4"
}
```

**Comment by mhsmith** [comment]
See #500 for updates.
