### ISSUE TITLE
Failed to build rpds-py whl: build-wheel: rpds.so is linked against unknown library 'libgcc_s.so.1'.

### ISSUE THREAD

**Issue by Yemaoxin** [chaquo/chaquopy#1193]
#### Relevant parts of your build.gradle file 

build_wheel.py 
build 
package:
  name: rpds_py
  version: "0.18.1"
#### Describe your issue

 python3.8 ./build-wheel.py --python 3.8 --abi x86_64 rpds-py
 
When I want to build notebook in Chaquopy, it stop at install rpds-py.
When I want to build whl for rdps-py , build-wheel: Error: /home/ymx/chaquopy-15.0.1/server/pypi/packages/rpds-py/build/0.18.1/cp38-cp38-android_21_x86_64/fix_wheel/rpds/rpds.so is linked against unknown library 'libgcc_s.so.1'.

**Comment by mhsmith** [comment]
Moved to #1192. Please don't create multiple issues about the same thing.
