### ISSUE TITLE
An exception occurred applying plugin request [id: 'com.chaquo.python'] > Failed to apply plugin 'com.chaquo.python'

### ISSUE THREAD

**Issue by surajsahani** [chaquo/chaquopy#1194]
> Could not find matching constructor for: com.android.build.gradle.internal.api.DefaultAndroidSourceDirectorySet(String, org.gradle.api.internal.project.DefaultProject_Decorated, com.android.build.gradle.internal.api.artifact.SourceArtifactType$JAVA_SOURCES)
   
#### Chaquopy version

10.0.1

#### Describe your issue

This version of chaquopy is not building on latest version of android plugins

Also after updating it to latest version not able to proceed forward 

`This version of Chaquopy has not been tested with Android Gradle plugin versions beyond 7.0.2. If you experience problems, please edit the version of com.android.tools.build:gradle in your top-level build.gradle file. See https://chaquo.com/chaquopy/doc/current/versions.html.
`

**Comment by mhsmith** [comment]
> Also after updating it to latest version not able to proceed forward
> 
> `This version of Chaquopy has not been tested with Android Gradle plugin versions beyond 7.0.2. If you experience problems, please edit the version of com.android.tools.build:gradle in your top-level build.gradle file. See https://chaquo.com/chaquopy/doc/current/versions.html. `

You can't have updated it correctly, because the latest Chaquopy version doesn't give the "has not been tested" warning anymore. The latest version is 15.0.1, and the instructions for using it are [here](https://chaquo.com/chaquopy/doc/current/android.html).
