### ISSUE TITLE
Update spacy

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#121]
Spacy version 2.1 cannot currently be released for Chaquopy, because it depends on blis, which doesn't have working support for ARM or ARM64.

https://github.com/explosion/spaCy/issues/3861
https://github.com/explosion/spaCy/issues/3451
https://github.com/explosion/cython-blis/issues/9

**Comment by honnibal** [comment]
Installation should now be possible, although it requires a bit of indirection (so maybe you still can't update the dependency). See here: https://github.com/explosion/cython-blis/issues/9

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
