### ISSUE TITLE
Install package at app runtime

### ISSUE THREAD

**Issue by deva666** [chaquo/chaquopy#1218]
Is this even possible? 
Something like this
```
import sys
import subprocess
subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'numpy'])
```
But `sys.executable` is not available at runtime, any other way maybe?

**Comment by deva666** [comment]
I tried to install it with [get-pip.py](https://pip.pypa.io/en/stable/installation/#get-pip-py) bootstrapping script and the installation was successful, I can `import pip` in the code. But when I try to install a package with `pip.main(['install', 'numpy']` I get FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/cache/chaquopy/tmp/tmpx9t9bvg5/pip.zip'

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/623#issuecomment-2079196964.
