### ISSUE TITLE
Open source license request 

### ISSUE THREAD

**Issue by daniel-sudz** [chaquo/chaquopy#122]
I have sent an email to contact@chaquo.com but I'm posting here as well as it time sensitive to me. Sorry for the duplicate.

I would like to apply for a license for my chaquopy project. The end goal of my app is to be a full featured mobile wrapper for the popular youtube-dl python project. Currently my app is only able to download a video file given a link. 

Details: 
applicationId "com.dansudz.youtube_dlunnoficialmobile"
source code: https://github.com/daniel-sudz/youtubedl-mobile/tree/master
distribution method: google play store 
licensing: MIT open source license

Thanks, 
Daniel

**Comment by mhsmith** [comment]
Sorry for the delay, I'll respond to your email right now.
