### ISSUE TITLE
How can I cache python library with Chaquopy and Github Actions?

### ISSUE THREAD

**Issue by thaidmfinnick** [chaquo/chaquopy#1221]
Hi @mhsmith, thank you for Chaquopy, I used it a lot in my Flutter apps. I am building CICD with Github Actions.

In build step, each time I build, I realize server will download python packages again, I want to cache them to improve build time.
![Screenshot 2024-07-24 at 12 11 05](https://github.com/user-attachments/assets/8fdf92a9-90ca-48c7-ab73-03c5ca5aefe5)

Can I cache them? I cannot find where Chaquopy store files.

Hope you can reply. 
Thank you!

**Comment by mhsmith** [comment]
On Linux these files will be cached in $HOME/.cache/chaquopy.

**Comment by thaidmfinnick** [comment]
Thanks for response!

Now, I can cache chaquopy folder, but how chaquopy know if I add new package. Does chaquopy have a file something like `requirements.txt`? 
I want identify new packages and get them.

**Comment by mhsmith** [comment]
Chaquopy can use a requirements.txt file as shown in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements), or you can list the packages directly in your build.gradle file. You could use either of those files to decide when to update your cache.

However, all of these packages are already coming from fast servers, so before you make this any more complex, I suggest you measure whether the cache really makes any difference.

**Comment by thaidmfinnick** [comment]
I agree, seems the packages were loaded very fast. My cache is around 90MB, so it doesn't make too much difference.

I will close issue now. Thank you for your response and hope Chaquopy will grow more!
