### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by p1anuj2** [chaquo/chaquopy#1223]
The following versions:

1 .classpath 'com.chaquo.python:gradle:15.0.0'
2. 'com.android.tools.build:gradle:4.0.2'
3. 
![Screenshot 2024-07-26 112729](https://github.com/user-attachments/assets/69dea4d4-e5b0-4320-bc53-aea7b650dfe4)
python {
// buildPython "C:/Users/DELL1/AppData/Local/Programs/Python/Python39/python.exe"
pip{
install "numpy"
install "scipy"
install "pandas"
// install "smt"
install "crccheck"
}
}
ndk {
abiFilters "arm64-v8a", "x86_64"

**Comment by mhsmith** [comment]
See #1217, and please don't create multiple issues about the same thing.
