### ISSUE TITLE
Changed package name requires new licence 

### ISSUE THREAD

**Issue by daniel-sudz** [chaquo/chaquopy#123]
I needed to change my package name to not be violating google's TOS. Could I get a new open source license generated?

Migration: https://github.com/daniel-sudz/youtubedl-mobile/ to: 
 https://github.com/daniel-sudz/simple-dl

Package name: 
com.dansudz.youtube_dlunnoficialmobile to com.dansudz.simpledl

Thank You,
Daniel Sudzilouski

**Comment by mhsmith** [comment]
I've answered your email. For any further license issues, please use email, not GitHub.
