### ISSUE TITLE
Can't upgrade numpy library from 1.19 to 1.23.3

### ISSUE THREAD

**Issue by osama-shehab** [chaquo/chaquopy#1234]
Failed to install numpy==1.23.3 from https://files.pythonhosted.org/packages/0a/88/f4f0c7a982efdf7bf22f283acf6009b29a9cc5835b684a49f8d3a4adb22f/numpy-1.23.3.tar.gz#sha256=51bf49c0cd1d52be0a240aa66f3458afc4b95d8993d2d04f0d91fa60c10af6cd.

**Comment by mhsmith** [comment]
As you can see from [the repository](https://chaquo.com/pypi-13.1/numpy/), NumPy 1.23.3 is only available for Python 3.9, 3.10 and 3.11. To change your app's Python version, follow the instructions [here](https://chaquo.com/chaquopy/doc/current/android.html#python-version).
