### ISSUE TITLE
_ctypes not found

### ISSUE THREAD

**Issue by rkbroder** [chaquo/chaquopy#1241]
working with existing scripts. I added code that required upgrading from 3.8 to >=3.10. Installed 3.12 on RHEL Linux and when running the code I get an immediate error loading PYMIQ with a _ctype module not found.

I have tried all the suggestions I found online. Still have the issue. I did originally build the 3.8 manually. I do not see the setup.py file in the root directory of the unzipped downloaded file. Was going to try manually building PYMQI.

During te reinstall of Python 3.12 I check the output and it said the ctypes was found and is OK.

**Comment by mhsmith** [comment]
> I get an immediate error loading PYMIQ with a _ctype module not found.

Please post the full error.

> I did originally build the 3.8 manually. 

Built what exactly, and how?

>  I do not see the setup.py file in the root directory of the unzipped downloaded file. 

What file?

> I check the output and it said the ctypes was found and is OK.

What output? Please post it here.

**Comment by rkbroder** [comment]
Malcom,
Thanks for answering. I rebuild PYTHON and PYMQI 4 times. The 4th time was the clincher. The error went away.


Bobbee Broderick (917) 453-6790

Don’t look back, you are not going in that direction!

From: Malcolm Smith ***@***.***>
Sent: Tuesday, September 10, 2024 11:22 AM
To: chaquo/chaquopy ***@***.***>
Cc: Robert K Broderick ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [chaquo/chaquopy] _ctypes not found (Issue #1241)

I get an immediate error loading PYMIQ with a _ctype module not found. Please post the full error. I did originally build the 3. 8 manually. Built what exactly, and how? I do not see the setup. py file in the root directory of the unzipped downloaded


I get an immediate error loading PYMIQ with a _ctype module not found.

Please post the full error.

I did originally build the 3.8 manually.

Built what exactly, and how?

I do not see the setup.py file in the root directory of the unzipped downloaded file.

What file?

I check the output and it said the ctypes was found and is OK.

What output? Please post it here.
