### ISSUE TITLE
Error during build-wheel processing

### ISSUE THREAD

**Issue by ytremare** [chaquo/chaquopy#1246]
Error : build-wheel.py: Error: /home/ytrem/miniconda3/chaquopy-eccodes/server/pypi/packages/libaec/build/1.1.2/py3-none-android_21_x86_64/fix_wheel/chaquopy/lib/**libaec.so has no .dynamic section**

link to Fork [https://github.com/ytremare/chaquopy](url)

[resu_libaec.txt](https://github.com/user-attachments/files/17119294/resu_libaec.txt)

Environment: 
miniconda3 with python 3.11.9
[resu_libaec.txt](https://github.com/user-attachments/files/17119281/resu_libaec.txt)
.

**Comment by ytremare** [comment]
Please find attach full build log.
[resu_libaec.txt](https://github.com/user-attachments/files/17126333/resu_libaec.txt)
Please find attach result_readelf.txt dump for the current build and in resu_libaec_old_laptop.txt dump from my oldlaptop which was working.
[resu-readelf_old_laptop.txt](https://github.com/user-attachments/files/17126402/resu-readelf_old_laptop.txt)
[resu-readelf_libaecf.txt](https://github.com/user-attachments/files/17126403/resu-readelf_libaecf.txt)

**Comment by mhsmith** [comment]
Strange, it looks like libaec.so is being built correctly with `-shared`, and readelf shows that it does have a dynamic section. Can you attach libaec.so to this issue, or upload it somewhere else and post a link?

**Comment by ytremare** [comment]
You're rihght. whl file is generated in /home/ytrem/miniconda3/chaquopy-eccodes/server/pypi/packages/libaec/build/1.1.2/py3-none-android_21_x86_64/src .  It seems the tool fails in some checks.

File is available at (you eM is allowed for downloading.
https://drive.google.com/file/d/1MuBwC4nqHLrPMVS9ic400EHKbXIxoBWj/view?usp=drive_link

**Comment by mhsmith** [comment]
Sorry, I don't have access to that link.

**Comment by ytremare** [comment]
I've updated google drive allowing acces to **notifications@github.com**  email.  https://drive.google.com/drive/folders/1T1kAl9z0etMSLa5yJOpNaxMcXIrFAj76
In case access is not working as the
 tool dosn't allow .so file I've rename it .so.txt, hope it won't be altered.
[libaec.so.txt](https://github.com/user-attachments/files/17186057/libaec.so.txt)

**Comment by ytremare** [comment]
I run some tests to check generated whl files. I move the whl file from build folder, unfortunately it dosn't work. Even the app build is done without failure, while app invoke the eccodes lib I get the following error: **RuntimeError: Could not load the ecCodes library!**
.

**Comment by ytremare** [comment]
I run some tests to check generated whl files. I move the whl file from build folder to my local Dist folder, unfortunately it doesn't work. Even the app build is done without failure, while app invokes the eccodes lib I get the following error: RuntimeError: Could not load the ecCodes library!

**Comment by ytremare** [comment]
I re-install all the environment et take particularly care of python requirements, Build processing is now running successfully. I guess i can close the issue.

**Comment by mhsmith** [comment]
> I've updated google drive allowing acces to notifications@github.com

That won't work, because that obviously isn't the address of my Google account. But in general, it's better to attach files on GitHub so anyone can access them.
