### ISSUE TITLE
Unable to install any version of mediapipe with python version 3.11 and above in Android build.gradle

### ISSUE THREAD

**Issue by rajputashu** [chaquo/chaquopy#1247]
chaquopy {
        defaultConfig {
            buildPython(".../Python312/python.exe") // Using my original path to python.exe
            pip {
                install("opencv-python")
                install("mediapipe==0.10.15") // Getting error for this lib
            }
        }
    }

Getting below error while running the app

ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.15 (from versions: none)
ERROR: No matching distribution found for mediapipe==0.10.15
Could not find a version that satisfies the requirement mediapipe==0.10.15 (from versions: none)

No matching distribution found for mediapipe==0.10.15

Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
See #479, and in future please search the existing issues before creating new ones.
