### ISSUE TITLE
ERROR: Failed to install llama_cpp_python==0.2.90 

### ISSUE THREAD

**Issue by wangminrui2022** [chaquo/chaquopy#1252]
#### Chaquopy version

15.0.1
#### Relevant parts of your build.gradle file

plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.chaquo.python.console'
    compileSdk = 34
    defaultConfig {
        applicationId "com.chaquo.python.console"
        minSdk = 21
        targetSdk = 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        python {
            pip {
                install "six"
                install "llama_cpp_python-0.2.90.tar.gz"
            }
        }
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
    testImplementation 'androidx.arch.core:core-testing:2.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}

#### Describe your issue

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/tmp/tmpts_ovdbu/build/CMakeFiles/CMakeOutput.log".
*** CMake configuration failed
----------------------------------------
ERROR: Failed to install llama_cpp_python==0.2.90 from file:///home/ai-wmr/workspace/project/chaquopy-console/app/llama_cpp_python-0.2.90.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
See #1094, and in future please search the existing issues before creating new ones.
