### ISSUE TITLE
build-wheel gives SSLError: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#1255]
_Originally posted by @RicBar10 in https://github.com/chaquo/chaquopy/issues/863#issuecomment-2379469889_

Hello, last week I tried with the command line ./build-wheel.py --python 3.10 --abi arm64-v8a /home/developer/chaquopy/server/pypi/packages/asammdf/ 
and with this in my meta.yaml:
![image](https://github.com/user-attachments/assets/01028dec-c80d-4f9b-8922-d24ccc9e3e4c)

But I'm having these errors about ssl certificate:
![image](https://github.com/user-attachments/assets/f9082f93-08cf-45fe-93d1-e560e5426283)

I need to check my network connection

**Comment by mhsmith** [comment]
Possible causes:
* Are you using a broken proxy?
* Have you installed everything in server/pypi/requirements.txt?
* Are you using an up to date version of Python?

If you still need help, please let me know exactly which version of Python you're using, how you installed it, and what operating system you're using.

**Comment by RicBar10** [comment]
- I'm using a private proxy.
- I installed evrything of requirements.txt -->
 ![image](https://github.com/user-attachments/assets/ddc4ebe3-a2fa-438d-a1ea-e5574778ceb4)
- I'm using python 3.10.12

**Comment by mhsmith** [comment]
Then maybe your proxy is broken, or maybe you're not using the proxy when you should be. Check your environment variables as shown [here](https://requests.readthedocs.io/en/latest/user/advanced/#proxies).
