### ISSUE TITLE
 ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by lachung305** [chaquo/chaquopy#1256]
ERROR: Command errored out with exit status 1:      command: 'C:\Users\Sir\Desktop\ChatGptApp\app\build\python\env\debug\Scripts\python.exe' 'C:\Users\Sir\Desktop\ChatGptApp\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Sir\AppData\Local\Temp\tmpe4apgmwc'

**Comment by mhsmith** [comment]
Please post the following:

#### Chaquopy version
The version of com.chaquo.python:gradle in your app's top-level build.gradle file.

#### Relevant parts of your build.gradle file
Please include at least the "chaquopy", "python" and "ndk" sections.

#### The complete build log
To display it, click the “Build: failed” caption to the left of the error.

**Comment by mhsmith** [comment]
If you still need help, please post the information requested above, and I'll reopen the issue.
