### ISSUE TITLE
Tensorflow -Keras on Android (Validation Accuracy is Zero)

### ISSUE THREAD

**Issue by AyeshaGurnani** [chaquo/chaquopy#126]
Hello,

I am trying to train a model using Tensorflow - Keras in Chaquopy, I use a Sequential CNN to train the model. However the model is perfectly training on my Laptop, but when I put the same model in my Android App, it shows validation accuracy as 0.0. I don't really understand what is wrong here. Please help.

Here is my code.

```
def load_model(n_classes, file):
    model = Sequential()
    model.add(Conv1D(32, (3), input_shape=(20, 1)))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))

    model.add(Conv1D(64, (3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))

    model.add(Dropout(0.5))
    model.add(Conv1D(128, (3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv1D(128, (3)))
    model.add(Activation('relu'))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dense(n_classes, activation='softmax'))
    model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=["accuracy"])
    model.summary()
    X_train, Y_train =load_data(file)
    print(Y_train)
    batch_size = 4
    model.fit(X_train, Y_train, batch_size, epochs=20, validation_split=0.2, shuffle=False)
    save_model(model, 'keras_model.h5')
```

**Comment by mhsmith** [comment]
Can you provide a simple self-contained example, including the test data and the expected results?

**Comment by AyeshaGurnani** [comment]
This is my function. 


def load_model(n_classes, file):
    model = Sequential()
    model.add(Conv1D(32, (3), input_shape=(20, 1)))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))

    model.add(Conv1D(64, (3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))

    model.add(Dropout(0.5))
    model.add(Conv1D(128, (3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv1D(128, (3)))
    model.add(Activation('relu'))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dense(n_classes, activation='softmax'))
    model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=["accuracy"])
    model.summary()
    X_train, Y_train =load_data(file)
    print(Y_train)
    batch_size = 4
    model.fit(X_train, Y_train, batch_size, epochs=20, validation_split=0.2, shuffle=False)
    return None

This is the result when I train the model on my Laptop.
<img width="682" alt="modellaptop" src="https://user-images.githubusercontent.com/25550360/61822448-26d19780-ae1f-11e9-86cf-a8f73d53dfd9.PNG">

This is the result when I train on the Android.
<img width="869" alt="modelandroid" src="https://user-images.githubusercontent.com/25550360/61822517-4ff22800-ae1f-11e9-8c70-bc413cfc76e8.PNG">

**Comment by mhsmith** [comment]
I can't look into this unless you give me something I can run myself, including the test data. If you can't provide your actual data, can you come up with a simpler example?

**Comment by AyeshaGurnani** [comment]
Let me know if you need anything else. n_classes = 3

[train.zip](https://github.com/chaquo/chaquopy/files/3428743/train.zip)

**Comment by mhsmith** [comment]
I think I can guess what `load_data` does, but can you provide it anyway?

**Comment by AyeshaGurnani** [comment]
def get_samples(file):
    data = genfromtxt(file, delimiter=",")
    data = np.around(data, decimals=4)
    return data[:, 0:20] , data[:, -1]

def load_data(file):
    X, Y = get_samples(file)
    X = X.reshape(X.shape[0], 20, 1)
    encoder = LabelEncoder()
    encoder.fit(Y)
    encoded_Y = encoder.transform(Y)
    return X, encoded_Y

**Comment by AyeshaGurnani** [comment]
Can you help, please!!

**Comment by mhsmith** [comment]
I think this is something to do with the version of TensorFlow. With TensorFlow 1.10.1 and 1.13.1 on Linux, I can reproduce your Android results exactly. With version 1.14.0 (the current stable version), I get a different result:

```
Epoch 20/20
207/207 [==============================] - 1s 3ms/sample - loss: 3.8686e-06 - acc: 1.0000 - val_loss: 7.9069 - val_acc: 0.4808
```

What version of TensorFlow are you using on your laptop?

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information. We would probably provide a newer version of TensorFlow on request, as long as it was a stable version and not a pre-release.

**Comment by mhsmith** [comment]
For future reference, here is a self-contained script:

```
from os.path import dirname, join

from numpy import *
from tensorflow.keras import *
from tensorflow.keras.layers import *


def main():
    load_model(3, join(dirname(__file__), "train.csv"))


def load_model(n_classes, file):
    model = Sequential()
    model.add(Conv1D(32, (3), input_shape=(20, 1)))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Conv1D(128, (3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv1D(128, (3)))
    model.add(Activation('relu'))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dense(n_classes, activation='softmax'))
    model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=["accuracy"])
    model.summary()
    X_train, Y_train =load_data(file)
    print(Y_train)
    batch_size = 4
    model.fit(X_train, Y_train, batch_size, epochs=20, validation_split=0.2, shuffle=False)


def get_samples(file):
    data = genfromtxt(file, delimiter=",")
    data = np.around(data, decimals=4)
    return data[:, 0:20] , data[:, -1]


def load_data(file):
    X, Y = get_samples(file)
    X = X.reshape(X.shape[0], 20, 1)
    encoder = LabelEncoder()
    encoder.fit(Y)
    encoded_Y = encoder.transform(Y)
    return X, encoded_Y
```

**Comment by fozbolt** [comment]
Hello, I got error in Keras: "ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow". Does Chaquopy now support tensorflow 2.2.0?

**Comment by mhsmith** [comment]
As it says [here](https://github.com/keras-team/keras/releases/tag/2.4.0), the standalone `keras` package is no longer maintained, so you should use the copy which comes with TensorFlow instead. Simply remove `keras` from your build.gradle file, and replace all `keras` imports in your code with `tensorflow.keras`.
