### ISSUE TITLE
We use cloud build to package APK, but cloud build does not have a Python environment. How to package Python into offline lib

### ISSUE THREAD

**Issue by zuoni1018** [chaquo/chaquopy#1260]
We use cloud build to package APK, but cloud build does not have a Python environment. How to package Python into offline lib

**Comment by mhsmith** [comment]
According to [this page](https://cloud.google.com/build/docs/cloud-builders), Cloud Build can use any Docker image, which means it can provide any tools you want, including Python. But I've never used this service, so I can't give any more specific advice.
