### ISSUE TITLE
Add pip uninstall

### ISSUE THREAD

**Issue by rbebb** [chaquo/chaquopy#1265]
This may seem like an odd feature request at first, but I’d love to have the ability to pip uninstall packages during the build process. Sometimes packages install several other packages to enable features that you don’t actually use, so being able to uninstall them would be great from both a storage and security perspective.

**Comment by mhsmith** [comment]
Thanks for the request. I don't think this is a common enough situation to be worth supporting directly, but there's a fairly simple workaround at https://github.com/chaquo/chaquopy/issues/807#issuecomment-1416742815.

**Comment by rbebb** [comment]
Ok I appreciate you linking the workaround!
