### ISSUE TITLE
Unable install latest version of transformers 4.45.2 and langchain

### ISSUE THREAD

**Issue by onkar-n** [chaquo/chaquopy#1268]
Use with transformers
Starting with transformers >= 4.43.0 onward, you can run conversational inference using the Transformers pipeline abstraction or by leveraging the Auto classes with the generate() function.

Make sure to update your transformer installation via pip install --upgrade transformers.

**Comment by mhsmith** [comment]
See #607, and in future please search the existing issues before creating new ones.
