### ISSUE TITLE
Opening file from chaquopy

### ISSUE THREAD

**Issue by Jbiloki** [chaquo/chaquopy#127]
Is there a way to open a file from assets in python?

**Comment by mhsmith** [comment]
The easiest solution is probably to move your file from the asset folder into the Python source folder, then you can access it using one of the ways described [here](https://chaquo.com/chaquopy/doc/current/android.html#resource-files).

Or if you must use an Android asset, there are many examples online for how to extract an asset to a separate file in Java, e.g. see [here](https://stackoverflow.com/questions/15574983/copy-directory-from-assets-to-local-directory). You should be able to translate one of these examples into Python using the [Chaquopy API](https://chaquo.com/chaquopy/doc/current/python.html), or you could just create a Java method and call it from your Python code.
