### ISSUE TITLE
Update Pandas

### ISSUE THREAD

**Issue by rbebb** [chaquo/chaquopy#1270]
It would be awesome to have the latest version of Pandas for each version of Python. If only one version of Python can be supported though, I’d say Python 3.11 would be the most beneficial.

**Comment by mhsmith** [comment]
As you can see from [the repository](https://chaquo.com/pypi-13.1/pandas/), we currently provide version 2.1.3 for Python 3.12, which is less than a year old. Are you able to use this? If not, please explain why.

**Comment by rbebb** [comment]
@mhsmith Unfortunately, the other packages I use do not have Python 3.12 wheels available, but most have a 3.11 wheel available.

**Comment by rbebb** [comment]
@mhsmith Creating a wheel for 2.1.3 for Python 3.11 would suffice. Although, if it is possible to get a newer version, then I’d say 2.2.2 would be best because that’s the last version that lets you use numpy versions before 2.0.

**Comment by mhsmith** [comment]
> the other packages I need do not have Python 3.12 wheels available, but most have a 3.11 wheel available

Which packages specifically?

**Comment by rbebb** [comment]
> Which packages specifically?

Packages without 3.12 wheels: Shapely, SciPy, aiohttp

**Comment by rbebb** [comment]
My mistake regarding aiohttp! Looks like I missed that!

Also, my goal is to upgrade to Python 3.11 or higher (so a wheel for 3.11 or 3.12 would be ideal).

**Comment by mhsmith** [comment]
Pandas version 2.1.3 is now available for Python 3.9 - 3.13.

**Comment by rbebb** [comment]
Thank you so much @mhsmith!
