### ISSUE TITLE
Update aiohttp

### ISSUE THREAD

**Issue by rbebb** [chaquo/chaquopy#1271]
Would it be possible to get a wheel for the latest version of aiohttp (for Python 3.11 if it’s not possible to publish one for all Python versions)? Thank you to everyone that has put so much work into this project!

**Comment by mhsmith** [comment]
`aiohttp` version 3.10.10 is now available for Python 3.13. For older Python versions, the newest version is 3.9.1. If that doesn't work for your project, please explain why.

**Comment by mhsmith** [comment]
OK, aiohttp version 3.10.10 is now available for Python 3.9 - 3.13.

**Comment by rbebb** [comment]
Thank you so much!
