### ISSUE TITLE
Missing torch libraries in python 3.12

### ISSUE THREAD

**Issue by PhanTranHung** [chaquo/chaquopy#1273]
I need these libraries in python 3.12, please update it  🥺🥺🥺

_torch==2.5.0
Pillow==11.0.0
torchvision==0.20.0
PyYAML==6.0.2
pytorch_lightning==2.4.0
timm==1.0.11
nltk==3.9.1_

**Comment by rbebb** [comment]
Can you confirm which packages were not able to build?

Also, it looks like Pillow 11.0.0 was added to the package index recently, and PyYAML 6.0.2 appears to able to create a wheel on its own during the build process!

**Comment by mhsmith** [comment]
See the following issues, and in future please search for existing issues before creating new ones:

* #1215
* #758
* #606
