### ISSUE TITLE
Pyqt support

### ISSUE THREAD

**Issue by cacoze** [chaquo/chaquopy#1276]
Hello,
I'm getting this error when trying to install pyqt5 using chaquopy (actually, by trying to build an android app with beeware and including pyqt5 as a requirement)

`AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'`

Does chaquopy support pyqt5? I've seen this previous issue mentioning that it doesn't support, but I want to confirm if that's still true. https://github.com/chaquo/chaquopy/issues/418

**Comment by mhsmith** [comment]
Yes, it's still true. To use PyQT on Android, you should use a PyQT-specific tool such as pyqtdeploy.
