### ISSUE TITLE
Adding  a package for  pylsd android support

### ISSUE THREAD

**Issue by ngreedy** [chaquo/chaquopy#1279]
#### Chaquopy version
classpath "com.chaquo.python:gradle:9.0.0"

id("com.chaquo.python") version "16.0.0" apply false

#### Describe your issue
I need a  pylsd python package in :  https://github.com/OCR-D/pylsd

Here is the setup.py 

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, Extension

clib = Extension('pylsd.lib',
                 sources=['source/src/lsd.cpp'],
                 include_dirs=['source/include'],
                 depends=['source/include/lsd.h'],
                 language="c++")

setup(
    name='ocrd-fork-pylsd',
    version='0.0.8',
    description='pylsd is the python bindings for LSD - Line Segment Detector',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Gefu Tang',
    author_email='tanggefu@gmail.com',
    maintainer='kba',
    license='AGPL',
    keywords=["LSD", 'line segmentation'],
    url='https://github.com/OCR-D/pylsd',
    packages=['pylsd', 'pylsd.bindings'],
    install_requires=['numpy'],
    ext_modules=[clib],
)
```

I haven't seen any examples like this in   pypi/packages  , I wonder if it's  supported ?

and if supported ,  how can I set the  meta.yaml  file  to  build  an  armv7  whl ? 

Looking forward to your reply.

**Comment by mhsmith** [comment]
> classpath "com.chaquo.python:gradle:9.0.0"
> 
> id("com.chaquo.python") version "16.0.0" apply false

That's two completely different versions. You should pick one version, preferably the newest one, and set up your app according to the instructions in that version's documentation.

> I haven't seen any examples like this in pypi/packages , I wonder if it's supported ?

The pylsd package on PyPI hasn't been updated for 7 years, but it looks like this fork is more actively maintained. So I don't see any reason why it wouldn't work.

In the meta.yaml file, you can get the source from a GitHub repository using the `git_url` and `git_rev` settings. Search for those strings in the the existing recipes to find examples.

> if supported , how can I set the meta.yaml file to build an armv7 whl ?

The ABI of the whl is determined by the build-wheel command, not the meta.yaml file. See [the README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md) for instructions.

**Comment by ngreedy** [comment]
thankful for reply.

I change some thing and run ./build-wheel.py --python 3.8 --abi armeabi-v7a pylsd

my meta.yaml: 

`
package:
  name: pylsd
  version: "0.0.8"

build:
  number: 1

source:
  path: src

requirements:
  build:
    - cmake 3.28.1
  host:
    - numpy 1.17.4
    - python
`

I have cloned the **https://github.com/OCR-D/pylsd.git**  in the src path.

finally got this:

**build-wheel: Error: /home/hjn/chaquopy/server/pypi/packages/pylsd/build/0.0.8/cp38-cp38-android_24_armeabi_v7a/fix_wheel/pylsd-0.0.8.dist-info does not exist**

and I saw some issues about this error.  there are some C  files like [lsd.h](https://github.com/OCR-D/pylsd/blob/master/source/include/lsd.h) 

Do  I need compile the  C code with a separate recipe? 

or something else is wrong？

**Comment by ngreedy** [comment]
> > classpath "com.chaquo.python:gradle:9.0.0"
> > id("com.chaquo.python") version "16.0.0" apply false
> 
> That's two completely different versions. You should pick one version, preferably the newest one, and set up your app according to the instructions in that version's documentation.
> 
> > I haven't seen any examples like this in pypi/packages , I wonder if it's supported ?
> 
> The pylsd package on PyPI hasn't been updated for 7 years, but it looks like this fork is more actively maintained. So I don't see any reason why it wouldn't work.
> 
> In the meta.yaml file, you can get the source from a GitHub repository using the `git_url` and `git_rev` settings. Search for those strings in the the existing recipes to find examples.
> 
> > if supported , how can I set the meta.yaml file to build an armv7 whl ?
> 
> The ABI of the whl is determined by the build-wheel command line, not the meta.yaml file. See [the README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md#building-a-package) for instructions.

got it

**Comment by ngreedy** [comment]
OK I've solve that problem. that is because a wrong filename.

Now **I build successful and run in the device**! ! ! 

but it's error  in the logcat,  because the python  can't  load the **so** file in the python project 

the code :
`
def load_lsd_library():
    lib_dir = os.path.dirname(os.path.dirname(__file__))
    lib_path = None
    for lib_name in ['lib.*.so', 'lib.*.dll', 'lib.*.dylib', 'lib.*.lib']:
        libs = glob.glob(os.path.join(lib_dir, lib_name))
        if libs:
            lib_path = libs[0]
            break
    if not lib_path:
        return None
    return ctypes.cdll[lib_path]

lsdlib = load_lsd_library()
if lsdlib == None:
    raise ImportError('Cannot load dynamic library. Did you compile LSD?')
`

there need to be a **liblsd.so**  in the project path 

I check the exmaples and find maybe I need to creat a build.sh file to link to the so file.   is that right? 

or is  there  another way to make  **load_lsd_library**  worked?

**Comment by mhsmith** [comment]
Single backticks have no effect across line breaks. Please surround multi-line code blocks with triple backticks: <code>```</code>. 

> pylsd/build/0.0.8/cp38-cp38-android_24_armeabi_v7a/fix_wheel/pylsd-0.0.8.dist-info does not exist

As you can see from the setup.py you quoted above, this fork has changed its name to `ocrd-fork-pylsd`, so your meta.yaml file will need to match that.

> there need to be a liblsd.so in the project path

If I understand the setup.py correctly, the filename will actually just be `lib.so`, because build-wheel removes the Python ABI tag. Is there a file with that name inside the whl file? If so, you can probably edit the code to use that name unconditionally:

```py
def load_lsd_library():
    lib_dir = os.path.dirname(os.path.dirname(__file__))
    return ctypes.cdll[f"{lib_dir}/lib.so"]
```

**Comment by ngreedy** [comment]
> Single backticks have no effect across line breaks. Please surround multi-line code blocks with triple backticks: `` ``` ``.
> 
> > pylsd/build/0.0.8/cp38-cp38-android_24_armeabi_v7a/fix_wheel/pylsd-0.0.8.dist-info does not exist
> 
> As you can see from the setup.py you quoted above, this fork has changed its name to `ocrd-fork-pylsd`, so your meta.yaml file will need to match that.
> 
> > there need to be a liblsd.so in the project path
> 
> If I understand the setup.py correctly, the filename will actually just be `lib.so`, because build-wheel removes the Python ABI tag. Is there a file with that name inside the whl file? If so, you can probably edit the code to use that name unconditionally:
> 
> ```python
> def load_lsd_library():
>     lib_dir = os.path.dirname(os.path.dirname(__file__))
>     return ctypes.cdll[f"{lib_dir}/lib.so"]
> ```

thanks a lot for your patient ^.^
 
I unzip my whl file and there is a lib.so in there.

![image](https://github.com/user-attachments/assets/fe03e33a-6758-4046-ac6e-0f66aebb2703)

but when I check the app storage, there is no **so** file in the app's directory. 

![image](https://github.com/user-attachments/assets/dd1ac659-6c01-4758-85cd-db712d05deb6)

I think pylsd need the **so** file in his directory ,  just like the **cv2**  above.

so how ?

**Comment by ngreedy** [comment]
```
def load_lsd_library():
    # may fail if CWD (via sys.path) contains pylsd/bindings/__init__.py,
    # but otherwise contains the auto-built library for this platform/installation:
    lib_dir = os.path.dirname(os.path.dirname(__file__))
    lib_path = None
    for lib_name in ['lib.*.so', 'lib.*.dll', 'lib.*.dylib', 'lib.*.lib']:
        libs = glob.glob(os.path.join(lib_dir, lib_name))
        if libs:
            lib_path = libs[0]
            break
    if not lib_path:
        return None
    return ctypes.cdll[lib_path]

lsdlib = load_lsd_library()
if lsdlib == None:
    raise ImportError('Cannot load dynamic library. Did you compile LSD?')
```

**Comment by ngreedy** [comment]
OK，  I fixed it ！  some path  problem ，that‘s all my fault，  and thank you  very much！

**Comment by mhsmith** [comment]
> but when I check the app storage, there is no so file in the app's directory

Chaquopy doesn't extract .so files into the app's directory until something tries to load them. `ctypes.cdll` is one function which can trigger the extraction.
