### ISSUE TITLE
How to train a linear regression use chaquo in Android device, save the model and load it for predict 

### ISSUE THREAD

**Issue by Lily-sh** [chaquo/chaquopy#1283]
I am trying to train a logistic regression model on android devices. I am wondering if I can use chaquo with sklearn to train the model and save the model for inferring.
if you have any idea please help me.
Thanks a lot.

**Comment by mhsmith** [comment]
We have [Android builds of scikit-learn](https://chaquo.com/pypi-13.1/scikit-learn/) available for Python 3.8 - 3.10.

* To add it to your app, see [here](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements).
* To set the Python version of your app, see [here](https://chaquo.com/chaquopy/doc/current/android.html#python-version).
