### ISSUE TITLE
how to realize human tracking on android

### ISSUE THREAD

**Issue by Edward-YS** [chaquo/chaquopy#1290]
I have realized the human tracking one the computer.Now i want to realize it on the android studio. How can i do to make it true? Can you give me any advice?

**Comment by mhsmith** [comment]
Sorry, I don't understand your question. Are you talking about pose tracking? If so, what libraries are you using?

**Comment by Edward-YS** [comment]
I'm not talking about pose tracking but pedestrian track such as YOLO+deepsort. Have you heard about that？

**Comment by mhsmith** [comment]
[This](https://chaquo.com/pypi-13.1/) is the list of packages we currently support, but I'm not an expert on *using* most of these packages, so I can't advise you about that. 

Many of the common image processing packages, including YOLO, have been discussed several times on this tracker before, so you should start by searching for that.
