### ISSUE TITLE
How can i use chaquopy in kotlin?

### ISSUE THREAD

**Issue by Edward-YS** [chaquo/chaquopy#1292]
there is no similar answer

#### Chaquopy version
8.6.0

#### Relevant parts of your build.gradle file
chaquopy 15.0.1 python 3.9.0 

#### Describe your issue

Hello! I have imported chaquopy in groovy successfully. However, something wrong happened in my following work with groovy. So i need to turn it from groovy to kotlin. How can i use chaquopy in kotlin?

**Comment by mhsmith** [comment]
Chaquopy has supported Kotlin build.gradle files since version 15.0.1, but they require a different syntax. The documentation of Chaquopy 14 and older uses the old syntax, and the documentation of Chaquopy 15 and newer uses the new syntax. All versions of the documentation are available [here](https://chaquo.com/chaquopy/documentation/).

**Comment by Edward-YS** [comment]
Thanks for your reply!
There are two more questions:
1.Can chaquopy support ultralytics  to realize object detection?
2.Is there an interface document because i want to implement java to call to python functions?
3.if i use chaquopy do i need to configure python interpreter? It can't recognize the module that i pip in gradle like this:

**Comment by mhsmith** [comment]
> 1.Can chaquopy support ultralytics to realize object detection?

Please search the issue tracker for previous mentions of ultralytics – everything I know is there.

> 2.Is there an interface document because i want to implement java to call to python functions?

See [the documentation](https://chaquo.com/chaquopy/doc/current/java.html).

> 3.if i use chaquopy do i need to configure python interpreter? It can't recognize the module that i pip in gradle and still can't recognize the ultralytics module which i put into straightly, like this:

See [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin).
