### ISSUE TITLE
Failed to pip install together

### ISSUE THREAD

**Issue by Thejas775** [chaquo/chaquopy#1294]
#### Describe your issue
The below issue is occurring while installing together ai . 
Failed to install pydantic-core==2.23.4 from https://files.pythonhosted.org/packages/e2/aa/6b6a9b9f8537b872f552ddd46dd3da230367754b6f707b8e1e963f515ea3/pydantic_core-2.23.4.tar.gz#sha256=2584f7cf844ac4d970fba483a717dbe10c1c1c96a969bf65d61ffe94df1b2863 (from pydantic<3.0.0,>=2.6.3->together).

**Comment by mhsmith** [comment]
For `pydantic` version 2, see #1017.

The last version of `together` which didn't have this requirement was 0.2.7. Hopefully that's still new enough for your app.
