### ISSUE TITLE
How to apply pip "options" to specific dependencies without affecting others in pip "install" scripts?

### ISSUE THREAD

**Issue by Robyve** [chaquo/chaquopy#1296]
I am trying to install pip dependencies as follows, where hmmlearn is a .whl package I created using `chaquopy/server/pypi`. I only want the `options ("--extra-index-url", "/home/yxm/codes/iod/chaquopy/server/pypi/dist")` and `options ("--no-cache-dir")` to apply to hmmlearn. However, it seems that the options have a global effect, impacting all `install` lines, regardless of whether they are in the same `pip` block (see the 2 examples below). Is there any way to achieve this? Thank you for your help!
```
            defaultConfig {
                buildPython("/home/yxm/.conda/envs/IOD/bin/python")
                pip {
                    install "numpy"
                    install "pandas"
                    install "scipy"
                    install "scikit-learn"
                    install "numba"
                    install "xgboost"
                    options("--no-cache-dir")
                    options("--extra-index-url", "/home/yxm/codes/iod/chaquopy/server/pypi/dist")
                    install "hmmlearn"
                }
                pyc {
                    src = true
                }
            }
```

```
            defaultConfig {
                buildPython("/home/yxm/.conda/envs/IOD/bin/python")
                pip {
                    install "numpy"
                    install "pandas"
                    install "scipy"
                    install "scikit-learn"
                    install "numba"
                    install "xgboost"
                }
                pip {
                    options("--no-cache-dir")
                    options("--extra-index-url", "/home/yxm/codes/iod/chaquopy/server/pypi/dist")
                    install "hmmlearn"
                }
                pyc {
                    src = true
                }
            }
```

**Comment by mhsmith** [comment]
The only options that pip accepts on a per-requirement level are [these ones](https://pip.pypa.io/en/stable/reference/requirements-file-format/#per-requirement-options), and then only in a requirements file. 

And I don't think either of these options would be useful on a per-requirement level anyway:

* `--extra-index-url` – if you don't want other requirements to be loaded from your local index, then don't put them in your local index. 
* `--no-cache-dir` – Pip only caches two things: wheels it builds from sdists, and files it downloads from web servers. But in this case your file is coming from a local directory, and is presumably already a wheel, so there's nothing to cache.

Please explain why you thought you needed to stop these options affecting other requirements, and maybe I can suggest a better solution.

**Comment by mhsmith** [comment]
If this is still a problem, please provide the information requested above, and I'll reopen the issue.
