### ISSUE TITLE
Standalone Python executable

### ISSUE THREAD

**Issue by 0cococ** [chaquo/chaquopy#1298]
Can it be packaged into binary and run through adb instead of embedded in the app?

**Comment by mhsmith** [comment]
If by "it" you mean Python, then we currently only support it when embedded in an app.

There is a script at target/standalone_python.sh which used to do this, but:
* It won't be compatible with our current Python build process.
* Even if you did build a standalone Python executable, security restrictions on newer versions of Android might make it difficult to run.
