### ISSUE TITLE
can't Python.start(AndroidPlatform(applicationContext)) 

### ISSUE THREAD

**Issue by mubasi29** [chaquo/chaquopy#1302]
![image](https://github.com/user-attachments/assets/bc60ec85-7dcc-4753-8124-1c4a7411b952)

gradle : 7.2
kotlin version: 1.7.2
android 8

i'm implement python start in MainApplication and always looping and i can't error in this problem.

and this logcat showing:
![image](https://github.com/user-attachments/assets/c834550b-6c2b-4fc2-b67c-d25a599aae7f)

**Comment by mhsmith** [comment]
You've closed the issue; does that mean you've fixed the problem. If so, what was the solution?

**Comment by mubasi29** [comment]
permission my device is locked to access path so androidplatform
