### ISSUE TITLE
Failed to build 'av._core' extension

### ISSUE THREAD

**Issue by ranjitsingha** [chaquo/chaquopy#1304]
building 'av._core' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install av==11.0.0 from https://files.pythonhosted.org/packages/21/e8/fadad78511fd108e17f0df1dd2a29755020e92345791e4fe207d304a0cd4/av-11.0.0.tar.gz#sha256=48223f000a252070f8e700ff634bb7fb3aa1b7bc7e450373029fbdd6f369ac31.

![Screenshot_20241206-155040_1](https://github.com/user-attachments/assets/0e9b83ec-927d-4c4c-bfd4-951360e03331)

My build.gradle
```java
python {
            pip {
                install "av==11.0.0"
            }
        }
```

**Comment by mhsmith** [comment]
See #1012.
