### ISSUE TITLE
Send output to custom log framework

### ISSUE THREAD

**Issue by topcoco** [chaquo/chaquopy#1305]
Can the python log be output to the custom log framework? Now it seems that it can only be output to the log of the android system.

**Comment by mhsmith** [comment]
If you're generating logs with the `print` function or something similar, then you can redirect them by replacing `sys.stdout` and `sys.stderr` with whatever streams you want. If you're using a more complex logging framework, then it will probably have its own redirection features.

**Comment by topcoco** [comment]
> If you're generating logs with the print function or something similar, then you can redirect them by replacing sys.stdout and sys.stderr with whatever streams you want. If you're using a more complex logging framework, then it will probably have its own redirection features.

May I ask how to change it? I use python's peint to output it to my custom log framework. Can you give me a simple example? Any log framework or custom log is fine?

**Comment by mhsmith** [comment]
This isn't really a question about Chaquopy, so you should search for help elsewhere. I'm sure you can find lots of examples if you search for terms like "redirect Python stdout".
