### ISSUE TITLE
Use Termux build of `av`

### ISSUE THREAD

**Issue by ranjitsingha** [chaquo/chaquopy#1307]
#### Chaquopy version
16.0.0

#### Relevant parts of your build.gradle file

```
pip {
     install "src/main/python/modules/av-14.0.1-cp311-cp311-linux_aarch64.whl"
    }
```

#### Python version installed on device
Python 3.11.6

#### Describe your issue
1. I have build ffmpeg 7.1 from github source with `--disable-static`. ffmpeg version: 7.1 is installed now in termux
2. Then I have build [av](https://github.com/PyAV-Org/PyAV) wheel for aarch64 from its github source within termux and it generated this .whl file: 
av-14.0.1-cp311-cp311-linux_aarch64.zip
and then i installed this wheel with pip

Then to test the av wheel in termux i did:
`python -c "import av; print(av.__version__)"` and it prints :
`14.0.1`
Which means its successfully working.

Now but when i add the same wheel with chaqopy in build.gradle as:
```
pip {
     install "src/main/python/modules/av-14.0.1-cp311-cp311-linux_aarch64.whl"
    }
```
i don't get error while building the app (the app successfully builds) but i get error at app runtime.
error:
`
Stack trace:  
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'av._core'
`

**While the same issue was also coming in termux if we have ffmpeg version *less then 7.0* installed in termux**
error:
`
ModuleNotFoundError: No module named 'av._core'
`

How should i fix it?

**Comment by mhsmith** [comment]
Sorry, Chaquopy can't currently load .whl files built on termux. We only support pure-Python .whls, or native .whls built with [our own build tool](https://github.com/chaquo/chaquopy/tree/master/server/pypi).

The current obstacle is probably that this .whl file contains filenames with `.cpython-311.so` suffixes, while Chaquopy expects simply `.so`.

However, it sounds like this build is dynamically linked against ffmpeg, in which case you'd also need to include ffmpeg in your app somehow.

**Comment by mhsmith** [comment]
You might find some hints by searching this tracker for other issues related to ffmpeg or av.

**Comment by mhsmith** [comment]
Or maybe you could avoid the problem by building against a static ffmpeg.

**Comment by ranjitsingha** [comment]
Sorry, we don't need ffmpeg to be installed to use av wheel. We only need ffmpeg wheel while building the wheel. Since av is a pythonic binding for ffmpeg libraries.

Since you have mentioned we need to use chaquopy build tool to for native wheel build. But i am trying to use this tool but failing due to lots of problems.

Is it possible to build native wheel within termux. Since i already have installed android sdk and android ndk for building android app. Also ffmpeg is installed. Also av wheel can be build here. I wounder if it would be possible to build native wheel too. It would be great.

Since i am on arm64-v8a device and i want to build av native wheel for arm64-v8a only. Because using chaquopy tool we need to be on x86 device and cross compilation for multiple architecture is hard. There are lots of problems with library paths setting problem for me.

**Comment by mhsmith** [comment]
Sorry, I'm not familiar with this package, or with Termux, so I don't have any more suggestions.

**Comment by mhsmith** [comment]
Thanks, that's very helpful. I'll close this issue now, but I'll link it from #1017 for future reference.

**Comment by HanzoDev1375** [comment]
> متأسفیم، Chaquopy در حال حاضر نمی تواند فایل های whl. ساخته شده بر روی termux را بارگیری کند. ما فقط از Python .whls خالص یا بومی .whls ساخته شده با [ابزار ساخت خودمان](https://github.com/chaquo/chaquopy/tree/master/server/pypi) پشتیبانی می کنیم .
> 
> مشکل فوری شما احتمالاً این است که این فایل .whl حاوی نام فایل با `.cpython-311.so`پسوند است، در حالی که Chaquopy به سادگی انتظار دارد `.so`.
> 
> با این حال، به نظر می رسد که این بیلد به صورت پویا در برابر ffmpeg مرتبط است، در این صورت شما همچنین باید به نوعی ffmpeg را در برنامه خود قرار دهید. ممکن است با جستجوی این ردیاب برای سایر مسائل مربوط به ffmpeg یا av نکاتی را بیابید. یا شاید بتوانید با ساختن در برابر یک ffmpeg ایستا از مشکل جلوگیری کنید.

Hello, I want to create a code sorter for my IDE, for example with the black library. Does this library not support it?

**Comment by mhsmith** [comment]
The black library is pure-Python, so it should work fine.

Please don't post questions on unrelated issues – create a new issue instead.

**Comment by Jzhenli** [comment]
> Took the wheel that i build and then unpacked it, then i renamed every .cpython-311.so with .so and then applied patches to every .so files and then again packed it with wheel tool.

hi, you  applied patches to every .so files, what does this mean, would u give some detail info about this? @ranjitsingha

**Comment by Jzhenli** [comment]
@ranjitsingha thansk for your reply, I have try it, but don't know to modify which path for the .so file, below is my helloworld.cpython-310.so build with nuitka, I have renamed it to helloworld.so

![Image](https://github.com/user-attachments/assets/133cb57d-a06d-4e94-ac1a-8d6879c670d4)

**Comment by Jzhenli** [comment]
After try, I am able to build and use the so file created in termux with chaquopy. You can do it as follows,
1. set the the rpath to ""
    `patchelf --set-rpath '' your_library.so   `
2. change lib in the *.so file, for example " libpython3.10.so.1.0" to "libpython3.10.so"
   `patchelf --replace-needed libpython3.10.so.1.0 libpython3.10.so your_library.so`
