### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by shuantsu** [chaquo/chaquopy#1308]
#### Chaquopy version
16.0

#### Devices or emulators where the issue happens
android studio

#### Relevant parts of your code
```
haquopy {
    defaultConfig {
        pip {
            install("-r", "requirements.txt")
        }
        buildPython("C:/Python312/python.exe")
    }
}
```
#### Describe your issue
I'm trying to to run the pip install -r requirements.txt but it keeps giving me this error:

Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Where should I put the requirements.txt file? I tried in the python folder in my project or other places like gradle folder and main app folder but it doesn't work.
Can't find the info on documentation.

**Comment by mhsmith** [comment]
As [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements) says, it should be in the project directory, i.e. the same directory as the build.gradle file.

**Comment by shuantsu** [comment]
I still can't make it work with requirements.txt.
putting it on the same folder of build.gradle doen'st fix it

**Comment by mhsmith** [comment]
There are usually two build.gradle files; it should be in the same directory as the one you quoted, i.e. the one that contains the pip install command.

If it's already there:

* Are you sure you've spelled the filename correctly?
* Are you doing anything which could cause the working directory to change?

**Comment by shuantsu** [comment]
it worked!

```
drwxr-xr-x 1 ******* 197609    0 Dec 17 15:37 ./
drwxr-xr-x 1 ******* 197609    0 Dec 17 15:34 ../
-rw-r--r-- 1 ******* 197609    6 Dec 12 15:40 .gitignore
drwxr-xr-x 1 ******* 197609    0 Dec 12 16:17 build/
-rw-r--r-- 1 ******* 197609 1656 Dec 17 15:37 build.gradle.kts
-rw-r--r-- 1 ******* 197609  750 Dec 12 15:40 proguard-rules.pro
-rw-r--r-- 1 ******* 197609   31 Dec 17 15:35 requirements.txt
drwxr-xr-x 1 ******* 197609    0 Dec 12 15:40 src
```/

thanks!

**Comment by jadan4498-arch** [comment]
![Image](https://github.com/user-attachments/assets/50e1b50b-6cf6-4489-ab87-64d4770e8e8c)
![Image](https://github.com/user-attachments/assets/340bdad9-674e-4ffb-9bb8-79c6f906d810)
![Image](https://github.com/user-attachments/assets/ce15dece-c0e1-415a-9b65-2e60e337d1ba)
![Image](https://github.com/user-attachments/assets/cae64fb7-3bc0-40b4-a193-981d4800afe8)

**Comment by jadan4498-arch** [comment]
Alguien q m ayude con este problema tengo un redmi note 11 pro 5g

**Comment by mhsmith** [comment]
You aren't using Chaquopy, you're using Termux. Please ask for help in one of their support forums.

**Comment by gvinayshekhar-cmyk** [comment]
pip install -r requirements.txt
