### ISSUE TITLE
Could not find a version that satisfies the requirement google-generativeai>=0.8.2 (from versions: 0.1.0rc1, 0.1.0rc2)

### ISSUE THREAD

**Issue by Thejas775** [chaquo/chaquopy#1309]
#### Chaquopy version
16.0.0
#### Relevant parts of your build.gradle file
python {
//            buildPython  "C:\\Users\\utsav\\AppData\\Local\\Programs\\Python\\Python311\\python.exe"
            buildPython "python3.10"
        }
        python {
            pip {
                install "numpy"
                install "pillow"
                install "requests"
                install "urllib3==1.25.4"
                install "boto3==1.34.65"
                install "google-generativeai>=0.8.2"
            }
        }
    }

#### Describe your issue
The google generative ai library needs to be updaed

**Comment by mhsmith** [comment]
The current versions of this package require at least Python 3.9. You can set your app's Python version as shown in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

To work around #1017, you'll also have to add the following line:
```
install "pydantic<2"
```

**Comment by mhsmith** [comment]
I said "at least Python 3.9", so 3.10 should also be fine.

**Comment by Thejas775** [comment]
python {
//            buildPython  "C:\\Users\\utsav\\AppData\\Local\\Programs\\Python\\Python311\\python.exe"
            buildPython "python3.10"
        }
        python {
            pip {
                install "numpy"
                install "pillow"
                install "requests"
                install "urllib3==1.25.4"
                install "boto3==1.34.65"
                install "google-generativeai>=0.8.2"
                install "pydantic<2"
//                install "together"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    sourceSets {
        main {
            python.srcDir "python3.10"
        }
    }

**Comment by Thejas775** [comment]
> ```
>     python {
> ```
> 
> // buildPython "C:\Users\utsav\AppData\Local\Programs\Python\Python311\python.exe" buildPython "python3.10" } python { pip { install "numpy" install "pillow" install "requests" install "urllib3==1.25.4" install "boto3==1.34.65" install "google-generativeai>=0.8.2" install "pydantic<2" // install "together" } } }
> 
> ```
> buildTypes {
>     release {
>         minifyEnabled false
>         proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>     }
> }
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> kotlinOptions {
>     jvmTarget = '1.8'
> }
> sourceSets {
>     main {
>         python.srcDir "python3.10"
>     }
> }
> ```

@mhsmith still doesnt-'t work

**Comment by mhsmith** [comment]
You still haven't changed the Python version of your app. Follow the instructions in [my previous comment](https://github.com/chaquo/chaquopy/issues/1309#issuecomment-2542017015).

**Comment by Thejas775** [comment]
> You still haven't changed the Python version of your app. Follow the instructions in [my previous comment](https://github.com/chaquo/chaquopy/issues/1309#issuecomment-2542017015).

 chaquopy {
            defaultConfig {
                version = "3.9"
            }
        }

Package 'numpy' requires a different Python: 3.8.10 not in '>=3.9'

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/1295#issuecomment-2480239823

**Comment by Thejas775** [comment]
> install "google-generativeai>=0.8.2"
>                 install "pydantic<2"

Thank you it works.
