### ISSUE TITLE
can't use asyncio and nest_asyncio

### ISSUE THREAD

**Issue by shuantsu** [chaquo/chaquopy#1310]
#### Chaquopy version
16.0

#### Devices or emulators where the issue happens
android studio

#### Relevant parts of your code
chaquopy {
    defaultConfig {
        pip {
            install("asyncio")
            install("edge-tts")
            install("flask")
            install("mutagen")
            install("nest_asyncio")
        }
        buildPython("C:/Python312/python.exe")
    }
}

#### Describe your issue
when I try to import asyncio it crashes. I'm also trying to import nest_asyncio
I wonder if asyncio is even supported

**Comment by mhsmith** [comment]
Asyncio is fully supported, but it comes with the Python standard library and can't be installed with pip. Remove it from this list, and everything else should install successfully.

**Comment by shuantsu** [comment]
thanks for the clarification
