### ISSUE TITLE
Question: add pytorch and torchvision to project

### ISSUE THREAD

**Issue by OleksandrGrument** [chaquo/chaquopy#132]
Hello, can you describe please how to add this two modules two project. As far as I understood they are no in your repository. Can I add them to project manualy? Where them put? and what versions do I need? Thanks

**Comment by mhsmith** [comment]
We would need to build them and add them to our repository. This is the first request we've received for these packages, so they're not currently a priority, but if anyone else wants them too, please add a thumbs-up to the original post and we may provide them in the future.

**Comment by OleksandrGrument** [comment]
Thanks for clarifications. Also i would ask you to add package "setuptools".

Is there a possibility to provide the community guide how to properly prepare unlisted in repo packages and setup them mannualy to project?

**Comment by EugeneBondrenko** [comment]
Good day, i'm also looking for a possibility to setup project that should contain pythorch and tourchvision.

**Comment by mhsmith** [comment]
Setuptools, like most pure-Python packages, can already be installed. Just follow the instructions in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements).

**Comment by kadman7** [comment]
I also want to add and use in the project tourchvision

**Comment by skrello** [comment]
Vote +1 to add them to repository

**Comment by jackie099** [comment]
Vote +1 for pytorch and torchvision!

**Comment by jkufro** [comment]
Vote +1 for this. I am also willing to work on this @mhsmith if you could provide some guidance on how you setup your environment to create the whl files.

**Comment by mhsmith** [comment]
PyTorch is now available for Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.

Torchvision is not yet available. If you want that package, please see #233.
