### ISSUE TITLE
Error running chaquopy on Ubuntu

### ISSUE THREAD

**Issue by raymondklutse** [chaquo/chaquopy#134]
Hello,I have been trying to use Chaquopy in an android app I am developing on my Ubuntu machine and I keep having an issue with the python version even though I have installed python 3.6.5. Here is the Error

Execution failed for task ':app:generateArmDebugPythonRequirements'.
> buildPython failed (org.gradle.process.internal.ExecException: Process 'command 'python3'' finished with non-zero exit value 1). For full details, open the 'Build' window and switch to text mode with the 'Toggle view' button on the left.
Kindly let me know how to solve this issue. Thanks

**Comment by mhsmith** [comment]
Please provide the "full details", as the message explains.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information.

**Comment by raymondklutse** [comment]
> If this is still a problem, please reopen and provide the requested information.

Sorry for the late reply. It is fine now. Thanks for your quick response
