### ISSUE TITLE
How to Import Local Modules

### ISSUE THREAD

**Issue by canewsin** [chaquo/chaquopy#135]
Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'Config'

main->python->zeronet->src->Config.py

build.gradle
extractpackages "zeronet"

calling "from Config" from file zeronet->zeronet.py throws above error

**Comment by canewsin** [comment]
Also does files neccesary to compile to pyc 
if not i dont want to compile to pyc, how to do that

also how to extract full package instead of file in build.gradle what is the configuration

**Comment by mhsmith** [comment]
If you want to import `zeronet/src/Config.py` from `zeronet/zeronet.py`, then the correct syntax would be:

`from .src.Config import ...`

Or if `zeronet.py` and `Config.py` were in the same directory:

`from .Config import ...`

> Also does files neccesary to compile to pyc

Compiling your own source files to .pyc is not currently supported, though we may add it in the future.

> also how to extract full package instead of file in build.gradle what is the configuration

`extractPackages` already extracts the full package.

**Comment by canewsin** [comment]
no its not extracting whole package i use root file explores only extracts 
imported files like if i import 
> from .src.Config import
only src/Config file is extracted and that to it converted to .pyc files
how to extract full app.zip without binary compaliation
i was on version 6.2.1 latest

**Comment by mhsmith** [comment]
Please post the `python {}` block from your build.gradle file.

**Comment by canewsin** [comment]
python {
//            buildPython "C:/Python36/python.exe"
            extractPackages "zeronet"
//            pyc {
//                stdlib false
//            }
            pip {
                install "-r", "requirements.txt"
            }
        }

**Comment by canewsin** [comment]
@mhsmith  ^^^

**Comment by canewsin** [comment]
zeronet so many references like
> from Config import config

so instead of renaming all to .Config or .someThing is there any PATH_VARIABLE to add to environment so that it can search in specific enviroment for files itself ?

**Comment by mhsmith** [comment]
I assume you've copied the source code from https://github.com/HelloZeroNet/ZeroNet/tree/py3/src. If that code assumes that all of its the modules are at the top level, then that's the way you'll have to use it. Just put the code directly in `src/main/python`, without any `zeronet/src` subdirectory.

**Comment by canewsin** [comment]
If i want to load native lib openssl libcrypto.so from python file where it is stored to access

**Comment by canewsin** [comment]
i was open-sourcing the zeronet port for android project where i have to apply for chaquopy license

**Comment by canewsin** [comment]
though it is almost 3/4 of porting completed and runnable app but small modifications are required to load some libs

**Comment by mhsmith** [comment]
Please email contact@chaquo.com for a license key.
