### ISSUE TITLE
Type conversion for PyObjectList to kotlin FloatArray

### ISSUE THREAD

**Issue by Yahyaali1** [chaquo/chaquopy#138]
Is there faster/efficient way for converting list of PyObjects to FloatArray ? 
Currently I am using following method. 
```kotlin
 private fun convertPyDataToFloat(list: List<PyObject>?): FloatArray {
        val size = list?.size ?: 0
        return FloatArray(size){ i->list!![i].toFloat()}
    }
```
However for an array of 512 obj it is taking upto 1000-2000ms

**Comment by Yahyaali1** [comment]
Found another method. If there is anything better then this approach do share. 
``` kotlin 
val array = dataFromPython?.toJava(FloatArray::class.java)
```

**Comment by mhsmith** [comment]
Yes, `toJava` is probably the most efficient method available. How long did that take for you?

**Comment by Yahyaali1** [comment]
Currently it is taking around 25-35ms. Relatively very fast. However I am still looking for something more efficient as I need to process very large size audio arrays back and forth with python modules.

**Comment by mhsmith** [comment]
If you can represent your data as `bytes` in Python and `byte[]` in Java (which I assume is the same as `ByteArray` in Kotlin), conversions between those types should be even faster.

**Comment by Yahyaali1** [comment]
Thank you for your suggestion. Can you please elaborate on the suggestion for incorporating the idea you have given in the code sample below ? 

Kotlin Code 
```kotlin
override fun process(audio: AudioEvent?): Boolean {
                val timings = TimingLogger("YOUR", "methodA");
                val audioData = audio?.byteBuffer
                timings.addSplit("copy of float data")
                val dataFromPython = classvar?.callAttr("perform_fft", audioData, audioData?.size)
                timings.addSplit("performing fft in python");
                val array = dataFromPython?.toJava(FloatArray::class.java)?: FloatArray(0)
                timings.addSplit("type conversion pyobject to float");
}
```
Python Code 
```python
import numpy as np
class processAudioData:
    def perform_fft(self,array,size):
        fft = np.fft.fft(array)
        return np.abs(fft)[:size//2]
```

**Comment by mhsmith** [comment]
On the Python side, I think you can convert the FFT result to bytes using [`tobytes`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.tobytes.html).  Then use `toJava` to convert that to a `ByteArray`.

**Comment by mhsmith** [comment]
Since Chaquopy version 8.0.0, NumPy arrays and Java arrays of the same type can now converted directly, which gives much better performance.
