### ISSUE TITLE
Numba

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#139]
Required by several audio processing packages.

If you need this package, please add a thumbs up.

**Comment by jkufro** [comment]
@mhsmith I was trying out the preview of Chaquopy 7.0 with numba and could not successfully import it in the Python console. 

I'm running with a Galaxy S4, and the wheels it's pulling seems to be correct: `https://chaquo.com/pypi-7.0/numba/numba-0.48.0-6-cp38-cp38-android_16_armeabi_v7a.whl` and `https://chaquo.com/pypi-7.0/llvmlite/llvmlite-0.31.0-2-cp38-cp38-android_16_armeabi_v7a.whl`. 

The specific error is: `Could not load shared object file: libllvmlite.so`. Running `from llvmlite import binding` produces the same error.

**Comment by mhsmith** [comment]
Version 7.0.0 is missing some bug fixes needed for Numba. Please try version 7.0.1 instead.  Edit your app's top-level `build.gradle` file as follows:

* Change `https://chaquo.com/maven` to `https://chaquo.com/maven-test`.
* Change the version number of `com.chaquo.python:gradle` to `7.0.1`.

**Comment by jkufro** [comment]
That seemed to fix it. Thanks!

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.

**Comment by mhsmith** [comment]
If you're using the above pre-release build, please now change `https://chaquo.com/maven-test` back to `https://chaquo.com/maven`, and switch to version 7.0.2 as described in the previous comment.

The pre-release build will be removed in 2 weeks.

**Comment by mhsmith** [comment]
You will receive the following warning when you import numba:

>UserWarning: Could not obtain multiprocessing lock due to OS level error: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
>A likely cause of this problem is '/dev/shm' is missing orread-only such that necessary semaphores cannot be written.
>*** The responsibility of ensuring multiprocessing safe access to this initialization sequence/module import is deferred to the user! ***

This is harmless as long as you don't use Numba's parallel execution features. 

If you do use parallel execution, you may need to [set the threading layer](https://numba.pydata.org/numba-doc/latest/user/threading-layer.html#setting-the-threading-layer): try the values `threadsafe`, `omp` or `workqueue`.

**Comment by mhsmith** [comment]
The pre-release build has now been removed. See https://github.com/chaquo/chaquopy/issues/139#issuecomment-595355336 for what to do if you're still using it.
