### ISSUE TITLE
NumPy support

### ISSUE THREAD

**Issue by aez90** [chaquo/chaquopy#14]
It would be nice to add functionality for using NumPy through Chaquopy! Which would require getting the wheel built for android, or somehow convincing NumPy to release an architecture-agnostic wheel.

**Comment by mhsmith** [comment]
We have built Android wheels for NumPy and a few other native packages, and added support for them in Chaquopy version 0.6.1. See [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#python-requirements) for more details.

**Comment by companyofbala** [comment]
Hello, I am using the latest version of chaquo.
I saw in repository that sympy is not included, so I tried to pip install sympy, i get an error 

A problem occurred starting process 'command 'py''. Please set buildPython to your Python executable path.

I use Macbook pro, So i could not find the exe file.

and also I tried to use the package that is in the repository(Numpy) already;
My app is simply getting crashed, Please explain to me how to import that and use it in my function.

and also suggest a way for my above question
