### ISSUE TITLE
How to use the Main UI Thread from sub thread in order to update image view ?

### ISSUE THREAD

**Issue by oras** [chaquo/chaquopy#141]

**Comment by oras** [comment]
Like following example in Java:

new Thread(new Runnable() {
        public void run() {
           

            //update frame view on the main thread
        }
    }).start();

**Comment by oras** [comment]
Can I use the following method ?

AppCompatActivity.runOnUiThread

**Comment by mhsmith** [comment]
Yes, you can use any of the same methods which you would use in Java. You can create a `Runnable` in Python like this:

https://github.com/chaquo/chaquopy/blob/461964cec0a96c14e5e6071c21dc4fd285e1043c/app/src/main/python/chaquopy/test/test_proxy.py#L428-L429

(Click the link for more context.)
