### ISSUE TITLE
Question How to init java service ?

### ISSUE THREAD

**Issue by oras** [chaquo/chaquopy#146]
Thanks for the answer about last issue!

can you please describe hot to use android-java service from python

I want to transfer camera frames to python using OpenCV

**Comment by mhsmith** [comment]
Are you talking about an actual Android [`Service`](https://developer.android.com/guide/components/services)? If so, you can use the same APIs as you would use in Java. If you've tried that and had difficulty, please give details.

Or if you're referring to some other kind of service, please give details.

**Comment by oras** [comment]
I want to send camera frames to python (has I understands the chaquopy doesn’t support camera access) I am using OpenCV

נשלח מה-iPhone שלי

‫ב-10 בספט׳ 2019, בשעה 14:15, ‏‏Malcolm Smith ‏<notifications@github.com> כתב/ה:‬

**Comment by mhsmith** [comment]
The most efficient way would be to convert the frame to a Java `byte[]` array and pass it to Python through the [PyObject](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html) methods "call", "callAttr" or "put". Then in Python, convert it to a Python byte array by passing it to the `bytes` function, and load it into OpenCV with the appropriate image format.

Whether you structure this as a service is up to you.

**Comment by oras** [comment]
How can I get the service start running ? The init is throw python ? Do you have any example for init such a service.

נשלח מה-iPhone שלי

‫ב-10 בספט׳ 2019, בשעה 23:20, ‏‏Malcolm Smith ‏<notifications@github.com> כתב/ה:‬

**Comment by mhsmith** [comment]
If you're talking about an actual Android [`Service`](https://developer.android.com/guide/components/services), I don't have any examples of using them in Python. Services are a relatively specialized feature which would usually not be the right choice for an app which interacts with the user. 

If you're new to Android programming, I'd suggest you keep things simple and just do everything in a single-threaded activity. If that doesn't work for you then you'll have to explain why.
