### ISSUE TITLE
Reading images file in python scipt

### ISSUE THREAD

**Issue by priyansh007** [chaquo/chaquopy#149]
I have python script which is reading external images by using cv2.imread.It is working fine in spyder conda but it is showing null file in android application. i am not sure how to give path of those images.

can you explain me how to use image files in python

**Comment by mhsmith** [comment]
If your image file is packaged along with the code, see [here](https://github.com/chaquo/chaquopy/issues/144).

Or if you're copying it over USB, see [here](https://github.com/chaquo/chaquopy/issues/38#issuecomment-388632574).

**Comment by priyansh007** [comment]
Thanks man it works.

**Comment by Vijju203** [comment]
> 
> 
> I have python script which is reading external images by using cv2.imread.It is working fine in spyder conda but it is showing null file in android application. i am not sure how to give path of those images.
> 
> can you explain me how to use image files in python

**Comment by Vijju203** [comment]
Hi Priyansh, can you please share your code of displaying chaquopy python image on to android, I have been facing problem with this also , I have to convert rgb to gray with this chqauopy python.
