### ISSUE TITLE
Can't edit main.py file?

### ISSUE THREAD

**Issue by 2020akumar** [chaquo/chaquopy#150]
![pythonEdit](https://user-images.githubusercontent.com/50772992/65430822-88de5700-dde6-11e9-8b6d-9ba0b3f1b0cb.PNG)

When I try and create a main.py file in my src/main/python folder, android studio does not recognize the python file. It is my understanding that I should be able to edit the python file in Android Studio itself. Am I wrong, and should edit the python file with different software? or is there some way to edit my python files in Android Studio?

**Comment by mhsmith** [comment]
You can get some Python support in Android Studio by installing a plugin, as described [here](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin). Unfortunately there's no way to configure your Python path or standard library, so the IDE will think that your code has many errors, but you'll be able to build it anyway.
