### ISSUE TITLE
How to compile only needed functions into final APK

### ISSUE THREAD

**Issue by logbook** [chaquo/chaquopy#153]
Hello, 
I've used Chaquopy, it does compile all files into the final APK, i find myself with almost 60mb eventhough i use a very limited number of function from the package.

**Comment by mhsmith** [comment]
Which pip packages are you using?

**Comment by logbook** [comment]
Hello again, i used "scipy" and "numpy". is there a way to extract only needed functions when compiling the APK?

**Comment by mhsmith** [comment]
I'm not aware of any way to do that. However, if you want to reduce the size of the released APK, you can omit the x86 and x86_64 ABIs, since they're probably only needed during development. See [here](https://chaquo.com/chaquopy/doc/current/android.html#abi-selection) for details.
