### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by KebAz** [chaquo/chaquopy#154]
I'm trying to use Nucypher with Chacopy in Android studio but the project does not build.

Here is my code:

` python {
            buildPython "C:/Python/Python37/python.exe"
            pip {
                install "git+https://github.com/nucypher/nucypher-pre-python.git"    
            }
        }`

And here is the output of the project building:

`
> Task :app:createMockableJar UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugAndroidTestBuild SKIPPED
> Task :app:compileDebugAndroidTestAidl NO-SOURCE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests
> Task :app:mainApkListPersistenceDebug
> Task :app:processDebugManifest
> Task :app:processDebugAndroidTestManifest
> Task :app:compileDebugAndroidTestRenderscript NO-SOURCE
> Task :app:generateDebugAndroidTestBuildConfig
> Task :app:prepareLintJar
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-2.1, https://chaquo.com/pypi-6.2
Collecting git+https://github.com/nucypher/nucypher-pre-python.git
  Cloning https://github.com/nucypher/nucypher-pre-python.git to c:\users\azbeg\appdata\local\temp\pip-req-build-9z5iqrd1
Collecting msgpack-python (from npre==0.3)
  Using cached https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz
Collecting pysha3 (from npre==0.3)
  Using cached https://chaquo.com/pypi-2.1/pysha3/pysha3-1.0.2-0-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting cryptography (from npre==0.3)
  Using version 2.6.1 (newest version is 2.7, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-6.2/cryptography/cryptography-2.6.1-1-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->npre==0.3)
  Using version 1.11.5 (newest version is 1.12.3, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-2.1/cffi/cffi-1.11.5-0-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting asn1crypto>=0.21.0 (from cryptography->npre==0.3)
  Using cached https://files.pythonhosted.org/packages/8d/c3/be192e56ab85a7b2439caf83049b9936292aaf0398038a2fe28716f18951/asn1crypto-1.0.1-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->npre==0.3)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->npre==0.3)
  Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
Collecting chaquopy-libffi>=3.2.1 (from cffi!=1.11.3,>=1.8->cryptography->npre==0.3)
  Using cached https://chaquo.com/pypi-2.1/chaquopy-libffi/chaquopy_libffi-3.2.1-0-py2.py3-none-android_15_armeabi_v7a.whl
Building wheels for collected packages: npre, msgpack-python, pycparser
  Running setup.py bdist_wheel for npre: started
  Running setup.py bdist_wheel for npre: finished with status 'error'
  Complete output from command C:\Python\Python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\azbeg\\AppData\\Local\\Temp\\pip-req-build-9z5iqrd1\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\azbeg\AppData\Local\Temp\pip-wheel-h4xhbhrl --python-tag py3:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\npre
  copying npre\bbs98.py -> build\lib.win-amd64-3.7\npre
  copying npre\curves.py -> build\lib.win-amd64-3.7\npre
  copying npre\umbral.py -> build\lib.win-amd64-3.7\npre
  copying npre\__init__.py -> build\lib.win-amd64-3.7\npre
  creating build\lib.win-amd64-3.7\npre\util
  copying npre\util\__init__.py -> build\lib.win-amd64-3.7\npre\util
  running build_ext
  building 'npre.elliptic_curve' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
 ` 
`Command "C:\Python\Python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\azbeg\\AppData\\Local\\Temp\\pip-req-build-9z5iqrd1\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\azbeg\AppData\Local\Temp\pip-wheel-h4xhbhrl --python-tag py3" failed with error code 1 in C:\Users\azbeg\AppData\Local\Temp\pip-req-build-9z5iqrd1\ `
`  ----------------------------------------
ERROR: Failed to install npre==0.3 from git+https://github.com/nucypher/nucypher-pre-python.git.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
> Task :app:generateDebugPythonRequirements FAILED
> Task :app:prepareLintJarForPublish 
FAILURE: Build failed with an exception.`
`* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Python/Python37/python.exe'' finished with non-zero exit value 1. For full details, open the 'Build' window and switch to text mode with the 'Toggle view' button on the left.
`* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`* Get more help at https://help.gradle.org
BUILD FAILED in 40s
11 actionable tasks: 8 executed, 3 up-to-date
ERROR: Process 'command 'C:/Python/Python37/python.exe'' finished with non-zero exit value 1. For full details, open the 'Build' window and switch to text mode with the 'Toggle view' button on the left. `

Thanks!!

**Comment by mhsmith** [comment]
Please try switching your app over to `umbral`, and if you have any issues with it, give details at #98.

**Comment by KebAz** [comment]
Hi, please how to fix this error:
ValueError: Input ciphertext must be a bytes object of length >= 12
It's occurred when I'm trying to decrypt the encrypted message using pre.decrypt() function.

**Comment by mhsmith** [comment]
This isn't the place for general umbral support. Unless you have some reason to believe that the problem is specific to Chaquopy, please use [the umbral GitHub page](https://github.com/nucypher/pyUmbral/issues). 

And I'm sure they'd appreciate a full stack trace, plus any other relevant information you can provide.

**Comment by mhsmith** [comment]
Ah, I see you've already done so: https://github.com/nucypher/pyUmbral/issues/253.
