### ISSUE TITLE
I'd like to ask if I can open the file in the local directory of the mobile phone. Can I read the stram passed by Android?

### ISSUE THREAD

**Issue by postdep** [chaquo/chaquopy#156]
I'd like to ask if I can open the file in the local directory of the mobile phone. Can I read the stram passed by Android?

**Comment by postdep** [comment]
#38 It seems to answer my question, but it just prints out the root directory path of the android phone. If I want to load the XLS file under the root directory download, how should I write the complete code? I hope you can help me

**Comment by mhsmith** [comment]
If you've followed the steps from #38:

> First, make sure your app has the `WRITE_EXTERNAL_STORAGE` permission in its manifest. If the app targets API 23 or later, you'll also have to activate the storage permission, either by requesting it interactively as described [here](https://developer.android.com/training/permissions/requesting), or by enabling it in Settings > Apps.
>
>Then you can do something like this:
>```
>>>> from android.os import Environment
>>>> d = str(Environment.getExternalStorageDirectory())
>>>> d
>'/storage/emulated/0'
>```

Then you can construct the filename with something like `d + "/filename.xls"`.

**Comment by postdep** [comment]
thank you i try it success！
