### ISSUE TITLE
how can I inherit the local Python library through PIP

### ISSUE THREAD

**Issue by postdep** [chaquo/chaquopy#158]
When I use PIP integration to specify Python library, because of network problems, I can't download it in gradle, so I download Python library through other ways, so how can I inherit the local Python library through PIP?

**Comment by postdep** [comment]
For example, in some developing countries, there will be a network blockade, which will result in the inability to access and download websites that could have been accessed

**Comment by mhsmith** [comment]
You can install Python libraries in any format supported by pip (whl, zip or tar.gz), by giving a local filename, as in the "LocalPackage" example shown [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements). The pip `--find-links` and `--index-url` options can also be used with a local directory path.

You won't be able to use a whl file from pypi.org if it contains native code (i.e. its filename contains an OS name such as `win32` or `manylinux`). Instead, these packages should be downloaded from https://chaquo.com/pypi-2.1/.

**Comment by postdep** [comment]
I still don't understand. For example, https://chaquo.com/pypi-2.1/numpy/, only 1.14.2 above, but the version is already 1.17. However, the version I specified in gradle always indicates that it can't be downloaded, so I hope you can help me

**Comment by mhsmith** [comment]
You can only specify the versions which are available from chaquo.com (e.g. `install "numpy==1.14.2"`). Or you can specify no version (e.g. `install "numpy"`), and the newest compatible version will be used.

To be updated when we release a newer version of NumPy, please subscribe to #159.
