### ISSUE TITLE
Update NumPy

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#159]
I've received a couple of requests to provide a new version of NumPy. If anyone else is interested in this, please subscribe to this issue and add a thumbs up.

**Comment by daqiit** [comment]
the native numpy is 1.14，but the latest version is 1.17.

**Comment by mhsmith** [comment]
NumPy 1.17.4 is now available.

If you're using TensorFlow, you might see the following warning:

`tensorflow 1.10.1 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.17.4 which is incompatible.`

This is probably harmless (https://github.com/tensorflow/tensorflow/issues/21866), but can be worked around by explicitly installing "numpy==1.14.2".
