### ISSUE TITLE
 Read .pickle file with Chaquopy

### ISSUE THREAD

**Issue by Leandropslv** [chaquo/chaquopy#160]
How should the setting be so that I can access a .pickle file (where I should put it, and how I access it) in my script.py. I could not do this through the documentation.

**Comment by Leandropslv** [comment]
E/MethodChannel#processing.channel/milho_scan(13098): com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'my_classifier.pickle'

I added the .pickle file to the same directory as the script.

import pickle

    f = open('my_classifier.pickle', 'rb')
    classifier = pickle.load(f)
    f.close()

**Comment by mhsmith** [comment]
See #144.

**Comment by mhsmith** [comment]
[By @Leandropslv, moved from #144]

I received this error:

```
com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.codecs.decode(codecs.py:321)
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.new.test(new.py:180)
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.example.milho_scan_app.MainActivity.lambda$onCreate$0(MainActivity.java:63)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.example.milho_scan_app.-$$Lambda$MainActivity$FJZXqDLBvILvLH7E3hcCNSZrVNA.onMethodCall(lambda)
E/MethodChannel#processing.channel/milho_scan(24144): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#processing.channel/milho_scan(24144): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#processing.channel/milho_scan(24144): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.app.ActivityThread.main(ActivityThread.java:5530)
E/MethodChannel#processing.channel/milho_scan(24144): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
```

My code is this:

```
from os.path import dirname, join
f = open(join(dirname(file), 'my_classifier.pickle'))
import pickle
classifier = pickle.load(f)
resultado = classifier.predict(dados)    #Essa é a linha 180
print(resultado)
```

The (open) method in the Chaquopy environment returns: <class '_io.TextIOWrapper'>
In the Normal Python environment, returns: <class '_io.BufferedReader'>

My code in the Normal Python environment is this:

```
import pickle
f = open('my_classifier.pickle', 'rb')
classifier = pickle.load(f)
print(type(f))
f.close()
resultado = classifier.predict(dados)
print(resultado)
```

**Comment by mhsmith** [comment]
Are you sure the stack trace corresponds to that code? If the line you've indicated with the comment is actually line 180, then the error is happening inside `classifier.predict`, after the file has already finished loading.

However, if it is related to loading the file, then the cause is probably that you forgot to pass `rb` to the `open` function. As mentioned in the [`pickle` documentation](https://docs.python.org/3.7/library/pickle.html), pickle files must be opened in binary mode.

**Comment by Leandropslv** [comment]
Good friend, this part is running well now, is returning the same thing as the Normal Python environment, I'm just getting it now:

PlatformException (error, ModuleNotFoundError: No module named 'sklearn', null)

do i have to import something?

I am doing a very good project, just missing this to conclude, I will disclose to people to clear these doubts that I had.

**Comment by Leandropslv** [comment]
classifier = pickle.load(f)  #This is the line containing the error.

**Comment by Leandropslv** [comment]
In my Python project I just import the pickle and wheel.

**Comment by mhsmith** [comment]
You'll have to install `scikit-learn` using the `pip` block in your `build.gradle` file, as described [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements).

**Comment by Leandropslv** [comment]
Thank you very much, you are an excellent professional. It all worked out now.
