### ISSUE TITLE
 com.chaquo.python.PyException: OSError: Unable to open file (unable to open file: name = 'C:\Users\PCNAME\AndroidStudioProjects\OpenCVExample-master\app\src\main\python\model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by abhishekpundir22** [chaquo/chaquopy#161]
Working on some open cv number detection app where I was trying to load a trained keras model into chaquopy python api but it shows that it isnt able to open the file 'No such file or directory'

I have pasted the actual location of my model and still its not working..
    model = load_model(r'C:\Users\PCNAME\AndroidStudioProjects\OpenCVExample-master\app\src\main\python\model\model.h5')

**Comment by mhsmith** [comment]
To access data files stored in the source code directory, see #144.
