### ISSUE TITLE
com.chaquo.python.PyException: ValueError: Unknown layer:name

### ISSUE THREAD

**Issue by abhishekpundir22** [chaquo/chaquopy#162]
Having this error while deploying a Keras model in chaquoPy.

**Comment by mhsmith** [comment]
We can't really help with general Keras questions. But if you've found something that works on other platforms but not on Chaquopy, please give more details.

**Comment by abhishekpundir22** [comment]
I have seen people claiming that this issue is solved in keras 2.2.4 update. Is there anyway to update keras in ChaquoPy?

**Comment by mhsmith** [comment]
You can install any specific version of `keras` using the `pip` block in `build.gradle`. Then access the API through the `keras` package rather than `tf.keras`.

**Comment by abhishekpundir22** [comment]
Found a way to solve this problem... just need to match the keras version of your model with the version of keras you are installing in ChaquoPy.

**Comment by SirCarlitros** [comment]
> Found a way to solve this problem... just need to match the keras version of your model with the version of keras you are installing in ChaquoPy.

Can you provide code?
do you talk about add version keras in python code like:
tf.compat.v1.keras.applications.vgg19.VGG19

**Comment by mhsmith** [comment]
The current version of Chaquopy uses TensorFlow 2.x, for which using the standalone `keras` package is [no longer recommended](https://github.com/keras-team/keras/releases/tag/2.4.0).

If you're trying to convert a model to be compatible with TensorFlow 2.x, you might find some useful information in #325.

However, this isn't the place to get general support with Keras or TensorFlow. Unless you've found something that works on other platforms but not on Chaquopy, you should seek help elsewhere.
