### ISSUE TITLE
Do we have any support in Chaquopy where we can write signal processing code?

### ISSUE THREAD

**Issue by karimkhanp** [chaquo/chaquopy#163]
I have written my code in Python. Which does signal processing using scientific and mathematical libraries like numpy, scipy, pandas.

I wanted to use this functionality in the Android device. So I have two option

1. I run the same python code in Android device ( But I guess this is not supported yet. I am ready to write utility if this is possible. ) 

2. Write the same signal processing code for Android. Let me know what is the recommended option for this.

Can I run this signal processing code in Android device using Chaquopy?

**Comment by mhsmith** [comment]
Numpy, scipy and pandas are all supported by Chaquopy. Just build them into your app as described in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements). Then you should be able to reuse your existing Python code.
