### ISSUE TITLE
import library

### ISSUE THREAD

**Issue by tuananhkidd** [chaquo/chaquopy#166]
I can not install "cv2" library 
![image](https://user-images.githubusercontent.com/31892061/68580297-a5bf0e80-04a8-11ea-81d0-eca15f5397bf.png)
Please help.

**Comment by tuananhkidd** [comment]
This is log:
![image](https://user-images.githubusercontent.com/31892061/68580333-ba030b80-04a8-11ea-9941-85d681a0e8c3.png)

**Comment by mhsmith** [comment]
The OpenCV package name on PyPI is `opencv-python`, not `cv2`.
