### ISSUE TITLE
Python read image from camera preview 

### ISSUE THREAD

**Issue by tuananhkidd** [chaquo/chaquopy#167]
In camera i get byte[] then how can i read image in python from this byte[].
Pls help me.

Thanks and best regard,

**Comment by mhsmith** [comment]
If you pass your byte[] to Python code, it can be converted to a Python byte array by passing it to the `bytes` function. Then you can convert it to whatever type you want, e.g. to make a NumPy array you would use [`frombuffer` and `reshape`](https://stackoverflow.com/questions/53376786).

**Comment by mhsmith** [comment]
To do the reverse (pass a NumPy array to Java):

* Convert the array to a Python `bytes` object using [`tobytes`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.tobytes.html).
* Return the `bytes` object from Python to Java using [`callAttr`](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html#callAttr-java.lang.String-java.lang.Object...-) or [`get`](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html#get-java.lang.Object-).
* Convert it to a Java array using [`toJava(byte[].class)`](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html#toJava-java.lang.Class-).

**Comment by sarthaksharma058439** [comment]
You can watch this video , in this video you will learn how to pass image in chaquopy and convert this image into grayscale and set image after process in imageview in android app

https://youtu.be/gHrfPuT4qDE

**Comment by sergiysavelyev** [comment]
> Once you've passed your byte[] to Python code, it can be efficiently converted to a Python byte array using the `bytes` function. Then you can convert it to whatever type you want, e.g. to make a NumPy array you would use [`frombuffer` and `reshape`](https://stackoverflow.com/questions/53376786).


Question: following the above advice I pass the byte[] object from Java to Python, then convert it to Python 'bytes', then use 'frombuffer' function and end up with numpy array shape (1382400,). This number is basically 640x480x3x1.5. My Java byte[] is NV21 camera preview frame. The issue is that I need to get a 3D numpy array after applying reshape to frombuffer output, but 640, 480, 3 arguments won't work, as it expects (921600,) shape array. I have read many different articles and posts from many different resources, but so far have not been able to find a working solution. The link to youtube video does not cover camera preview bytes manipulation in Java and Python. Any help is appreciated.

**Comment by mhsmith** [comment]
If you need an RGB image, then the simplest solution would be to ask the camera preview API to give you an RGB image to start with, but that might not be supported by all devices.

If you can work out which part of the array corresponds to the Y channel, then you could treat it as a grayscale image.

You could use the Android API to encode the image as PNG, pass that to Python as a byte array, and decode it back into RGB. That would save you needing to worry about dimensions and pixel formats, but it probably wouldn't have very good performance.

Or you could convert NV21 to RGB directly. There are probably ways to to this in Java, but it looks like you can also do it in Python using OpenCV, as described in [this answer](https://stackoverflow.com/questions/54566713). In summary:
* Reshape the byte array to `((3*h)//2, w)`, i.e. (720, 640) for a 640x480 image.
* Pass it to `cv2.cvtColor` with `cv2.COLOR_YUV2BGR_NV21` or `COLOR_YUV2RGB_NV21`.

However, I don't understand where the x3 is coming from in your calculation. All sources I've read indicate that NV21 is 1.5 bytes per pixel.

**Comment by sergiysavelyev** [comment]
Thanks for the last tip. Apparently all this time I have been working with the wrong camera preview resolution. I was doing parameters.setPreviewSize in startPreview() function, but it was not really changing the preview size. Now when I update the previewsize in surfaceCreated function (it's in another class in my instance), I can process the cameraPreview frame in Python correctly using various methods including the one you originally described. I have chosen to continue experimenting with PIL.image. Once I pass the bytes jarray (data - argument on Python side) to Python, next I apply the below 2 lines to get the PIL image object. 

```
p_bytes = bytes(data)
img = PIL.Image.frombytes('L', (640,480), p_bytes, 'raw')
```

This gives me a grayscale image.
