### ISSUE TITLE
ReadTimeoutError in pip install when building application.

### ISSUE THREAD

**Issue by 2020akumar** [chaquo/chaquopy#170]
Whenever I try and build my application, I get a ReadTimeoutError while Chaquopy collects the packages I use in my app(numpy and tensorflow). This error appeared around 2 days ago, even though I had made no changes to previously working code. 

Here is the exact error that I get:
![pip failing](https://user-images.githubusercontent.com/50772992/68876129-fa919d80-06d1-11ea-82d3-790eba1afd97.PNG)

**Comment by mhsmith** [comment]
You've closed the issue: does this mean the problem has stopped?

**Comment by 2020akumar** [comment]
> You've closed the issue: does this mean the problem has stopped?

Turns out it was an issue with my local computer - not Chaquopy.
