### ISSUE TITLE
Executing more than one single line code.

### ISSUE THREAD

**Issue by SuhasSrikar** [chaquo/chaquopy#171]
I want to execute more than single line code for example like functions. But the console is not giving me the output. Should I change any py scripts?

**Comment by mhsmith** [comment]
If you mean you want to write your own console-based app, have a look at https://github.com/chaquo/chaquopy-console/. 

If you mean something else, please give more details.

**Comment by SuhasSrikar** [comment]
I did the same. But if I want to execute multi line code.
Something like this : 

def reverse(s): 
	return s[::-1] 

```
def isPalindrome(s): 
	rev = reverse(s) 
	if (s == rev): 
		return True
	return False


s = "madam"
ans = isPalindrome(s) 

if ans == 1: 
	print("Yes") 
else: 
	print("No") 

```

If I try to execute the above code. I'm getting this error

**Comment by mhsmith** [comment]
Although you can type multi-line programs into the interactive console, indentation is difficult to get right. I suggest you use [the console template](https://github.com/chaquo/chaquopy-console/) instead.

**Comment by SuhasSrikar** [comment]
Okay. I'll try it

**Comment by SuhasSrikar** [comment]
I see that [console template](https://github.com/chaquo/chaquopy-console/) doesn't run the python code. Should I explicity do that?

**Comment by SuhasSrikar** [comment]
Hey @mhsmith I have used [console template](https://github.com/chaquo/chaquopy-console/) but still I couldn't execute multi line program. It gives me the same Indentation error

**Comment by mhsmith** [comment]
I've taken the code above and pasted it into the body of the `main` function at https://github.com/chaquo/chaquopy-console/blob/master/app/src/main/python/main.py. It works fine, and correctly prints "Yes".

However, your code is indented with tabs whereas the original version of main.py uses spaces. A Python  file must be indented either with all tabs or all spaces. If there is any mixture, you'll get indentation errors.

**Comment by SuhasSrikar** [comment]
Yeah it is working. But not when I enter dynamically and I guess I know where is the problem.


So basically when we are entering the code directly into the main.py body. It takes all the lines and executes. So I was trying in Python IDE to assign the code as a string to a variable and execute through `exec()` .

When I code like

```
code = '''
def reverse(s): 
	return s[::-1] 
def isPalindrome(s): 
	rev = reverse(s) 
	if (s == rev): 
		return True
	return False


s = "madam"
ans = isPalindrome(s) 

if ans == 1: 
	print("Yes") 
else: 
	print("No") '''

exec(code)
```
I'm getting the correct output which is `Yes`

But when I try to enter the same code dynamically by taking it as input


```
code = input()
codeFormat = "\'\'\'%s\'\'\'"%code
compile(codeFormat,"file_name","exec") #it compiles inputs like code, functions etc
exec(codeFormat)
```

Then by theory it should work. The problem is `input()` is reading only one line which makes me more frustated whenever I run this code. I googled some methods to read multiline line inputs. But no luck

@mhsmith I hope you got a solution for this.

**Comment by mhsmith** [comment]
Well, if you want to input multiple lines, then just call `input` multiple times in a loop until the user enters a blank line or some other [sentinel value](https://en.wikipedia.org/wiki/Sentinel_value). Then join all the lines together into a single string, which I think you probably shouldn't wrap in triple-quotes in this context.

This isn't really a question about Chaquopy anymore: this code would behave the same with Python on any platform.

**Comment by SuhasSrikar** [comment]
Sorry @mhsmith it was my bad. Actually it was working without the console template. But we need to press enter twice to get the correct output. I just enter the code and waiting it showed me `... ...` I didn't get it anything then out of frustration I just tapped the enter again and it gave me the correct output. LOL
