### ISSUE TITLE
How to use a python function?

### ISSUE THREAD

**Issue by massicalic** [chaquo/chaquopy#174]
I don't understand how to use a python module function inside the java code.

I wrote module test.py, with one function
def c_area(b,h):
    area=h*b
    return area

In the activity, for run python i wrote:
if (! Python.isStarted()) {
            Python.start(new AndroidPlatform(activity.getApplicationContext()));
        }
Python py = Python.getInstance();
PyObject test = py.getModule("test");

What sholuld i do now?

**Comment by mhsmith** [comment]
You can use `test.callAttr`, as you previously posted in #173. Then to convert the function's result to a Java data type, you can use `toString`, `toInt`, `asList`, or any of the other conversion methods listed in [the PyObject documentation](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html).

**Comment by massicalic** [comment]
I have insert:
 int i = test.callAttr("c_area", 2, 3).toInt();

Thank's now run!
