### ISSUE TITLE
Add a python native library migration guide,please.

### ISSUE THREAD

**Issue by ghost** [chaquo/chaquopy#175]
During use, I need some python wrapper for the c language native library. 
For example: opencv-contrib-python.
I tried to compile it with NDK, but only generated the java wrapper.
So I want to know how to generate python wrappers

**Comment by mhsmith** [comment]
Building native packages for Android is a complicated process, so rather than writing a guide, we'd be more likely to open-source our actual build system. We're not ready to do that yet, but I'll update this issue if we do.

**Comment by mhsmith** [comment]
If you want to build Python libraries containing native code, you can now license our package build tool, which was used to build everything in our [native package repository](https://chaquo.com/pypi-7.0/). It supports pybind11, Cython, CMake, and many other build systems, and handles a wide variety of cross-compilation issues.

The tool runs on Linux, and comes with an optional Dockerfile for easier dependency management and reproducibility.

The cost of this tool is $250 -- this is separate to the license for Chaquopy itself. If you're interested in this, please [email us](https://chaquo.com/chaquopy/contact/) for more details.

**Comment by mhsmith** [comment]
The package build tool is now open-source and is available [here](https://github.com/chaquo/build-wheel).
