### ISSUE TITLE
How to download and run Python from the server

### ISSUE THREAD

**Issue by jhflovehqy** [chaquo/chaquopy#177]
I want to put Python scripts on the server，Place locally through script distribution.I try to download it and put it in data/data/{package name}/files/chaquopy/AssetFinder/app,But there will be an error. We can't find this file.Where should I put it.

**Comment by mhsmith** [comment]
Please don't alter the contents of `files/chaquopy`: this is an implementation detail and may change in future versions.

Instead, I suggest you create your own directory under `files`, and append it to `sys.path`. Then you'll be able to load files from that directory using `importlib.import_module`.

**Comment by jhflovehqy** [comment]
How should I refer to the customization file directory？Please give me some advice.

**Comment by jhflovehqy** [comment]
Where should I create this directory？How to write Python files dynamically？

**Comment by mhsmith** [comment]
You can get the `files` location programmatically like this:

```
from com.chaquo.python import Python
files_dir = Python.getPlatform().getApplication().getFilesDir()
```

Then you can create things into that directory using the standard Python file APIs.

**Comment by massicalic** [comment]
> You can get the `files` location programmatically like this:
> 
> ```
> from com.chaquo.python import Python
> files_dir = str(Python.getPlatform().getApplication().getFilesDir())
> ```
> 
> Then you can create things in that directory using the standard Python file APIs.

It doesn't seem to work for me. I create the CSV file like this:
files_dir = str(Python.getPlatform().getApplication().getFilesDir())
df_signaures.to_csv(files_dir+'graduate_signatures.csv')

When I try to open this file:
files_dir = str(Python.getPlatform().getApplication().getFilesDir())
open(join(dirname(files_dir), 'graduate_signatures.csv'))

I get this error:
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.graduationintime/graduate_signatures.csv'

**Comment by mhsmith** [comment]
`files_dir` is already a directory name (probably "/data/user/0/com.example.graduationintime/files". When you call `dirname` on it you're going one directory up.

Also, you should use `join` rather than `+`, because the filename you construct here is probably "filesgraduate_signatures.csv", without a slash.

**Comment by sdurandeu** [comment]
@mhsmith does this imply that we can potentially avoid shipping the python files with the apk and instead download it over-the-air once the app is installed/running (eg. after login). I'm asking this because we are evaluating approaches to minimize the exposure of our python code (although  aware that full protection is not possible). Thanks!

**Comment by mhsmith** [comment]
Yes, you can load any Python file at runtime by adding its directory to `sys.path` and calling `importlib.import_module`. After it's loaded you can delete the file if you want.

However, when a suitable version of Python is available at build time, Chaquopy will [compile your code to .pyc format](https://chaquo.com/chaquopy/doc/current/android.html#bytecode-compilation) by default, so your source code won't be included in the APK anyway.

**Comment by PhiFry** [comment]
I did it like this:

```kotlin
...
Python.start(MyPlatform(AndroidPlatform(applicationContext), applicationContext.filesDir.path + "/PythonScripts"))
...

class MyPlatform(
    private val androidPlatform: AndroidPlatform,
    private val path: String,
) : Python.Platform() {
    override fun getPath(): String = androidPlatform.path + ":" + path
    override fun onStart(py: Python) = androidPlatform.onStart(py)
}
```
