### ISSUE TITLE
How can I pass an image to my python script from my Kotlin script 

### ISSUE THREAD

**Issue by yellowwoods12** [chaquo/chaquopy#178]
I have an application with successful chaquopy integration in it. I want to pass an image to my called python function and return a string back to the kotlin code. I have a bitmap of the captured image. How can I accomplish passing an image as a parameter to a python function?

**Comment by mhsmith** [comment]
Assuming you want the Python code to access the actual image data, I recommend you convert your bitmap to a Java `byte[]` array, then pass that to the Python `bytes` function. See #167 for more details.

**Comment by sarthaksharma058439** [comment]
You can watch this video , in this video you will learn how to pass image in chaquopy and convert this image into grayscale and set image after process in imageview in android app

https://youtu.be/gHrfPuT4qDE

**Comment by jercylew** [comment]
Alternatively, I managed to do this by converting the Image to base64 encoded string, then decode it back to Image data of numpy.ndarray in the Python side

**Comment by mhsmith** [comment]
There's no need to use base64, just convert the Java `byte[]` array to a `numpy.ndarray` directly.
