### ISSUE TITLE
Python API to fetch android OS details

### ISSUE THREAD

**Issue by connect2satz** [chaquo/chaquopy#18]
Is there any python api to fetch os information for android, i tried os.name,sys.platform etc, these are not giving anything related to android.

**Comment by mhsmith** [comment]
Android is Linux-based, so the Python standard library APIs will report that the OS is Linux. If you want Android-specific details, you can do something like this:

```py
try:
    from android.os import Build
except ImportError:
    # Not running on Android
else:
    # Get Android OS and device information from Build
```
