### ISSUE TITLE
How to plot data in pyhton file?

### ISSUE THREAD

**Issue by Raghu17s** [chaquo/chaquopy#180]
Hi,
I have performed some calculations in python file and need to plot them for display. 
What is the best way to accomplish the task?

**Comment by mhsmith** [comment]
The simplest way is probably to write the plot to a temporary PNG file. Then you can load the file and display it in the user interface using Android APIs which you can easily find examples of elsewhere.

**Comment by Raghu17s** [comment]
I need to design a plot which changes it's values based on user selection.
Do you have any such issues examples?

**Comment by mhsmith** [comment]
I don't have an example specifically involving images, but for a complete example of an Android graphical user interface using Chaquopy, have a look at the [Electron Cash app](https://github.com/Electron-Cash/Electron-Cash/tree/master/android). 

This uses the recommended approach of programming the UI in Java or Kotlin using standard Android techniques, and accessing Python through the PyObject API.
