### ISSUE TITLE
How to import pillow?

### ISSUE THREAD

**Issue by Zhangpyxjtu** [chaquo/chaquopy#181]
I pip install "pillow" in the build.gradle, but when I use "from PIL import Image" in my .py file, my  logcat show "ModuleNotFoundError: No module named 'Image' ". 
Could you tell me how to solve this problem?

**Comment by mhsmith** [comment]
Please provide:
* The `python` block from your build.gradle file
* The section of source code which causes the error
* The full stack trace

By the way, are you the same person who asked [this question](https://stackoverflow.com/questions/58931675)?

**Comment by Zhangpyxjtu** [comment]
The python block from my build.gradle file
 python {
            buildPython "C:/Users/Z/AppData/Local/Programs/Python/Python36/python.exe"
            pip
                    {
                        install "numpy"
                        install "opencv-python"
                        install "pillow"
                    }
        }
The section of source code which causes the error
import numpy as np
from PIL import Image
from PIL import ImageDraw
sum_rows=imgtest.shape[0]
sum_cols=imgtest.shape[1]

I am not the same person who asked the question.

**Comment by mhsmith** [comment]
Are you sure you're rebuilt and reinstalled the app since adding the pip install commands? Please have a look at the comments in [this question](https://stackoverflow.com/questions/58931675).

Do you have a module or directory in your source code called `PIL` or `Image` which could clash with pillow?

If that doesn't help, please post the full stack trace.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and give the requested information.

**Comment by KingWu** [comment]
i face the same issue. Found the following error
name `image` is not defined

```
python {
            pip {
                install "matplotlib"
                install "schedule==0.6.0"
                install "numpy"
                install "imutils==0.5.3"
                install "dlib"
                install "opencv-python"
                install "scipy"
                install "Pillow"
            }
        }
```

**Comment by mhsmith** [comment]
Please post the full stack trace, and the relevant sections of your code.
