### ISSUE TITLE
Please support librosa Library

### ISSUE THREAD

**Issue by postdep** [chaquo/chaquopy#185]
Please support librosa library, unable to load at present！

**Comment by mhsmith** [comment]
As discussed in #21, please try the following in the [`pip` section](https://chaquo.com/chaquopy/doc/current/android.html#requirements) of your build.gradle:

```
install "joblib==0.11"
install "librosa==0.4.2"
```

When I did that, I still received some warnings, but the librosa import completed successfully.

**Comment by mhsmith** [comment]
If you still have problems after doing this, please give details in #21.

**Comment by mhsmith** [comment]
If you're using Chaquopy 8.0.1. or later, there's no longer any need to use old versions of librosa or joblib.

To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle`.
