### ISSUE TITLE
How to use opencv for image processing

### ISSUE THREAD

**Issue by Zhangpyxjtu** [chaquo/chaquopy#188]
Can you provide an example of image processing using opencv and chaquopy in Android Studio? If so, please give me a link to Github.

**Comment by mhsmith** [comment]
I don't have any example ready, but you should be able to use all the normal OpenCV features, except for the following:
* Direct access to camera hardware
* Direct user interaction (e.g. [waitKey](https://stackoverflow.com/questions/56224122), [imshow](https://stackoverflow.com/questions/57648034))
* Reading and writing video files (image files will be fine)

If you've had any specific issues then please give details. (Which I see you've already done in #190.)
