### ISSUE TITLE
Reading text files or config files

### ISSUE THREAD

**Issue by MustafaHalimehHH** [chaquo/chaquopy#19]
I can't read the content of text files or json files from the python scripts in the directory python in my android project.
It shows always that the path is wrong.
I checked the path using python os.path.dirname(__file__) it returns (/android_asset/chaquopy/app.zip/)
but that path is not exist when I try to use it with other not python files.
So how can I open and read files located beside my python scripts. does the library keep these files after building the apk because I could not find them in my application data folder.

**Comment by mhsmith** [comment]
All files in the python source directory are built into the APK (except .pyc files). However, they're stored in a ZIP file in the assets, so you can't open them directly. Instead, you can use [`pkgutil.get_data`](https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data). 

Here's an example which should work in the demo app Python console:

```
>>> from pkgutil import get_data
>>> import chaquopy.demo
>>> get_data(chaquopy.demo.__name__, "utils.py")
b'from os.path import join\r\nimport sys\r\n\r\nif sys.version_info[0] == 2:\r\n    from StringIO import StringIO\r\n [...]
```

If this code was running in any module in the `chaquopy.demo` package, then it could simply have passed `__name__`. as the first argument of `get_data`.

**Comment by MustafaHalimehHH** [comment]
Thanks.
So pkgutil.get_data returns the content or a raw file, and what does it take parameters, and if I want to access a file inside a folder then how the call to get_data will be.

**Comment by mhsmith** [comment]
It returns the content as a byte string. If you want to read it like a file, then you can wrap it in [`BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO) or [`StringIO`](https://docs.python.org/3/library/io.html#io.StringIO). For example:
```
>>> from io import StringIO
>>> f = StringIO(get_data(chaquopy.demo.__name__, "utils.py").decode())
>>> f.readline()
'from os.path import join\r\n'
>>> f.readline()
'import sys\r\n'
```

The first parameter of `get_data` is a module name, and the second parameter is a filename relative to that module's directory, which can include folders. For example `get_data("chaquopy", "demo/utils.py")` would return the same thing.
