### ISSUE TITLE
cv2.imwrite cause errors

### ISSUE THREAD

**Issue by Zhangpyxjtu** [chaquo/chaquopy#190]
When I write in the .py file：

import cv2
from android.os import Environment
d = str(Environment.getExternalStorageDirectory())
d
'/storage/emulated/0'
def img():
    img = cv2.imread("/storage/emulated/0/photo.jpg")
    cv2.imwrite("/storage/emulated/0/photo2.jpg",img)

I opened photo.jpg in "/storage/emulated/0/"
But I didn't find photo2.jpg in this directory;
I found photo2.jpg in the root directory, but it is 0b, I can't open it.

**Comment by mhsmith** [comment]
You've closed the issue: does that mean you solved the problem?

**Comment by Zhangpyxjtu** [comment]
I have solved the problem. Thanks

**Comment by davidyang180** [comment]
Hello! How do you solve this problem? I use cv2.imread to read the image file as none according to your method.

**Comment by mhsmith** [comment]
See also #251.
