### ISSUE TITLE
When some packages cannot be downloaded in gradle, can they be imported locally

### ISSUE THREAD

**Issue by postdep** [chaquo/chaquopy#192]
It's true that many packages can't be downloaded in gradle. Maybe it's because I'm in China. So some packages can be downloaded locally through other ways. How can I integrate them locally?

**Comment by mhsmith** [comment]
Package installation could fail for many reasons. Please provide the full error message.

**Comment by postdep** [comment]
In fact, there's no big reason. It's a well-known reason that makes some websites inaccessible to me, so I have to use the local update method

**Comment by mhsmith** [comment]
You can use the `pip { options ... }` syntax to pass custom options to `pip install`. In particular, you could look at the `--extra-index-url` and `--find-links` options. As the [pip documentation](https://pip.pypa.io/en/stable/reference/pip_install/) explains, both of these can be used with local directories.
