### ISSUE TITLE
ImportError: Failed to load coins.json

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#195]
_Originally posted by @liyanhrxy in https://github.com/Electron-Cash/Electron-Cash/issues/1062#issuecomment-564995393_

how to resolve error like this ? the file was really exists !!!

![image](https://user-images.githubusercontent.com/32901980/70713617-5e36d700-1d21-11ea-8b46-f96048857a2b.png)

**Comment by mhsmith** [comment]
Please don't use the Electron Cash issue tracker for issues which don't involve their code.

You're including the python-trezor source tree at the wrong level. The top-level package should be `trezorlib`, not `python-trezor.src.trezorlib`.

Instead of including the submodule directly within src/main/python, I suggest you move the submodule somewhere else, and then edit the [`sourceSets` section](https://chaquo.com/chaquopy/doc/current/android.html#source-code) of build.gradle to include the line:

```
srcDir "path/to/python-trezor/src"
```

**Comment by liyanhrxy** [comment]
> Please don't use the Electron Cash issue tracker for issues which don't involve their code.
> 
> You're including the python-trezor source tree at the wrong level. The top-level package should be `trezorlib`, not `python-trezor.src.trezorlib`.
> 
> Instead of including the submodule directly within src/main/python, I suggest you move the submodule somewhere else, and then edit the [`sourceSets` section](https://chaquo.com/chaquopy/doc/current/android.html#source-code) of build.gradle to include the line:
> 
> ```
> srcDir "path/to/python-trezor/src"
> ```
> 
> ... where `path/to` is the relative path to the place you've put the submodule.

you are right !!! my problem has resolved, thanks a lot

**Comment by liyanhrxy** [comment]
`chaquo`  how to read it ?

**Comment by mhsmith** [comment]
Sorry, I don't understand your question.

**Comment by liyanhrxy** [comment]
I just want to know how to read it in chinese

**Comment by mhsmith** [comment]
If you mean the documentation, then it's only available in English, sorry.
