### ISSUE TITLE
pycryptodomex==3.9.4  install failed

### ISSUE THREAD

**Issue by liyanhrxy** [chaquo/chaquopy#197]
![image](https://user-images.githubusercontent.com/32901980/71161815-0bab6c80-2285-11ea-9039-68ed76465539.png)

**Comment by mhsmith** [comment]
We currently only offer version 3.6.6. If you need a newer version, please explain why.

**Comment by liyanhrxy** [comment]
the electrum 4.0 was used the version 3.9.4, I don't know why , my project is depending on it

**Comment by mhsmith** [comment]
Version 3.9.4 is now available.

**Comment by Nouman255** [comment]
Hi @mhsmith, I am trying to use the "Instagrapi" Python library in my Android app using Chaquopy. But it required Pycryptodomex 3.18.0, and currently only version 3.9.4 is available. You can check the Instagrapi requirements here:
https://github.com/subzeroid/instagrapi/blob/master/requirements.txt

Please add Pycryptodomex 3.18.0

**Comment by mhsmith** [comment]
For updates to pycryptodomex, please subscribe to #807. Meanwhile, you could try:

* Using an older version of Instagrapi; or
* Building a new pycryptodomex version yourself by following the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md).
