### ISSUE TITLE
import sndfile lib fail

### ISSUE THREAD

**Issue by zengjundeveloper** [chaquo/chaquopy#201]
ERROR: Failed to install sndfile from https://files.pythonhosted.org/packages/db/ce/797cacd78490aa9de2e0e119491079d380e2fbbd7a1c5057c9fb2120a643/sndfile-0.2.0.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

build.gradle
python {
            pip
                    {
                        install "numpy"
                        install "matplotlib"
                        install "librosa==0.4.2"
                        install "joblib==0.11"
                        install "soundfile"
                        install "sndfile"
                    }
        }

**Comment by mhsmith** [comment]
What you need is probably not the `sndfile` Python package, which seems to have hardly any users, but the native libsndfile library which the `soundfile` package uses. 

We might add this library in the future, but it isn't a priority at the moment. If anyone else wants it too, please subscribe to this issue and add a thumbs up to the original post.

**Comment by rimshach** [comment]
Hey I am facing the same issue and due to this I am not able to use SoundFile

**Comment by 009-dev** [comment]
I cant use sound file either! Please help!!!

**Comment by pigstars7** [comment]
I am facing the same issue ,please help!

**Comment by mhsmith** [comment]
We use the thumbs up count to see how popular a package is. So if you need this package, please *don't* post a comment: just add a thumbs up at the top of the page.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 8.0.1. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle`.
