### ISSUE TITLE
"Cannot create a consistent method resolution order" with androidx

### ISSUE THREAD

**Issue by PhilippeDou** [chaquo/chaquopy#203]
I am trying to develop an application with Androidx. 
If I create a Tabbed Activity project with Android Studio 3.5.2 with Chaquopy by converting the MainActivity class to Python, everything works perfectly.
I tried with the basic project Navigation Drawer Activity but I have a problem with **'implementation' androidx.navigation: navigation-fragment: 2.2.0 '** in app buid.gradle which returns me this error when the application is launched:

_com.chaquo.python.PyException: TypeError: Cannot create a consistent method resolution
    order (MRO) for bases LifecycleOwner, ViewModelStoreOwner, HasDefaultViewModelProviderFactory, SavedStateRegistryOwner, OnBackPressedDispatcherOwner_

Could you help me for this issue ?
Best regards

**Comment by mhsmith** [comment]
I believe this problem is fixed in a pre-release build of Chaquopy. Edit your app's top-level `build.gradle` file as follows:

* Change `https://chaquo.com/maven` to `https://chaquo.com/maven-test`.
* Change the version number of `com.chaquo.python:gradle` to `6.3.4`.

**Comment by PhilippeDou** [comment]
Great, now everything works perfectly !
Thank you so much.

**Comment by mhsmith** [comment]
I'll leave it open so other people can see it until it's fixed in a stable version.

**Comment by PhilippeDou** [comment]
Ok. Thank you

------ Message d'origine ------
De: "Malcolm Smith" <notifications@github.com>
À: "chaquo/chaquopy" <chaquopy@noreply.github.com>
Cc : "PhilippeDou" <sma@oceanet.fr>; "State change" 
<state_change@noreply.github.com>
Envoyé : 05/01/2020 13:05:39
Objet : Re: [chaquo/chaquopy] "Cannot create a consistent method 
resolutionorder" with androidx (#203)

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.

**Comment by mhsmith** [comment]
If you're using the above pre-release build, please now change `https://chaquo.com/maven-test` back to `https://chaquo.com/maven`, and switch to version 7.0.2 as described in the previous comment.

The pre-release build will be removed in 2 weeks.

**Comment by mhsmith** [comment]
The pre-release build has now been removed. See the previous comment for what to do if you're still using it.
