### ISSUE TITLE
ERROR READING CSV FILE IN PYTHON

### ISSUE THREAD

**Issue by farhan-khan-se-official** [chaquo/chaquopy#204]
Hi sir ,
i have many python file in my android project they are running very nice but now when 
i am  reading csv file using pandas it is giving error ,even the csv file is in same directory

sir can you help me how to read csv file here 

![Ca2](https://user-images.githubusercontent.com/58539056/71833146-32173780-30ce-11ea-868f-9fe711817199.PNG)
![Ca](https://user-images.githubusercontent.com/58539056/71833149-33e0fb00-30ce-11ea-865b-ce942dcb1b16.PNG)

**Comment by mhsmith** [comment]
See #144.
