### ISSUE TITLE
how to use the specified module source for the command "pip install" in  build_gradle

### ISSUE THREAD

**Issue by wwtghx** [chaquo/chaquopy#206]
In Windows platform, I can use the following command ::
pip install -i "https://pypi.tuna.tsinghua.edu.cn/simple"  "pillow";

Now, How can I do to in build.gradle?

**Comment by mhsmith** [comment]
Command-line options can be passed to pip using an `options` line in build.gradle: see https://chaquo.com/chaquopy/doc/current/android.html#requirements.

However, in the case of native packages like Pillow, only our Android builds from https://chaquo.com/pypi-2.1/ will work. You're welcome to copy them to your own repository if you want.
