### ISSUE TITLE
How to import function from module?

### ISSUE THREAD

**Issue by massicalic** [chaquo/chaquopy#207]
I'm having this error: com.chaquo.python.PyException: ImportError: cannot import name 'load_signatures_graduates'.
In file py i wrote this: from utils import load_signatures_graduates, abs_distance.
I iserted "utils" into the app using the pip block in build.gradle.
Which is the problem?

**Comment by mhsmith** [comment]
> I iserted "utils" into the app using the pip block in build.gradle.

How exactly? If you used a line like `install "utils"`, then you'll get the package from https://pypi.org/project/utils/, which I assume isn't what you want.

**Comment by massicalic** [comment]
I solved my problem, was an internal module, not an external packet.
