### ISSUE TITLE
Could not install duo to envirnment issue

### ISSUE THREAD

**Issue by miharek** [chaquo/chaquopy#209]
python\\requirements\\debug\\armeabi-v7a\\networkx\\algorithms\\centrality\\tests\\test_betweenness_centrality_subset.py'

when i try to install scikit-image it shows that error

**Comment by miharek** [comment]
No such file or directory

**Comment by mhsmith** [comment]
Post the full build log please.

**Comment by mhsmith** [comment]
If this is still a problem. please reopen and give the requested information.
