### ISSUE TITLE
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'app/src/main/python/slmit_103.mat'

### ISSUE THREAD

**Issue by LuArtur** [chaquo/chaquopy#218]
I tried to load a .mat file but it throws me the error com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'app / src / main / python / slmit_103.mat'.

I need help loading the file that contains an ECG record

**Comment by mhsmith** [comment]
You need to give the full directory path on the device: see #144.

**Comment by LuArtur** [comment]
I tried and the result was the same error

**Comment by LuArtur** [comment]
`def ecgsignal():
    f = open(join(dirname(__file__), '..python/slmit_103.mat"'))`

**Comment by mhsmith** [comment]
`..python` doesn't look like a valid directory name. If it's supposed to represent your top-level `app/src/python` directory, and this code is in the same directory, then you can just write `slmit_103.mat`.

**Comment by mhsmith** [comment]
Also, you've got a double quote mark within the single quotes.

**Comment by LuArtur** [comment]
Solved that, now a doubt. I can work the variable f as if it were my .mat or it is necessary to load it with loadmat of scipy

**Comment by LuArtur** [comment]
f = open(join(dirname(__file__), 'slmit_103.mat'))  treat the file as if it were text when it is actually a file from matlab and that contains several float-type arrays represented by an electrocardiogram signal

**Comment by mhsmith** [comment]
Then either open the file as binary with [`mode="rb"`](https://docs.python.org/3/library/functions.html#open), or just pass the filename directly to the scipy function, if it supports that.

**Comment by LuArtur** [comment]
solved that
