### ISSUE TITLE
how can I convert a PyObject returned by a function and that contains an array of numpy in a float java array?

### ISSUE THREAD

**Issue by LuArtur** [chaquo/chaquopy#219]
I have a function that returns a numpy array and I need to convert it to a java float arrangement. How can I do it?
the error returns to me
java.lang.ClassCastException: TypeError: Cannot convert ndarray object to java.lang.Float

this is my code 
`PyObject object= py.getModule("pyecgtool");
        PyObject func=object.callAttr("ecgsignal");

        Float a=func.toJava(float.class);`

**Comment by mhsmith** [comment]
If you want to convert it to an array, then you should write `float[].class`, not `float.class`.

**Comment by LuArtur** [comment]
thanks you
