### ISSUE TITLE
Impossible to import android.print.PrintDocumentAdapter

### ISSUE THREAD

**Issue by PhilippeDou** [chaquo/chaquopy#222]
Dear,
I would like to use the PrintDocumentAdapter class but when I put android.print.PrintDocumentAdapter I have a syntax error.
Could you help me ?
Best regards

**Comment by mhsmith** [comment]
Please post your code and the error.

**Comment by PhilippeDou** [comment]
Just the following line occurs an error :

from android.print import PrintDocumentAdapter

On Android Studio we see the p of 'print' which is underlinend. print is blued like python keyword.

**Comment by mhsmith** [comment]
As [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin) says, the IDE integration for editing Python code is not complete, so it will display some incorrect error messages. You can go ahead and run your app anyway, and if the error is real then it'll cause an exception which you can see in the Logcat window.
