### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by BiggyBill** [chaquo/chaquopy#223]
PermissionError: [Errno 13] Permission denied: 'ffprobe'
Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
I have this type of exception,
In my build.gradle file
python{
            pip{
              install "ffmpeg"
              install "pydub"
              install "ffprobe"
            }
        }
What should I do?
Thanks for responding quickly

**Comment by mhsmith** [comment]
FFmpeg is not currently available: please subscribe to #143 for updates.
