### ISSUE TITLE
install secp256k1 failed

### ISSUE THREAD

**Issue by shuaiLiWang** [chaquo/chaquopy#226]
I want install secp256k1，but it need pkg-config. I encountered this problem when i install pkg-config:
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-2.1, https://chaquo.com/pypi-6.2
Collecting pkg-config==0.29.1 (from -r ../../contrib/requirements/requirements.txt (line 1))
  Could not find a version that satisfies the requirement pkg-config==0.29.1 (from -r ../../contrib/requirements/requirements.txt (line 1)) (from versions: )
No matching distribution found for pkg-config==0.29.1 (from -r ../../contrib/requirements/requirements.txt (line 1))
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
If you're trying to install the [`secp256k1`](https://pypi.org/project/secp256k1/#history) package on PyPI, it looks like that's been abandoned. 

Instead, I suggest you use the same approach as Electron Cash, which is to install and load the library via `coincurve`, and then access it via `ctypes`. See : https://github.com/Electron-Cash/Electron-Cash/blob/master/lib/secp256k1.py.
