### ISSUE TITLE
how to restart Python without restarting app

### ISSUE THREAD

**Issue by TheForgetTime** [chaquo/chaquopy#227]
I want to get a brand new python instance without restarting the app.

I tried the built-in functions exit () and quit (), but they didn't work. They reported an error and my application crashed because of this.

**Comment by mhsmith** [comment]
Sorry, we're unlikely ever to support this because it won't work with many native modules. You'll have to find a different approach.

**Comment by mhsmith** [comment]
If you want to restart Python in order to reload your code, see #382.
