### ISSUE TITLE
RuntimeException at Python.getInstance()

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#230]
Got the following error:

Today, 6:22 AM on app version 35
Huawei Mate 20 lite (HWSNE), Android 10
Report 1 of 1
java.lang.RuntimeException: 
  at com.chaquo.python.GenericPlatform.<init> (GenericPlatform.java:9)
  at com.chaquo.python.Python.getInstance (Python.java:28)

**Comment by mhsmith** [comment]
Your app isn't starting Python correctly: please see [the "Startup" documentation](https://chaquo.com/chaquopy/doc/current/android.html#startup).
