### ISSUE TITLE
Error loading CNN

### ISSUE THREAD

**Issue by LuArtur** [chaquo/chaquopy#232]
I have a model of a network trained on my laptop and I am trying to perform the classification of electrocardiogram signals on my android.
in the laptop everything works ok but in the mobile this error occurs.

> This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

this is my error
![error AS](https://user-images.githubusercontent.com/60788857/75849561-20db6600-5db3-11ea-8aec-fbe19ba28817.png)

`

**Comment by LuArtur** [comment]
as seen in the image the model is loaded but when starting with the evaluation crash the application

**Comment by mhsmith** [comment]
Are you still using keras 2.2.4 as you said in #221? The line number 372 in the stack trace doesn't seem to correspond to the [source code of that version](https://github.com/keras-team/keras/blob/1931e2186843ad3ca2507a3b16cb09a7a3db5285/keras/utils/data_utils.py#L372).

**Comment by LuArtur** [comment]
the libraries I use are keras 2.2.4, tensorflow 1.10.1, numpy 1.14.2 scipy 1.1.0, sklearn 0.0 and scikit-learn 0.19.1

**Comment by LuArtur** [comment]
the libraries I use are keras 2.2.4, tensorflow 1.10.1, numpy 1.14.2 scipy 1.1.0, sklearn 0.0 and scikit-learn 0.19.1

**Comment by mhsmith** [comment]
Sorry, I was looking at the stack trace in the other issue.

There's a bug [here](https://github.com/keras-team/keras/blob/2.2.4/keras/utils/data_utils.py#L433): it's checking for OSError, but the actual exception is ImportError. Try working around it by adding the following lines before you use keras:

```
from keras.utils import data_utils
data_utils._SEQUENCE_COUNTER = 0
```

**Comment by LuArtur** [comment]
It already works, only on my laptop it takes less than a minute to complete and the android says it will take 9 minutes. I don't finish because the application was closed because I don't have the license.

I would like to obtain a free open source license, I am developing this non-profit application as part of my project to obtain the title of Biomedical Engineer

**Comment by mhsmith** [comment]
To apply for a license, please follow the instructions at https://chaquo.com/chaquopy/license/, then send me an email at the address on our website.
