### ISSUE TITLE
我问一下能不能把python编译器加上一些包比如requests等等封装到位的app上 然后可以执行.py文件或者单行代码

### ISSUE THREAD

**Issue by tghjnjvg** [chaquo/chaquopy#240]
我问一下能不能把python编译器加上一些包比如requests等等封装到位的app上 然后可以执行.py文件或者单行代码

**Comment by mhsmith** [comment]
Yes, you can do all of that. For adding Python packages, see the [documentation here](https://chaquo.com/chaquopy/doc/current/android.html#requirements). For calling Python code from Java, see the code in this project, especially the [Java API demo](https://github.com/chaquo/chaquopy/blob/master/app/src/main/java/com/chaquo/python/demo/JavaDemoActivity.java) and [unit tests](https://github.com/chaquo/chaquopy/tree/master/app/src/main/java/com/chaquo/java)
