### ISSUE TITLE
A problem occurred starting process 'command 'py''. Please set buildPython to your Python executable path.

### ISSUE THREAD

**Issue by companyofbala** [chaquo/chaquopy#241]
Hello, I am using the latest version of chaquo.
I saw in repository that sympy is not included, so I tried to pip install sympy, i get an error

A problem occurred starting process 'command 'py''. Please set buildPython to your Python executable path.

I use Macbook pro, So i could not find the exe file.

and also I tried to use the package that is in the repository(Numpy) already;
My app is simply getting crashed, Please explain to me how to import that and use it in my function.

and also suggest a way for my above question

**Comment by companyofbala** [comment]
![15841199618576579621318460809510](https://user-images.githubusercontent.com/61572479/76644408-ef198a80-657c-11ea-8e12-fbf67f3dadaf.jpg)
![1584119998054951400580842208641](https://user-images.githubusercontent.com/61572479/76644489-11aba380-657d-11ea-9a74-6e193da854e8.jpg)

**Comment by mhsmith** [comment]
If you use the `buildPython` setting more than once, then the last one will take effect. `py -3.7` is a Windows command, but you're on a Mac, so you should just remove it.

None of the packages in the repository are installed by default, so if you want to use NumPy then you'll have to add a pip install line for that as well.
