### ISSUE TITLE
Is there a connection issue currently? 20200315

### ISSUE THREAD

**Issue by mauriceluo69** [chaquo/chaquopy#242]
I cannot even open the homepage https://chaquo.com/chaquopy/

When it comes to the programming issues, the build output indicates that Android Studio cannot connect both https://chaquo.com/pypi-2.1 and https://chaquo.com/pypi-6.2, which trigger connection errors as below:

![image](https://user-images.githubusercontent.com/20211277/76698578-b0501580-66df-11ea-992b-06988f2f819e.png)

You can check this website: https://www.isitdownrightnow.com/chaquo.com.html
![image](https://user-images.githubusercontent.com/20211277/76698733-5c463080-66e1-11ea-85f0-3ca59590af3a.png)

**Comment by BruceZhang1993** [comment]
It seems chaquo.py is temporary down. Hope it will be back soon.

**Comment by mhsmith** [comment]
Thanks for the report, the site is now back up.
