### ISSUE TITLE
Read 

### ISSUE THREAD

**Issue by Aniskonig** [chaquo/chaquopy#245]
Dear Chaquopy,
I'm trying to read a CSV file using pandas:
```
import pandas as pd
data_frame = pd.read_csv("fileName.csv")

```
But i got this error :
`    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.medanis.pythonintegrationdemoapp/com.medanis.pythonintegrationdemoapp.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] File b'fileName.csv' does not exist: b'fileName.csv'
`
> **Note:** I tried the same code on the python terminal and it's working correctly (the .csv and .py are in the same directory)
Help me please.

**Comment by mhsmith** [comment]
Please see #144.
