### ISSUE TITLE
Material Design and Chaquopy

### ISSUE THREAD

**Issue by lschaupp** [chaquo/chaquopy#248]
Hey,

I am pretty new to the android studio/chaquopy and mostly coming from the c++ and python section.
Im trying to run this code (it does compile) but the touch message is not being displayed....
It is based on this tutorial.

https://www.simplifiedcoding.net/bottom-navigation-android-example/

What am I doing wrong?

    from android.os import Bundle
    from android.view import MenuItem
    from androidx.appcompat.app import AppCompatActivity
    from com.chaquo.python.hello import R
    from com.google.android.material.bottomnavigation import BottomNavigationView
    from java import jvoid, Override, static_proxy, jclass, jboolean

    class MainActivity(static_proxy(AppCompatActivity,  
    BottomNavigationView.OnNavigationItemSelectedListener)):

    @Override(jvoid, [Bundle])
    def onCreate(self, state):
        AppCompatActivity.onCreate(self, state)
        self.setContentView(R.layout.activity_test)
        bottomNavigation = BottomNavigationView(self,self.findViewById(R.menu.bottom_navigation_menu))
        bottomNavigation.setOnNavigationItemSelectedListener(self)

    @Override(jboolean, [MenuItem])
    def onNavigationItemSelected(self, item):
        if item.getItemId() == R.id.bottomNavigationAlarmMenuId:
            Toast.makeText(self.activity, R.string.demo_toast_text,
                           Toast.LENGTH_SHORT).show()
            return True
        elif item.getItemId() == R.id.bottomNavigationClockMenuId:
            return True
        return False

**Comment by mhsmith** [comment]
I don't know what you're trying to achieve with this:

```
BottomNavigationView(self,self.findViewById(R.menu.bottom_navigation_menu))
```

The example you linked simply has `findViewById(R.id.navigation)`. To translate that to Python, you should just need to add `self.` at the start.

There may be other problems, but that's the one that's most obvious to me.

**Comment by lschaupp** [comment]
Hey there. Thanks for taking your time to give some new users used to this.
So you mean like this:

        bottomNavigation = self.findViewById(R.menu.bottom_navigation_menu)

Although it compiles. It does crash on my phone. On the page I have provided it is about the following two lines:

        //getting bottom navigation view and attaching the listener
        BottomNavigationView navigation = findViewById(R.id.navigation);
        navigation.setOnNavigationItemSelectedListener(this);

**Comment by mhsmith** [comment]
When you call `findViewById`, you should be passing the view ID (`android:id` in the BottomNavigationView XML element), not the menu ID.
