### ISSUE TITLE
pip install in build.gradle file causing error

### ISSUE THREAD

**Issue by tstreefkerk98** [chaquo/chaquopy#250]
Hallo,

I'm very new to Android Studio and Chaquopy so please forgive me if this ends up being an extremely stupid question.

What I am trying to do is set up an application which takes a photo from the camera and process this in a python file. This processing needs to be done with opencv and I would like to be able to use some other libraries as well. I managed to get this set up except for the importing of the libraries. I read in your guide that I should do a pip-install in the build.gradle file like this: 

```
python {
            buildPython "C:/Users/Thoma/AppData/Local/Programs/Python/Python37-32/python-3.7.4.exe"
            pip {
                install "opencv-python"
            }
        }
```

but whenever I do this I get a RuntimeException. When I run the code without the pip install it seems to work but I gather that I need it to be able to use opencv. The error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.application, PID: 25720
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.application/com.example.application.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: /data/user/0/com.example.application/files/chaquopy/AssetFinder/requirements
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: /data/user/0/com.example.application/files/chaquopy/AssetFinder/requirements
        at <python>.java.android.importer.__init__(importer.py:278)
        at <python>.pkgutil.get_importer(pkgutil.py:419)
        at <python>.java.android.importer.initialize_importlib(importer.py:64)
        at <python>.java.android.importer.initialize(importer.py:35)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:128)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.example.application.MainActivity.onCreate(MainActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

the error mentions a FileNotFoundError and after some googling I still had no idea what this file is or how I could get it.

Any help would be very much appreciated.

Thomas

**Comment by mhsmith** [comment]
Which devices or emulators does the problem happen on? If you've only tried one, it would be useful to try another one to see if the issue is device-specific.

Can you post the full output from Build > Rebuild Project? Here's how to view it:
* In Android Studio 3.6 and newer, open the Build Window and click the 'Build' caption at the top left.
* In Android Studio 3.5 and older, open the Build Window, and use the 'Toggle view' button on the left to switch to text mode.

Can you upload the project to GitHub, or at least a simplified version which shows the problem?

**Comment by tstreefkerk98** [comment]
Thank you for your response.

I originally ran it on my Samsung smart phone, I just tried it on a Pixel 3 emulator and I am getting the same error.

It wasn't completely clear to how to get the output from the Build > Rebuild Project but I believe this is it:

Executing tasks: [clean, :app:assembleDebug] in project C:\Users\Thomas\Documents\Personal\AndroidStudio\Application


> Configure project :app
Warning: This version of Chaquopy has not been tested with Android Gradle plugin versions beyond 3.6.1. If you experience problems, please edit the version of com.android.tools.build:gradle in your top-level build.gradle file. See https://chaquo.com/chaquopy/doc/current/versions.html.

> Task :clean UP-TO-DATE
> Task :app:clean
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:generateDebugBuildConfig
> Task :app:extractPythonBuildPackages
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugPythonRequirements
> Task :app:mergeDebugPythonSources
> Task :app:generateDebugPythonProxies
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:javaPreCompileDebug
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugManifest
> Task :app:mergeDebugResources
> Task :app:processDebugResources
> Task :app:compileDebugJavaWithJavac
> Task :app:compileDebugSources
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders
> Task :app:generateDebugAssets
> Task :app:generateDebugPythonAppAssets
> Task :app:generateDebugPythonLicenseAssets
> Task :app:generateDebugPythonMiscAssets
> Task :app:generateDebugPythonRequirementsAssets
> Task :app:generateDebugPythonBuildAssets
> Task :app:mergeDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:dexBuilderDebug
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJavaResource
> Task :app:generateDebugPythonJniLibs
> Task :app:mergeDebugJniLibFolders
> Task :app:validateSigningDebug
> Task :app:mergeExtDexDebug
> Task :app:mergeDebugNativeLibs

> Task :app:stripDebugDebugSymbols
WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
Compatible side by side NDK version was not found. Default is 20.0.5594570.
Unable to strip the following libraries, packaging them as they are: libchaquopy_java.so, libchaquopy_java.so, libcrypto_chaquopy.so, libcrypto_chaquopy.so, libpython3.8.so, libpython3.8.so, libsqlite3_chaquopy.so, libsqlite3_chaquopy.so, libssl_chaquopy.so, libssl_chaquopy.so.

> Task :app:mergeDexDebug
> Task :app:packageDebug
> Task :app:assembleDebug

BUILD SUCCESSFUL in 9s
35 actionable tasks: 34 executed, 1 up-to-date

Here is a link to the project on github:
https://github.com/tstreefkerk98/Application/tree/develop

Thanks

**Comment by mhsmith** [comment]
Strange, there should be some output from pip below the line `app:generateDebugPythonRequirements`. I wonder if it's somehow failing but the failure isn't being detected.

Can you try it with the `buildPython` line disabled? And if that doesn't work, install the current version of Python from python.org and try it again, still with the `buildPython` line disabled.

**Comment by mhsmith** [comment]
It's also a little strange that your `buildPython` line says python-3.7.4.exe. On my Windows machine, the Python executables are all just called python.exe. Do you know where that copy of Python came from?

**Comment by tstreefkerk98** [comment]
I installed the current version of python and now it seems to work (not giving the error anymore), but now I am struggling to import opencv into the python file where I want to use it.

import cv2 (--> No module named cv2)

def test():
    return "testing testing"

**Comment by mhsmith** [comment]
Please update the GitHub project with your current code.

**Comment by tstreefkerk98** [comment]
Updated.

**Comment by mhsmith** [comment]
> import cv2 (--> No module named cv2)

Do you mean there's an error indicator in the IDE? As explained in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin), most of the Python IDE features are unavailable, so you can just ignore these indicators and go ahead with building and running your app.

**Comment by tstreefkerk98** [comment]
Yes that's what I meant, must have overlooked that part. Thank you very much for all your help!

**Comment by saecmca** [comment]
**build.gradle(:app)**
defaultConfig {
        applicationId "com.example.application"
        sourceSets {
            main {
                python {
                    srcDirs = ["src/main/python"]
                }
            }
        }
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        python {
            buildPython "C:/Users/manikandan.r/Downloads/python3.10.0.exe"
            pip {
                install "opencv-python"
            }
        }

**build.gradle(Application)**
repositories {
        google()
        jcenter()
	maven { url "https://chaquo.com/maven" }
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
	    classpath "com.chaquo.python:gradle:7.0.2"
}


**MainActivity**

if (!Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }
        Python pyInstance = Python.getInstance();
        PyObject pyModule = pyInstance.getModule("ProcessImage");
        PyObject pyAttribute = pyModule.callAttr("test");

        TextView tv = (TextView) findViewById(R.id.textView);
        tv.setText(pyAttribute.toString());


**ProcessImage.py**
import cv2

def test():
    return "testing testing"

**My error is**
Process 'command 'C:/Users/manikandan.r/Downloads/python3.10.0.exe'' finished with non-zero exit value 1638
To view full details in Android Studio:
* In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
* In version 3.5 and older, click the 'Toggle view' button to the left of this message.
* Then scroll up to see the full output.
**If I comment buildpython**
Process 'command 'py'' finished with non-zero exit value 1

To view full details in Android Studio:
* In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
* In version 3.5 and older, click the 'Toggle view' button to the left of this message.
* Then scroll up to see the full output.

**Comment by saecmca** [comment]
I have downloaded chaquopy-matplotlib-master project from github

These are the pip installed in build.gradle.
python {
          //  buildPython "C:/Users/manikandan.r/Downloads/python.exe"
            pip {
                install "numpy"
                install "pandas"
                install "scipy"
                install "matplotlib"
                install "opencv-python"
             }
        }
Added python package and ProcessImage.py class but this face different error

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.myapplication/com.chaquo.myapplication.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'ProcessImage'

**Comment by saecmca** [comment]
> Yes that's what I meant, must have overlooked that part. Thank you very much for all your help!

[https://github.com/tstreefkerk98/Application/tree/develop](url)

Now I tried same updated GitHub project face the above two errors

1. java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.application/com.example.application.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: /data/user/0/com.example.application/files/chaquopy/AssetFinder/requirements

2. import cv2 (--> No module named cv2)

 python {
            buildPython "C:/Users/manikandan.r/Downloads/python.exe" (versions 3.10 and 3.8.10)
            pip {
                install "opencv-python"
             }

        }

**Comment by mhsmith** [comment]
@saecmca: I've moved your comments to #594. Please don't post on #250 again.

**Comment by saecmca** [comment]
> @saecmca: I've moved your comments to #594. Please don't post on #250 again.

Tried above steps not running in chaquopy python in android studio.

**Comment by mhsmith** [comment]
Keep all further discussion in #594 please.

**Comment by mhsmith** [comment]
> It's also a little strange that your `buildPython` line says python-3.7.4.exe. On my Windows machine, the Python executables are all just called python.exe. 

My best guess is that this Python executable was returning success without running anything, so the requirements directory was never created. Chaquopy now has a check for this.
