### ISSUE TITLE
Failed to read picture file in VMsdcard

### ISSUE THREAD

**Issue by davidyang180** [chaquo/chaquopy#251]
hello!I use CV2's imread function to access the image file in VM sdcard, without error, but the image output is none,How should I solve this problem?
```
d = str(Environment.getExternalStorageDirectory()) 
d 
'/storage/emulated/0/img' 
def input(): 
    img = cv2.imread(r"\storage\emulated\0\img\ee.jpg") 
    print("the image:",img)
```

**Comment by mhsmith** [comment]
Android is based on Linux, so you must use forward slashes, not backslashes.

On recent version of Android there may also be restrictions on accessing getExternalStorageDirectory. This is not a Chaquopy-specific problem, and you can easily find discussion of it elsewhere.

**Comment by davidyang180** [comment]
Thanks!I'll find out how to use it
