### ISSUE TITLE
Can't compile 'pip/src' to .pyc

### ISSUE THREAD

**Issue by ArvinZJC** [chaquo/chaquopy#253]
With Chaquopy 7.0.2, I am using Python 3.7.6. I got the following warnings when I rebuilt my [project](https://github.com/ArvinZJC/UoL_Y3_Project/tree/master/XShielder) on an emulator. Output is similar when rebuilding on a real device.

> Executing tasks: [clean, :app:assembleX86Debug] in project D:\...\XShielder
> Configure project :app
> Task :clean UP-TO-DATE
> Task :app:clean
> Task :app:preBuild UP-TO-DATE
> Task :app:preX86DebugBuild UP-TO-DATE
> Task :app:compileX86DebugRenderscript NO-SOURCE
> Task :app:compileX86DebugAidl NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsX86Debug
> Task :app:dataBindingMergeGenClassesX86Debug
> Task :app:generateX86DebugResValues
> Task :app:generateX86DebugResources
> Task :app:generateX86DebugBuildConfig
> Task :app:extractPythonBuildPackages
> Task :app:generateX86DebugPythonRequirements
Chaquopy: Installing for x86
(installing packages...)
Warning: buildPython version is 3.7.6 with bytecode magic number 420d0d0a (expected number is 550d0d0a)
Warning: Can't compile 'pip' files to .pyc format. This will cause the app to start up slower and use more storage space. See https://chaquo.com/chaquopy/doc/current/android.html#android-bytecode.
Task :app:mergeX86DebugPythonSources
Warning: buildPython version is 3.7.6 with bytecode magic number 420d0d0a (expected number is 550d0d0a)
Warning: Can't compile 'src' files to .pyc format. This will cause the app to start up slower and use more storage space. See https://chaquo.com/chaquopy/doc/current/android.html#android-bytecode.
> Task :app:generateX86DebugPythonProxies
> Task :app:dataBindingGenBaseClassesX86Debug
> Task :app:javaPreCompileX86Debug
> Task :app:mainApkListPersistenceX86Debug
> Task :app:createX86DebugCompatibleScreenManifests
> Task :app:extractDeepLinksX86Debug
> Task :app:processX86DebugManifest
> Task :app:processX86DebugResources
> Task :app:compileX86DebugJavaWithJavac
> Task :app:compileX86DebugSources
> Task :app:checkX86DebugDuplicateClasses
> Task :app:mergeLibDexX86Debug
> Task :app:dexBuilderX86Debug
> Task :app:desugarX86DebugFileDependencies
> Task :app:mergeX86DebugShaders
> Task :app:compileX86DebugShaders
> Task :app:generateX86DebugAssets
> Task :app:generateX86DebugPythonAppAssets
> Task :app:generateX86DebugPythonLicenseAssets
> Task :app:generateX86DebugPythonMiscAssets
> Task :app:mergeProjectDexX86Debug
> Task :app:generateX86DebugPythonRequirementsAssets
> Task :app:generateX86DebugPythonBuildAssets
> Task :app:mergeX86DebugAssets
> Task :app:mergeExtDexX86Debug
> Task :app:processX86DebugJavaRes NO-SOURCE
> Task :app:generateX86DebugPythonJniLibs
> Task :app:mergeX86DebugJniLibFolders
> Task :app:validateSigningX86Debug
> Task :app:mergeX86DebugJavaResource
> Task :app:mergeX86DebugNativeLibs
> Task :app:stripX86DebugDebugSymbols
> Task :app:packageX86Debug
> Task :app:assembleX86Debug

In this way, I know it does not affect running the app, although the size of it will be larger. I want to know if there is a solution to fix it.

Besides, I tried to set:

`defaultConfig {
    python {
        pyc {
            src true
        }
    }
}`

But then an error occurred.

> (...Same as the previous)
> Task :app:mergeX86DebugPythonSources FAILED
buildPython version is 3.7.6 with bytecode magic number 420d0d0a (expected number is 550d0d0a)
FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':app:mergeX86DebugPythonSources'.
> Process 'command 'py'' finished with non-zero exit value 1

**Comment by mhsmith** [comment]
As the documentation link in the message says, you can fix the warning by using Python 3.8.

**Comment by ArvinZJC** [comment]
> As the documentation link in the message says, you can fix the warning by using Python 3.8.

Tensorflow does not support Python 3.8. So I may just keep using Python 3.7 since it does not affect running the app.
Could you please tell me why I got an error when I added `defaultConfig { python { pyc { src true } } }`, as I think `true` is default?

**Comment by mhsmith** [comment]
> Tensorflow does not support Python 3.8. So I may just keep using Python 3.7 since it does not affect running the app.

TensorFlow 2.1.0 actually is compatible with Python 3.8, and we have wheels available. They didn't release any official wheels for that version because they were waiting on a Python 3.8 build of grpcio (https://github.com/tensorflow/tensorflow/issues/33374). 

> Could you please tell me why I got an error when I added `defaultConfig { python { pyc { src true } } }`, as I think `true` is default?

The default is to attempt pyc compilation, but it isn't a fatal error if it fails. If you set it to `true` then you're saying it's a requirement for your app, so then it becomes a fatal error.
