### ISSUE TITLE
Support for Tensorflow 1.15.2?

### ISSUE THREAD

**Issue by ArvinZJC** [chaquo/chaquopy#254]
Some Tensorflow 1.X code is not really easy to migrate to Tensorflow 2.X, as the latest Tensorflow changes much. This is especially for the code depending on `tf.contrib`.

Could you please add the support for Tensorflow 1.15.2 which is the latest version for Tensorflow 1.X?

**Comment by mhsmith** [comment]
If you go back to Chaquopy version 6.3.0, then you'll have access to TensorFlow version 1.10.1. However, our builds of that version still don't contain most of `tf.contrib`.

TensorFlow builds are very time-consuming, so we're unlikely to release any more versions of TensorFlow 1.x unless someone offers a significant payment.

As I understand it, in TensorFlow 2.x most of `tf.contrib` has either been moved into the main `tf` namespace, or has been split into separately-installed packages. So there's probably still a migration path open for you.
