### ISSUE TITLE
package pillow error (The _imagingft C module is not installed)

### ISSUE THREAD

**Issue by xiaomei1995** [chaquo/chaquopy#255]
An error occurred when I used ImageFont.

**dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath "com.chaquo.python:gradle:6.3.0"
 }**

# python
from PIL import Image, ImageDraw, ImageFont
font_path = '/storage/emulated/0/simhei.ttf'
font_size=20
font = ImageFont.truetype(font_path, font_size)

# error is
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mycanera.zdl.com.mycamera, PID: 9011
    com.chaquo.python.PyException: ImportError: **The _imagingft C module is not installed**
        at <python>.PIL.ImageFont.__getattr__(ImageFont.py:40)
        at <python>.PIL.ImageFont.__init__(ImageFont.py:136)
        at <python>.PIL.ImageFont.truetype(ImageFont.py:275)

**Comment by mhsmith** [comment]
Thanks for the report, we'll try to release a build of Pillow with FreeType support within the next couple of days.

**Comment by mhsmith** [comment]
We've released a new build of Pillow which fixes the problem. However, to use it you'll have to upgrade to the current version of Chaquopy. Edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.

**Comment by xiaomei1995** [comment]
> We've released a new build of Pillow which fixes the problem. However, to use it you'll have to upgrade to the current version of Chaquopy. Edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.
> 
> Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.

OK! Thanks !!!
