### ISSUE TITLE
How to Implement Callback Function with Chaquopy?

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#257]
How to call python callback function from java?

**Comment by mhsmith** [comment]
If the callback is called through a Java interface, you can use the [dynamic proxy](https://chaquo.com/chaquopy/doc/current/python.html#dynamic-proxy) syntax.

If it requires you to extend a base class, you can use the [static proxy](https://chaquo.com/chaquopy/doc/current/android.html#static-proxy-generator) syntax.

Or the easiest way may be to just write a Java wrapper class which interfaces with the Python code.

**Comment by chaocharleswang** [comment]
Thanks @mhsmith  a  lot for your quick reply!
However, I'm still not clear on how to implement it on my case.

How about the following simple example:

```
def my_hook(d):
    if d['status'] == 'downloading':
        print(d['_percent_str']) # print downloading progress
        
        
def download(url):
    ydl_opts = {
            'format': 'best',
            'progress_hooks': [my_hook] }
        
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
```

How to get `my_hook` when calling function `download` in java?

**Comment by mhsmith** [comment]
I'm not sure I understand your example, as `download` doesn't take any hook argument. But if it did, you could call it like this:

```
PyObject mod = py.getModule("your_module_name");
mod.callAttr("download", "http://whatever", mod.get("my_hook"));
```

**Comment by chaocharleswang** [comment]
Thanks @mhsmith
