### ISSUE TITLE
Is it possible to utilize the GPU using tensorflow via chaquopy?

### ISSUE THREAD

**Issue by PhantomSasuke** [chaquo/chaquopy#258]
I made a keras model using Conv2D that i wanted to deploy onto my android app. However, while executing this line: `y_pred = model.predict(inputarray,verbose=1)`, it produced this error:

>  Caused by: com.chaquo.python.PyException: UnimplementedError:  The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW
>     	 [[node sequential_10/conv2d_52/Conv2D (defined at /app/lines.py:108) ]] [Op:__inference_distributed_function_1677]

I assume this means I need to to utilize the GPU to use the model. Is this possible?

**Comment by PhantomSasuke** [comment]
Nvm I solved it by making the input of my Conv2D NHWC

**Comment by mhsmith** [comment]
Glad to hear it. To answer your original question, the current Chaquopy TensorFlow builds do not have GPU support, but we may add this in the future.
