### ISSUE TITLE
Not follow instruction to change Text of View!

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy#26]
Below code is modified from "chaquopy-hello-master" code, only add time delay and 3 Text changed of View but before the display indicated "Hello Chaquopy" it's only white blank, the 'Delay 1" and 'Delay 2" never happen.
I need this for debugging my the other code. Thanks.

`from android.os import Bundle
from android.support.v7.app import AppCompatActivity
from com.chaquo.python.hello import R
from java import jvoid, Override, static_proxy
from time import sleep

class MainActivity(static_proxy(AppCompatActivity)):

    @Override(jvoid, [Bundle])
    def onCreate(self, state):
        AppCompatActivity.onCreate(self, state)
        self.setContentView(R.layout.activity_main)
        sleep(2)
        self.findViewById(R.id.tvx).setText("Delay 1")
        sleep(2)
        self.findViewById(R.id.tvx).setText("Delay 2")
        sleep(2)
        self.findViewById(R.id.tvx).setText("Hello Chaquopy")`

**Comment by mhsmith** [comment]
https://stackoverflow.com/questions/29198262/android-sleep-without-blocking-ui

This is a common Android issue which has nothing to do with Chaquopy. Please search more carefully before asking for help here.
