### ISSUE TITLE
Input and Output regarding python execution into java

### ISSUE THREAD

**Issue by parshv17898** [chaquo/chaquopy#262]
How to get input into and output out of python execution into java using chaquopy ?

**Comment by mhsmith** [comment]
If you mean the standard input and output streams, see https://chaquo.com/chaquopy/doc/current/android.html#sys.

If you mean passing passing and returning values, see https://chaquo.com/chaquopy/doc/current/java.html.

**Comment by vidheyoza** [comment]
I have the same question as @parshv17898 ..

My target is to run a python file from Android, and get its outputs into Java so that I can display text on the app. I have designed my app in Java and Kotlin, but I have my coding logic in Python so I need to run that code and get output from there. 

I looked at the documentation but it either has all Java implementation or all Python documentation, and I can't figure out how to call a python function from java or java function from python.

**Comment by mhsmith** [comment]
Put your Python source code in src/main/python as described [here](https://chaquo.com/chaquopy/doc/current/android.html#source-code), and then access it from Java as described [here](https://chaquo.com/chaquopy/doc/current/java.html). There are many examples of this in the [demo apps](https://chaquo.com/chaquopy/doc/current/index.html#introduction).

**Comment by vidheyoza** [comment]
Okay so I got the code working, thank for the help!

I'm now stuck with another problem: my Python scripts use pre-saved data files from where I have to fetch data and process it. I'm a novice in Android, so I know that such files usually go in the assets directory. I have the files there, but the code throws an error of 'No such file or directory'. 

Do I store the files in a different directory? Or do I change the way I write my paths in the code? I'm following the chaquopy-console example app at the moment.

**Comment by mhsmith** [comment]
Please see #144.

**Comment by vidheyoza** [comment]
If I keep a single file inside the python directory, then it packages it and shows up in the device files, but this is not the case if I keep multiple nested files inside a folder structure.
Are you using something to add those files inside the app package?

![image](https://user-images.githubusercontent.com/45912675/79504038-ce4ac600-804f-11ea-80e1-496ca2f1a243.png)

Cannot access the Pushup_new_Good_1.npy file inside the folder files, but I can access the file Pushup_new_Good_1.npy  present in the root dir.

**Comment by mhsmith** [comment]
As it says in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#data-files):

> Data files in the root directory will be extracted from the APK the first time the app is started, while files within a top-level package will be extracted the first time that package is imported.

So if your files are in `src/main/python/files`, try adding `import files` to your code. You may need to add an __init__.py file to the directory to make this work.

**Comment by vidheyoza** [comment]
I understand what you are saying, but the directory does not contain any .py files at all, it only has data files. Should I still make an __init__.py file for that directory? If so, what do I write in the file? And where do I import this "package" that has no code?

**Comment by mhsmith** [comment]
> the directory does not contain any .py files at all, it only has data files. Should I still make an __init__.py file for that directory? If so, what do I write in the file?

It might not be necessary: just try it and you'll find out. If you do need the file, you can leave it empty.

> And where do I import this "package" that has no code?

Anywhere as long as it happens before you access the files.

**Comment by vidheyoza** [comment]
> It might not be necessary: just try it and you'll find out. If you do need the file, you can leave it empty.

Tried without as well as with the `__init__.py` file but getting this error: 

`ModuleNotFoundError: No module named 'npy_files_final'`

**Comment by mhsmith** [comment]
If the structure is as shown on the left of your image, then you don't need to import `npy_files_final`, only the top-level directory `files`

**Comment by vidheyoza** [comment]
Ok sorry missed that. This solved the problem! Thank you!
