### ISSUE TITLE
Reading CHECKPOINT

### ISSUE THREAD

**Issue by ArvinZJC** [chaquo/chaquopy#263]
I saw issue #144 . However, I still get a NotFoundError(/data/user/0/com.arvinzjc.xshielder/files/chaquopy/AssetFinder/app/cnn_trainer_saver; No such file or directory) in my project.

The relevant files are:
src/main/python/code.py
src/main/python/cnn_trainer_saver/cnn_trainer.ckpt

The relevant code is:
`tf.train.Saver().restore(session, os.path.join(os.path.dirname(__file__), 'cnn_trainer_saver', 'cnn_trainer.ckpt'))`

**Comment by mhsmith** [comment]
Are you sure you're using this API correctly? According to the [Saver documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Saver), the path parameter is not a complete filename but a "path prefix of the newly created checkpoint files".

**Comment by ArvinZJC** [comment]
More specifically, the relevant files are:
src/main/python/code.py
src/main/python/cnn_trainer_saver/cnn_trainer.ckpt.meta
src/main/python/cnn_trainer_saver/cnn_trainer.ckpt.index
src/main/python/cnn_trainer_saver/cnn_trainer.ckpt..data-00000-of-00001
src/main/python/cnn_trainer_saver/checkpoint

The exception occurred when I put these 4 checkpoint files in the folder cnn_trainer_saver. If I move them to the same directory of the PY file (i.e. src/main/python/(these checkpoint files)), then everything looks good. My question is why this happens. Thanks!

**Comment by mhsmith** [comment]
That's a question about TensorFlow rather than Chaquopy, so you should ask on the TensorFlow GitHub page, or on StackOverflow.
