### ISSUE TITLE
python configuration block to the top level of build.gradle, please.

### ISSUE THREAD

**Issue by TheForgetTime** [chaquo/chaquopy#264]
Is it possible to consider moving the python configuration block from defaultconfig to the top level of build.gradle which is at the same level as the android block.
The python configuration block should be independent of the android configuration.
It should expand the android block rather than modify it.

**Comment by mhsmith** [comment]
The python block is within defaultConfig because it works with the [product flavor](https://developer.android.com/studio/build/build-variants#product-flavors) system.

Why do you want it to be at the top level?

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and give the requested information.
