### ISSUE TITLE
How to use with a Library module

### ISSUE THREAD

**Issue by aditmodhvadia** [chaquo/chaquopy#266]
I am interested to use Chaquopy in my LIbrary for my Main application.
Do you support this? I want to create a wrapper around the Chaquopy so that my main application just calls the methods in my Library, and my library will call and run Chaquopy and return the result from the library. basically create a middleware library to centralize calling the python code for my app.

Thank you

**Comment by aditmodhvadia** [comment]
Basically I cannot write apply plugin: 'com.chaquo.python' for my Library module as it is giving me applicationVariants error. And due to this, I cannot import/use your SDK methods and classes.

**Comment by mhsmith** [comment]
Chaquopy currently only supports being used directly in an app, not in a library module, but we'll probably fix this in the next version

Please subscribe to #94 for updates.
