### ISSUE TITLE
Process 'command 'py'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by helloworld3567** [chaquo/chaquopy#269]
Hello, I want to use the following packages on python using Chaquopy onAndroid Studio:

from PIL import Image
import numpy
import cv2
from operator import xor
import pywt
import soundfile as sf
from scipy.fftpack import dct, idct

but I have an error like in the title "Process 'command 'py'' finished with non-zero exit value 1" and the code does not execute, can you confirm me please if these packages are available knowing that I use android studio 3.6.2 and chaquopy 7.0.2 and python 3.7

**Comment by mhsmith** [comment]
Please post the full build log, which you can see by opening the Build window and clicking the 'Build' caption at the top left.

**Comment by helloworld3567** [comment]
<img width="927" alt="1" src="https://user-images.githubusercontent.com/58222852/79974149-4ff38700-8488-11ea-9da4-b24d0d9dbbc6.png">

**Comment by helloworld3567** [comment]
<img width="501" alt="2" src="https://user-images.githubusercontent.com/58222852/79974470-ea53ca80-8488-11ea-9b01-8b9b22a6a9d8.png">
<img width="501" alt="3" src="https://user-images.githubusercontent.com/58222852/79974472-ec1d8e00-8488-11ea-9a67-5a0e24c6732b.png">

**Comment by mhsmith** [comment]
PIL is obsolete: you should install "pillow" instead. The Python code can remain unchanged.

Many pip installation problems aren't Chaquopy-specific, so please try searching for the error message before posting here.
