### ISSUE TITLE
Help to review and reply to the email

### ISSUE THREAD

**Issue by tongjingyu** [chaquo/chaquopy#270]
Help to review and reply to the email

**Comment by mhsmith** [comment]
I've just replied to your email. Sorry for the delay.

**Comment by tongjingyu** [comment]
The code used by our two projects is mostly the same, but the python code is different, that is, the two directions with completely different functions need to be listed in the application store.

发件人: Malcolm Smith <notifications@github.com>
发送时间: 2020年4月23日 12:08
收件人: chaquo/chaquopy <chaquopy@noreply.github.com>
抄送: tongjingyu <sobt@live.cn>; Author <author@noreply.github.com>
主题: Re: [chaquo/chaquopy] Help to review and reply to the email (#270)


I've just replied to your email. Sorry for the delay.

―
