### ISSUE TITLE
application caused this error at runtime build

### ISSUE THREAD

**Issue by Phineas019** [chaquo/chaquopy#272]
FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:generateDebugPythonMiscAssets'. > Could not resolve all files for configuration ':pythonDebugTargetStdlib'. > Could not find com.chaquo.python:target:3.8.1-6. Searched in the following locations: - https://dl.google.com/dl/android/maven2/com/chaquo/python/target/3.8.1-6/target-3.8.1-6.pom - https://jcenter.bintray.com/com/chaquo/python/target/3.8.1-6/target-3.8.1-6.pom - https://chaquo.com/maven/com/chaquo/python/target/3.8.1-6/target-3.8.1-6.pom Required by: project : * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

****--After ran with --stacktrace option--*****

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':pythonDebugTargetStdlib'.

org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.chaquo.python:target:3.8.1-6.

**Comment by mhsmith** [comment]
Could there have been some problem with your internet connection? Does the problem happen again when you run Build > Rebuild Project?

What's the version of Gradle in gradle/wrapper/gradle-wrapper.properties?

If you still can't work it out, can you upload the project to GitHub, or at least a simplified example which shows the same problem?

**Comment by Phineas019** [comment]
No i tried Chaquopy-Hello-world sample i got the same error, When i tried to manually access the URL i got 
![image](https://user-images.githubusercontent.com/41485361/80203863-7a3e7380-8645-11ea-8e0f-4833bc496842.png)
![image](https://user-images.githubusercontent.com/41485361/80203907-8b878000-8645-11ea-959d-ea06d708783e.png)
You can find the difference in URL's i don't know what to do. any help to fix this will be appriciated.

Thanks.

**Comment by mhsmith** [comment]
As you can see, the Gradle version number is different from the [one in this project](https://github.com/chaquo/chaquopy/blob/6a8842abdb1bcf622bb176edb75044820cf5891c/gradle/wrapper/gradle-wrapper.properties). I guess you must be using a pre-release version of Android Studio which offered to update the version when you opened the project. But Chaquopy isn't tested with pre-release Android Studio versions, so you shouldn't accept that offer.

To fix this:

* Reduce the Gradle version number to 5.6.4.
* Check your top-level build.gradle file for `com.android.tools.build:gradle`. The current stable version is 3.6.3, so anything higher than that is not supported by the current Chaquopy version.

**Comment by Phineas019** [comment]
Thank you, That was the issue ! after downgraded Gradle version everything is fine
