### ISSUE TITLE
Is there a way to read csv file with pd.read_csv() function?

### ISSUE THREAD

**Issue by rpt5366** [chaquo/chaquopy#274]
Hello, I am trying to run python codes on android for data preprocessing and classification.
The problem is, I want to use pd.read_csv("filename.csv") but I do not know how. 
I put the csv file(=test.csv) in the same folder where the python code is(main/python/hello.py), and when I write [ **df=pd.read_csv("test.csv")** ] in hello.py, it does not work.
Is there a way to do this?  Would you mind showing me the code?
 Thank you!

**Comment by mhsmith** [comment]
See #144.
