### ISSUE TITLE
不支持imutils包 

### ISSUE THREAD

**Issue by JetCSY** [chaquo/chaquopy#277]

**Comment by mhsmith** [comment]
Imutils is a pure-Python package, so you can already install it by following [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements). Depending on what you're doing with it, you may also need to install NumPy, SciPy, Matplotlib, or OpenCV.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen this issue and give details.
