### ISSUE TITLE
Image is returning None everytime using the opencv imread function.

### ISSUE THREAD

**Issue by raghavddps2** [chaquo/chaquopy#278]
Here is the python code.
`def predict_function():
    global_features = []
    fixed_size = (224,224)
    image = cv2.imread("app/src/main/python/ims.png")
`
1. I tried both absolute and relative paths.
2. Image size is not an issue, as it works in python shell.

Please help.

**Comment by mhsmith** [comment]
You should generate absolute paths at runtime using the technique described in #144.

**Comment by raghavddps2** [comment]
Hi,

Thanks for the quick reply. I tried even that, But seems there is some problem with opencv imread function.
**E/cv::error(): OpenCV(4.1.2) Error: Assertion failed (!ssize.empty()) in resize, file /home/smith/git/chaquo/python/server/pypi/packages/opencv-python/build/4.1.2.30/cp38-cp38-android_21_arm64_v8a/src/opencv/modules/imgproc/src/resize.cpp, line 3720**

I am getting this error every time. Stuck on it for over 2 days now. Please help :)
Any references to projects which use sklearn based pickled ML models, would be helpful.

**Comment by mhsmith** [comment]
Does the app crash immediately, or does it continue with `cv2.imread` returning None?

Please make sure you're generating the filename correctly as described in #144, and post the code if you still can't work it out.

**Comment by mhsmith** [comment]
> Any references to projects which use sklearn based pickled ML models, would be helpful.

Try searching for "sklearn pickle" in this issue tracker, and you'll find someone else with exactly the same question.

**Comment by raghavddps2** [comment]
`def predict_function(var)
    global_features = []
    fixed_size = (224,224)
    image = cv2.imread("1.png")

    image = cv2.resize(image,fixed_size)`

The application crashes while calling the resize function. When i tried printing image to the console, it is None only. resize, is giving the previous error, because it finds it as None.

**Comment by raghavddps2** [comment]
> > Any references to projects which use sklearn based pickled ML models, would be helpful.
> 
> Try searching for "sklearn pickle" in this issue tracker, and you'll find someone else with exactly the same question.

Sure, I will try that

**Comment by raghavddps2** [comment]
> ```
> def predict_function(var)
>     global_features = []
>     fixed_size = (224,224)
>     image = cv2.imread("app/src/main/python/1.png")
>     image = cv2.resize(image,fixed_size)
> ```
> 
> The application crashes while calling the resize function. When i tried printing image to the console, it is None only. resize, is giving the previous error, because it finds it as None.

Alternatively, If you can provide me some way to pass an image array from java to python, then, I can have a work around to solve my problem.

And thank you so much for the quick replies. Great work with chaquopy! Kudos <3

**Comment by mhsmith** [comment]
Like I said, you need to construct the filename using the method described in #144.

**Comment by raghavddps2** [comment]
Tried, It gave this error.
Caused by: com.chaquo.python.PyException: SystemError: <built-in function imread> returned NULL without setting an error
```

def predict_function():
    global_features = []
    fixed_size = (224,224)
    f = open(join(dirname(__file__), 'ims.png'))
    image = cv2.imread(f)
```

**Comment by mhsmith** [comment]
I think `imread` takes a filename, not a file object. Try removing the call to `open`.

Unfortunately OpenCV's exception messages are often unhelpful.

**Comment by raghavddps2** [comment]
> I think `imread` takes a filename, not a file object. Try removing the call to `open`.
> 
> Unfortunately OpenCV's exception messages are often unhelpful.

Oh yes, Sorry, I Kept bugging you for such a silly mistake. I was irritated that didn't notice it. It worked! Thanks a ton!!
Again, You are doing a great job!!

**Comment by PARKER-X** [comment]
how to resolve this issue plz help me ;-  
 image = cv2.imread(image_path)
    print(image_path)  -->./image/download%20(7)_qn1i5tm.jpg

    print(image)   -->None

**Comment by mhsmith** [comment]
To load files from your source code directory, follow the instructions [here](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

**Comment by nopa607** [comment]
do not use any path name except english
after del some chinese in path name, it works
