### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#279]
Where should i store external files which are required in the pyhton scripts in my android app? I guess my files should be somewhere in between: /data/user/0/com.example.myapplication/files/chaquopy/AssetFinder/app/
But how to access this directory in emulator? How to view this dir in Android studio?

**Comment by mhsmith** [comment]
You can store the files in your source code directory: see #144. 

You should be able to view the directory on the device using the Device File Explorer.
