### ISSUE TITLE
Simple Example Python API code..

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy#28]
It's difficult to me to understand how to implement python code with Andriod's UI by reading your demo code.  In the code,  use static_proxy and dynamic_proxy which I don't know how to decide when and how. 

Would you please help to have a python code for simple example to replace below Java code? 
I may be able to understand more how to use Chaquopy with Android from several simple examples with some description. That's will be great for me.

```
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity
            implements View.OnClickListener {
    int counter =0;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       ((TextView) findViewById(R.id.tvx)).setText("Test 1");
       ((Button) findViewById(R.id.button)).setOnClickListener(this);

    }

    @Override
    public void onClick(View v) {
        ((TextView) findViewById(R.id.tvx)).setText(String.valueOf(++counter));
    }
}```

**Comment by mhsmith** [comment]
I know this area may be hard to understand if you're unfamiliar with Java. Unfortunately you will need some basic understanding of Java in order to use the Android APIs.

The summary is that `static_proxy` can always be used, but is slightly less convenient, because:
* It requires the containing module to be listed in a `staticProxy` declaration in `build.gradle`.
* It imposes some restrictions on the structure of the code, as mentioned in the documentation.

`dynamic_proxy` is therefore preferable, but is limited to implementing Java interfaces, not extending concrete classes.

In this example, your class has both an `implements` and an `extends` declaration, and would therefore have to use `static_proxy`. The decorator would look like this:
```
@static_proxy(AppCompatActivity, View.OnClickListener)
```
Aside from that, the code structure with Chaquopy can be the same as in Java.

**Comment by mhsmith** [comment]
But remember that `++counter` [will not work in Python](https://stackoverflow.com/questions/1485841/behaviour-of-increment-and-decrement-operators-in-python)!

**Comment by hushanhsiang** [comment]
It's working as below python code.
`count =0

class MainActivity(static_proxy(AppCompatActivity, View.OnClickListener)):
    @Override(jvoid, [Bundle])
    def onCreate(self, state):
        AppCompatActivity.onCreate(self, state)
        self.setContentView(R.layout.activity_main)
        self.findViewById(R.id.tvx).setText("Chaquopy")
        self.findViewById(R.id.button).setOnClickListener(self)

    @Override(jvoid, [View])
    def onClick(self, state):
        global count
        count +=1
        self.findViewById(R.id.tvx).setText(str(count))
`
I don't know why there's a "state" in   "def onClick(self, state)" and a [View] in "@Override(jvoid, [View]".
May I have your opinion?


I actually have 2 Java books but no one introduced "static_proxy" or "dynamic_proxy". To understand them, it's not only familiar but needs Java profession someone like you.
Above is a friendly example to learn how to covert Android Java code to Chaquopy code. If there are more and more of this kind of examples, I will be familiar with Chaquopy to use the Android resource to develop Python code in Android Studio. Thank you.

**Comment by mhsmith** [comment]
Please surround code blocks with ```` ``` ````, as I've edited, otherwise the indentation is lost and it becomes impossible to read.

> I don't know why there need a "state" in "def onClick(self, state)" and a [View] in "@override(jvoid, [View]". May I have your opinion?

You need it because that's the parameter defined by the [`OnClickListener`](https://developer.android.com/reference/android/view/View.OnClickListener.html) interface. I don't know why you've called it "state". 

In other words, these lines in Java:
```
    @Override
    public void onClick(View v) {
```

Are equivalent to these lines in Python:
```
    @Override(jvoid, [View])
    def onClick(self, v):
```

**Comment by hushanhsiang** [comment]
Thank you for the description.
