### ISSUE TITLE
INSTALL_PARSE_FAILED_NOT_APK

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#282]
After importing tensorflow,
```
defaultConfig{
python{
pip{
                install "tensorflow"
}
}
}
```
and 
`import tensorflow as tf
`
when i run my application it fails:
> 05/12 18:33:37: Launching 'app' on Pixel 2 API 29.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_NOT_APK
Installation failed due to: 'null'
Retry

**Comment by mhsmith** [comment]
This is unlikely to have anything to do with Chaquopy. Does it only happen when you add TensorFlow to your build?

**Comment by sayan-sen** [comment]
yes. i have checked by commenting the pip install in build.gradle 
This error doesnt occur then and simply asks for "no module named tensorflow"
The moment i run it with the pip install it fails during install phase

**Comment by mhsmith** [comment]
Are you using the current stable version of Android Studio (3.6.3)? It's also worth upgrading the Gradle plugin to the same version (com.android.tools.build:gradle in your top-level build.gradle file).

Does the problem happen on all devices or only one?

Does it keep happening after you uninstall and reinstall the app?

**Comment by sayan-sen** [comment]
Andorid studio ver: 3.6.3
dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath "com.chaquo.python:gradle:7.0.2"
    }
Device: am using emulator for Pixel 2 (just like that. no specific reason) shall i use some high end device in the emulator?
Havent check uninstalling the app.

**Comment by mhsmith** [comment]
The choice of emulated device doesn't usually make any difference. Using a different Android version is more likely to help. 

But try just uninstalling the app first. Also try running Build > Clean Project in Android Studio.

**Comment by sayan-sen** [comment]
yeah i guess cleaning the project and rebuilding it along with uninstall>reinstall app really worked. Now its going past import tensorflow. Thanks!
