### ISSUE TITLE
Where are my files saved generated in runtime?

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#284]
In my pyhton scripts am eventually saving many files such as .csv, jpg etc.
`numpy.savetxt(join(dirname(__file__), "foo.csv"), point_list, delimiter=",")`

When i run the app in USB debugging mode with a connected mobile phone, where do these files get saved? which directory? how can i find them?

**Comment by mhsmith** [comment]
You shouldn't save files into the same directory as your source code, as these directories may be deleted when you upgrade the app. 

Instead, save them to the directory given by `os.environ["HOME"]`, which is the same as `getFilesDir()` in Java. You can create whatever subdirectories you want to keep the files organized.

To find the path of this directory on any particular device, just print it to standard output, which you can view in Android Studio using the [Logcat](https://developer.android.com/studio/debug/am-logcat.html) window. Then once you know the path, you can view it using the [Device File Explorer](https://developer.android.com/studio/debug/device-file-explorer)
