### ISSUE TITLE
Is Tensorflow==1.14 for Chaquopy available?

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#285]
I need to install "tensorflow==1.14" in my android app.
Chaquopy build fails:
`Collecting tensorflow==1.14
  Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.1.0)
No matching distribution found for tensorflow==1.14
Chaquopy: Exit status 1`
I need that version only. Can it be done in chaquopy? or does chaquopy have only tensorflow=2.1.0?

**Comment by mhsmith** [comment]
As I said in #37, the currently available versions are:

* TensorFlow 1.10.1 for Chaquopy version 6.3.0. 
* TensorFlow 2.1.0 for Chaquopy version 7 and later.

If neither of these versions are suitable, please explain why.
