### ISSUE TITLE
I got nothing return from python scripts when I use python to read an image.

### ISSUE THREAD

**Issue by chaotianjiao** [chaquo/chaquopy#286]
Hello~First thanks to your project, It's really a great repo.But I got something run when I use this:
This is **one.py** like this:

`
import cv2

def read_img(path):
    img = cv2.imread(path)
    return img
`
and this is **MainActivity.java**:

`
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        initPython();
        PyObject img = callPythonCode();
        Log.d("pylist", String.valueOf(img));
    }
   
    private PyObject callPythonCode() {
        Python py = Python.getInstance();
   
        PyObject img = py.getModule("one").callAttr("read_img","D:\\AndroidStudioProjects\\CallPython\\app\\src\\main\\python\\Penguins.jpg");

        return img;
    }
    // 初始化Python环境
    private void initPython() {
        if (!Python.isStarted()){
            Python.start(new AndroidPlatform(this));
        }
    }
}
`

When I open the logcat,I got nothing:
![Snipaste_2020-05-18_15-51-58](https://user-images.githubusercontent.com/42534375/82187875-a042f500-991f-11ea-85ae-795daf16469b.png)

and this is my gradle file:
![image](https://user-images.githubusercontent.com/42534375/82187997-c9638580-991f-11ea-97c5-639811648bbf.png)

What's wrong with my code?Thank you ~

**Comment by chaotianjiao** [comment]
I found #144 ,Thank you!~

**Comment by UtsaChattopadhyay** [comment]
@chaotianjiao Can u send me the code snippet on how you are reading the image?
Even following that issue im getting none.
Thanks

**Comment by mhsmith** [comment]
@UtsaChattopadhyay: See the [documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-data) on how to read data files in your source code directory. If it doesn't work, check for errors in the [Logcat](https://stackoverflow.com/a/23353174), and if you still need help, post the errors along with the relevant sections of your code.

**Comment by UtsaChattopadhyay** [comment]
Yeah it works. No problem
