### ISSUE TITLE
Is something lost when I transfer python bytes to java bytes?

### ISSUE THREAD

**Issue by chaotianjiao** [chaquo/chaquopy#288]
I have one.py like this

```
import cv2
from os.path import dirname, join

def read_img():
    f = join(dirname(__file__),"Penguins.jpg")
    img = cv2.imread(f)
    img =cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    return img.tobytes()
```

and in MainActivity.java I use this:

```
PyObject img = callPythonCode();
byte[] img_byte = img.toJava(byte[].class);
```

but when I try to recover Penguins.jpg to an ImageView,use this:

```
Bitmap bmp = BitmapFactory.decodeByteArray(img_byte, 0, img_byte.length);
ImageView img_show = findViewById(R.id.img_show);
img_show.setImageBitmap(bmp);
```

But Logcat shows that bmp is null, I got nothing in my screen.
What should I do ?

**Comment by mhsmith** [comment]
I think `BitmapFactory.decodeByteArray` expects to receive the bytes of an image file, not raw bitmap data. Try generating an image file in memory using the [method shown here](https://jdhao.github.io/2019/07/06/python_opencv_pil_image_to_bytes/#convert-image-to-bytes), though it's probably better to use PNG format rather than JPG.

**Comment by chaotianjiao** [comment]
It works!Thanks a lot!

**Comment by whf12345-hust** [comment]
> I have one.py like this
> 
> ```
> import cv2
> from os.path import dirname, join
> 
> def read_img():
>     f = join(dirname(__file__),"Penguins.jpg")
>     img = cv2.imread(f)
>     img =cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
>     return img.tobytes()
> ```
> 
> and in MainActivity.java I use this:
> 
> ```
> PyObject img = callPythonCode();
> byte[] img_byte = img.toJava(byte[].class);
> ```
> 
> but when I try to recover Penguins.jpg to an ImageView,use this:
> 
> ```
> Bitmap bmp = BitmapFactory.decodeByteArray(img_byte, 0, img_byte.length);
> ImageView img_show = findViewById(R.id.img_show);
> img_show.setImageBitmap(bmp);
> ```
> 
> But Logcat shows that bmp is null, I got nothing in my screen.
> What should I do ?

兄弟，我也有一样的问题，源代码能发上来看看吗？
