### ISSUE TITLE
Cannot install magenta

### ISSUE THREAD

**Issue by ak0005** [chaquo/chaquopy#290]
**Gradle:-**   
       ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        python {
            pip {
                install "numpy"
                install "magenta==1.3.1"
                install "tensorflow"
            }
        }

**Error:-**
copying apache_beam/runners/worker/statesampler_fast.pxd -> build/lib.linux-x86_64-3.7/apache_beam/runners/worker
  creating build/lib.linux-x86_64-3.7/apache_beam/testing/data
  copying apache_beam/testing/data/trigger_transcripts.yaml -> build/lib.linux-x86_64-3.7/apache_beam/testing/data
  copying apache_beam/portability/api/standard_coders.yaml -> build/lib.linux-x86_64-3.7/apache_beam/portability/api
  running build_ext
  building 'apache_beam.coders.stream' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
ERROR: Failed to install apache-beam[gcp]<2.19.0,>=2.14.0 from https://files.pythonhosted.org/packages/04/8f/01c7acfedbc74a6fbe0527225ce655b4584f5e3d4b2007e8fb92352014d8/apache-beam-2.18.0.zip (from magenta==1.3.1).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

**Comment by mhsmith** [comment]
Thanks for the report, I'll take a look at it.

**Comment by mhsmith** [comment]
Magenta currently requires TensorFlow 1, which isn't compatible with Python 3.8, so you won't be able to use it with the current version of Chaquopy.

Unfortunately it looks like it can't be used with the previous (Python 3.6) version of Chaquopy either, because even older versions of Magenta (as far back as 2017) required librosa, which requires numba, which we never released for Python 3.6.

So we won't be able to support Magenta until Magenta supports TensorFlow 2. If you'd like that to happen, please add a thumbs up at https://github.com/tensorflow/magenta/issues/1594, or fix it if you can.

**Comment by mhsmith** [comment]
The current version of Magenta (2.x) now supports TensorFlow 2. Unfortunately, Magenta also depends on apache-beam, which doesn't support Python 3.8 yet, though [it looks like they're actively working on it](https://issues.apache.org/jira/browse/BEAM-8494).

**Comment by ak0005** [comment]
I think this error (the current one)  is not related to apache-beam
here is the error

Collecting tensorflow-addons (from tensor2tensor->magenta)

  Could not find a version that satisfies the requirement tensorflow-addons (from tensor2tensor->magenta) (from versions: )
No matching distribution found for tensorflow-addons (from tensor2tensor->magenta)
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

**Comment by mhsmith** [comment]
Yes, there are a few other native dependencies we'd have to build, but apache-beam is the biggest obstacle at the moment.

**Comment by sarthaksharma058439** [comment]
Hey i found this video it helps me alot in install and import package in android studio with chaquopy , hopefully this will helps you 

https://youtu.be/BDmB3EFy0Qg

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be adding it in the foreseeable future. If anyone else is interested, please click the thumbs-up button above and post a comment, and I'll reopen the issue.
