### ISSUE TITLE
Use of matplotlib

### ISSUE THREAD

**Issue by coffeetimegit** [chaquo/chaquopy#294]
This might not be Chaquopy's issue but I have a python program that uses matplotlib's plt.show method to plot a graph. Problem is, my program does not display graphs. What is an easy approach to displaying matplotlib's graphs on say layout xml file?

**Comment by mhsmith** [comment]
The easiest way is to save the image in PNG format, then load it using Android's BitmapFactory. You can do this either via a temporary file, or a Python `bytes` object which you convert to a Java `byte[]` array.

**Comment by coffeetimegit** [comment]
Following your suggestion, I tried to display graphs by creating .png file and use BitmapFactory to load the file.
However I'm unable to display graphs.
.png is saved under os.environ["HOME"] + '/mygraph.png' directory.

![Screen Shot 2020-05-30 at 2 48 04](https://user-images.githubusercontent.com/57280286/83289515-21ec2a00-a220-11ea-9a18-2a3c485a7ac6.png)

```
class GraphRes : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_graphres)

        var data = intent.extras
        var graph = data!!.get("res").toString()
        // graph is where the .png file is stored
        // graph: /data/user/0/com.example.inprogress/files/mygraph.png


        var graph = ImageView(this)
        graph.setImageBitmap(BitmapFactory.decodeFile(graph))

    }
}
```

**Comment by mhsmith** [comment]
> I had people look into my program and they suspect that it might be an issue with the .png file.

You can check the file by using the Device File Explorer to copy the file to your development machine, and viewing it there.

However, your problem is probably the line `var graphId = ImageView(this)`. That is not the correct way to get a reference to an ImageView in your activity. Look for ImageView examples elsewhere and you'll see how it should be done.

**Comment by programmingfever05** [comment]
check out this video to use matplotlib in chaquopy

https://youtu.be/6h2_VPey0Tc
