### ISSUE TITLE
ERROR: Failed to install pyedflib 

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#296]
I need to install pyedflib for my py script. But building fails with this error:
ERROR: Failed to install **pyedflib** from https://files.pythonhosted.org/packages/ab/3a/63b316df182020c9fe7eab81a91c131a96df53101a3617b57e1a70445a12/pyEDFlib-0.1.17.tar.gz.

How to config the pip install for **pyedflib**?

**Comment by sayan-sen** [comment]
Tried:                 `install "pyEDFlib"`

Still:
`Failed to install pyEDFlib from https://files.pythonhosted.org/packages/ab/3a/63b316df182020c9fe7eab81a91c131a96df53101a3617b57e1a70445a12/pyEDFlib-0.1.17.tar.gz.`

**Comment by sayan-sen** [comment]
I guess 

> https://chaquo.com/pypi-7.0/

 doesnt have that package. How to install it then?

**Comment by mhsmith** [comment]
We don't currently support this package, but it looks like there are alternative ways of reading EDF files in Python, such as [MNE](https://pypi.org/project/mne/).

If anyone else wants pyedflib too, please add a thumbs-up to the original post.

**Comment by sarthaksharma058439** [comment]
Hey i found this video it helps me alot in install and import package in android studio with chaquopy , hopefully this will helps you 

https://youtu.be/BDmB3EFy0Qg

**Comment by mhsmith** [comment]
It's been more than a year and only one person has requested this package, so we won't be adding it in the foreseeable future. If anyone else is interested, please post a comment and I'll reopen the issue.
