### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by coffeetimegit** [chaquo/chaquopy#297]
I have a python script that writes on json files but I get FileNotFoundError. 
My python script works fine when I execute it on pycharm IDE but get this error when I use Chaquopy to run the script. Thank you in advance.

Errror:
> com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/Users/myname/AndroidStudioProjects/myproject/app/src/main/assets/sample.json'

**Comment by mhsmith** [comment]
See #284.

**Comment by coffeetimegit** [comment]
I want to write a file and I get a directory below but cannot find its path in android studio. Followed https://developer.android.com/studio/debug/device-file-explorer but don't see the same path.

> /data/user/0/com.example.myproject/files

**Comment by mhsmith** [comment]
Some devices don't work well with the device file explorer, especially if the app is not debuggable. If you need to see what's in the directory, you can add `print` calls to your code, or try testing it on an emulator.

**Comment by mhsmith** [comment]
Some devices don't work well with the device file explorer. First, make sure your app is [debuggable](https://developer.android.com/studio/debug#enable-debug). If that still doesn't fix the problem, try testing it on an emulator, or adding `print` calls to your code to log information about what's in the directory.

**Comment by coffeetimegit** [comment]
I have the file directory given by directory given by os.environ["HOME"]. Below is mine.

> /data/user/0/com.example.myproject/files

Now I know where to save files but the original issue still persists. My python script works fine to create/update json file when I execute it on pycharm IDE but get this error when I use Chaquopy to run the script.

Error I get when I execute my python script on Android Studio.
> com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/Users/myname/Documents/AndroidStudio/DeviceExplorer/emulator-5554/data/data/com.example.myproject/files/news.json'

**Comment by coffeetimegit** [comment]
Below are my Kotlin/Python scripts for your reference.

Kotlin script
```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initNews()
    }

    private fun initNews(): String{
        val python = Python.getInstance()
        val pythonFile = python.getModule("worldnews")
        return pythonFile.callAttr("function").toString()
    }
```

worldnews.py
```
def function():
    data = []
    # append data to data list
    json = json.dumps(data)
    with open('/Users/myname/Documents/AndroidStudio/DeviceExplorer/emulator-5554/data/data/com.example.myproject/files/news.json', 'w') as f:
        f.write(json)
```

**Comment by mhsmith** [comment]
Change your code to look up `os.environ["HOME"]` and write the file to whatever directory it returns.

**Comment by coffeetimegit** [comment]
I get below directory with os.environ["HOME"].
> /data/user/0/com.example.inprogress/files

This is an incomplete directory so I get NullPointerException from changing my python code to below.

worldnews.py
```
def function():
    data = []
    # append data to data list
    json = json.dumps(data)
    with open('os.environ["HOME"] + 'news.json', 'w') as f:
        f.write(json)
```

**Comment by coffeetimegit** [comment]
I get below directory with os.environ["HOME"].

> /data/user/0/com.example.inprogress/files

This is an incomplete directory so I get NullPointerException from changing my python code to below.

worldnews.py
```
def function():
    data = []
    # append data to data list
    json = json.dumps(data)
    with open('os.environ["HOME"] + 'news.json', 'w') as f:
        f.write(json)
```
Concatenating with 'os.environ["HOME"] + 'news.json' to create a full directory does not work neither. I get FileNotFoundError. Why is it that I can run this script fine on Pycharm but not on Android Studio through Chaquopy?

**Comment by mhsmith** [comment]
Why do you think it's an incomplete directory? It looks fine to me.

`+` is just string concatenation, so that will return "/data/user/0/com.example.inprogress/filesnews.json". You'll have to either manually insert an extra slash between the directory and the filename, or use `os.path.join`.

**Comment by coffeetimegit** [comment]
I also tried with + 'news.json' but still get NullPointerException on Android.

I also tried the same code on Pycharm but get FileNotFoundError
> FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.inprogress/files/news.json'

I'm thinking this is an incomplete directory because the full directory is
'**/Users/myname/Documents/AndroidStudio/DeviceExplorer/emulator-5554/data**/data/com.example.inprogress/files'

**Comment by coffeetimegit** [comment]
I also tried with os.environ["HOME"] + '/news.json' but still get NullPointerException on Android.

Also, I tried to run the code on Pycharm with the directory above but get FileNotFoundError

> FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.inprogress/files/news.json'

I'm thinking this is an incomplete directory because the full directory is
> '**/Users/myname/Documents/AndroidStudio/DeviceExplorer/emulator-5554/data**/data/com.example.inprogress/files'

**Comment by Timepiecequinn** [comment]
Inspect this comment https://pythondev.space/questions/android-studio-issue-chaquopythonpyexception-filenotfounderror-errno-2-the-specified-file-or-directory-cannot-be-found
