### ISSUE TITLE
pip install requests failed

### ISSUE THREAD

**Issue by xinyadada** [chaquo/chaquopy#299]
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
i use  anaconda python

**Comment by mhsmith** [comment]
Try installing the current stable version of Python from [python.org](https://www.python.org) (or your distribution's version if on Linux). Then, if necessary, [configure Chaquopy to use it](https://chaquo.com/chaquopy/doc/current/android.html#buildpython).

**Comment by mhsmith** [comment]
If this is stlil a problem, please reopen and give details.
