### ISSUE TITLE
Support Android Gradle plugin version 3.0

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#3]
Internal issue ID #5180

Android Studio 2.3 is currently the recommended stable version, and the only one supported by Chaquopy. Version 3.0 is in beta, and based on the timeline of previous releases, it's likely to become the recommended stable version within the next month or two.

**Comment by mhsmith** [comment]
Android Studio 3.0 has now been released, and we expect to have support for it within the next few days. 

Meanwhile, even if you're already using Android Studio 3.0, I believe you should still be able to use the older version of the plugin. Edit your top-level build.gradle file to change the version number of com.android.tools.build:gradle to 2.3.3, and ignore any suggestions from Android Studio to change it back.

**Comment by connect2satz** [comment]
Thanks Smith :)

**Comment by mhsmith** [comment]
Fixed in version 0.5.0.

**Comment by connect2satz** [comment]
Thanks smith :)
