### ISSUE TITLE
Unlicensed copy of Chaquopy: app will shut down in 10 seconds

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#304]
I was using Chaquopy and suddenly got this error:
```
W/python.stderr: Unlicensed copy of Chaquopy: app will shut down in 10 seconds.
W/python.stderr:  
    See https://chaquo.com/chaquopy/license/
```
After a while i got this error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 25298 (e.myapplication), pid 24535 (e.myapplication)`

What is happening here? is it because Chaquopy is shutting down or something?

**Comment by mhsmith** [comment]
Yes, see the URL in the message for how to apply for a license.
