### ISSUE TITLE
A way or guide to add general packages

### ISSUE THREAD

**Issue by Neur1n** [chaquo/chaquopy#305]
Is there a way or a guide to add general packages instead of waiting for Chaquopy official support? Thanks.

**Comment by mhsmith** [comment]
Not at the moment: see #175.

Which packages are you interested in?

**Comment by Neur1n** [comment]
Well at first it was a general issue, but finally lead me to #201. Actually it is still a "package independent" issue.

And your effort is much appreciated.

**Comment by mhsmith** [comment]
Thanks for the support. If you have problems with any specific packages, please create separate issues for them, or give thumbs up to the issues which already exist.
