### ISSUE TITLE
Buffer dtype mismatch when loading pkl file using joblib

### ISSUE THREAD

**Issue by sufiaji** [chaquo/chaquopy#309]
Hi Malcolm,

I got below issue when trying to load pkl file using joblib. I use newest joblib library. 
Thank you in advance.

![image](https://user-images.githubusercontent.com/7789546/83961785-d04b3b80-a8c0-11ea-99ae-dff86bd012b9.png)

**Comment by sufiaji** [comment]
Same issue when I changed to use pickle. Please advise.
Thank you.

![image](https://user-images.githubusercontent.com/7789546/83963243-a3058a00-a8ce-11ea-87b8-889a703cdb63.png)

**Comment by mhsmith** [comment]
See #168.
