### ISSUE TITLE
Get Object from Python

### ISSUE THREAD

**Issue by Neur1n** [chaquo/chaquopy#310]
So I have a Python file thats contains a `main()` function which makes use of a class inherited from `threading.Thread`. Basically it looks like this:

```python
def main():
    # some code
    foo = Foo()
    foo.start()
    
class Foo(threading.Thread):
    def __init__(self):
        # some code

    def set_sth(self, data):
         self.data = data

    def run(self):
        while True:
            if len(self.data) > 0:
                # some code
                self.data = []
```

So how can I call `foo.set_th()` from Java side? Thanks.

**Comment by mhsmith** [comment]
That depends on how you want to pass `foo` to the Java side. For example, you could return it from `main`:

```
def main():
    ...
    return foo
```

```
PyObject mod = py.getModule(...);
PyObject foo = mod.callAttr("main");
foo.callAttr("set_sth", ...);
```

**Comment by Neur1n** [comment]
Thanks for the hint. Actually when I put a `threading.Thread.start()` ahead of `return`, seems that it will never return. So I just use a global variable for a quick fix.
