### ISSUE TITLE
There is no selenium library

### ISSUE THREAD

**Issue by hbb-polinema** [chaquo/chaquopy#313]
Please add selenium library. Thanks.

**Comment by mhsmith** [comment]
Like most pure-Python libraries, it should be possible to add Selenium to your app using [pip install](https://chaquo.com/chaquopy/doc/current/android.html#requirements). Unfortunately, as discussed in the comments of [this StackOverflow question](https://stackoverflow.com/questions/61881317), it looks like the driver programs aren't available for Android.
