### ISSUE TITLE
python script not getting executed/called

### ISSUE THREAD

**Issue by arunmvr** [chaquo/chaquopy#315]
Hi,
I am using python to process data stored in a csv file in the phone storage. The csv files are processed when the script is executed but often the script doesn't get executed. 

Code calling the script.
```
LogUtil.writeToTxtFile("Calling python script");
Python python = mApplication.getPythonInstance();
if (python != null) {
python.getModule("beacon_code_version_4");
LogUtil.writeToTxtFile("Beacon python script executed");
} else {
LogUtil.writeToTxtFile("python not initialized");
}
```
Code initializing python.
```
public class BeaconApplication extends PyApplication {
    public Python getPythonInstance() {
        return mPython;
    }

    private Python mPython;
    @Override
    public void onCreate() {
        super.onCreate();
        if(!Python.isStarted()){
            Python.start(new AndroidPlatform(getApplicationContext()));
        }
        mPython = Python.getInstance();
    }
}
```

Depending on the size of the file the script takes about 30 seconds or more to process the file and the python script also generates some logs and in instances where the script doesn't get executed or called there are no logs from the script and the logs before and after calling the script show a time difference of ~10ms. No error logs in the logcat when this happens.

I have also tried an implementation without the Application class and starting python locally before calling the script but still have the issue. 

The script is called either from a foreground service which collects the data or inside an activity which checks for unprocessed files. The rate of failure is low when calling from an activity but very high when calling from the foreground service but i have observed the issue in both instances. In both instances the script is run inside a thread. 

I have added some checks to make sure the script doesn't get called simultaneously from both the foreground service and the activity.

**Comment by mhsmith** [comment]
You haven't explained how your background thread is created, but if the thread accesses mPython, then obviously you need to make sure that the thread isn't started until after mPython has been initialized.

Assuming your BeaconApplication class is set in the [`android:name`](https://developer.android.com/guide/topics/manifest/application-element#nm) attribute of your manifest, its onCreate method should be called before any methods of any activity or service. So any threads created in those methods should be safe.

On the other hand, starting threads in an Activity, Service or Application class *constructor* would not be safe. Use the Android lifecycle methods instead.

If you're not clear on what order things are being executed, try adding some logging.

**Comment by arunmvr** [comment]
The Application class is set in the manifest under `android:name` and i am not calling starting the thread from a constructor. 
Here is the method calling the script.
```
private Thread mPythonScriptThread;
private void runPythonScript(){
        mPythonScriptThread = new Thread(new Runnable() {
            @Override
            public void run() {
                LogUtil.writeToTxtFile("Calling python script");
                /*if (!Python.isStarted()) {
                    Python.start(new AndroidPlatform(getApplicationContext()));
                }*/
                if (!mPythonScriptThread.isInterrupted()) {
                    Python python = mApplication.getPythonInstance();
                    if (python != null) {
                        python.getModule("beacon_code_version_4");
                        LogUtil.writeToTxtFile("Beacon python script executed");
                    } else {
                        LogUtil.writeToTxtFile("python not initialized");
                    }
                }
                stopForegroundService(false);
            }
        });
        mPythonScriptThread.start();
    }
```
The method is called after the bluetooth device i am getting data from goes out of range or gets disconnected. And I initialize the application class variable in the `onCreate` of the Foreground Service so the thread gets called only after python is initialized. 

As i mentioned before i have also tried starting python when needed instead of the Application class but that doesn't make a difference and the issue still occurs.

**Comment by mhsmith** [comment]
You have some code which assigns to mPython, and you have some other code which reads it. You just need to structure your app so that the first code always runs before the second code.

Try adding some logging at the end of BeaconApplication.onCreate, and at the beginning of BeaconApplication.getPythonInstance. If they don't appear in that order, then you need to understand why. 

Note that the thread ID appears as the second number in the logcat. For example:

```
2020-06-11 22:09:52.009 10057-10165/com.chaquo.python.demo3 W/python.stderr: ok
```

10057 is the process ID, and 10165 is the thread ID. If they're the same number, then this is the main thread, on which all the Android callback methods are called.

> As i mentioned before i have also tried starting python when needed instead of the Application class

If you're referring to the commented-out code in runPythonScript, that obviously won't have any effect on mPython, so mApplication.getPythonInstance would still return null. You should call Python.getInstance here instead.

**Comment by arunmvr** [comment]
> If you're referring to the commented-out code in runPythonScript, that obviously won't have any effect on mPython, so mApplication.getPythonInstance would still return null. You should call Python.getInstance here instead.

Sorry. While i commented out the starting part i replaced the initialization part.
So when i am using the commented out part i use
`Python python = Python.getInstance();`
instead of 
`Python python = mApplication.getPythonInstance();`

Since i need to use python only when processing the data i was initially starting python when needed and the commented out part is what i started with. I switched to using the Application class only after i started getting this issue.  Starting python when needed is more suitable for my me since my app doesn't use python frequently.

> Try adding some logging at the end of BeaconApplication.onCreate, and at the beginning of BeaconApplication.getPythonInstance. If they don't appear in that order, then you need to understand why.

I will add some logs and check this.

**Comment by mhsmith** [comment]
> when i am using the commented out part i use
> `Python python = Python.getInstance();`
>
>  i was initially starting python when needed and the commented out part is what i started with. I switched to using the Application class only after i started getting this issue.

What do you mean by "getting this issue"? Python.getInstance should never return null, and if you've managed to make that happen then I'd like to know the details. But more likely, you've just had some confusion between different Python variables in your own code.

**Comment by arunmvr** [comment]
> What do you mean by "getting this issue"?

The script was not getting called even before i added the Application Class. I started Python inside the Application class to see if it fixes the issue(script not getting called).

My original code was this
```
private void runPythonScript(){
        mPythonScriptThread = new Thread(new Runnable() {
            @Override
            public void run() {
                LogUtil.writeToTxtFile("Calling Python Script");
                if (!Python.isStarted()) {
                    Python.start(new AndroidPlatform(getApplicationContext()));
                    LogUtil.writeToTxtFile("Starting Python...");
                }else {
                    LogUtil.writeToTxtFile("Python already started... Calling script");
                }
                if (!mPythonScriptThread.isInterrupted()) {
                    Python python = Python.getInstance();
                    if (python != null) {
                        python.getModule("beacon_code_version_4");
                        LogUtil.writeToTxtFile("Beacon python script executed");
                    } else {
                        LogUtil.writeToTxtFile("python not initialized");
                    }
                }
                stopForegroundService(false);
            }
        });
        mPythonScriptThread.start();
    }
```
With this code the python script was not called most of the time so i added the BeaconApplication class to start Python but that also didn't fix the issue.

> Python.getInstance should never return null, and if you've managed to make that happen then I'd like to know the details.

I don't think `Python.getInstance()` ever returned null. I added  `python != null` to rule out possible initialization issue. 

When the issue occurs, the python doesn't get started(it's already running and  doesn't go into the `!Python.isStarted()` loop) and the `python` variable is also not null but the script doesn't run. 

> But more likely, you've just had some confusion between different Python variables in your own code.

I know there are some commented out code but i always use the correct variables before i run so i am not confusing different python variables in the code.

**Comment by mhsmith** [comment]
OK, I I see the problem now. You shouldn't think of `getModule` as "running a script". It's actually the equivalent of the Python `import` statement. And if you import a Python module more than once, the top-level code in the module will only be run the first time.

If you want to run some code multiple times, put it in a function and call it using `callAttr`.

**Comment by arunmvr** [comment]
Thank you! Its working now.
