### ISSUE TITLE
could not find com.chaquo.python：target :3.6.5-10

### ISSUE THREAD

**Issue by zx5259011** [chaquo/chaquopy#316]
![1592188349(1)](https://user-images.githubusercontent.com/66512246/84612528-7a474b00-aef3-11ea-8f2a-7a57b80c8356.jpg)
![1592188398(1)](https://user-images.githubusercontent.com/66512246/84612560-90550b80-aef3-11ea-92ab-71a7ac4a340b.jpg)
![1592188467(1)](https://user-images.githubusercontent.com/66512246/84612603-b5497e80-aef3-11ea-977e-a693936ae273.jpg)

**Comment by mhsmith** [comment]
Does that error message really correspond to the code you've shown? Chaquopy version 7.0.3 uses Python 3.8, not Python 3.6.

Please also make sure you're using the correct version of Gradle (see [this answer](https://stackoverflow.com/a/61973603)).

If you still get the same error after a rebuild, please post the full message. You can find it in the right side of the Build window, which is just visible in your top screenshot, to the left of "Device File Explorer"

**Comment by zx5259011** [comment]
> 该错误消息确实与您显示的代码相对应吗？Chaquopy版本7.0.3使用Python 3.8，而不是Python 3.6。
> 
> 还请确保您使用的Gradle版本正确（请参阅[此答案](https://stackoverflow.com/a/61973603)）。
> 
> 如果重建后仍然出现相同的错误，请发布完整消息。您可以通过在“设备文件资源管理器”的左侧扩展“生成”窗口的右侧（在顶部屏幕截图中可以看到）来找到它。

thank you very much，  I've solved my problem. I can't download python3.6.5-10 ，but i can download python3.8
