### ISSUE TITLE
Spafe Library implementation 

### ISSUE THREAD

**Issue by williamcheung94** [chaquo/chaquopy#319]
Hi,

I have issues with importing the Spafe library into android implementation for audio feature computation. Is the Spafe library available or is there a work around for this.

**Comment by mhsmith** [comment]
Have you tried installing as described in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements)? If you've done that and you still have problems, please post:

* The full error message.
* The `python` section of your build.gradle file.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and provide the requested information.
