### ISSUE TITLE
Problems with paho-mqtt

### ISSUE THREAD

**Issue by sa20001** [chaquo/chaquopy#321]
Hi, I have written a code in Python for a school project and I'm trying to use it in Android Studio. 

I have imported  the libraries with the code:
 python {
            pip {
                install "paho-mqtt"
                install "termcolor"
            }

But when I go in the .py files I receive errors saying that there are no modules. What am I doing wrong, am I importing the libraries in the wrong way?

import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish
import ast  
from termcolor import colored

Thx in advance

**Comment by mhsmith** [comment]
As it says in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin), Android Studio's error highlighting doesn't work correctly for Python files. Just go ahead and run your app, and if there really is an error, the details will be displayed in the Logcat.

**Comment by sa20001** [comment]
Ok, I keep getting these errors, when I launch the app:

2020-06-20 13:04:21.855 10263-10263/zzz.despair.testchaquo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: zzz.despair.testchaquo, PID: 10263
    java.lang.RuntimeException: Unable to start activity ComponentInfo{zzz.despair.testchaquo/zzz.despair.testchaquo.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 1] Operation not permitted
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.chaquo.python.PyException: PermissionError: [Errno 1] Operation not permitted
        at <python>.socket.__init__(socket.py:231)
        at <python>.paho.mqtt.client._socketpair_compat(client.py:269)
        at <python>.paho.mqtt.client.__init__(client.py:566)
        at <python>.Antifurto_main.test_1(Antifurto_main.py:44)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at zzz.despair.testchaquo.MainActivity.onCreate(MainActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-06-20 13:04:21.876 10263-10263/zzz.despair.testchaquo I/Process: Sending signal. PID: 10263 SIG: 9


Here my code:

`import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish
import ast  # da bytecode a dictionary

from termcolor import colored

def test_1():

    # TODO: aggiungere supporto log, con data e ora --> meglio farlo in Android
    # TODO: vedere perché (raramente perde i messaggi dal server)

    topic_base = 'afp/mr/home/Antifurto_Uf_SEhh/'
    device_id = "Antifurto_main"
    broker_server = 'broker.hivemq.com'

    # Antifurto_centralina.Start_thread_centralina()  # avvio il thread della centralina

    # faccio girare il programma in loop, fino a quando non arriva il comando "kill"
    while True:

        server_response = 0  # variabile per estrarre la risposta dal server
        server_response_dictionary = 0  # inizializzata a 0 in caso di eccezione
        program_killer = 0  # inizializzata a 0 in caso di eccezione


        def callback_connessione(client, userdata, flags, rc):
            print("Super Connected to the server: \"", broker_server + " \" with result code", str(rc))
            # sottoscrivo gli argomenti di interesse
            client.subscribe(topic_base + "#")


        def callback_disconnessione(client, userdata, rc):
            if rc != 0:
                print('Disconnesso')


        def callback_ricezione(client, userdata, message):
            print(userdata)
            print("Messagge received from " + message.topic + " with content " + str(message.payload))
            global server_response  # variabile definita global per estrarre la risposta del server dalla funzione
            server_response = message.payload  # estraggo la risposta da message.payload e la salvo in questa variabile


        client = mqtt.Client(client_id="AFP")
        client.on_connect = callback_connessione  # Define the connect callback implementation.
        client.on_disconnect = callback_disconnessione

        # Called when a message has been received on a topic that the client subscribes
        client.on_message = callback_ricezione
        client.connect(broker_server)  # si connette al broker server
        client.loop_start()  # inizia il loop per rimanere in attesa dei messaggi dal broker

        # entro nel ciclo sempre vero
        while True:

            try:  # gestione eccezione per il metodo literal_eval (a volte va in crash) e per bad json format

                if server_response != 0:  # se ho ricevuto un messaggio la variabile è diversa da 0
                    dict_str = server_response.decode("UTF-8")  # decodifco il byte code ricevuto secondo lo standard UTF-8
                    server_response_dictionary = ast.literal_eval(dict_str)  # converto il bytecode in dictionary

                    # The repr() function returns a printable representation of the given object.
                    # https://www.programiz.com/python-programming/methods/built-in/repr
                    print(repr(server_response_dictionary))
                    print(type(server_response_dictionary))  # stampo il tipo della variabile server_response_dictionary

                    checker = False

                    # TODO: da qui creare array di sensori in android, estrarre dati da "server_response_dictionary" e dal file cfg.json
                    for i in server_response_dictionary["sensor_list"]:  # stampo tutti valori della lista dei sensori

                        if i["sensor_status"] == 0:  # se il sensore non ha rilevato nulla
                            print(colored(i["sensor_id"] + " No trigger", "blue"))

                        else:  # se il sensore ha rilevato qualcosa
                            checker = True

                            print(colored(i["sensor_id"] + " Sì trigger", "yellow"))
                            publish.single(topic_base + device_id + "_alarm",
                                           payload="Someone triggered a sensor!!!",
                                           hostname=broker_server)

                    if checker:
                        for index, element in enumerate(server_response_dictionary["sensor_list"]):  # entro nella lista del dict
                            if element["sensor_id"] == "Siren":
                                server_response_dictionary["sensor_list"][index][
                                    "sensor_status"] = 1  # cambia lo stato a 1 all'interno del dict
                                print(colored(server_response_dictionary, "magenta"))   # debug
                    # TODO: fino a qui creare array di sensori in android

                    break  # esco dal ciclo

            except (KeyError, ValueError, SyntaxError):  # gestisco l'eccezione solo se è ValueError e SyntaxError
                print(colored("A ValueError, SyntaxError or KeyError occurred!!!", "red"))  # stampo in rosso
                break  # esco dal ciclo

        client.loop_stop()  # stoppo il client

        # if no errors occurred
        if server_response_dictionary != 0:

            try:  # gestisco l'eccezione se non è presente la chiave "System_status" nel file JSON
                program_killer = server_response_dictionary[
                    "System_status"]  # estraggo il valore della chiave "System_status" e lo associo alla variabile programm_killer

            except KeyError:  # gestisco l'eccezione solo se è KeyError
                print(colored("Wrong key \"System_status\", maybe mistyped or missing\nCheck JSON sent", "red"))
                print(colored("EXCEPTION CORRRECTLY HANDLED\nCheck \"System_status\" key", "green"))

            if program_killer == "kill":  # se la key "System_status" ha valore "kill"
                print(colored("Command \"kill\" received from Broker", "red"))

                publish.single(topic_base + device_id + "_kill",
                               payload="Message \"" + program_killer + "\" correctly received from server. System correctly terminated",
                               hostname=broker_server)  # stampo il messaggio di kill
                # Antifurto_centralina.Stop_thread_centralina()  # stoppo il thread della centralina
                break  # esco dal ciclo while principale

            # invio al server quello che ho ricevuto dal server in un solo messaggio
            publish.single(topic_base + device_id + ("_check"), payload="Message " + str(server_response_dictionary) +
                                                                        " correctly received", hostname=broker_server)

        else:
            # if errors occurred during conversion from bytecode to dicitonary
            print(colored("RECEIVED BAD/WRONG MESSAGE FROM BROKER\nAST FAILED TO EVAL", "red"))
            print(colored("EXCEPTION CORRRECTLY HANDLED\nMAKE SURE TO SEND CORRECT JSON FORMAT NEXT TIME", "green"))

            # Publish multiple messages to a broker, then disconnect cleanly.
            multiple_publish = [{'topic': topic_base + device_id + ("_error"),
                                 'payload': "An error occurred"},
                                (topic_base + device_id + ("_error_message"), "With message BAD JSON FORMAT", 0, False)]
            publish.multiple(multiple_publish, hostname=broker_server)  # invio al server più messaggi nello stesso momento
`
Thank you for your time

**Comment by mhsmith** [comment]
Does your app have the [INTERNET permission](https://stackoverflow.com/questions/2378607)?

**Comment by sa20001** [comment]
yes, I haev this permissions in manifest

```
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />

```

**Comment by mhsmith** [comment]
Your code works fine for me as long as I include the INTERNET permission. Please check you've included it correctly.

If you're sure you've included it and you still get the error, please try it on the Android emulator if you haven't already, and then let me know which devices or emulators the problem occurs on.

**Comment by sa20001** [comment]
Ok, this is strange. I was using Pixel 3 XL emulator, no success. I switched to Nexus 5X and magic, now I do not get anymore errors and the code kinda works.

**Comment by mhsmith** [comment]
For me it worked in the emulator (Nexus 4 profile) on API levels 16 and 29, and also on a real Nexus 5X.

**Comment by sa20001** [comment]
Yeah, I have just tested it with my S7 with api 29 and it works, with pixel emulator still not luck.

**Comment by sa20001** [comment]
I'm facing another problem, I have this error code:

2020-06-21 11:19:59.942 15051-15051/zzz.despair.testchaquo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: zzz.despair.testchaquo, PID: 15051
    java.lang.RuntimeException: Unable to start activity ComponentInfo{zzz.despair.testchaquo/zzz.despair.testchaquo.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'cfg.json'

I am using this line of code:
`read_file = open("cfg.json", "r")`

and the cfg.json file is in the same folder of the .py file

**Comment by mhsmith** [comment]
See #144. And if you want to use the emulator, see if it works with a different hardware profile.

**Comment by sa20001** [comment]
Thank you very much, it works perfectly.
Last question, is it possible to use print(colored()) in ADB?

**Comment by mhsmith** [comment]
Anything you pass to `print` will be sent to the Logcat. I don't expect any color formatting will appear in Android Studio, but it's possible it might work if you run adb in a Linux terminal or similar.

Did you work out what the problem was with the emulator?

**Comment by sa20001** [comment]
I think the emulator was, somehow, corrupted. I have created a new emulator with same phone and settings and it works...
