### ISSUE TITLE
Could not find com.chaquo.python:target:3.8.1-6.

### ISSUE THREAD

**Issue by dhruvik1999** [chaquo/chaquopy#326]
![Screenshot from 2020-06-29 18-54-20](https://user-images.githubusercontent.com/32356700/86011205-0b610a80-ba3a-11ea-942e-7306b1fec7a2.png)

![Screenshot from 2020-06-29 18-55-36](https://user-images.githubusercontent.com/32356700/86011292-229ff800-ba3a-11ea-9315-991a746d2acd.png)

**Comment by mhsmith** [comment]
When using the Android Gradle plugin version 3.6. you should also make sure that gradle-wrapper.properties uses the [corresponding version of Gradle](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle), which is 5.6.4.

**Comment by dhruvik1999** [comment]
Thank you!!!
It is working now.

But I got another error.
 How can I include python modules in my android project?
 because right now android studio is showing that **" com.chaquo.python.PyException: ModuleNotFoundError: No module named 'requests'"**

**Comment by mhsmith** [comment]
See [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements).

**Comment by dhruvik1999** [comment]
thank you so much :)
