### ISSUE TITLE
Could not find the file, invalid path : /home/dhruvik/Desktop/MyWork/SU/pythonandroid/app/src/main/python/cert.pem

### ISSUE THREAD

**Issue by dhruvik1999** [chaquo/chaquopy#327]
![Screenshot from 2020-06-29 21-12-16](https://user-images.githubusercontent.com/32356700/86026731-6ea86800-ba4d-11ea-8bab-fc05ec9f7fdc.png)

**Comment by mhsmith** [comment]
See #144.
