### ISSUE TITLE
 ConnectionError: HTTPSConnectionPool(host='sandbox.api.visa.com', port=443): Max retries exceeded with url: /visadirect/fundstransfer/v1/pushfundstransactions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xcef87b80>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))

### ISSUE THREAD

**Issue by dhruvik1999** [chaquo/chaquopy#328]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.arpcache.pythonandroid/com.arpcache.pythonandroid.MainActivity}: com.chaquo.python.PyException: ConnectionError: HTTPSConnectionPool(host='sandbox.api.visa.com', port=443): Max retries exceeded with url: /visadirect/fundstransfer/v1/pushfundstransactions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xcef87b80>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))

**Comment by mhsmith** [comment]
Please search existing issues before creating new ones. You'll get an answer to your problem much more quickly that way.

**Comment by dhruvik1999** [comment]
The same code is running in my local computer but not with android python chaquopy SDK.

**Comment by mhsmith** [comment]
Have you searched for the phrase "No address associated with hostname" on this issue tracker?

**Comment by mhsmith** [comment]
Make sure your app has the [INTERNET permission](https://stackoverflow.com/questions/2378607).
