### ISSUE TITLE
Cannot use mmcv with chaquopy

### ISSUE THREAD

**Issue by rudra-sett** [chaquo/chaquopy#330]
The python program I am trying to use with chaoquopy depends on mmcv.

It is giving me this error:
`  building 'mmcv._ext' extension
  error: CCompiler.compile: Chaquopy cannot compile native code`

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please add a thumbs-up to the original post and we may provide it in the future.

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
It's been over 3 years, and only 2 people have requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
