### ISSUE TITLE
Data/Resource Not Found Error

### ISSUE THREAD

**Issue by objectc** [chaquo/chaquopy#331]
I've seen how to load a file at https://github.com/chaquo/chaquopy/issues/144. However, when I did the same work with Chaquopy 6.3.0, I got an error: 
`com.chaquo.python.PyException: NotFoundError: /data/user/0/com.chaquo.python.hello/files/chaquopy/AssetFinder/app/bravo/filename.txt `
The python file is src/main/python/hello.py, and the data file is src/main/python/bravo/filename.txt
I could only found compiled pyc files in the target path, but no data/resource there.
Anything else I need to do?
Thanks.

**Comment by mhsmith** [comment]
If your source code has a `bravo/__init__.py`, then you should run `import bravo` before you try to access the data file. This applies to all versions of Chaquopy.

If you don't have a `bravo/__init__.py`, then on Chaquopy 6 and 7 you'll need to create it (an empty file is fine) and import it as above. On Chaquopy 8 and later, this is no longer necessary, and the data file will be accessible as soon as the app starts.

**Comment by objectc** [comment]
Thanks. Problem solved.
