### ISSUE TITLE
tflite_runtime

### ISSUE THREAD

**Issue by alisonwh** [chaquo/chaquopy#332]
With chaquopy's tensorflow .whl, my code using tflite python API works successfully on Android. As I need to do some modification for tensorflow source code, I build my tflite_runtime-2.1.0-cp37-cp37m-linux_aarch64.whl. Then I change build.gradle as below:
pip {
// install "tensorflow==2.1.0"
    install "tflite_runtime-2.1.0-cp37-cp37m-linux_aarch64.whl"
....
}

During the building, I get the following error:
> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
tflite_runtime-2.1.0-cp37-cp37m-linux_aarch64.whl is not a supported wheel on this platform.
Chaquopy: Exit status 1

Any suggestion about this issue? Thanks.

**Comment by mhsmith** [comment]
Unfortunately .whl files built for Linux won't work on Android. We'd probably be willing to build this package for Android in exchange for a payment: please [email us](https://chaquo.com/chaquopy/contact/) if you'd like to discuss this. 

If anyone else is interested in this package, please click the thumbs up button above.

**Comment by mhsmith** [comment]
TensorFlow Lite is now available for Chaquopy. It can be installed in the [`pip` block](https://chaquo.com/chaquopy/doc/current/android.html#requirements) of your build.gradle file using the name `tflite_runtime`.

**Comment by kongkip** [comment]
Hi @mhsmith  the tflite_runtime above is version 2.1.0-1 which doesn't support TRANSPOSE CONV  op. Could you please updeleate to version 2.5.0 or how can I build the wheel.

**Comment by mhsmith** [comment]
I'll look into it and get back to you in the next couple of days.

**Comment by kongkip** [comment]
Ok thanks, looking forward to your reply.

**Comment by mhsmith** [comment]
tflite-runtime version 2.5.0 is now available.
