### ISSUE TITLE
Returning dict from Python

### ISSUE THREAD

**Issue by vidheyoza** [chaquo/chaquopy#333]
Hi, 

I have been trying to return a dict from Python into Kotlin. Once the output object is returned from `pyObject.callAttr()`, I cast it into a Map using `.toMap()`. But when I try to access the values from the map, I am getting only null values. 

I also tried to return a list of strings and cast it into `.toList()`, but I'm getting the same issue. 

Am I missing something, or is there some issue with returning a "compound" data type like dict or list? Because I can return a single value easily.

**Comment by mhsmith** [comment]
Please post a small example of both the Python and the Java code.

**Comment by vidheyoza** [comment]
Python code (main.py): 
```
def foo(param1, param2): 
    ...
    val1, val2 = bar()
    return {
        "val1": val1, 
        "val2": val2
    }
```
Kotlin code: 

```
val py = Python.getInstance()
val mainPyObject: PyObject = py.getModule("main")
....
val out = mainPyObject.callAttr(
    "foo",
    Kwarg("param1", param1),
    Kwarg("param2", param2)        
).toMap()

val val1 = out["val1"]?.toString()?.toBoolean() ?: false
val val2 = out["val2"]?.toString()?.toInt() ?: 0 

globalVal1 = val1

return val2
```

**Comment by mhsmith** [comment]
You should be using the Chaquopy method [`asMap`](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html#asMap--), not the Kotlin extension function [`toMap`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/to-map.html). `toMap` will access the object's attributes (Python “.” syntax), whereas `asMap` will access the object as a container (Python “[]” syntax).

**Comment by vidheyoza** [comment]
Thanks so much for the help! 

The asMap() converts the object into a PyObject map. How do I pass a PyObject key to the map to access what I want? Do I just typecast my string to a PyObject?
