### ISSUE TITLE
Request MTCNN Package to be added

### ISSUE THREAD

**Issue by xXRuzzlesXx** [chaquo/chaquopy#334]
Hello there,

I am implementing an Android Kotlin Application and am trying to use Chaquopy.
While configuring Chaquopy I've been searching for the package MTCNN in the repository.

Unfortunately I couldn't find the package. This package would help a lot to process images.

Thanks in Advance.

**Comment by mhsmith** [comment]
It looks like [this is a pure-Python package](https://pypi.org/project/mtcnn/#files), so it doesn't need to be in the repository. Just try installing it, and if you have any problems, please give details.

**Comment by xXRuzzlesXx** [comment]
Thanks for the hint.
I have also asked for more information via the Chaquopy email address.

Issue closed for now.
