### ISSUE TITLE
Long module loading time

### ISSUE THREAD

**Issue by ntreepoint** [chaquo/chaquopy#336]
Hi,
I am using chaquopy trial version v8.0.0 using Android Studio 4.0 on a Pixel4 phone.
When getting reference on a sample python module in my java application, using "getModule" API, i have measured an execution time of 573 ms the first time i do it when starting the application. In other runs, the time is 0 ms. I guess this loading time is coming from the loading of package dependencies, for information here are my dependencies:
```
import torch
import numpy as np
from itertools import product as product
from math import ceil
from torchvision.ops import nms
import typing
```
Is there any way like using the commercial version to make with loading time smaller?

BR

**Comment by mhsmith** [comment]
Numpy, torch and torchvision are all fairly large packages, so I think 573 ms is a reasonable amount of time to import them. In fact, I have a Linux server which takes about 700 ms to import those three packages, so on your phone Chaquopy is actually faster than that.

The performance will not be affected by whether you have the trial version or a licensed copy.

**Comment by mhsmith** [comment]
If the delay makes your app feel unresponsive, then you could try calling `getModule` on a background thread.

**Comment by ntreepoint** [comment]
Yes ,creating a background thread may be a good solution. Thank you for your reply.
