### ISSUE TITLE
需要加载的.py文件放在SD卡可以吗

### ISSUE THREAD

**Issue by workhoust** [chaquo/chaquopy#337]
需要加载的Python文件放在SD卡，不放在自动创建的那个python文件夹下面可以吗

**Comment by mhsmith** [comment]
If you want to load Python code from the SD card, or from any other directory, then you can just add the directory to `sys.path`.

For example, if you have a script in `/some/dir/hello.py`, then you can do this:

```
import sys
sys.path.append("/some/dir")
import hello
```

**Comment by YangKee** [comment]
nice
