### ISSUE TITLE
can't install kiteconnect 

### ISSUE THREAD

**Issue by aditya3001** [chaquo/chaquopy#338]
i am getting this error installing kiteconnect

ERROR: Chaquopy: can't happen: requirement kiteconnect from https://files.pythonhosted.org/packages/b3/ca/13d0565cb51baa1df6344f2dd7f10eb32c0e28a7213a49d82d70cab9326a/kiteconnect-3.8.2.tar.gz is still not a wheel.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
Thanks for the report, I'll look into it.

**Comment by mhsmith** [comment]
We'll fix this in the next version of Chaquopy. Meanwhile, you can work around it by installing kiteconnect version 3.6.2.

**Comment by aditya3001** [comment]
thanks! will do that@mhsmith

**Comment by mhsmith** [comment]
Let's leave the issue open until it's been fixed.

**Comment by sarthaksharma058439** [comment]
Hey i found this video it helps me alot in install and import package in android studio with chaquopy , hopefully this will helps you 

https://youtu.be/BDmB3EFy0Qg

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 9.0.0. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle`.
