### ISSUE TITLE
Can't open image from storage

### ISSUE THREAD

**Issue by superchampionoftheworld** [chaquo/chaquopy#339]
My python script requires the path for an image, where it will take that image and run the rest of the function on it. On the Java side, I have an intent that allows the user to pick an image from the gallery and it will also take the path of that image. (/storage/emulated/0/...) This part functions properly, as I can log the correct file path of the image and display it as a bitmap.

I am passing that path to the python function, but when I try to open the image at that path within python (using Pillow to open it), I get a permission denied error. The AndroidManifest does include the permission WRITE_EXTERNAL_STORAGE. I checked issue #144 for this, but that seems to be about reading files within the project, whereas I want one on the storage of the device.

**Comment by mhsmith** [comment]
Can you post the relevant code?

* The Java code which gets the path 
* The Java code which passes the path to Python
* The Python code which receives the path and opens it

Are you definitely loading the image from a simple path, or is it some kind of URI?

**Comment by superchampionoftheworld** [comment]
```
if(requestCode==GET_FROM_GALLERY && resultCode == Activity.RESULT_OK) {
            Uri selectedImage = data.getData();
            Bitmap bitmap = null;
            String path = null;
            try {
                bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), selectedImage);
                Log.d("Initial path",selectedImage.toString()); //NOT a file path, is content:/// instead
                String picturePath = getPath( this.getApplicationContext( ), selectedImage);
                Log.d("Picture Path", picturePath);

                ImageView img = findViewById(R.id.pic);
                img.setImageBitmap(bitmap);
                Python py = Python.getInstance();
                PyObject pyfile = py.getModule("classifier");
                String result = pyfile.callAttr("classify","weights/global.pth",picturePath).toString();
```

This snippet above is run after the user picks an image from the gallery. Yes, the variable "selectedImage" is a URI. I confirmed this with the first Log.d statement. However, I have a function that turns this URI into an actual path (/storage/emulated/0/DCIM...)

**Java code which gets the path**
```
String picturePath = getPath( this.getApplicationContext( ), selectedImage);
                Log.d("Picture Path", picturePath); //properly logs a /storage/emulated/0/... file path
```
These two lines do produce a "/storage/emulated" file path in the logger output, using a function in the program called getPath(). I'm reasonably sure everything is correct on the Java side. 

**Python code to receive the path and open it**

```
import os
import sys
import torch
import android
import android.os
from PIL import Image

... 

def classify(model, img_path, model_file='utils/dlib_face_detector/mmod_human_face_detector.dat'):

    im_w, im_h = Image.open(img_path).size //this is the line that gives an error, saying permission denied
```

This script is called classifier.py, which I referenced with: `PyObject pyfile = py.getModule("classifier");`
and takes a model (which is in the project files and not the issue right now) and a file path to an image, both of which I pass to the function with `String result = pyfile.callAttr("classify","weights/global.pth",picturePath).toString();`

**Comment by superchampionoftheworld** [comment]
The WRITE_EXTERNAL_STORAGE permission was in the manifest but was never actually requested by the app. That solves this issue.

**Comment by superchampionoftheworld** [comment]
Correction: that was not actually the main issue. This app targets Android 10 and is affected by scoped storage rules. A _temporary_ fix is to add this to the <application> section of the manifest: android:requestLegacyExternalStorage="true"

**Comment by mhsmith** [comment]
I'm not familiar with the storage rules on newer versions of Android, but my guess is that even though you can get the path, your app still won't have permission to access it directly.  

Instead, you might have to read it into a byte[] array using [`ContentResolver.openInputStream`](https://developer.android.com/reference/android/content/ContentResolver#openInputStream(android.net.Uri)). This array can then be converted into a Python bytes object by passing it to [`bytes`](https://docs.python.org/3/library/functions.html#func-bytes), or wrapped in a file-like object by passing it to [`BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO).
