### ISSUE TITLE
Invalid Python version

### ISSUE THREAD

**Issue by MisterY** [chaquo/chaquopy#34]
Hi,

Just trying out the plugin, which looks like an interesting approach. I am trying with
```
        python {
            version "3.6.4"
```
but getting `Error:Cause: debug: invalid Python version '3.6.4'. Available versions are [2.7.10].`
Does this mean that only Python 2 is supported? Based on #1 and #2, I'd believe that Python 3 is supported. Or am I misunderstanding this setting?

If I put "2.7.10", then the error is "could not resolve com.chaquo.python:target:2.7.10-2".

**Comment by mhsmith** [comment]
What version of Chaquopy are you using (i.e. version of `com.chaquo.python:gradle`)?

Python 2.7.10 should be available in all Chaquopy versions, while the current version also supports 3.6.3 and 2.7.14 (see [here](https://chaquo.com/chaquopy/doc/current/android.html#python-version)).

**Comment by MisterY** [comment]
Good question! I was using `com.chaquo.python:gradle:0.6.0` as per (some) instructions. I see there is 1.3.1 in the current docs. Probably got a link to the documentation of an older version via google search.

Now the available versions list 3.6.3. Thanks!

**Comment by mhsmith** [comment]
That is strange, since 0.6.0 was an internal test version which was never even publicly released. Do you know where you got those instructions?

**Comment by MisterY** [comment]
Let me check my browsing history!

**Comment by MisterY** [comment]
Oh, I see. I was reading the instructions under the Basic Setup
`For a minimal example, see chaquopy-hello, a Python version of the Android Studio “Empty Activity” app template. For a more complete example, see the demo app.`
Then I checked the example at `https://github.com/chaquo/chaquopy-hello`, the marked commit that shows the differences, and copied the parts that referred to Chaquopy to my existing project. 
Oops! Sorry for the inconvenience.

**Comment by mhsmith** [comment]
Aha, thanks, I'll reword that to stop anyone else doing the same thing.
