### ISSUE TITLE
interfacing c++ code with chaquopy

### ISSUE THREAD

**Issue by yakovdan** [chaquo/chaquopy#344]
Hi, 
I have some c++ code that I want to call from python. I've solved this on ubuntu/x86 using pybind11.
How can I do this on android using chaquopy?

**Comment by mhsmith** [comment]
If you need to build your own C++ code for Chaquopy, then you can license our package build tool, which was used to build everything in our [native package repository](https://chaquo.com/pypi-7.0/). It supports pybind11, Cython, CMake, and many other build systems, and handles a wide variety of cross-compilation issues.

The tool runs on Linux, and comes with an optional Dockerfile for easier dependency management and reproducibility.

The cost of this tool is $250 -- this is separate to the license for Chaquopy itself. If you'd like to order it, please [email us](https://chaquo.com/chaquopy/contact/) for payment instructions.
