### ISSUE TITLE
demo报错Read timed out

### ISSUE THREAD

**Issue by workhoust** [chaquo/chaquopy#347]
![QQ图片20200720155300](https://user-images.githubusercontent.com/4724639/87913144-25be5f00-caa1-11ea-9a1b-43ef9b7b7aef.png)

**Comment by mhsmith** [comment]
Please post the full build log, not just the error message. You can view it by scrolling up the list of tasks at the bottom left of the screen, and clicking the "Build" line at the top.

**Comment by workhoust** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaquo/chaquopy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 凌晨3:40
收件人:&nbsp;"chaquo/chaquopy"<chaquopy@noreply.github.com&gt;;
抄送:&nbsp;"马永立"<593021743@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chaquo/chaquopy] demo报错Read timed out (#347)





 
Please post the full build log, not just the error message. You can view it by scrolling up the list of tasks at the bottom left of the screen, and clicking the "Build" line at the top.

**Comment by mhsmith** [comment]
You can't send images to GitHub via email. Upload them on the website instead.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and provide the requested information.
