### ISSUE TITLE
can't install pyjnius

### ISSUE THREAD

**Issue by everydaysayhello** [chaquo/chaquopy#348]
I think it's a good idea that chaquopy can install pyjnius,but I can't install pyjnius!can you help me ?thank you~

**Comment by mhsmith** [comment]
Chaquopy itself already supports all the functionality of pyjnius. You'll just have to make a few minor changes to your code:

* Replace [`jnius.autoclass`](https://pyjnius.readthedocs.io/en/stable/quickstart.html) with [`java.jclass`](https://chaquo.com/chaquopy/doc/current/python.html#classes).
* Replace [`jnius.PythonJavaClass`](https://pyjnius.readthedocs.io/en/stable/api.html#jnius.PythonJavaClass) with [`java.dynamic_proxy`](https://chaquo.com/chaquopy/doc/current/python.html#dynamic-proxy).

**Comment by everydaysayhello** [comment]
But I have an error,how to solve it?thank you!
<img width="718" alt="QQ20200722-000218@2x" src="https://user-images.githubusercontent.com/56616684/88145198-ebdb7e80-cbae-11ea-9f9a-7f9a0cf9550c.png">

**Comment by mhsmith** [comment]
Remove pyjnius from your build.gradle file, and alter your code to use the Chaquopy API instead, as I describe above.
