### ISSUE TITLE
Package request: astropy

### ISSUE THREAD

**Issue by jcgoble3** [chaquo/chaquopy#349]
Hello. For our app that processes astronomy data, we need the astropy package, which has C components. Can this be added to the Chaquopy repository?

**Comment by mhsmith** [comment]
We might be willing to build this package for Chaquopy in exchange for a payment: please [email us](https://chaquo.com/chaquopy/contact/) if you'd like to discuss this. 

If anyone else is interested in this package, please click the thumbs up button above, and subscribe to this issue for updates.

**Comment by jcgoble3** [comment]
I have submitted this to my supervisor who handles the money and will see what she wants to do.

**Comment by mhsmith** [comment]
No, but if you'd like to try building it yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
Related: #812
