### ISSUE TITLE
Other version of opencv-python package 

### ISSUE THREAD

**Issue by iElsha** [chaquo/chaquopy#350]
Hello,

I am facing an issue with opencv-python (version 4.1.2) in chaquopy (v 8.0). I'd like to use another version of opencv-python:

I try to load a custom darknet model (Yolov3-tiny) like that: 
```python
self.network = cv2.dnn.readNetFromDarknet(f"{path}/yolo_tiny/yolov3-tiny-prn.cfg",
                                          f"{path}/yolo_tiny/yolov3-tiny-prn_last.weights")
```
But I'm getting this error:
```
using opencv 4.1.2
I/python.stdout: Attempting to load Darknet model    
A/libc: /buildbot/src/android/ndk-release-r18/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::out_of_range: vector" failed
    Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15324 (.camerax.tflite), pid 15324 (.camerax.tflite)
```

In the meantime I've tried these things:
1. Run my python code in my IDE with python 3.6 & opencv 4.1.2 plus with python 3.8.5 & opencv 4.1.2
```
Attempting to load Darknet model

Process finished with exit code -1073740791 (0xC0000409)
```
2. Same thing with python 3.6 & opencv 4.2.0.34 and it worked.
```
Attempting to load Darknet model
Darknet model loaded
```

it seems like the version 4.1.2 of opencv-python has an issue to load darknet networks. **Would it be possible to use another opencv-python version?**

Thank you in advance for your answer.

**Comment by mhsmith** [comment]
Thanks for the report. If we provide a newer version of opencv-python, it would preferably be to the newest one, 4.3.0.36. Can you check whether your model works with that version?

**Comment by iElsha** [comment]
Hello,

I just tested and version 4.3.0.36 works smoothly with my models & networks.

**Comment by mhsmith** [comment]
We'd be willing to add this version in exchange for a small payment. Let's continue discussion over email.
