### ISSUE TITLE
How to Import modules from parent folder?

### ISSUE THREAD

**Issue by objectc** [chaquo/chaquopy#352]
If in the same level or subfolder, I can use `import .module_path`. How to do with the parent folder and why there is a `.` for the subfolder? Thanks.

**Comment by mhsmith** [comment]
To import from the parent package you use two dots, e.g. `import ..module_path`. This can be extended to any three or more dots for the grandparent package etc.

This issue tracker is only for Chaquopy issues; please don't ask general Python questions here.

**Comment by mhsmith** [comment]
Actually, `import .module_path` isn't valid Python syntax: it should be `from . import module_path`. Search for "python relative import" for more information.
