### ISSUE TITLE
Problem regarding loading csv file using chaquopy on Android Studio

### ISSUE THREAD

**Issue by gursimransinghbrar** [chaquo/chaquopy#353]
@mhsmith
We have integrated python in android studio using chaquopy. We have used csv file to read our data set. The data set is in libs folder as shown below. We are getting an error of file not found in android studio. We have provided the right path in the script. We tried your GitHub solution but we couldn’t understand it. I don’t know if we have to give the csv file path in android studio or not. Please help us in this matter. We also mailed you regarding this matter.

![python script](https://user-images.githubusercontent.com/62603979/88477681-b55f8400-cf5f-11ea-8058-7d897c623b0a.jpg)
![Annotation 2020-07-26 163049](https://user-images.githubusercontent.com/62603979/88477682-b7294780-cf5f-11ea-97ad-da5d310d95c0.jpg)
![Annotation 2020-07-26 163103](https://user-images.githubusercontent.com/62603979/88477683-b7c1de00-cf5f-11ea-9940-fa10582b4742.jpg)
![Python file's path provided in Android Studio](https://user-images.githubusercontent.com/62603979/88477684-b85a7480-cf5f-11ea-8c3a-fa07ccdfad8e.jpg)

**Comment by mhsmith** [comment]
See #144.

**Comment by gursimransinghbrar** [comment]
Sir we saw that solution but were not able to solve it. Where we need to
add that lines?

**Comment by mhsmith** [comment]
If your Python file is src/main/python/final_2.py, and your data file is src/main/python/libs/train.csv, then you can do this:

```
from os.path import dirname, join
filename = join(dirname(__file__), "libs/train.csv")
df = pd.read_csv(filename)
```

**Comment by gursimransinghbrar** [comment]
Thank you sir. But when when we start the script in app there is black
screen and then app closes without giving any error? Script takes about 2
minutes to start in python IDLE though

**Comment by gursimransinghbrar** [comment]
EOFError: EOF when reading a line. Now i am getting this error can you help
me with it?

**Comment by mhsmith** [comment]
If you're trying to read from standard input, then you should use the [chaquopy-console](https://github.com/chaquo/chaquopy-console) template. This will also help if your code takes a long time to run, because it runs everything in a background thread.
