### ISSUE TITLE
cvtcolor python code used to generate grayscale image but failed to display in android device

### ISSUE THREAD

**Issue by Vijju203** [chaquo/chaquopy#354]
Hi,
I would like to use opencv-python in .py file to convert an RGB image to gray image, I have given source image in res/drawable folder , it gives only colored image as output.When I tried to override the color image file with grayscale using cv2.imwrite it fails.
Please help.

Image - Copy.py
```
import matplotlib.pyplot as plt
# importing cv2  
import cv2
from os.path import dirname, join
```
  
importing os module   
```
import os 
def test():
    # Image path
    filename = join(dirname(__file__), "flowers.jpg")
    #image_path = r'F:\Projects\app\src\main\res\drawable\flowers.jpg'
    # Image directory
    #directory = 'src/main/res/drawable'
    # Using cv2.imread() method
    # to read the image

    img = cv2.imread(filename)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Filename
    gray = cv2.imwrite(filename, gray)
    # Using cv2.imwrite() method
    # Saving the image
    return gray
```

activity.xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:id="@+id/textView5"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text=""
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.591" />

    <ImageView
        android:id="@+id/imageView5"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:src="@drawable/flowers"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.192" />
```

MainActivity.java
```
package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;


import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

import com.chaquo.python.PyObject;
import com.chaquo.python.Python;
import com.chaquo.python.android.AndroidPlatform;

public class MainActivity extends AppCompatActivity {
    TextView textView;
    ImageView imageView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        if (! Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }
        Python py = Python.getInstance();
        PyObject pyobj = py.getModule("Image - Copy");
        PyObject obj = pyobj.callAttr("test");


        imageView = (ImageView) findViewById(R.id.imageView5);
        imageView.setImageResource(R.drawable.flowers);


    }
}
```

**Comment by mhsmith** [comment]
What do you mean, "it fails"? What happens?

If the app crashed, please post the full stack trace from the logcat.

**Comment by Vijju203** [comment]
Image.py
import numpy as np
import matplotlib.pyplot as plt
# importing cv2  
import cv2
from os.path import dirname, join
import io
from com.chaquo.python import Python
  
# importing os module   
import os 
def test():
    from os.path import dirname, join
    # Image path
    filename = join(dirname(__file__), 'Hydrangeas.jpg')
    if os.path.exists('Hydrangeas.jpg'):
        print("The file exists")
    else:
        print("The file does not exist")
    #image_path = r'F:\Projects\app\src\main\res\drawable\flowers.jpg'
    # Image directory
    #directory = 'src/main/res/drawable'
    # Using cv2.imread() method
    # to read the image

    img = cv2.imread(filename)
    img = img.tobytes()
  
    return img 

And MainActivity.java code is as below to convert bytes to Java bytes , but the decodebytearray is always null

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        if (! Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }



        Python py = Python.getInstance();
        PyObject pyobj = py.getModule("Image - Copy");
        byte[] obj = pyobj.callAttr("test"). toJava(byte[].class);
        if(obj == null && obj.length < 0)
            Log.e("TAG", "No file in Image ");
        else
            Log.e("TAG", "File Image exists");

//        String fname = Python.getPlatform().getFilesDir().getAbsolutePath()+"/myfile.png";
//        ImageView imageView = (ImageView) findViewById(R.id.imageView5);
//        Bitmap bm = BitmapFactory.decodeFile("F:/Projects/app/src/main/python/Hydrangeas.jpg");
//        imageView.setImageBitmap(obj);
//        byte[] frameData = obj.callAttr("bytes", obj).toJava(byte[].class);
//        ImageView image = new ImageView(this);
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inSampleSize = 2;

        Bitmap bitmap = BitmapFactory.decodeByteArray(obj, 0, obj.length,options);
        if(bitmap == null)
            Log.e("TAG", "Bitmap empty");
        else
            Log.e("TAG", "Bit not empty");

//        bitmap.compress(Bitmap.CompressFormat.PNG, 100, obj);
//        image.setImageBitmap(bitmap);
        ((ImageView) findViewById(R.id.imageView5)).setImageBitmap(bitmap);
}
}

Logcat:

2020-08-01 20:18:44.759 21890-21890/? E/libc: Access denied finding property "persist.vendor.sys.activitylog"
2020-08-01 20:18:50.315 21890-21890/com.example.myapplication E/TAG: File Image exists
2020-08-01 20:18:50.378 21890-21890/com.example.myapplication E/TAG: Bitmap empty
2020-08-01 20:18:53.996 21890-21936/com.example.myapplication E/ion: ioctl c0044901 failed with code -1: Invalid argument
2020-08-01 20:18:53.996 21890-21936/com.example.myapplication E/ion: ioctl c0044901 failed with code -1: Invalid argument

**Comment by mhsmith** [comment]
`decodeByteArray` expects an encoded image file, but your Python code is returning a raw bitmap array. See #288 for the solution.

**Comment by whf12345-hust** [comment]
> Image.py
> 
> ```
> import numpy as np
> import matplotlib.pyplot as plt
> ```
> 
> importing cv2
> 
> ```
> import cv2
> from os.path import dirname, join
> import io
> from com.chaquo.python import Python
> ```
> 
> importing os module
> 
> ```
> import os 
> def test():
>     from os.path import dirname, join
>     # Image path
>     filename = join(dirname(__file__), 'Hydrangeas.jpg')
>     if os.path.exists('Hydrangeas.jpg'):
>         print("The file exists")
>     else:
>         print("The file does not exist")
>     #image_path = r'F:\Projects\app\src\main\res\drawable\flowers.jpg'
>     # Image directory
>     #directory = 'src/main/res/drawable'
>     # Using cv2.imread() method
>     # to read the image
> 
>     img = cv2.imread(filename)
>     img = img.tobytes()
>   
>     return img 
> ```
> 
> And MainActivity.java code is as below to convert bytes to Java bytes , but the decodebytearray is always null
> 
> ```
> protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.activity_main);
>         if (! Python.isStarted()) {
>             Python.start(new AndroidPlatform(this));
>         }
> 
>         Python py = Python.getInstance();
>         PyObject pyobj = py.getModule("Image - Copy");
>         byte[] obj = pyobj.callAttr("test"). toJava(byte[].class);
>         if(obj == null && obj.length < 0)
>             Log.e("TAG", "No file in Image ");
>         else
>             Log.e("TAG", "File Image exists");
> 
> //        String fname = Python.getPlatform().getFilesDir().getAbsolutePath()+"/myfile.png";
> //        ImageView imageView = (ImageView) findViewById(R.id.imageView5);
> //        Bitmap bm = BitmapFactory.decodeFile("F:/Projects/app/src/main/python/Hydrangeas.jpg");
> //        imageView.setImageBitmap(obj);
> //        byte[] frameData = obj.callAttr("bytes", obj).toJava(byte[].class);
> //        ImageView image = new ImageView(this);
>         BitmapFactory.Options options = new BitmapFactory.Options();
>         options.inSampleSize = 2;
> 
>         Bitmap bitmap = BitmapFactory.decodeByteArray(obj, 0, obj.length,options);
>         if(bitmap == null)
>             Log.e("TAG", "Bitmap empty");
>         else
>             Log.e("TAG", "Bit not empty");
> 
> //        bitmap.compress(Bitmap.CompressFormat.PNG, 100, obj);
> //        image.setImageBitmap(bitmap);
>         ((ImageView) findViewById(R.id.imageView5)).setImageBitmap(bitmap);
> }
> }
> ```
> 
> Logcat:
> 
> ```
> 2020-08-01 20:18:44.759 21890-21890/? E/libc: Access denied finding property "persist.vendor.sys.activitylog"
> 2020-08-01 20:18:50.315 21890-21890/com.example.myapplication E/TAG: File Image exists
> 2020-08-01 20:18:50.378 21890-21890/com.example.myapplication E/TAG: Bitmap empty
> 2020-08-01 20:18:53.996 21890-21936/com.example.myapplication E/ion: ioctl c0044901 failed with code -1: Invalid argument
> 2020-08-01 20:18:53.996 21890-21936/com.example.myapplication E/ion: ioctl c0044901 failed with code -1: Invalid argument
> ```

hello，I have the same problem with you. Could you show me the code that solve the problem ??

**Comment by mhsmith** [comment]
See #288 for the solution.
