### ISSUE TITLE
Install local library

### ISSUE THREAD

**Issue by masoodkhademi** [chaquo/chaquopy#355]
Hi, How to install a library from the asstes?
Can you help me?

**Comment by mhsmith** [comment]
You can install most libraries using the instructions in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements).

If you want to do something different to that, please give details.

**Comment by masoodkhademi** [comment]
Ok, Thaks.
How I can use freely in closed source?

**Comment by mhsmith** [comment]
Please follow the instructions on [our website](https://chaquo.com/chaquopy/license/) to contact us about a license.
