### ISSUE TITLE
Gradle chquopy version in documentation's gradle setup instructions wrong

### ISSUE THREAD

**Issue by milselarch** [chaquo/chaquopy#357]
I got "Could not find com.chaquo.python:gradle:8.0.2." after configuring my android project for chaquopy as per [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#gradle-plugin). As far as I can tell the latest version is only  8.01, so the gradle config ought to be **classpath "com.chaquo.python:gradle:8.0.1"** instead of **classpath "com.chaquo.python:gradle:8.0.2"**

**Comment by mhsmith** [comment]
Sorry about that, it's now been fixed. Thanks very much for reporting it.
