### ISSUE TITLE
"Too many libraries" error may occur on API level 17 and older

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#36]
These versions of Android had a hard 128 item limit on the number of .so files that can be loaded per process, much of which may already have been consumed by the system (https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/aFJUYucfmFI).

This affects Python packages with many native modules, such as scikit-learn.

Since these versions now make up [less than 5% of Android users](https://developer.android.com/about/dashboards/index.html), we're unlikely to look into this.

**Comment by sarthaksharma058439** [comment]
Hey i found this video it helps me alot in install and import package in android studio with chaquopy , hopefully this will helps you 

https://youtu.be/BDmB3EFy0Qg

**Comment by mhsmith** [comment]
The next version of Chaquopy will have a minimum API level of 21.
