### ISSUE TITLE
support for matplotlib?

### ISSUE THREAD

**Issue by whf12345-hust** [chaquo/chaquopy#360]
hi, im trying to install matplotlib.is matplotlib available for chaquopy？

**Comment by mhsmith** [comment]
Yes, just follow the instructions in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements). If you have any specific problem then please give details.

**Comment by whf12345-hust** [comment]
> Yes, just follow the instructions in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements). If you have any specific problem then please give details.

a sincere thanks from China,buddy
