### ISSUE TITLE
Cannot use library Localization or shapely via pip install

### ISSUE THREAD

**Issue by naumanaejaz** [chaquo/chaquopy#363]
I am trying to add this library in my Android project (https://pypi.org/project/Localization/). It compiles but gives an error when importing the library:
```
    java.lang.RuntimeException: Unable to resume activity {com.vecna.human.agent/com.vecna.human.agent.app.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'shapely'
```
After seeing the error, I added `shapely` in the install section, it gave an error:
```
Failed to install shapely from https://files.pythonhosted.org/packages/44/ec/4eddbf9d17a917c51fb4ad159aa7137f506681e91ab559cf87d120e1d78d/Shapely-1.7.0.tar.gz.
```
Any ideas?

**Comment by mhsmith** [comment]
Thanks for the report, I'll look into it and get back to you later today

**Comment by mhsmith** [comment]
Shapely version 1.7.0 is now available.
