### ISSUE TITLE
Tensorflow Type Compatibility [Java vs Python][Android]

### ISSUE THREAD

**Issue by seounghanSong** [chaquo/chaquopy#368]
'''com.chaquo.python.PyException: TypeError: 'Tensor$Tensor_float32' object is not subscriptable'''

I've tried to carry the "Tensor_float32 class" type object to a python function in order to run the preprocessing the output Tensor from the DNN model for human face detection task.

But I thought I matched the type of required input, but the error message seems not.

I don't know what's the difference between those two,,

Do I have to do something to achieve this?

==============

Required Input Type (Python): 

![image](https://user-images.githubusercontent.com/26698511/91109747-d6c6a380-e6b6-11ea-89d2-e4cb0bf00363.png)

Carried Input Type (Java):

![image](https://user-images.githubusercontent.com/26698511/91109780-f231ae80-e6b6-11ea-9baf-961ad89533c2.png)

**Comment by mhsmith** [comment]
Please post the full stack trace, and the relevant sections of your code.

Also, the issue title says TensorFlow, but these code snippets refer to PyTorch. Are you using them both?

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and give the requested information.
