### ISSUE TITLE
Using chaquo on Android via AIDE

### ISSUE THREAD

**Issue by pj-mathematician** [chaquo/chaquopy#369]
I am making an app on [AIDE](https://play.google.com/store/apps/details?id=com.aide.ui) I followed the basic setup instructions present in the documentation, when i had to use buildPython, i had [pydroid3](https://play.google.com/store/apps/details?id=ru.iiec.pydroid3) on my phone installed, so i added the `sys.executable` path `(buildPython "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3")` now when i am trying to `import com.chaquo.python.*;` it says `Unknown type or package 'chaquo'`. How can i fix this?

My build.gradle-
```
apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'

android {
    compileSdkVersion 30
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.PjMathematician.ImgMath"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0.0"
		ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
		python{
			buildPython "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
		}
		
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
	implementation 'com.android.support:appcompat-v7:27.1.1'
	compile 'io.github.kexanie.library:MathView:0.0.6'
}
```
I got this error 
```
java.lang.RuntimeException: Unable to instantiate application com.chaquo.python.android.PyApplication: java.lang.ClassNotFoundException: Didn't find class "com.chaquo.python.android.PyApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.PjMathematician.ImgMath-eTW9eDHGnj9c7z5AkxylFw==/base.apk"],nativeLibraryDirectories=[/data/app/com.PjMathematician.ImgMath-eTW9eDHGnj9c7z5AkxylFw==/lib/arm64, /system/lib64]]
```
![Screenshot_20200829-131907](https://user-images.githubusercontent.com/55710610/91631831-4c55ab00-e9fa-11ea-800f-d942469dc98b.png)

**Comment by pj-mathematician** [comment]
I have created [this](https://github.com/pj-mathematician/ImgMath/tree/chaquotest) if you want to look at the other files

**Comment by mhsmith** [comment]
According to [this page](https://www.android-ide.com/tutorial_androidstudio.html):

> AIDE also supports basic Android Studio projects, which follow the default project structure. The full gradle build system is not yet supported though. 

Unfortunately Chaquopy does require the full Gradle build system, so I don't think you'll be able to build Chaquopy-based projects with AIDE. Sorry about that.

**Comment by pj-mathematician** [comment]
Oh okay its fine. Thanks!
