### ISSUE TITLE
Support for  installing Tensorflow?

### ISSUE THREAD

**Issue by jyl2010** [chaquo/chaquopy#37]
Even with the ndk supporting tensorflow, it would just be easier in some cases for python to use it

**Comment by mhsmith** [comment]
Thanks: Tensorflow isn't currently available for Chaquopy, but we'll add it if there's enough demand. If anyone else sees this issue and wants the same thing, please add a thumbs up.

**Comment by mhsmith** [comment]
Until TensorFlow is available, Keras with Theano may be an alternative. After installing them both, set the following environment variable before importing keras:
```
os.environ["KERAS_BACKEND"] = "theano"
```

If anyone has tried this, please let us know your experience.

**Comment by mhsmith** [comment]
TensorFlow 1.10.1 is now available for Chaquopy. If you have any problems with it, please report them as separate issues.

**Comment by mhsmith** [comment]
I should mention that this is for Python 3 only. We have no plans to provide TensorFlow (or any other future packages) for Python 2.

**Comment by sayan-sen** [comment]
Even after mentioning: 
` pip {     .....
                install "tensorflow==1.10.1"         }` in build.gradle(app) i get this error during build:

> Collecting tensorflow==1.10.1
>   Could not find a version that satisfies the requirement tensorflow==1.10.1 (from versions: 2.1.0)
> No matching distribution found for tensorflow==1.10.1
> Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
TensorFlow 1.10.1 is only available for the previous version of Chaquopy (6.3.0). For Chaquopy version 7 and later, use TensorFlow 2.1.0.

**Comment by sayan-sen** [comment]
yeah @mhsmith but can you please look at this issue https://github.com/chaquo/chaquopy/issues/282
