### ISSUE TITLE
How/Can run XXX.py  at  python console  ?

### ISSUE THREAD

**Issue by CMingTseng** [chaquo/chaquopy#372]
Dear Sir

for my case  i want use python console to run XXX.py 

to  download file 

now i try put xxx.py into app path 

when i try to find path at python 

i use 

___

import os

print(OS.getcwd)

i only get  "/" 

try  use 

os.listdir()

i get 

Permission denied 

i  want know path  let me push /put my *.py into 

THX

**Comment by mhsmith** [comment]
I assume you're using the Python console activity from one of the demo apps. The easiest way to add a Python file to one of those apps is just to put it in the app/src/main/python directory, and rebuild and install the app. Then, assuming the file is called `xxx.py`, you can just type `import xxx`.

**Comment by CMingTseng** [comment]
> I assume you're using the Python console activity from one of the demo apps. The easiest way to add a Python file to one of those apps is just to put it in the app/src/main/python directory, and rebuild and install the app. Then, assuming the file is called `xxx.py`, you can just type `import xxx`.
Dear Sir

very thx

can tell me  

if i put *.py file into   app/src/main/python 

the app running , the *.py  unzip to  where ?

because  i want know real path  to get  *.py processing  log *.txt file 

THX

**Comment by CMingTseng** [comment]
Dear Sir

from  Chaquopy demo  

https://github.com/chaquo/chaquopy

& 

chaquopy-console

https://github.com/chaquo/chaquopy-console

i know  that 

if i want run  "demo.py" at python console

i must put  "demo.py" into python folder  

and then  rebuild and install the app

but now i have  "demo2.py "

i can put where  ? direct run ? not   rebuild 

THX

**Comment by mhsmith** [comment]
For performance reasons, the .py files built into your app are not unzipped into separate files at runtime. However, you can still access any data files included in your source code by using `__file__`, as described in #144.

You shouldn't create any files in this location at runtime, because it may be erased when the app is reinstalled. Instead, you should create files in `os.environ["HOME"]`, which will point to your app's private files directory (`Context.getFilesDir()`). If your app is debuggable, you can also upload files to this directory using the Device File Explorer window in Android Studio.

**Comment by CMingTseng** [comment]
> For performance reasons, the .py files built into your app are not unzipped into separate files at runtime. However, any data files included in your source code are unzipped, and can be found relative to `__file__` as described in #144.
> 
> You shouldn't create any files in this location at runtime, because it may be erased when the app is reinstalled. Instead, you should create files in `os.environ["HOME"]`, which will point to your app's private files directory (`Context.getFilesDir()`). If your app is debuggable, you can also upload files to this directory using the Device File Explorer window in Android Studio.
Dear Sir

sorry for my English &  my knowledge 

i  follow you say 

i can get  os.environ["HOME"] at 

ReplActivity 

or

repl.py

but when i try use 

`exec(code(filename.py).read()) `

i get error

i try add full path 

/data/user/0/com.chaquo.python.demo3/files

i get the same error

the error is 

File "<console>" ,line 1 in <module> FileNotFoundError

the console is  src/main/python/chaquopy/utils/console.py  ? 

the module is ?

https://i.imgur.com/waiMQdx.png


PS. the open repl.py  is new file  is "hello world" <--- just  not re-name filename

THX
THX

**Comment by mhsmith** [comment]
Did you actually create the filename you passed to `open`? You would have to copy it to the device or emulator with the [Device File Explorer](https://developer.android.com/studio/debug/device-file-explorer).

Your English is fine, but spreading

your posts

across multiple lines

like this

is hard to read.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and provide details.
