### ISSUE TITLE
ERROR: Failed to install libmr while installing pip install evm package

### ISSUE THREAD

**Issue by vaibhavkulk** [chaquo/chaquopy#377]
Hello I am trying use evm package in android  but I am getting following error Please guide me for the same ASAP.

Collecting evm
  Using cached https://files.pythonhosted.org/packages/a5/ee/187044f9158fcfd4cf808a5ca58115a987f79228b76bf230e1abac0c2636/EVM-0.1.2.zip
Collecting chaquopy-openblas>=0.2.20 (from numpy)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-openblas/chaquopy_openblas-0.2.20-5-py3-none-android_21_arm64_v8a.whl
Collecting libmr>=0.1.8 (from evm)
  Using cached https://files.pythonhosted.org/packages/f3/48/f9d43abb742cbebec15933a052042da84d682da2142e803a0c1fa4524210/libmr-0.1.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\111808\AppData\Local\Temp\pip-install-zbh4rtuf\libmr\setup.py", line 3, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\111808\AppData\Local\Temp\pip-install-zbh4rtuf\libmr\
ERROR: Failed to install libmr>=0.1.8 from https://files.pythonhosted.org/packages/f3/48/f9d43abb742cbebec15933a052042da84d682da2142e803a0c1fa4524210/libmr-0.1.9.zip (from evm).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
Failed to install libmr>=0.1.8 from https://files.pythonhosted.org/packages/f3/48/f9d43abb742cbebec15933a052042da84d682da2142e803a0c1fa4524210/libmr-0.1.9.zip (from evm).

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

**Comment by vaibhavkulk** [comment]
Please add it as soon as possible.
evm package and its dependencies (for ex: libmr)

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
It's been over 3 years, and only 2 people have requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
