### ISSUE TITLE
showing black screen after calling python script in activity using callattr function

### ISSUE THREAD

**Issue by MiteshGabani** [chaquo/chaquopy#378]

**Comment by mhsmith** [comment]
You'll have to provide more information in order for me to help you.  For example, did you get a dialog saying the app had crashed? Is there a stack trace in the [Logcat](https://developer.android.com/studio/debug/am-logcat.html)?

Or does your Python script take a long time to run? In that case, you'll have to run it on a background thread, not on the [UI thread](https://developer.android.com/guide/components/processes-and-threads#Threads).

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and provide the requested information.
