### ISSUE TITLE
How to capture an image in background with python and upload it to the server ?

### ISSUE THREAD

**Issue by Unicas** [chaquo/chaquopy#379]
Hi guys and I am looking for something capturing the image in background with python and upload it to the server in android. I tried this with cv2 but it failed and capturing the image with Java does not work on some of the devices. Any idea to do that. Thanks in advance

**Comment by mhsmith** [comment]
Capturing the image in Java is much more likely to work. If you're having trouble with that, then please seek assistance in a general Android forum such as StackOverflow.
