### ISSUE TITLE
Please add nagisa

### ISSUE THREAD

**Issue by Taverz** [chaquo/chaquopy#381]
install "nagisa"
 install "pykakasi"
 install "jamdict"

**Comment by mhsmith** [comment]
nagisa isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

pykakasi and jamdict appear to be pure-Python packages, so they should work fine. If you had problems with them, please give details.

**Comment by Taverz** [comment]
can i download and add a package instead of downloading?

**Comment by mhsmith** [comment]
If you mean "can I download a copy of nagisa from PyPI and copy it into my app", then the answer is no, because it won't be an Android-compatible build. The same is true of nagisa's requirement, DyNet.

**Comment by mhsmith** [comment]
It's been more than a year and only one person has requested this package, so we won't be adding it in the foreseeable future. If anyone else is interested, please post a comment and I'll reopen the issue.
