### ISSUE TITLE
 How to Get path from URI and pass it as an argument to a python script 

### ISSUE THREAD

**Issue by Thaslim** [chaquo/chaquopy#383]
Hi, I am trying to build an app in which the user can select an audio file from the device and the app can classify the audio type. I am using python modules for preprocessing and Machine learning model. 
The python script needs the file path for processing and prediction.
I am getting the following error when passing the filepath received from uri.getpath() to the python script
Please help how to pass the filepath to the python script

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/audioFiles/186_3b3_Tc_mc_AKGC417L_3.wav flg=0x1 }} to activity {com.cmpe.healthcareai/com.cmpe.healthcareai.RespiratoryActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/document/raw:/storage/emulated/0/Download/audioFiles/186_3b3_Tc_mc_AKGC417L_3.wav'
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)

**Comment by mhsmith** [comment]
This is the same problem as #384, so let's keep the discussion there.
