### ISSUE TITLE
     Caused by: com.chaquo.python.PyException: OSError: [Errno 14] Bad address: '/storage/emulated/0/Download/audioFiles/104_1b1_Al_sc_Litt3200.wav'

### ISSUE THREAD

**Issue by Thaslim** [chaquo/chaquopy#384]
Hi I am trying to get a file path using URI and pass it to my python script. 

![image](https://user-images.githubusercontent.com/3530663/95670694-5d3e2400-0b43-11eb-97a7-661ed1e4dbf1.png)

featureExtraction is the python script. And I am calling the build_feat function which takes the selected audio path as argument. I am getting error  in that line. Please help.

![image](https://user-images.githubusercontent.com/3530663/95670717-b27a3580-0b43-11eb-8c44-4b76f38b8b9b.png)
This is the snippet of python script

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/339#issuecomment-658151563.

**Comment by Thaslim** [comment]
I saw the issue 339, It seems like they are getting permission denied error. (I also added permission settings in my code) But I am getting an OSError. BadAddress

**Comment by Thaslim** [comment]
Error is resolved after changing CompileSDKVersion and targetSDK Version to 28. I latest version has some issue

**Comment by mhsmith** [comment]
Thanks: this was probably caused by the new scoped storage limitations. Once I've had a chance to learn about this, I'll add some recommendations to #38.
