### ISSUE TITLE
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'googletrans'

### ISSUE THREAD

**Issue by Supermonu** [chaquo/chaquopy#385]
I am getting below error while running script "from googletrans import Translator" in python console.

`com.chaquo.python.PyException: ModuleNotFoundError: No module named 'googletrans'`
I am using chaquopy android python plugin. I have a sample program which use the googletrans parser so I have to use "from googletrans import Translator" in my python script. my application is crashing because it is not able to find the module "googletrans " error.

**Comment by mhsmith** [comment]
You'll have to install the googletrans packge into your app: see [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements) for instructions.
