### ISSUE TITLE
add cvxopt 

### ISSUE THREAD

**Issue by audvi** [chaquo/chaquopy#388]
Hello, 
My app uses a library which uses cvxopt, but I cannot install it because Chaquopy says "error: CCompiler.compile: Chaquopy cannot compile native code".
Would it be possible to make it work ? 
Thank you !

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

**Comment by audvi** [comment]
Hello,
Thank you for your answer.
Is there a way to make this package have more priority, or a way to adapt it myself ?
Have a nice day,


[cid:image003.png@01D6A78B.A0C0A200]

Audrey VIDAL
DSYS/SSCE/LSSC

Commissariat à l’énergie atomique et aux énergies alternatives
MINATEC Campus | 17 rue des martyrs | F-38054 Grenoble Cedex
T. +33 (0)4 38 78 09 18
audrey.vidal@cea.fr<mailto:audrey.vidal@cea.fr>



De : Malcolm Smith <notifications@github.com>
Envoyé : vendredi 16 octobre 2020 15:40
À : chaquo/chaquopy <chaquopy@noreply.github.com>
Cc : VIDAL Audrey 212854 <audrey.vidal@cea.fr>; Author <author@noreply.github.com>
Objet : Re: [chaquo/chaquopy] add cvxopt (#388)


Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

**Comment by mhsmith** [comment]
We might be able to build it in exchange for a payment. If you'd be interested in this, please [email us](https://chaquo.com/chaquopy/contact/) with the following information:

* Which version of the library you would like.
* Which [`abiFilters`](https://chaquo.com/chaquopy/doc/current/android.html#abi-selection) you're using in your app.
* If possible, some example code showing how you're planning to use the library.

**Comment by mhsmith** [comment]
cvxopt version 1.2.5 is now available. 

As we discussed over email, there are some problems with the x86 build which cause it to throw ArithmeticError, or simply return incorrect results. Some of these problems can be worked around by setting `cvxopt.cholmod.options["supernodal"] = 0`, which we do by default, but the x86 build should still be viewed as unreliable.

All other ABIs (armeabi-v7a, arm64-v8a and x86_64) work fine as far as I can tell.
