### ISSUE TITLE
Stopped

### ISSUE THREAD

**Issue by juseniah** [chaquo/chaquopy#393]
Learning the ropes of Chaquopy. Everything is going fine except that I get a "[app] has stopped" error in my emulator when I run it. My code is public at https://github.com/juseniah/ChaquopyTest/. 

Can anyone advise?

**Comment by mhsmith** [comment]
You can see the full error message in the [Logcat](https://developer.android.com/studio/debug/am-logcat.html).

In this case, the error is `ModuleNotFoundError: No module named 'script.py'`. 

When calling `getModule`, you should pass the name of the module exactly as it would appear in an `import` statement, with no `.py` suffix.
