### ISSUE TITLE
Failed to install gensim

### ISSUE THREAD

**Issue by SnehalSK2001** [chaquo/chaquopy#396]
:app:generateDebugPythonRequirements
Failed to install gensim from https://files.pythonhosted.org/packages/a0/b4/f4e45875a4cb1c4f6a76d6d07a2981753aab5f135dac2381f625e8807542/gensim-3.8.3.tar.gz.
Process 'command 'C:/Users/karan/AppData/Local/Programs/Python/Python37-32/python.exe'' finished with non-zero exit value 1
![error](https://user-images.githubusercontent.com/55588024/98500716-3292d880-2273-11eb-81b1-7b1e28659fe7.jpg)

**Comment by mhsmith** [comment]
gensim version 3.8.3 is now available.

**Comment by SnehalSK2001** [comment]
Okay, Thank you for your assistance.
