### ISSUE TITLE
Build python error

### ISSUE THREAD

**Issue by Manavjain25** [chaquo/chaquopy#399]
Hey , I am getting an error - No signature of method: build_2y9jex6zynqwuovvyp05096wt.android() is applicable for argument types: (build_2y9jex6zynqwuovvyp05096wt$_run_closure1) values: [build_2y9jex6zynqwuovvyp05096wt$_run_closure1@5a340d39]
My code :-
```
 sourceSets{
            main{
                python{
                    srcDirs = ["src/main/python"]
                }
            }
        }

        python{
              buildPython "C:\\Users\\Python39\\python.exe"  // this is the location where I have my python.exe file
              buildPython "python3"
        }
        ndk{
            abiFilters "armeabi-v7a","x86"
        }
```

Pls help !

**Comment by mhsmith** [comment]
As shown in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html), the `python` and `ndk` blocks should be inside the `defaultConfig` block.

**Comment by Manavjain25** [comment]
@mhsmith  , Actually I didn't post the whole code . This is the whole code .

defaultConfig {
        applicationId "com.example.helloworld"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        sourceSets{
            main{
                python{
                    srcDirs = ["src/main/python"]
                }
            }
        }

        python{
              buildPython "C:\\Users\\Python39\\python.exe"
              buildPython "python3"
        }
        ndk{
            abiFilters "armeabi-v7a","x86"
        }

    }

**Comment by mhsmith** [comment]
As shown in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#source-code), the `sourceSets` block should *not* be within `defaultConfig`.

But `src/main/python` is already the default directory, so you don't actually need the `sourceSets` block at all. Just delete it.

If that still doesn't work, make sure you've [applied the Chaquopy plugin](https://chaquo.com/chaquopy/doc/current/android.html#gradle-plugin) correctly.

**Comment by Manavjain25** [comment]
@mhsmith  thanks a lot
