### ISSUE TITLE
Failed to install RPi.GPIO package

### ISSUE THREAD

**Issue by bharat8** [chaquo/chaquopy#402]
RPi.GPIO package can't be installed when developing the app. The command finished with non-zero exit value 1.
Please suggest some workarounds.

**Comment by mhsmith** [comment]
This package is specifically for the Raspberry Pi, so I don't think it could ever work on Android, unless you're using a heavily-modified device.

**Comment by bharat8** [comment]
Yeah, Actually I was running android on raspberry pi and cant able to access GPIO on android via python. Can you suggest some workaround of accessing GPIO in android?

**Comment by mhsmith** [comment]
OK, we could build the packages for you for $75. However, you would need to make sure your device is configured to allow access to the necessary special files. I'm not familiar with Android on Raspberry Pi, so I don't know how difficult this would be.

If you'd like to proceed with this, please [email us](https://chaquo.com/chaquopy/contact/) to arrange payment.

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be adding it in the foreseeable future. If anyone else is interested, please click the thumbs-up button above and post a comment, and I'll reopen the issue.

**Comment by plabon5150** [comment]
I need this package. can you please assist with this matter? it says  can't install

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add it to the public repository.

**Comment by mhsmith** [comment]
Actually, we probably wouldn't add this to the public repository, because it isn't possible to test on a normal Android device or emulator. But you're still free to build it yourself by following the instructions above.
