### ISSUE TITLE
Minimizing app size

### ISSUE THREAD

**Issue by KacemRostom** [chaquo/chaquopy#404]
Hello,

After importing Chaquopy into my app to use the specific function of Griddata, i ended up having an app size of about 50mb up from just less than 1mb which is huge for a simple app. 

Is there a way i can only keep the Griddata scipy function and getting rid of the rest of framework in order to save unnecessary used space.

Thanks in advance.

**Comment by mhsmith** [comment]
Not really, but you can reduce the size of your app by removing unnecessary ABIs, as described in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#abi-selection).
