### ISSUE TITLE
App takes lots of time to start the chaquopy 

### ISSUE THREAD

**Issue by aswathy-mbl-test** [chaquo/chaquopy#407]
I am using Chaquopy on my android application that accesses the SQLite DB data and does some calculations with that. But it takes lots of time to start the Chaquopy plugin. I mean it takes almost 1minute to show the license related message. But it works fine on some of the devices. May I know any hint?

**Comment by mhsmith** [comment]
Do you mean it's slow to start on some devices and fast on others? If so, which devices are slow and which ones are fast?

Could you be doing anything else which would make your app unresponsive during startup? For example, if you start Python and then immediately call a long-running function on the main thread, then nothing will update in the user interface until the function returns, including the license message. It's better to call such functions on a background thread.

**Comment by aswathy-mbl-test** [comment]
yes, it's working fine on Moto and redmi devices but slowness is on One plus device. And I am doing python codes inside an AsyncTask to run that in the background and that python script accessing the data from the application's SQLite database. The application just shows the result returned from python, which is written inside the onPostExecute file.

Also, the app crashing in between the python execution with the below error. This is happening on all devices but very rarely.

2020-12-08 19:53:14.116 17303-17438/com.ust.step_count_directions A/libc: /home/smith/git/chaquo/python/server/pypi/packages/chaquopy-llvm/build/8.0.0/py3-none-android_21_arm64_v8a/src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp:402: void llvm::RuntimeDyldELF::resolveAArch64Relocation(const llvm::SectionEntry &, uint64_t, uint64_t, uint32_t, int64_t): assertion "static_cast<int64_t>(Result) >= INT32_MIN && static_cast<int64_t>(Result) <= UINT32_MAX" failed
2020-12-08 19:53:14.116 17303-17438/com.ust.step_count_directions A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 17438 (AsyncTask #7), pid 17303 (ount_directions)

**Comment by mhsmith** [comment]
OK, if you can work out a way of reproducing the crash, please create a separate issue and include the relevant parts of your code.

> it's working fine on Moto and redmi devices but slowness is on One plus device

What devices exactly, and how long does it take on each one?

Please make sure you're using the [current version of Chaquopy](https://chaquo.com/chaquopy/doc/current/changelog.html), as there have been some performance improvements recently.

If you add some [Logcat](https://developer.android.com/studio/debug/am-logcat.html) calls to your app, you should find that actually starting Python only takes a few seconds at most. If you then import a large number of Python modules (directly or indirectly), that may cause an additional delay, especially the first time you run the app on a device. However, it should be faster the second and subsequent times.

You can probably track down which module is taking the most time by adding some print statements in between the import statements, and then checking the timestamps in the Logcat. If one of them seems unreasonably slow, please give details.

**Comment by mhsmith** [comment]
If this is still a problem, please answer the questions above.
