### ISSUE TITLE
OpenCV upgrade

### ISSUE THREAD

**Issue by gushenjie** [chaquo/chaquopy#409]
can you upgrade version,i need use opencv-contrib-python 4.4.0.46,thank you

**Comment by mhsmith** [comment]
Can you provide some example code and explain why it needs the new version?

**Comment by mhsmith** [comment]
If anyone else needs a newer version of OpenCV, please click the thumbs-up button above, and post a comment explaining why you need the new version.

**Comment by Maxwell2Gyamfi** [comment]
For YOLOV4 support
Thanks

**Comment by mhsmith** [comment]
OpenCV version 4.5.1.48 is now available. To upgrade your app, edit your build.gradle file to specify the new version, as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements).

**Comment by Maxwell2Gyamfi** [comment]
Hi @mhsmith , I've just installed it.
Can't thank you enough !
