### ISSUE TITLE
Does twilio can be install in chaquopy?

### ISSUE THREAD

**Issue by largolowell** [chaquo/chaquopy#410]

**Comment by mhsmith** [comment]
Yes, just follow the instructions in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#requirements). If you had any problems then please give details.

**Comment by lowelldavelargo** [comment]
can i ask sir what to put in the install area??
        python{
            pip{
                install ""
            }

**Comment by mhsmith** [comment]
"twilio"

**Comment by lowelldavelargo** [comment]
it will error sir if i use android studio. if just on python it is ok. can you help me sir? i already install it in chaquopy

**Comment by mhsmith** [comment]
What error?

**Comment by lowelldavelargo** [comment]
the app will close sir i used this code in python

from twilio.rest import Client

    account_sid = "########"
    auth_token = "#########"
    client = Client(account_sid, auth_token)

    client.messages \
                    .create(
                            body="Your Score is: ",
                            from_='#######',
                            to='########'
                     )

it will work if just on python if i integrate it in android studio it will error.

**Comment by lowelldavelargo** [comment]
or do i still need to install the client? i only just install twilio in chaquopy

**Comment by mhsmith** [comment]
The details of the error will be in the [Logcat](https://developer.android.com/studio/debug/am-logcat.html).

If your app accesses the internet, you'll need to include the [INTERNET permission](https://stackoverflow.com/questions/2378607).

**Comment by lowelldavelargo** [comment]
Good afternoon sir

i would like to subscribe a license, how much is for the
commercial  license?

**Comment by mhsmith** [comment]
I've sent you the details by email.

**Comment by lowelldavelargo** [comment]
Thank you so much sir, it fix the error

**Comment by lowelldavelargo** [comment]
i did what you told, i include the internet permission. you are a life saver thank you so much
