### ISSUE TITLE
Requests does connect to server directly without using proxy

### ISSUE THREAD

**Issue by mrklintscher** [chaquo/chaquopy#412]
proxies={'http': 'http://rockit5:rockit5@gate.dc.smartproxy.com:20000'}
r = requests.get('http://icanhazip.com', headers={'User-Agent': '?'}, proxies=proxies)
print (r.text)

**Comment by mhsmith** [comment]
Do you mean it's printing your own IP address? I ran this with requests version 2.25.1 on an API level 30 emulator, and it returned a different IP address every time, but none of them were my own.

**Comment by mrklintscher** [comment]
Okay then i do something wrong. You can Close. Thank you.

Malcolm Smith <notifications@github.com> schrieb am Fr., 18. Dez. 2020,
17:01:
