### ISSUE TITLE
cannot install textacy because of requirement "pyemd>=0.5.0"

### ISSUE THREAD

**Issue by sukrutsathaye** [chaquo/chaquopy#415]
I tried installing textacy faced the following issue.

error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
  Command "C:\Users\sukru\AppData\Local\Programs\Python\Python37\python.exe -u -S -c "import setuptools, tokenize;__file__='C:\\Users\\sukru\\AppData\\Local\\Temp\\pip-install-hnh7w9ag\\pyemd\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\sukru\AppData\Local\Temp\pip-wheel-fj_thkne --python-tag py3" failed with error code 1 in C:\Users\sukru\AppData\Local\Temp\pip-install-hnh7w9ag\pyemd\
ERROR: Failed to install pyemd>=0.5.0 from https://files.pythonhosted.org/packages/c0/c5/7fea8e7a71cd026b30ed3c40e4c5ea13a173e28f8855da17e25271e8f545/pyemd-0.5.1.tar.gz (from textacy).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
It's been nearly 3 years, and only 2 people have requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
