### ISSUE TITLE
PyQt5 was not availaible

### ISSUE THREAD

**Issue by priyansh17** [chaquo/chaquopy#418]
Failed to install PyQt5 from https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz.

code used:
python {
            pip {
                install "PyQt5"
            }
}

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

In general I recommend people to use the standard Android user interface toolkit with Chaquopy. [Here's](https://github.com/chaquo/chaquopy-matplotlib) a simple example of that, and [here's](https://www.youtube.com/watch?v=X0JNxGay7JY) a video where I discuss the example in detail.

However, if you really want to use PyQt5, have a look at the pyqtdeploy project.

**Comment by priyansh17** [comment]
I wanted to use some packages which are not listed on chaqoupy yet. 
Is there any other way in which I can bypass the pip install either by directly pasting package files somewhere in folder. 
Could you please help me with this?

**Comment by mhsmith** [comment]
Which packages?

**Comment by mhsmith** [comment]
Chaquopy is unlikely ever to support PyQt5. For advice, please see my comments above.
