### ISSUE TITLE
LivePopularTimes from PyPi is not available

### ISSUE THREAD

**Issue by Welazhari** [chaquo/chaquopy#419]
Hello, 

I need  the "LivePopularTimes" library from PyPi for an android studio  project but  obviously its not available.
 
When i try this (build.gradle:app)  : 
     

 python{
            pip{

                install "LivePopularTimes"

            }
        }

i have the following error message  : 

Process 'command 'python'' finished with non-zero exit value 1

To view full details in Android Studio:
* In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
* In version 3.5 and older, click the 'Toggle view' button to the left of this message.
* Then scroll up to see the full output.

However, I have no probleme with others libraries like "numpy" "lxml

Wassim,

**Comment by mhsmith** [comment]
The current version of LivePopularTimes (1.1) has incorrectly listed some standard library modules in its requirements, so it can't be installed on any OS. Try installing `LivePopularTimes==1.0` instead.
