### ISSUE TITLE
Nltk .download() failed

### ISSUE THREAD

**Issue by utkarsh2211** [chaquo/chaquopy#42]
Hello ,
I am trying to develop an app on nltk and in a particular line I have to call nltk.download(). 
this function call is required for downloading necessary models which i could use later for creating nltk apps.
But since these models can't be installed through pip I have to make an explicit call to this function and the program fails at this point.
Any insight on this would be of great help

**Comment by mhsmith** [comment]
I've answered your [question on StackOverflow](https://stackoverflow.com/questions/50906501/what-directory-does-chaquopy-code-search-for-the-python-packages-which-are-impor/50907616#50907616). If you need any further help, please comment there.
