### ISSUE TITLE
Unable to install NLTK

### ISSUE THREAD

**Issue by priyansh17** [chaquo/chaquopy#420]
Command "python setup.py egg_info" failed with error code 1 in C:\Users\KIIT\AppData\Local\Temp\pip-install-o5inwfdl\nltk\
ERROR: Failed to install nltk>=3.1 from https://files.pythonhosted.org/packages/92/75/ce35194d8e3022203cca0d2f896dbb88689f9b3fce8e9f9cff942913519d/nltk-3.5.zip (from textblob).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install nltk>=3.1 from https://files.pythonhosted.org/packages/92/75/ce35194d8e3022203cca0d2f896dbb88689f9b3fce8e9f9cff942913519d/nltk-3.5.zip (from textblob).

Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
Does the full build log contain the error from #416? If so, you can work around it by using Python 3.8 as described in that issue.

**Comment by priyansh17** [comment]
It worked. Thank you so much. All I had to do was downgrade to python 3.8.6
