### ISSUE TITLE
Failed to install tokenizers==0.7.0 when install transformers==2.11.0 

### ISSUE THREAD

**Issue by DungLeMTA** [chaquo/chaquopy#422]
I am installing transformers into my project in Android Studio 
Chaquopy version 9.0

python{
            pip{
                install "pip==20.3.3"
                install "numpy"
                install "opencv-python"
                install "Pillow==7.0.0"
                install "tensorflow==2.1.0"
                install "transformers==2.11.0"
            }
        }

=> numpy, opencv-python, Pillow and tensorflow is successful until transformers, then I get this error:

File "C:\Users\Admin\AppData\Local\Temp\pip-install-d9ias2u3\tokenizers\setup.py", line 2, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
Failed to install tokenizers==0.7.0 from https://files.pythonhosted.org/packages/83/9e/7163dc8ea080e901d8b6c0c64eb3c0b3ffe27a820145448b64d24ca78b97/tokenizers-0.7.0.tar.gz (from transformers==2.11.0)

Someone help me, please!

**Comment by mhsmith** [comment]
We can probably provide the current versions, transformers==4.1.1 and tokenizers==0.9.4. Would those be OK for you? If not, please explain why.

**Comment by DungLeMTA** [comment]
I don't know the reason. When 'pip install transformers==4.1.1' ,  it is still 'Failed to install tokenizers==0.9.4 from ...'
![image](https://user-images.githubusercontent.com/69489506/104024165-43b98080-51f5-11eb-9007-101cc31b30ab.png)

**Comment by mhsmith** [comment]
Neither version is currently available. What I'm asking is, IF we provided the current versions, would that work for your app? Or is there some reason why you need transformers version 2.11.0 specifically?

**Comment by DungLeMTA** [comment]
Ah, I use 'transformers 2.11.0' in my project NLP. I use pretrained BERT and the minium required version of transformers is 2.11.0. 
It ran on PyCharm and I want to intergrate it with android studio

**Comment by mhsmith** [comment]
OK, I'll look into it and get back to you.

**Comment by mhsmith** [comment]
`tokenizers==0.7.0` is now available.
