### ISSUE TITLE
 Pmdarima  & clientserver package  issues 

### ISSUE THREAD

**Issue by ammatrls** [chaquo/chaquopy#424]
Hello 😊

I just discovered chaqoupy and I'm very happy that it is exists! But I have  issues with clientserver and pmdarima  it always field when I call pip install  , is that because the libraries don't exist in the repository!?

Thank you so much

**Comment by mhsmith** [comment]
What is "clientserver"? There's no package by that name on PyPI.

For pmdarima, see #425.

**Comment by ammatrls** [comment]
Hello Sir ,

Thank you for fast replying, I meant mysqlclient  package, but it's okay ,
I used PyMySQL instead of it . But I was trying for days for pmdarima or
pyramid-arima but always I got field error messages . Thank you so much
