### ISSUE TITLE
Import gdal 

### ISSUE THREAD

**Issue by MazahirRajabov** [chaquo/chaquopy#427]
pip {
                 install "numpy"
                install "utm"
                install "opencv-python"
                install "ogr"
                install "osgeo"
                install "GDAL==3.0.0"

            }

when i add gdal ,i get error;
  error: CCompiler.compile: Chaquopy cannot compile native code
Failed to install GDAL==3.0.0 from https://files.pythonhosted.org/packages/e7/12/c52764aa0e2e0aa9b2195956417844bbcd956f948b0823499778db958c8b/GDAL-3.0.0.tar.gz.
Process 'command 'python'' finished with non-zero exit value 1

Please can you help me?

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

**Comment by mhsmith** [comment]
It's been nearly a year and only one person has requested this package, so we won't be adding it in the foreseeable future. If anyone else is interested, please post a comment and I'll reopen the issue.

**Comment by tmrose** [comment]
Trying to use GDAL in a project. Thanks

**Comment by mhsmith** [comment]
OK, I'll reopen this issue for visibility. However, we're no longer adding new packages to Chaquopy's wheel repository, so you should either request Android support in the package's own issue tracker, or try to build it yourself. See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-pip) for instructions.
