### ISSUE TITLE
Unlicensed chaquopy notification lingers after app has closed

### ISSUE THREAD

**Issue by marceloneil** [chaquo/chaquopy#43]
The "unlicensed chaquopy" warning lingers around long after the app has been closed (by the 5 minute timer), and cleared from memory (swiped away). I guess there is still some process running, so the app needs to be force stopped for the notification to go away. This is the notification I'm talking about:
> ### Chaquopy <app name> tests
> This app was built with an unlicensed copy of Chaquopy. Public distribution is prohibited.

Maybe the 5 minute timer could force stop the app, or at least dismiss this persistent notification when the time is up? It's not a huge headache, but it's a bit irritating.

**Comment by mhsmith** [comment]
> Maybe the 5 minute timer could force stop the app

It already does, but I guess Android is attempting to give a sense of continuity by keeping the notification visible unless the process was force closed by user request.

> It's not a huge headache, but it's a bit irritating

Then I think we've got the balance about right. It is a nag screen after all. :smile:

**Comment by marceloneil** [comment]
> Then I think we've got the balance about right. It is a nag screen after all.

I'm less of a fan, mostly because I need to go to the App icon > App info > Force quit after each dev session, or i have an irritating persistent notification at the top of my stack.

**Comment by mhsmith** [comment]
Since your project has now agreed to buy a license, I'll send you a key to remove the warning and the time limit.

**Comment by tongjinlv** [comment]
Do I need to spend money to buy it?

**Comment by mhsmith** [comment]
It's free for open-source apps and paid for closed-source ones. For details, see https://chaquo.com/chaquopy/license/.

**Comment by tongjinlv** [comment]
I compiled into release   but is run  error  
error message：
lang.ClassNotFoundException: Didn't find class "com.chaquo.python.PyException" on path: DexPathList[[zip file "/data/app/com.matatalab.matatacode-9_fj_Bw-RN1FBE6tu42f0A==/base.apk"],nativeLibraryDirectories=[/data/app/com.matatalab.matatacode-9_fj_Bw-RN1FBE6tu42f0A==/lib/arm64, /data/app/com.matatalab.matatacode-9_fj_Bw-RN1FBE6tu42f0A==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

**Comment by tongjinlv** [comment]
How to force exit when python is running in a loop

**Comment by mhsmith** [comment]
See #58.

And please create separate issues for separate questions in future.
