### ISSUE TITLE
Error unused DT entry whenever wants to run chaquopy

### ISSUE THREAD

**Issue by Mrsydh** [chaquo/chaquopy#430]
**Hi, do you know why i got this logcat message whenver i want to run chaquopy and how do i solve this. This makes my app run really slow**

W/linker: _traversal.so: unused DT entry: type 0x6ffffffe arg 0x1500
    _traversal.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _min_spanning_tree.so: unused DT entry: type 0x6ffffffe arg 0x1df8
    _min_spanning_tree.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _flow.so: unused DT entry: type 0x6ffffffe arg 0x1f90
    _flow.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _matching.so: unused DT entry: type 0x6ffffffe arg 0x1de4
    _matching.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _reordering.so: unused DT entry: type 0x6ffffffe arg 0x2030
    _reordering.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: murmurhash.so: unused DT entry: type 0x6ffffffe arg 0x17f8
    murmurhash.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _bz2.so: unused DT entry: type 0x6ffffffe arg 0x1478
    _bz2.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _lzma.so: unused DT entry: type 0x6ffffffe arg 0x1de8
    _lzma.so: unused DT entry: type 0x6fffffff arg 0x1
W/python.stderr: /data/data/com.example.skin/files/chaquopy/AssetFinder/requirements/joblib/_multiprocessing_helpers.py:45: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
W/linker: ckdtree.so: unused DT entry: type 0x6ffffffe arg 0x2be0
    ckdtree.so: unused DT entry: type 0x6fffffff arg 0x3

**Comment by mhsmith** [comment]
I believe this message only affects devices with API level 22. It's not an error, only a harmless warning, and I don't think it will make any difference to the speed of your app.
