### ISSUE TITLE
Problems running chaquopy with android studio in real device

### ISSUE THREAD

**Issue by Mrsydh** [chaquo/chaquopy#431]
Hi, I have problems whenever I try to run sklearn through chaquopy in android studio. It works well with the emulator, but when I use real device, it keeps on crashing. The problem occurs when I try to run _estimator.fit_

      if hasThresholding == True:
        number_of_colors +=1
      
      img = image.copy()
      
      img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
      
      img = img.reshape((img.shape[0]*img.shape[1]) , 3)
      
      estimator = KMeans(n_clusters=number_of_colors, random_state=0)
    
      estimator.fit(img)  
    
      colorInformation = getColorInformation(estimator.labels_,estimator.cluster_centers_,hasThresholding)
      
      return colorInformation

**Comment by Mrsydh** [comment]
It gives these warnings too.


W/linker: _k_means_fast.so: unused DT entry: type 0x6ffffffe arg 0x2480
    _k_means_fast.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: _k_means_lloyd.so: unused DT entry: type 0x6ffffffe arg 0xcf30
    _k_means_lloyd.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _k_means_elkan.so: unused DT entry: type 0x6ffffffe arg 0xcf30
    _k_means_elkan.so: unused DT entry: type 0x6fffffff arg 0x1
W/linker: _hierarchical_fast.so: unused DT entry: type 0x6ffffffe arg 0x2214
    _hierarchical_fast.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: _fast_dict.so: unused DT entry: type 0x6ffffffe arg 0x2acc
    _fast_dict.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: _dbscan_inner.so: unused DT entry: type 0x6ffffffe arg 0x1898
    _dbscan_inner.so: unused DT entry: type 0x6fffffff arg 0x2

**Comment by mhsmith** [comment]
As I said in #430, the warnings are harmless. But please post the crash report from the [Logcat](https://developer.android.com/studio/debug/am-logcat.html), including the full stack trace.

Also, which device is this happening on?

**Comment by mhsmith** [comment]
If this is still a problem. please post the requested information and I'll reopen the issue.
