### ISSUE TITLE
Run a python script from a file

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#433]
I am new to chaquopy. I have worked with static code and it works. I am using Flutter Framework and calling the static code file through dart on kotlin side through method channel. Now, I want to take Input python code entered by user, save it in a file and run it from native side. I don't want to run a function only, but a whole script. how can I do it?

**Comment by mhsmith** [comment]
You can use the built-in [`exec`](https://docs.python.org/3/library/functions.html#exec) function. There's no need to actually write the code to a file, you can pass it as a string.

**Comment by jay9440** [comment]
@mhsmith Thank you for your response, your solution is the one I was looking for. I have another problem, How can I return output from the logs? I have tried below code and it prints object for correct output while for error it prints error String. I need to print output String for the to be printed on the screen. Here's my code. 

`fun _runPythonCode(code: String): String {
        val _python: Python = Python.getInstance()
        val _console: PyObject = _python.getModule("script")
        val _sys: PyObject = _python.getModule("sys")
        val _stdOut: PyObject? = _sys.get("stdout")
        val _stdErr: PyObject? = _sys.get("stderr")

        try {
            _console.callAttrThrows("main", code)
            return _stdOut.toString()
        } catch (e: Error) {
            return _stdErr.toString()
        }

    }`

**Comment by mhsmith** [comment]
The simplest way is to for your Python code to use [`contextlib.redirect_stdout`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) and `redirect_stderr`.

These are questions about general Python programming, which you could easily have answered with a Google or StackOverflow search. Please only use this issue tracker for questions about Chaquopy specifically.
