### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by taylorbriee** [chaquo/chaquopy#434]
after implementing all the dependencies and steps in the documentation I keep getting the error 

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.chaquo.python:gradle:9.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/chaquo/python/gradle/9.1.1/gradle-9.1.1.pom
       - https://jcenter.bintray.com/com/chaquo/python/gradle/9.1.1/gradle-9.1.1.pom
       - https://chaquo.com/maven/com/chaquo/python/gradle/9.1.1/gradle-9.1.1.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by mhsmith** [comment]
Sorry, the current version is actually 9.1.0. I'll correct the documentation right now.

**Comment by taylorbriee** [comment]
Thanks for the quick response, that worked.
