### ISSUE TITLE
Error when refrencing modules in the python file.

### ISSUE THREAD

**Issue by taylorbriee** [chaquo/chaquopy#436]
I get this error in android studio 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.smartrevisionschedule2, PID: 9945
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.smartrevisionschedule2/com.example.smartrevisionschedule2.subject_and_grades}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'pandas'

even though my build directory is referencing the correct location.
        python {
            buildPython "C:/Users/Taylor Brierley/.conda/envs/tensorflow/python.exe"
        }

**Comment by mhsmith** [comment]
You'll have to [build pandas into your app](https://chaquo.com/chaquopy/doc/current/android.html#requirements), along with any other Python libraries you use.

**Comment by taylorbriee** [comment]
ok, would this work with sklearn because that I what I am using it for?

**Comment by mhsmith** [comment]
Yes, but the pip package name is "scikit-learn".
