### ISSUE TITLE
Unable to locate file even when file is present.

### ISSUE THREAD

**Issue by taylorbriee** [chaquo/chaquopy#437]
I have checked the directory the python file is stored in and the csv file is present but I still get this error in android studio. 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.smartrevisionschedule2, PID: 10880
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.smartrevisionschedule2/com.example.smartrevisionschedule2.subject_and_grades}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] File b'final_dataset.csv' does not exist: b'final_dataset.csv'

**Comment by mhsmith** [comment]
See #144, and please search for existing issues before creating new ones.

**Comment by taylorbriee** [comment]
I was wondering if I could still use pandas to do this, rather than a different file handler?

**Comment by mhsmith** [comment]
You can generate the filename using the method in #144, then pass that filename to whatever function you like.

**Comment by taylorbriee** [comment]
ok, thanks I will try that.
