### ISSUE TITLE
Support for yolov4 opencv 4.4.0.40

### ISSUE THREAD

**Issue by Maxwell2Gyamfi** [chaquo/chaquopy#438]
Hi
I was wondering if there was a way to install opencv 4.4.0.40 in order to use yolov4?
Unfortunately yolov4 doesn't support anything less than 4.4.0.40.
I've tried installing with the "install" command however I get error "no module named skbuild". It seems that a way to fix this is to upgrade pup however it's not possible through chaquopy?

Currently the version available with the command install " opencv-python " and opencv-contrib is 4.1.2

Thanks in advance for your help

**Comment by mhsmith** [comment]
OK, I'll look into it. Please subscribe to #409 for updates.
