### ISSUE TITLE
saving pyplot graph in a file and opening it through flutter

### ISSUE THREAD

**Issue by jaydangar** [chaquo/chaquopy#440]
Greetings, I am using this awesome package for my IDE project. The Text data works great, but when it comes to image data it's throwing error. I am trying to use Matplotlib package and save its output in a file like following :[
```

import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.savefig("test.png")
```

it throws following error while saving the file. 

`Android Read-only file system: 'test.png', com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: 'test.png', null)`

Kindly let me know how can I save the output file in android??

**Comment by mhsmith** [comment]
You should save files in `os.environ["HOME"]`, which is set to your [app-specific files directory](https://developer.android.com/training/data-storage/app-specific). If your app is debuggable, you can also read and write this directory from Android Studio using the [Device File Explorer](https://developer.android.com/studio/debug/device-file-explorer).

**Comment by jaydangar** [comment]
@mhsmith I have resolved this problem by returning the bitmap, thanks for the response. no Need to save the image.
