### ISSUE TITLE
Is Chaquopy ready to use in production?

### ISSUE THREAD

**Issue by jaydangar** [chaquo/chaquopy#441]
According to [this](https://www.youtube.com/watch?v=rh2Ws5cCpMg) video, Chaquopy is not production ready. Can you elaborate more about the usecase in production and let me know how good it performs in terms of production use? is there any issue while using it in production?

**Comment by mhsmith** [comment]
Chaquopy has been production ready for years and has been used by hundreds of apps. 

That video was based on some misunderstandings, so I contacted its creator and we recorded another video together last month which should answer your questions. You can see it [here](https://www.youtube.com/watch?v=X0JNxGay7JY).

**Comment by jaydangar** [comment]
Thanks @mhsmith for your response. Kindly tell the creator to take it down. Thanks & Regards.

**Comment by mhsmith** [comment]
That's up to him, but thanks for leaving a comment on the video.
