### ISSUE TITLE
Unable to install wordcloud package

### ISSUE THREAD

**Issue by royaldevops** [chaquo/chaquopy#443]
error: CCompiler.compile: Chaquopy cannot compile native code

  Command "/usr/bin/python3.8 -u -S -c "import setuptools, tokenize;__file__='/tmp/pip-install-isqkyhz_/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nqd75ebf --python-tag py3" failed with error code 1 in /tmp/pip-install-isqkyhz_/wordcloud/
ERROR: Failed to install wordcloud==1.8.1 from https://files.pythonhosted.org/packages/be/33/5bdd39587f0e8ede3fe12d9d16d6f1fb5e7a43f29621604a949ee362d013/wordcloud-1.8.1.tar.gz

**Comment by mhsmith** [comment]
Wordcloud version 1.8.1 is now available.
