### ISSUE TITLE
Scipy Modules are missing.

### ISSUE THREAD

**Issue by fnc11** [chaquo/chaquopy#444]
I checked with the help of debugger and found that these libraries don't always contain all the modules. For instance, the scipy library doesn't contain stats and optimize module. Am I missing something, are they present and I was unable to found them, then please let me know.

**Comment by mhsmith** [comment]
Our SciPy builds contain both of those modules. Please explain exactly what you did and what happened.

**Comment by fnc11** [comment]
Dear @mhsmith I later found out the syntax is different, when my colleague experimented with some more syntax options. I would say the project chaquopy is great, but please give some more scientific examples in the documentation. The documentation around how to use your Java API is not that good.

**Comment by mhsmith** [comment]
If you can explain exactly what you were confused about, and give some examples, then I'll be happy to clarify it in the documentation.
