### ISSUE TITLE
chaquopy being transfed to a mobile app

### ISSUE THREAD

**Issue by taylorbriee** [chaquo/chaquopy#445]
I have chaquopy on an android emulator, in android studio referencing python on my pc in the Gradle build file, but let's say I wanted to use the app on my phone, would I have to transfer all the python libraries to a directory that can be referenced on the phone?

**Comment by mhsmith** [comment]
The only Python code visible to your app is [your own code](https://chaquo.com/chaquopy/doc/current/android.html#android-source) and any [pip requirements](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements) from build.gradle. These will work just as well on a phone as they do on an emulator, as long as you've included the [necessary ABIs](https://chaquo.com/chaquopy/doc/current/android.html#abi-selection).

The Python libraries on your PC have no effect on the app: they are not visible to it even in the emulator.

**Comment by taylorbriee** [comment]
ok, so I won't need to transfer any python code to my phone, I could basically just run the app on my phone normally and it would work?

**Comment by mhsmith** [comment]
Yes, if you've included the ARM ABIs, and it works on the emulator, then it should also work on the phone.
