### ISSUE TITLE
APK or AAB size

### ISSUE THREAD

**Issue by RipPennell** [chaquo/chaquopy#448]
Good day,

This is an amazing tool and was the only solution to making my application possible. I go to upload the app and Play Store says the max is 150mb. I look at my file, 600mb.

As the documentation said, I removed the ABIs except for one, but I am still at 230MB. My app has an 80mb tflite TensorFlow model, and if I build the app without installing any libraries, I can get the app down to 100MB. I need to however use TensorFlow to make a classification, but installing just the tensorflow library makes it 180 MB, meaning tensorflow itself is 80 MB. Is there anything further I can do to reduce the size? Using the android studio settings like minifyEnabled and ShrinkResources do nothing as is expected. I've tried to install the tensorflowLite library, which just has enough to run a trained tflite model, but that won't work.

Perhaps there is a way to do the pip install after the app is deployed to the device? Or a way to go through the installed libraries and cut out the ones that aren't being used? Or a way to do compression that would also impact the python libraries?

Play Asset Delivery might be the solution...

Build gradle below:

plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "rip.thesis.automatedspokenlanguagedetector"
        minSdkVersion 24
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        sourceSets {
            main {
                python.srcDir "src/main/python"
            }
        }
        python {
            //buildPython "C:/Users/Rip/anaconda3/python.exe"
            pip {
                install "numpy"
                install "librosa"
                install "tensorflow"
            }
        }
        ndk {
            abiFilters "armeabi-v7a"//, "arm64-v8a", "x86", "x86_64"
//            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.navigation:navigation-fragment:2.3.3'
    implementation 'androidx.navigation:navigation-ui:2.3.3'
    implementation 'com.arthenica:mobile-ffmpeg-full:4.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

**Comment by mhsmith** [comment]
Unfortunately the full TensorFlow package is very large. We may provide a Python build of TensorFlow Lite in the future: please subscribe to #332 for updates.

Meanwhile, since your model is already tflite-compatible, your best option is probably to use the [official Android TensorFlow Lite packages](https://www.tensorflow.org/lite/guide/android). You can either use it directly from Java/Kotlin code, or from Python using the [Chaquopy Python API](https://chaquo.com/chaquopy/doc/current/python.html).

**Comment by RipPennell** [comment]
I was able to break the model away from the package using https://developer.android.com/guide/app-bundle/asset-delivery/build-native-java. I wasn't able to figure out a way to get the installs to be put into the assets folder in another directory (directory at the same level as "app"), but perhaps this is something that could be looked at?

I got really lucky and my installs brought my app to 149MB, with my model being treated as an install at setup

Thank you for all your work! This is an amazing tool!!

**Comment by RipPennell** [comment]
I found out you can actually port all the libraries and files you'll want python to access to the asset directory by adding a "../" before the src Dir:

python.srcDir "../modelasset/src/main/assets/python"

No one should have any size issues now!

**Comment by mhsmith** [comment]
Great, thanks for letting me know.

**Comment by mhsmith** [comment]
But I'm not sure about your last point. If you pass a directory to python.srcDir, then it'll be included in the base APK, so that won't help you get under the 150 MB limit.

**Comment by RipPennell** [comment]
I've included some code snippets that shows how the Play Asset Delivery, set to "install-time" allows you to use "expansion" data that is available immediately upon launch. Since it normally requires you to use asset manager to access these resources, the solution (kind of non-elegant) is to copy all of the assets into an internal directory, which allows you to treat everything as if it was in the base APK. The con of this is that you are effectively doubling the size of the app on the phone.

modelasset build.gradle

```
// In the asset pack’s build.gradle file:
apply plugin: 'com.android.asset-pack'

assetPack {
    packName = "modelasset" // Directory name for the asset pack
    dynamicDelivery {
        deliveryType = "install-time"
    }
}
```

make internal repo

```
        String dirPath = getFilesDir().getAbsolutePath() + "/oneTimeTestDatabase";
        File projDir = new File(dirPath);
        if (!projDir.exists())
            projDir.mkdirs();
```

copy assets to internal repo (from here https://stackoverflow.com/a/4530294) 

```
        AssetManager assetManager = getAssets();
        String[] files = null;
        try {
            files = assetManager.list("");
        } catch (IOException e) {
            e.printStackTrace();
        }
        if (files != null) for (String filename : files) {
            InputStream in = null;
            OutputStream out = null;
            try {
                in = assetManager.open(filename);
                File outFile = new File(dirPath, filename);
                out = new FileOutputStream(outFile);
                copyFile(in, out);
            } catch(IOException e) {
                e.printStackTrace();
            }
            finally {
                if (in != null) {
                    try {
                        in.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                if (out != null) {
                    try {
                        out.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
        }
```

```
    private void copyFile(InputStream in, OutputStream out) throws IOException {
        byte[] buffer = new byte[1024];
        int read;
        while((read = in.read(buffer)) != -1){
            out.write(buffer, 0, read);
        }
    }
```

**Comment by mhsmith** [comment]
OK thanks, this all looks like standard Android asset handling which has nothing to do with your Python source code, so there's no need for the `python.srcDir` line.

**Comment by mhsmith** [comment]
Chaquopy now provides a Python build of TensorFlow Lite. For instructions, see https://github.com/chaquo/chaquopy/issues/332#issuecomment-781480272.

**Comment by mhsmith** [comment]
I don't think so, but we now have [an FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size) which suggests various ways to reduce the size of your app.
