### ISSUE TITLE
not able to generate split apks

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#449]
Hello I am using ndk abi filters to reduce app size, but when I use `flutter build apk --split-per-abi` to build apk files according to architecture it gives me following error : 

> FAILURE: Build failed with an exception.                                
>                                                                         
> * Where:                                                                
> Build file '/Users/jaydangar/Downloads/DcodeAI/android/android/build.gradle' line: 30
>                                                                         
> * What went wrong:                                                      
> A problem occurred evaluating root project 'android'.                   
> > A problem occurred configuring project ':app'.                        
>    > Conflicting configuration : 'armeabi-v7a,x86_64,arm64-v8a' in ndk abiFilters cannot be present when splits abi filters are set : x86_64,armeabi-v7a,arm64-v8a
>                                                                         
> * Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                         
> * Get more help at https://help.gradle.org                              
>                                                                         
> BUILD FAILED in 7s                                                      
> Running Gradle task 'assembleRelease'...                                
> Running Gradle task 'assembleRelease'... Done                       8.0s
> Gradle task assembleRelease failed with exit code 1

I haven't specified the splits or enabled it. can you let me know how can I build two different apks for the reducing the size of  apk? 

This is how my build.gradle looks like : 

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw GradleException('Flutter SDK not found. Define location with flutter.sdk in the local.properties file.')
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.python.srcDirs += 'src/main/python'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId 'com.dcodeai.ai'
        multiDexEnabled true
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 9
        versionName '1.0.9'
        multiDexEnabled true
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        python {
            pip {
                install 'numpy'
                install 'scipy'
                install 'pandas'
                install 'matplotlib'
                install 'nltk'
                install 'opencv-python'
                install 'pillow'
            }
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    //  setting up firebase
    implementation platform('com.google.firebase:firebase-bom:26.2.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'
}

```

**Comment by jay9440** [comment]
I cannot generate split apks if I use ndk abiFilters.

**Comment by mhsmith** [comment]
We'll add proper app bundle support in a future version of Chaquopy, but currently the only supported way to build separate APKs per ABI is using a product flavor dimension, as described in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size). 

After editing the build.gradle file in this way, you'll probably then need to execute Gradle directly rather than going through the flutter command:

* In Android Studio, click the "Sync now" prompt at the top of the screen, or choose File > Sync Project with Gradle Files. Then to build one APK at a time, you can select it in View > Tool Windows > Build Variants and then click the build button in the toolbar. Or to build all of them at once, use Build > Generate Signed Bundle / APK.

* Or on the command line, change to your project directory and run `./gradlew tasks --all | grep assemble` to list the available APK tasks, then run them with <code>/gradlew *assembleTask1* [*assembleTask2...*]</code>.

**Comment by jay9440** [comment]
Thank you for your prompt response. The solution worked, I am closing the issue. Thanks again.
