### ISSUE TITLE
NLTK offline language data

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#451]
I am using NLTK for one of my production app, my app requires NLTK to use nltk data, but It should be offline, is there a way I can use nltk language data without using nltk.download('all'), is there a package for the same? The problem with nltk.download('all') is that I can't notify users that the data has been downloaded or error occurred while downloading and user should retry. Kindly suggest a way to provide any one of the solution for the problem above. Thanks & Regards.

**Comment by jay9440** [comment]
or is there a way to run `python -m nltk.downloader all` this command in chaquopy and get success/failed result?

**Comment by jay9440** [comment]
How can I give folder access if I want to integrate NLTK data into the app as offline first feature as described in manual installing section according to this page? https://www.nltk.org/data.html#

**Comment by mhsmith** [comment]
If you unzip the packages inside your Python source directory, as described in that link, you can then set the `NLTK_DATA` variable using a path relative to `__file__`. For example, if your data is in `src/main/python/nltk_data`, and your code is in `src/main/python/some_package/test.py`, then you could do the following:

```
import os
from os.path import dirname
os.environ["NLTK_DATA"] = f"{dirname(__file__)}/../nltk_data"
```

You should probably make sure this code runs before importing any NLTK modules.

**Comment by jay9440** [comment]
so i need to create a folder called nltk_data inside src/main/python/ directory and unzip the model files and run the following code before I run any NLTK modules, right? :

```
import os
from os.path import dirname
os.environ["NLTK_DATA"] = f"{dirname(__file__)}/../nltk_data"
```

**Comment by mhsmith** [comment]
I don't know how you got anything out of the nltkdata package, it doesn't look as if it contains anything, and it isn't documented anywhere.

Please try the code I posted and let me know how you get on. Make sure you unzip the files in the correct subfolder as described in the "manual installation" section. And if your code isn't directly within a top-level package as in my example, adjust the relative path accordingly.

**Comment by jay9440** [comment]
@mhsmith Your solution worked like a charm. Thanks & Regards.
