### ISSUE TITLE
is it possible to load nltk data from downloads folder?

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#452]
I am creating an app which requires me to use all the nltk data files, which comes around 700+ MBs. I have integrated some of the packages which made my app size around 200+ mb. Now I am thinking about hosting the NLTK packages on google drive and download it as per user's requirement. so once the packages are downloaded in android's download folder I would be able to use it to run the code. I need your advice if changing this path `os.environ["NLTK_DATA"] = f"{dirname(__file__)}/../nltk_data"` to Downloads folder would work or I need some other changes?

**Comment by mhsmith** [comment]
As it says in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-sdcard), recent versions of Android don't allow direct access to the Downloads folder, so this approach wouldn't work. 

I think your best solution would be to use `nltk.download` as you mentioned in [your previous issue](https://github.com/chaquo/chaquopy/issues/451). You said the problem with that was:

> I can't notify users that the data has been downloaded or error occurred while downloading and user should retry.

If you mean that the download function doesn't raise an exception on failure, it looks like you could change that using the `raise_on_error` option as documented [here](https://www.nltk.org/api/nltk.html#nltk.downloader.Downloader.download).

**Comment by jay9440** [comment]
Okay I will be using the raise on error method as of now. Thank you for the prompt response.
