### ISSUE TITLE
Why list comprehensions don't work in chaquopy?

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#454]
Greetings of the day. I am trying to run the following code, but it says stop_words is not defined but it is as you can clearly infer it from the code. can you let me know why it's not working?

```import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet = WordNetLemmatizer()
paragraph = "Hi this is DcodeAI and I am here to teach you how humans can interact with machines. This is our NLP Tutorial"

sentences = nltk.sent_tokenize(paragraph)
stop_words = set(stopwords.words('english'))
print(stop_words) # This works.
corpus = []

for i in range(len(sentences)):
  review = re.sub('[^a-zA-Z]',' ',sentences[i])
  review = review.lower()
  review = review.split()
  #  The following line is the Error Line.
  review = [wordnet.lemmatize(word) for word in review if not word in stop_words]
  review = ' '.join(review)
  corpus.append(review)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
X
bow_df = pd.DataFrame(X,columns=cv.get_feature_names())
bow_df

**Comment by mhsmith** [comment]
Please post the full stack trace.

**Comment by jay9440** [comment]
> W/ple.flutter_app(14762): type=1400 audit(0.0:49913): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/chaquopy/lib/libgfortran.so.3" dev="mmcblk0p54" ino=50286 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49914): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/chaquopy/lib/libopenblas.so" dev="mmcblk0p54" ino=3238 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49915): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/numpy/core/_multiarray_umath.so" dev="mmcblk0p54" ino=35015 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49916): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/numpy/core/_multiarray_tests.so" dev="mmcblk0p54" ino=158036 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49917): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/numpy/linalg/lapack_lite.so" dev="mmcblk0p54" ino=6540 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49918): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/numpy/linalg/_umath_linalg.so" dev="mmcblk0p54" ino=63177 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49919): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/stdlib-arm64-v8a/_decimal.so" dev="mmcblk0p54" ino=30228 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49920): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/numpy/fft/_pocketfft_internal.so" dev="mmcblk0p54" ino=63114 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49921): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/numpy/random/mtrand.so" dev="mmcblk0p54" ino=63157 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49938): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/stdlib-arm64-v8a/unicodedata.so" dev="mmcblk0p54" ino=32151 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49939): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/matplotlib/_image.so" dev="mmcblk0p54" ino=63454 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49940): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/matplotlib/backends/_backend_agg.so" dev="mmcblk0p54" ino=63469 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49941): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/chaquopy/lib/libjpeg_chaquopy.so" dev="mmcblk0p54" ino=6118 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49945): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/tslibs/conversion.so" dev="mmcblk0p54" ino=45580 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49946): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/tslibs/c_timestamp.so" dev="mmcblk0p54" ino=45866 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49947): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/tslibs/nattype.so" dev="mmcblk0p54" ino=45699 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49948): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/tslibs/np_datetime.so" dev="mmcblk0p54" ino=45651 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49949): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/tslibs/timezones.so" dev="mmcblk0p54" ino=45776 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49977): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/reshape.so" dev="mmcblk0p54" ino=16224 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49978): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/window.so" dev="mmcblk0p54" ino=16227 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49979): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/skiplist.so" dev="mmcblk0p54" ino=16328 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49980): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/groupby.so" dev="mmcblk0p54" ino=16351 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:49981): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/pandas/_libs/reduction.so" dev="mmcblk0p54" ino=15997 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50002): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/sparse/csgraph/_reordering.so" dev="mmcblk0p54" ino=50391 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50003): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/spatial/ckdtree.so" dev="mmcblk0p54" ino=50405 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50004): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/spatial/qhull.so" dev="mmcblk0p54" ino=50407 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50005): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/_lib/messagestream.so" dev="mmcblk0p54" ino=50409 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50006): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/spatial/_voronoi.so" dev="mmcblk0p54" ino=50415 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50050): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/stats/statlib.so" dev="mmcblk0p54" ino=52448 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50051): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/stats/mvn.so" dev="mmcblk0p54" ino=52595 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50052): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/regex/_regex.so" dev="mmcblk0p54" ino=52594 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50053): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/sklearn/__check_build/_check_build.so" dev="mmcblk0p54" ino=53642 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50054): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/sklearn/utils/murmurhash.so" dev="mmcblk0p54" ino=53653 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/python.stderr(14762): /data/user/0/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/joblib/_multiprocessing_helpers.py:45: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
> W/ple.flutter_app(14762): type=1400 audit(0.0:50060): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/sklearn/utils/_random.so" dev="mmcblk0p54" ino=56965 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50061): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/sklearn/datasets/_svmlight_format_fast.so" dev="mmcblk0p54" ino=45288 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50062): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/io/matlab/mio_utils.so" dev="mmcblk0p54" ino=45064 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50063): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/io/matlab/mio5_utils.so" dev="mmcblk0p54" ino=45051 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file
> W/ple.flutter_app(14762): type=1400 audit(0.0:50064): avc: granted { execute } for uid=10569 path="/data/data/com.example.flutter_app/files/chaquopy/AssetFinder/requirements/scipy/io/matlab/streams.so" dev="mmcblk0p54" ino=45088 scontext=u:r:untrusted_app:s0:c57,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c258,c512,c768 tclass=file

while running the above code these are the logs printed, while I get following error printed on the screen. 

![image](https://user-images.githubusercontent.com/73017747/108380396-cee25900-722c-11eb-8950-8f00adea855b.png)

**Comment by mhsmith** [comment]
I assume you're passing the code to `exec` or something similar at runtime, but I think you must be doing it incorrectly. Check the [documentation of `exec`](https://docs.python.org/3/library/functions.html#exec) or whatever you're using, especially the part about the globals and locals dictionary. If you still can't work it out, post the code that runs the code.

**Comment by jaydangar** [comment]
@mhsmith I am putting all of my code inside exec() bloc. it works for all the other codes. I am adding the running code for your reference :

```
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re

ps = PorterStemmer()
wordnet = WordNetLemmatizer()
paragraph = "Hi this is DcodeAI and I am here to teach you how humans can interact with machines. This is our NLP Tutorial"

sentences = nltk.sent_tokenize(paragraph)
stop_words = set(stopwords.words('english'))
corpus = []

for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]',' ',sentences[i])
    review = review.lower()
    review = review.split()
    #  From here the code is modified
    for word in review:
        word = wordnet.lemmatize(word)
        review = ''.join(word)
        corpus.append(review)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
X
bow_df = pd.DataFrame(X,columns=cv.get_feature_names())
bow_df
```

**Comment by mhsmith** [comment]
Like I said, I think the bug isn't in this code, but in the code that calls `exec`.

**Comment by mhsmith** [comment]
If you post that then I may be able to help you.

**Comment by jaydangar** [comment]
It's a simple code. I have declared main function like following and calling it, through kotlin code, as per your chaquopy example. 

This is my kotlin code:

fun _runPythonCode(data: Map<String, Any?>): Map<String, Any?> {
        val _returnOutput: MutableMap<String, Any?> = HashMap()

        val _python: Python = Python.getInstance()

        val _console: PyObject = _python.getModule("script")
        val _sys: PyObject = _python.getModule("sys")
        val _io: PyObject = _python.getModule("io")

        return try {
            val _textOutputStream: PyObject = _io.callAttr("StringIO")
            _sys["stdout"] = _textOutputStream
            val _imgOutputStream: PyObject = _console.callAttrThrows("main", data["code"])
            _returnOutput["textOutput"] = _textOutputStream.callAttr("getvalue").toString()
            _returnOutput["graphOutput"] = _imgOutputStream.toJava(ByteArray::class.java)
            _returnOutput
        } catch (e: PyException) {
             print(e.message.toString())
            _returnOutput["error"] = e.message.toString()
            _returnOutput
        }
    }

This is my script.py file :

```
def main(code):
    exec(code)
```

**Comment by mhsmith** [comment]
If your first example failed and your second example succeeded, then this is probably because of the scope change in the list comprehension, as described at https://stackoverflow.com/questions/45132645. Try changing it to:

```
def main(code):
    env = {}
    exec(code, env, env)
```

**Comment by jaydangar** [comment]
Okay @mhsmith , I will try and update you on this for the same. Thank you for the prompt response.

**Comment by jaydangar** [comment]
Thank you @mhsmith Your approach worked like a charm. Thanks again.

**Comment by jay9440** [comment]
Thank you @mhsmith Your approach worked like a charm. Thanks again.
