### ISSUE TITLE
a native null pointer crash in chaquopy.so

### ISSUE THREAD

**Issue by doloveme** [chaquo/chaquopy#455]
#### Chaquopy version

    classpath "com.chaquo.python:gradle:9.0.0"

#### Devices or emulators where the issue happens

DEVICE： 'HUAWEI/TAS-AL00'
#### Relevant parts of your code

2-18 16:33:47.282 1096 1147 E bastetd : [ProxySocket ] NotifySocketErrState# No record found by comm prop, state=196619
02-18 16:33:49.444 16625 19414 F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 19414 (Thread-19), pid 16625 (coration.record)
02-18 16:33:49.572 19439 19439 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-18 16:33:49.572 19439 19439 F DEBUG : Build fingerprint: 'HUAWEI/TAS-AL00/HWTAS:10/HUAWEITAS-AL00/11.0.0.165C00:user/release-keys'
02-18 16:33:49.572 19439 19439 F DEBUG : Revision: '0'
02-18 16:33:49.572 19439 19439 F DEBUG : ABI: 'arm'
02-18 16:33:49.575 19439 19439 F DEBUG : SYSVMTYPE: Maple
02-18 16:33:49.575 19439 19439 F DEBUG : APPVMTYPE: Art
02-18 16:33:49.575 19439 19439 F DEBUG : Timestamp: 2021-02-18 16:33:49+0800
02-18 16:33:49.575 19439 19439 F DEBUG : pid: 16625, tid: 19414, name: Thread-19 >>> com.lianjia.decoration.record <<<
02-18 16:33:49.575 19439 19439 F DEBUG : uid: 10344
02-18 16:33:49.575 19439 19439 F DEBUG : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
02-18 16:33:49.575 19439 19439 F DEBUG : Cause: null pointer dereference
02-18 16:33:49.575 19439 19439 F DEBUG : r0 b3b9e828 r1 00005131 r2 00000014 r3 a76e8240
02-18 16:33:49.575 19439 19439 F DEBUG : r4 b3b9e828 r5 00000000 r6 b3b8aa4c r7 a82201b8
02-18 16:33:49.575 19439 19439 F DEBUG : r8 b3bac6d8 r9 b3816b21 r10 b3b8f440 r11 a8220230
02-18 16:33:49.575 19439 19439 F DEBUG : ip b3b9c34c sp a82201a8 lr b382111b pc b382111a
02-18 16:33:49.576 19439 19439 F DEBUG :
02-18 16:33:49.576 19439 19439 F DEBUG : backtrace:
02-18 16:33:49.576 19439 19439 F DEBUG : NOTE: Function names and BuildId information is missing for some frames due
02-18 16:33:49.576 19439 19439 F DEBUG : NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
02-18 16:33:49.576 19439 19439 F DEBUG : NOTE: found under the lib/ directory are readable.
02-18 16:33:49.576 19439 19439 F DEBUG : #00 pc 0001d11a /data/data/com.lianjia.decoration.record/files/chaquopy/bootstrap-native/armeabi-v7a/java/chaquopy.so
02-18 16:33:49.576 19439 19439 F DEBUG : #01 pc 0001d047 /data/data/com.lianjia.decoration.record/files/chaquopy/bootstrap-native/armeabi-v7a/java/chaquopy.so
02-18 16:33:49.576 19439 19439 F DEBUG : #02 pc 0004a355 /data/app/com.lianjia.decoration.record-svvhKORRIu3YyzYMV1ttDQ==/lib/arm/libpython3.8.so (PyObject_Call+140)
02-18 16:33:50.295 1142 1142 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_02
02-18 16:33:50.391 1666 2194 E ZrHung.AppEyeFocusWindow: NFW check!
02-18 16:33:50.406 1666 2815 E WindowManager: win=Window{10847b9 u0

#### Describe your issue

little chance appear this issue and i had not buy the licensing

thank you !

**Comment by mhsmith** [comment]
If the crash is caused by the licensing time limit, then this message should appear in the log shortly before the crash: "Unlicensed copy of Chaquopy: app will now shut down."  If you see that message, please [contact us](https://chaquo.com/chaquopy/license/) to request a license. 

If you don't see that message, please provide more information about exactly what your app was doing with Chaquopy at the time of the crash.

**Comment by mhsmith** [comment]
If you still need help, please respond to my previous message and I'll reopen the issue.
