### ISSUE TITLE
show alertdialog while chaquopy is running the code

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#459]
@mhsmith , i am facing an issue regarding showing alertDialog. My problem is, whenever I am calling the native code, it doesn't wait for the response and it dismisses the alertDialog, although my code is still running in the background and shows output. How can I wait till the output becomes available? I am adding all the codes here for your reference.

```
 void appendAndRunPythonCode(BuildContext context) async {
    FocusScope.of(context).unfocus();
    String code = _controller.text;
    _alertDialogUtils.showAlertDialog(context);
    await runPythonScript(code);
    _alertDialogUtils.dismissAlertDialog(context);
  }
```

runPythonScript function : 

```
Future<void> runPythonScript(String code) async {
    if (code.isEmpty) {
      ToastUtils.showToastMessage(text: ConstUtils.code_empty);
      return;
    }

    data.putIfAbsent("code", () => code);

    final result = await _channel.invokeMethod("runPythonNLTKScript", data);

    setState(() {
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        curve: Curves.easeOut,
        duration: const Duration(milliseconds: 300),
      );
      output = result['textOutput'];
      data.clear();
    });
  }
```

From MethodChannel I am calling following function : 

```
override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "runPython").setMethodCallHandler { call, result ->
            if (call.method == "runPythonNLTKScript") {
                try {
                    val data: Map<String, Any?> = call.arguments()
                    val _result: Map<String, Any?> = _runPythonNLTKCode(data)
                    result.success(_result)
                } catch (e: Exception) {
                    val _result: MutableMap<String, Any?> = HashMap()
                    _result["textOutput"] = e.message.toString()
                    print(e.message.toString())
                    result.success(_result)
                }
            }  
       }
    }
```

```
//  * This will run python code consisting of error and result output...
    fun _runPythonNLTKCode(data: Map<String, Any?>): Map<String, Any?> {
        val _returnOutput: MutableMap<String, Any?> = HashMap()

        val _python: Python = Python.getInstance()

        val _console: PyObject = _python.getModule("script")
        val _sys: PyObject = _python.getModule("sys")
        val _io: PyObject = _python.getModule("io")

        return try {
            val _textOutputStream: PyObject = _io.callAttr("StringIO")
            _sys["stdout"] = _textOutputStream
            _console.callAttrThrows("mainNLTK", data["code"])
            _returnOutput["textOutput"] = _textOutputStream.callAttr("getvalue").toString()
            _returnOutput
        } catch (e: PyException) {
            print(e.message.toString())
            _returnOutput["textOutput"] = e.message.toString()
            _returnOutput
        }
    }
```

this is my python script :

```
#  This is the code to run NLTK functions...
def mainNLTK(code):
    global thread1
    thread1 = threading.Thread(target=nltk_thread_run, args=(code,))
    thread1.start()
    timeout = 30 # seconds
    thread1_start_time = time.time()
    while thread1.is_alive():
        if time.time() - thread1_start_time > timeout:
            # thread does not provide stop method, so just exit to kill process
            stop_thread(thread1)
            raise TimeoutError
        time.sleep(1)
    thread1.join()
```

This is my nltk_thread_run function : 

```
def nltk_thread_run(code):
    try:
        os.environ["NLTK_DATA"] = f"{dirname(__file__)}/nltk_data"
        env={}
        exec(code,env,env)
    except Exception as e:
        print(e)
```

**Comment by mhsmith** [comment]
The Python-related sections of your code look fine, so the issue is probably with the way you're using the Dart coroutines or MethodChannel. Unfortunately I don't know anything about Dart, so you'd better seek help on StackOverflow or some Flutter/Dart forum.

**Comment by jay9440** [comment]
@mhsmith , actually the thing is that I have tried adding manual timeout like a sleep function after calling method channel, which actually works and shows the alertDialog for the specified time. Thus, I think the problem should be from python or methodChannel. is there a way to prevent the code from python till it's running? I tried with thread.join() but it doesn't work. The output however gets updated after sometime.

**Comment by mhsmith** [comment]
> is there a way to prevent the code from python till it's running? I tried with thread.join() but it doesn't work. 

Do you mean that thread.join is returning before the background thread is finished? I suggest you add some logging to your code to work out which lines in each thread are being executed, and in what order. `print` in Python and `Log` in Java will both send messages to the [Logcat](https://developer.android.com/studio/debug/am-logcat.html).

**Comment by jay9440** [comment]
@mhsmith , I found the solution, actually the problem was for the first time python loads libraries which actually takes time and runs in the background, so it was having a delay while showing the output, from next time onwards it runs fast. So, I added 1 second artificial delay, which is not the perfect situation but gets the job done.
