### ISSUE TITLE
efficientnet package with Chaquopy

### ISSUE THREAD

**Issue by Mahila171** [chaquo/chaquopy#460]
I have been trying to install the efficientnet package, but it seems to fail or has not support? Can anyone help me? Thanks in advance!

Chaquopy: 9.1.0

**Comment by Mahila171** [comment]
Also, I have been trying to install "tf-nightly" package to get EfficientNetB7 model , but it seems to has not support?

**Comment by mhsmith** [comment]
> I have been trying to install the efficientnet package, but it seems to fail or has not support?

Please describe exactly what you did and what happened, including any error messages.

> Also, I have been trying to install "tf-nightly" package to get EfficientNetB7 model , but it seems to has not support?

TensorFlow is a very complex and fast-moving project, so we're unlikely ever to support their nightly releases. However it looks like they've included EfficientNet in their stable versions 2.3.0 and later, which we will support in the future. Please subscribe to #374 for updates.

**Comment by Mahila171** [comment]
Thanks for your response, I want to sure of something after I read some issues, Until now Chaquopy does not support Tensorflow version 2.3.0, or even Tensorflow version 2.2.0, is this correct now?

**Comment by mhsmith** [comment]
Yes, we're currently on version 2.1.0.

**Comment by mhsmith** [comment]
But you might be able to use that with the separate "efficientnet" package. If you had difficulty with that, then please give details.

**Comment by Mahila171** [comment]
Thanks

OK, I will try to use the separate efficientnet package, and I will tell you the details.

**Comment by mhsmith** [comment]
OK, if you need any more help, just let me know and I'll reopen the issue.
