### ISSUE TITLE
unable to pip install omsnx because of pyproj

### ISSUE THREAD

**Issue by pksiwan11** [chaquo/chaquopy#463]
I'm using the following code for `osmnx` pip [[link for pip]](https://pypi.org/project/osmnx/) in Android Studio:

            python{ 
            version "3.6.5"

               pip {

                    install "networkx==1.10" 

                    install "osmnx>=0.15.1"
                    }
               }

**Build Error Produced:**
_:OSMNavigator:generateDebugPythonRequirements
Failed to install pandas>=1.1 from https://files.pythonhosted.org/packages/fb/e4/828bb9c2474ff6016e5ce96a78220d485436d5468c23068f4f6c2eb9cff8/pandas-1.1.5.tar.gz (from osmnx>=0.15.1). For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues. Or try using one of the following versions, which are available as pre-built wheels: ['0.22.0'].
Cause: buildPython failed (org.gradle.process.internal.ExecException: Process 'command 'python3'' finished with non-zero exit value 1)_

After adding `pandas`, got following build error:

            python{ 
            version "3.6.5"

               pip {

                    install "networkx==1.10" 

                    install "pandas"

                    install "osmnx>=0.15.1"
                    }
               }

**new Build error produced:**
_:OSMNavigator:generateDebugPythonRequirements
Failed to install Shapely>=1.7 from https://files.pythonhosted.org/packages/42/f3/0e1bc2c4f15e05e30c6b99322b9ddaa2babb3f43bc7df2698efdc1553439/Shapely-1.7.1.tar.gz (from osmnx>=0.15.1). For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Cause: buildPython failed (org.gradle.process.internal.ExecException: Process 'command 'python3'' finished with non-zero exit value 1)_

In issue #363 its mentioned that Chaquopy has support for `Shapely`. Thus tried adding `Shapely` explicitly like this:

            python{ 
            version "3.6.5"

               pip {

                    install "networkx==1.10" 

                    install "pandas"
                    install "Shapely==1.7.0"

                    install "osmnx>=0.15.1"
                    }
               }

**the Build error now produced:**
_:OSMNavigator:generateDebugPythonRequirements
Failed to install Shapely==1.7.0 from https://files.pythonhosted.org/packages/44/ec/4eddbf9d17a917c51fb4ad159aa7137f506681e91ab559cf87d120e1d78d/Shapely-1.7.0.tar.gz. For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Cause: buildPython failed (org.gradle.process.internal.ExecException: Process 'command 'python3'' finished with non-zero exit value 1)_

**Requirement:** I want to use `osmnx` in Android Studio. Can you please help with this?

**Comment by mhsmith** [comment]
It looks like you're using an old version of Chaquopy. You'll have to upgrade to Chaquopy 7 or newer in order to use Shapely.

The pandas requirement could probably be fixed as well, by using a slightly older version of osmnx.

However, it looks like all versions of osmnx for at least the last two years require pyproj, either directly or via geopandas. Since we don't currently support pyproj, you won't be able to use osmnx either. 

Sorry about that. If anyone else needs this package, please click the thumbs up button above, and subscribe to this issue for updates.
