### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by Tedxjbc** [chaquo/chaquopy#466]
Hi, I want to run webserver in AndroidStudio. If I am right I have to run it in Services to run in background. First of all I try to run Python in ShowWebsiteActivity.java but webview shows just blank page. So, this reason why I try to call and run Python script in Services. Python file works, I tried to run it on my pc but in AdnroidStudio doesnt. It raise this error - Cannot convert bytes object to java.lang.String. How can I run Python webserver in background? All settings are set, like dependencies etc.

**Java class**
`
   public class ShowWebsiteActivity extends FragmentActivity {
   WebView web;
   TextView textView

   @Override
   protected void onCreate(@Nullable Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
    
    // CALLING SERVICES
    startService(new Intent(this,StartPythonWebServer.class)); 
    
    setContentView(R.layout.activity_website);
    web = findViewById(R.id.webView);
    WebSettings webSettings = web.getSettings();
    webSettings.setBuiltInZoomControls(true);
    webSettings.setJavaScriptEnabled(true);
    webSettings.setAllowContentAccess(true);
    webSettings.setDomStorageEnabled(true);
    web.setWebViewClient(new Callback());
    web.loadUrl("http://10.0.2.2:8080/");

    textView = findViewById(R.id.DateTime);
    Calendar calendar = Calendar.getInstance();
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEEE, dd-MM-yyyy hh:mm:ss a");
    String dateTime = simpleDateFormat.format(calendar.getTime());
    textView.setText(dateTime);

    final Button logout = findViewById(R.id.logout);
    logout.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            web.loadUrl("http://10.0.2.2:8080/menu");
        }
    });
}`

**Service class**
`   public class StartPythonWebServer extends Service {

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Toast.makeText(this, "Service started by user.", Toast.LENGTH_LONG).show();
        Python py = Python.getInstance();
        py.getModule("webserver").callAttr("start");
    
        return START_STICKY;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        Toast.makeText(this, "Service destroyed by user.", Toast.LENGTH_LONG).show();
    }}`

**Python**
    `
    from flask import Flask, render_template, url_for, redirect, render_template, request
    import os
    from werkzeug.utils import secure_filename
    app = Flask(__name__,
                static_folder='static',
                template_folder='templates')
    
    @app.route('/')
    def main():
        return render_template('login.html')
    
    @app.route('/menu', methods=['GET', 'POST'])
    def menu():
        return render_template('menu.html')
    
    @app.route('/content', methods=['GET', 'POST'])
    def content():
    return render_template('index.html')
    
    def start():
        app.run(debug=True, host='0.0.0.0', port=8080)
    
    '''
    if __name__ == '__main__':
        app.run(debug=True, host='0.0.0.0', port=8080)
    '''
`

**Comment by Tedxjbc** [comment]
Sorry for bad formating of code..

**Comment by mhsmith** [comment]
> Cannot convert bytes object to java.lang.String

This error was actually reported a few days ago by someone else, and there's a workaround in #464.

In future, please search for existing issues before creating new ones.

**Comment by mhsmith** [comment]
You can format blocks of code by putting <code>```</code> before and after.
