### ISSUE TITLE
Installing module from existed project

### ISSUE THREAD

**Issue by JasonAntario** [chaquo/chaquopy#467]
I have a project with multiple modules. I need to install one of these modules - `python-ubloxgps`. I can install it using the terminal and run `pip install .` when I am in that directory. I've tried many syntax options for installing a module from `build.gradle` to no avail. How can I do this if possible?

![image](https://user-images.githubusercontent.com/58884138/111994729-24aa6980-8b29-11eb-9a62-8bf30d4d55cb.png)

**Comment by mhsmith** [comment]
You have several options:

Arrange src/main/python to be a single hierarchy of Python packages and modules. For example, if your code is under python-ubloxgps/src, move the content of that directory so it's directly under src/main/python.

Or, if you prefer, keep your code outside of src/main/python and add it to the build using the [`srcDir`](https://chaquo.com/chaquopy/doc/current/android.html#android-source) command.

Or, if there's a setup.py script which needs to be run, keep your code outside of src/main/python and pass the directory containing the setup.py to the [`install`](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements) command.

**Comment by JasonAntario** [comment]
These options don't work for me. If they were just files, I would do that, but this is the same module as those downloaded from github. If I were using code like in terminal, it would look like this: 

```
python {
            pip {
                install "serial"
                install "libadvian"
                install "." //in directory "android_gnss_example/python-ubloxgps"
            }
        }
```

I have no `requirements.txt` or` setup.py` files in the module. Can I install this module in some way?

**Comment by mhsmith** [comment]
If there is no setup.py file, just use `srcDir` with the location of the directory containing the Python files. I can't find this library on GitHub so I can't tell you what this directory is, but I assume it's `python-ubloxgps/src` or some subdirectory of it.

Or if there is a setup.py file, use `install` with the location of the directory containing it. 

In both cases you should:
* Keep the library outside of src/main/python. That directory should be a single Python source tree: it can't be subdivided as shown in your screenshot.
* Express the location as a path relative to the location of the build.gradle file. So `install "."` is not correct unless you've got a setup.py file in the same directory as build.gradle, which I would not recommend.
