### ISSUE TITLE
Failed to install jinus even though I am adding it to pip

### ISSUE THREAD

**Issue by Jaiv24** [chaquo/chaquopy#471]
`Failed to install jnius from https://files.pythonhosted.org/packages/45/f5/5673f3906a9e8ca68cb7bc2d9a1eaa944c321271c4af621dbb51c13d385a/jnius-1.1.0.tar.gz.`

I am adding it to my pip like this;
```
python {
            pip {
                // A pip requirement specifier, with or without a version number:
                install "jnius"
                install "usbserial4a"
            }
        }
```

and this is my python script:
```
from usb4a import usb
from usbserial4a import serial4a

def main(data):
    usb_device_list = usb.get_usb_device_list()
    usb_device_name_list = [device.getDeviceName() for device in usb_device_list]
    usb_device_dict = {
        device.getDeviceName():[            # Device name
            device.getVendorId(),           # Vendor ID
            device.getManufacturerName(),   # Manufacturer name
            device.getProductId(),          # Product ID
            device.getProductName()         # Product name
        ] for device in usb_device_list
    }

    if usb_device_list:
        serial_port = serial4a.get_serial_port(
            usb_device_list[0].getDeviceName(),
            9600,   # Baudrate
            8,      # Number of data bits(5, 6, 7 or 8)
            'N',    # Parity('N', 'E', 'O', 'M' or 'S')
            1)      # Number of stop bits(1, 1.5 or 2)
        if serial_port and serial_port.is_open:
            serial_port.write(data)
            serial_port.close()
            return data
```

**Comment by mhsmith** [comment]
See #348. You might need to make your own local copy of the usbserial4a library in `src/main/python` and edit it as required to access Java through Chaquopy rather than pyjnius.

**Comment by Jaiv24** [comment]
Ok so when you say that I have to make my own local copy of usbserial4a do I need to clone https://github.com/jacklinquan/usbserial4a in my `src/main/python` or should I just add the downloaded `.tar.gz` file.

Also, I am a bit confused when you say 

> Replace `jnius.autoclass` with `java.jclass.`

> Replace `jnius.PythonJavaClass` with `java.dynamic_proxy.` 

Can you elaborate?

**Comment by mhsmith** [comment]
Actually it looks like jnius isn't used directly by usbserial4a, but by its requirement usb4a. So here's what I suggest:

* Remove "jnius" from your build.gradle file, but keep "usbserial4a".
* Download the usb4a .whl file from [PyPI](https://pypi.org/project/usb4a/#files), and unzip it into `src/main/python`. This will override the copy installed by pip.
* Edit [usb4a/usb.py](https://github.com/jacklinquan/usb4a/blob/457ae9d4c220c05f2585008f3fa32bdb749683b3/usb4a/usb.py) as follows:
  * Change `from jnius import autoclass` to `from java import jclass as autoclass`
  * Remove the `autoclass` lines for `org.kivy` classes.
  * Remove the body of `get_context` except for the last line: `return context`. 
* Then before you use any of the USB functions, set this `context` variable to the context of your app. For example, you could pass your Activity as a second argument to `main`, and then add this line to the top of `main`: `usb.context = activity`

**Comment by Jaiv24** [comment]
Ok so I did what you say and also change the body of context like this 
`def get_context():
    '''Get the mActivity or mService context depending on what is available'''
    context = Context.mActivity

    return context
`


and what I wrote above my main is 
`usb.context = 'send_seven_seg.java'
def main(data):
    usb_device_list = usb.get_usb_device_list()
    usb_device_name_list = [device.getDeviceName() for device in usb_device_list]
    usb_device_dict = {
        device.getDeviceName():[            # Device name
            device.getVendorId(),           # Vendor ID
            device.getManufacturerName(),   # Manufacturer name
            device.getProductId(),          # Product ID
            device.getProductName()         # Product name
        ] for device in usb_device_list
    }`

Still getting this context has no attribute error
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.firebaseheartratemonitor, PID: 8059
    com.chaquo.python.PyException: AttributeError: type object 'Context' has no attribute 'send_seven_seg'
        at <python>.java.chaquopy.JavaClass.__getattribute__(class.pxi:142)
        at <python>.usb4a.usb.get_context(usb.py:49)
        at <python>.usb4a.usb.get_usb_manager(usb.py:58)
        at <python>.usb4a.usb.get_usb_device_list(usb.py:75)
        at <python>.get.main(get.py:9)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)`

**Comment by mhsmith** [comment]
No, that's not what I said at all.

Remove the ENTIRE body of `get_context` except for the last line: `return context`

Add a second argument to `main`, and use that argument to set the `usb.context` variable:
```
def main(data, activity):
    usb.context = activity
    ...
```

Then wherever you call `main`, pass your app's Activity object as the second argument. For example, if you're calling `main` from within an Activity class, then the Activity object is just `this`, so you would do something like:
```
yourPythonModule.callAttr("main", data, this)
```

And when posting multi-line code blocks on GitHub, please surround them with 3 backticks  \`\`\`like this\`\`\`, otherwise the formatting will be lost.

**Comment by Jaiv24** [comment]
Hi, thanks for suggesting me multiline code blocks trick.

Ok, so I am a little bit confused over here. What I did is this, but don't I need to declare a context first inside my `get_context()`. I get the problem but I am not sure how to solve it
```
def get_context():
    context = Context //Error
    return context
````

and in my main:
```
def main(data, activity):
    usb.context = activity
    ....
```

As doing this I received this error
``` com.chaquo.python.PyException: TypeError: android.content.Context.getSystemService cannot be applied to (str): options are final java.lang.Object android.content.Context.getSystemService(java.lang.Class), java.lang.Object android.content.Context.getSystemService(java.lang.String)```

**Comment by Jaiv24** [comment]
here's what I did
```
def get_context():
    
    return context
```

My main function:
```
def main(data, activity):
    usb.context = activity
    ...
```

And in my activity:
```
 if (!Python.isStarted()){
            Python.start(new AndroidPlatform(this));
        }
        Python py = Python.getInstance();
        PyObject module = py.getModule("get");

sendDataOverDisplay.setOnClickListener(v -> {
            PyObject pyObject = module.callAttr("main", heartrate, this);

            sendData.setText(pyObject.toString());
        });
```

And I still receive an error
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.firebaseheartratemonitor, PID: 6507
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.chaquo.python.PyObject.toString()' on a null object reference
        at com.example.firebaseheartratemonitor.send_seven_seg.lambda$onCreate$0$send_seven_seg(send_seven_seg.java:109)
```

**Comment by mhsmith** [comment]
That's because your `main` function isn't returning anything, or is returning `None`.

It looks like you've solved the original problem, so I'll close this issue. You can create separate issues for separate problems.

**Comment by MarkusPiotrowski** [comment]
@mhsmith May I awake this issue?
Coincidentally, I'm also interested in using serial communication on Android with `usb4a` and `usbserial4a`. 

So in the context of beeware, how would I do this?

I understand replacing the `jnius` autoclass with `java.jclass` but I'm lost regarding `context` and `activity` and the term 'Activity class`.

**Comment by mhsmith** [comment]
In a BeeWare Toga app, you can get a reference to the [`Activity`](https://developer.android.com/reference/android/app/Activity) object from your `App` object like this: `app._impl.native`.

`Activity` is a subclass of `Context`, so you can use the same object in both cases.
