### ISSUE TITLE
Failed to install pyjnius 

### ISSUE THREAD

**Issue by doublekill2020** [chaquo/chaquopy#472]
Collecting Cython
  Using cached https://files.pythonhosted.org/packages/9e/98/bff39b3acaebbc6102be71797f655bbe60738f7339db4ad7bd0772c08daf/Cython-0.29.22-py2.py3-none-any.whl
Collecting pyjnius
  Using cached https://files.pythonhosted.org/packages/69/62/a81f0bdd7a96831b920efeaec80d80b66991cb582a65f6e4ae8c9a10cffd/pyjnius-1.3.0.0.tar.gz
Collecting six>=1.7.0 (from pyjnius)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Building wheels for collected packages: pyjnius
  Running setup.py bdist_wheel for pyjnius: started
  Running setup.py bdist_wheel for pyjnius: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -S -c "import setuptools, tokenize;__file__='/tmp/pip-install-e9d1umad/pyjnius/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-n8t2k2rh --python-tag py3:
  warning: [options] bootstrap class path not set in conjunction with -source 1.7
  1 warning
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying jnius_config.py -> build/lib.linux-x86_64-3.5
  copying setup_sdist.py -> build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/jnius
  copying jnius/__init__.py -> build/lib.linux-x86_64-3.5/jnius
  copying jnius/env.py -> build/lib.linux-x86_64-3.5/jnius
  copying jnius/reflect.py -> build/lib.linux-x86_64-3.5/jnius
  copying jnius/signatures.py -> build/lib.linux-x86_64-3.5/jnius
  creating build/lib.linux-x86_64-3.5/jnius/src
  warning: [options] bootstrap class path not set in conjunction with -source 1.7

  creating build/lib.linux-x86_64-3.5/jnius/src/org
  creating build/lib.linux-x86_64-3.5/jnius/src/org/jnius
  copying jnius/src/org/jnius/NativeInvocationHandler.java -> build/lib.linux-x86_64-3.5/jnius/src/org/jnius
  copying jnius/src/org/jnius/NativeInvocationHandler.class -> build/lib.linux-x86_64-3.5/jnius/src/org/jnius
  running build_ext
  building 'jnius' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
  error: CCompiler.compile: Chaquopy cannot compile native code

  Command "/usr/bin/python3 -u -S -c "import setuptools, tokenize;__file__='/tmp/pip-install-e9d1umad/pyjnius/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-n8t2k2rh --python-tag py3" failed with error code 1 in /tmp/pip-install-e9d1umad/pyjnius/
ERROR: Failed to install pyjnius from https://files.pythonhosted.org/packages/69/62/a81f0bdd7a96831b920efeaec80d80b66991cb582a65f6e4ae8c9a10cffd/pyjnius-1.3.0.0.tar.gz.
Failed to install pyjnius from https://files.pythonhosted.org/packages/69/62/a81f0bdd7a96831b920efeaec80d80b66991cb582a65f6e4ae8c9a10cffd/pyjnius-1.3.0.0.tar.gz.

**Comment by mhsmith** [comment]
See #348, and please search for existing issues before creating new ones.
