### ISSUE TITLE
Unable to install paddlepaddle moudle

### ISSUE THREAD

**Issue by Y1ga** [chaquo/chaquopy#473]
#### Chaquopy version

Chaquopy Version:9.1.0

#### Describe your issue

When I write
pip {
                install "paddlepaddle"
            }
            }
then I'm sad to see that
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:\Users\Kiana\AppData\Local\Programs\Python\Python38\python.exe'' finished with non-zero exit value1
I wonder if the paddlepaddle is supported by Chaquopy now.

**Comment by mhsmith** [comment]
See #136, and please search for existing issues before creating new ones.
