### ISSUE TITLE
How can i return a python array to android studio java array?

### ISSUE THREAD

**Issue by largolowell** [chaquo/chaquopy#476]

**Comment by largolowell** [comment]
in java
short[] data =pyobj.callAttr("answerkey", imageString).toJava(short[].class);
in python
def answerkey(data):
decoded_data = base64.b64decode(data)
    np_data = np.fromstring(decoded_data,np.uint8)
    img = cv2.imdecode(np_data,cv2.IMREAD_UNCHANGED)

    img = cv2.resize(img, (widthImg, heightImg))
    imgContours = img.copy()
    imgBiggestContours = img.copy()
    imgFinal = img.copy()
    img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    imgBlur = cv2.GaussianBlur(img_gray, (5, 5), 1)
    imgCanny = cv2.Canny(imgBlur, 10, 50)

    contours, hierarchy = cv2.findContours(imgCanny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    cv2.drawContours(imgContours, contours, -1, (0, 255, 0), 3)
    # FIND RECTANGLES
    rectCon = utilis.rectCountour(contours)
    biggestContour = utilis.getCornerPoints(rectCon[0])
    biggestContour_1 = utilis.getCornerPoints(rectCon[1])

    if biggestContour.size != 0 and biggestContour_1.size != 0:
        cv2.drawContours(imgBiggestContours, biggestContour, -1, (0, 255, 0), 20)
        cv2.drawContours(imgBiggestContours, biggestContour_1, -1, (255, 0, 0), 20)

    biggestContour = utilis.reorder(biggestContour)
    biggestContour_1 = utilis.reorder(biggestContour_1)

    # first
    pt1 = np.float32(biggestContour)
    pt2 = np.float32([[0, 0], [widthImg, 0], [0, heightImg], [widthImg, heightImg]])
    matrix = cv2.getPerspectiveTransform(pt1, pt2)
    imgWarpColored = cv2.warpPerspective(img, matrix, (widthImg, heightImg))

    # second
    pt1_1 = np.float32(biggestContour_1)
    pt2_1 = np.float32([[0, 0], [widthImg, 0], [0, heightImg], [widthImg, heightImg]])
    matrix = cv2.getPerspectiveTransform(pt1_1, pt2_1)
    imgWarpColored_1 = cv2.warpPerspective(img, matrix, (widthImg, heightImg))

    # APPLY THRESHOLD
    imgWarpGray = cv2.cvtColor(imgWarpColored, cv2.COLOR_BGR2GRAY)
    imgThresh = cv2.threshold(imgWarpGray, 100, 255, cv2.THRESH_BINARY_INV)[1]
    # APPLY THRESHOLD_1
    imgWarpGray_1 = cv2.cvtColor(imgWarpColored_1, cv2.COLOR_BGR2GRAY)
    imgThresh_1 = cv2.threshold(imgWarpGray_1, 100, 255, cv2.THRESH_BINARY_INV)[1]

    boxes_1 = utilis.splitBoxes(imgThresh)
    # cv2.imshow("test",boxes_1[78])
    boxes_2 = utilis.splitBoxes(imgThresh_1)
    # cv2.imshow("test1",boxes_2[78])

    #############
    myPixelVal_1 = np.zeros((questions, choices))
    countC = 0
    countR = 0
    for image in boxes_1:
        totalpixels = cv2.countNonZero(image)
        myPixelVal_1[countR][countC] = totalpixels
        countC += 1
        if (countC == choices): countR += 1; countC = 0
        myIndex_1 = []
        for x in range(0, questions):
            counter = 0
            redunt = 0
            finalcounter = 0
            for y in range(0, choices):
                if (myPixelVal_1[x][y] >= 1200):
                    if (finalcounter < 1):
                        if (redunt < 1):
                            data = y
                            myIndex_1.append(data)
                            redunt += 1
                        else:
                            myIndex_1.pop();myIndex_1.append("wrong");finalcounter += 1
                else:
                    counter += 1
                if (counter == 4):
                    myIndex_1.append("no answer")

    fs, myIndex_1 = wavfile.read(myIndex_1)
    return myIndex_1.tobytes()

**Comment by mhsmith** [comment]
You've provided the code but you haven't described the problem. Is it throwing an exception, or returning the wrong answer, or what?

**Comment by largolowell** [comment]
i already get it sir thanks
