### ISSUE TITLE
Update PyTorch

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#477]
If anyone needs a newer version of PyTorch, please click the thumbs-up button below, and post a comment explaining why you need the new version.

**Comment by mhsmith** [comment]
Generating a file in a newer PyTorch version and loading it in 1.4.0 may cause the following error (#475).

> RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132)

Until we provide a newer version of PyTorch, the simplest way to fix this is to regenerate your file with the PyTorch 1.4.0. Version 1.5.x may also work.

**Comment by Ponprabhakar-pg** [comment]
> Generating a file in a newer PyTorch version and loading it in 1.4.0 may cause the following error (#475).
> 
> > RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132)
> 
> Until we provide a newer version of PyTorch, the simplest way to fix this is to regenerate the file with PyTorch 1.4.0. Version 1.5.x may also work.

How can I do that?

**Comment by mhsmith** [comment]
I mean, whatever you did to generate the file, just do it again, but this time with PyTorch 1.4.0. I don't have much experience with PyTorch, so if you have any problems with that, please search for help elsewhere.

Alternatively, there may be some way to generate an older version file with a newer version of PyTorch, but again, you'll have to find instructions for that elsewhere.

**Comment by PetervE** [comment]
For a ML project I'm using PyTorch models based on [YOLOV5](https://pytorch.org/hub/ultralytics_yolov5/) which are generated in PyTorch 1.8.1. I would like to keep working with these models instead of downgrading to previous one since v4 usually has a bigger size and/or less accurate.

Myself and probably many mobile developers would love to see Chaquopy updated so it works with the latest PyTorch version. Thanks a lot in advance!

**Comment by Nine-days** [comment]
com.chaquo.python.PyException: RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132)

**Comment by mhsmith** [comment]
PyTorch version 1.8.1 is now available.

The corresponding Torchvision version (0.9.1) is also available. If you use this, make sure you have Chaquopy 8.0.0 or newer, otherwise you may get the following error on API level 22 and older:

      File "/data/data/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/torchvision/extension.py", line 104, in <module>
      File "/data/data/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/torchvision/extension.py", line 83, in _check_cuda_version
      File "/data/data/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/torch/_ops.py", line 60, in __getattr__
    RuntimeError: No such operator torchvision::_cuda_version
    Exception raised from operator() at ../torch/csrc/jit/python/init.cpp:1003 (most recent call first):
