### ISSUE TITLE
Porting Libs

### ISSUE THREAD

**Issue by claudiosx** [chaquo/chaquopy#48]
Hi ,
I'm interested in porting  for   mpi4py,  obspy. and pyside

**Comment by mhsmith** [comment]
PySide would be quite difficult, so we're unlikely to provide it, unless someone wants to pay us to do the work.

We'll have a look at mpi4py and obspy and get back to you in the next few days.

**Comment by mhsmith** [comment]
From the documentation, it looks like mpi4py expects to be used in a process which was launched by mpiexec, so I don't see how this would be usable in the context of an Android app. If you can explain your use case, perhaps I can help you work something out.

obspy will probably be fine, but it requires lxml, so please give us a few more days.

**Comment by mhsmith** [comment]
ObsPy is now available, but it requires lxml, which will only work with the newest Chaquopy version 4.0.0. Please update the version number in your build.gradle as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#gradle-plugin).
