### ISSUE TITLE
Plotly image is not display when i integrate with java andriod studio

### ISSUE THREAD

**Issue by deepik27** [chaquo/chaquopy#483]
I am using plotly but that plotly image is not displayed and i am not getting any error also i will share my both the codes mainactivity.java and python code 

mainactivity.java

```
package com.example.integrate_python;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Bundle;
import android.os.Handler;
import android.util.Base64;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import java.io.InputStream;
import java.util.List;
import com.chaquo.python.PyObject;
import com.chaquo.python.Python;
import com.chaquo.python.android.AndroidPlatform;
import com.google.android.material.bottomnavigation.BottomNavigationItemView;
import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.series.DataPoint;
import com.jjoe64.graphview.series.LineGraphSeries;
import android.widget.Toast;
import android.os.Handler;
public class MainActivity extends AppCompatActivity {


    Button btn;
    ImageView iv;
    final Handler handler = new Handler();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btn = (Button) findViewById(R.id.submit);
        iv = (ImageView) findViewById(R.id.image);


        //Now checking python is started or not
        if (!Python.isStarted())
            Python.start(new AndroidPlatform(this));

        final Python py = Python.getInstance();

        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {


                Bitmap bmp = null;
                for (int i = 0; i < 12; i++) {
                    Log.d("Printing i value", String.valueOf(i));
                    PyObject pyo = py.getModule("volume");
                    //python object to load the script
                    PyObject obj = pyo.callAttr("main");
                    Log.d("printing", String.valueOf(obj));
                    String str = obj.toString();
                    byte data[] = android.util.Base64.decode(String.valueOf(obj), Base64.DEFAULT);
                    bmp = BitmapFactory.decodeByteArray(data, 0, data.length);
                    Log.d("Bitmap:", String.valueOf(bmp));
                    //iv.setImageBitmap(bmp);
                    Bitmap finalBmp = bmp;
                    
                    new Handler().postDelayed(() -> iv.setImageBitmap(finalBmp),  20000);


                }




            }
    });

        }
    }
```

python code plotly:-

```
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import numpy as np
def main():

    z = np.linspace(0, 10, 50)
    x = np.cos(z)
    y = np.sin(z)
    trace = go.Scatter3d(
    x = x, y = y, z = z,mode = 'markers', marker = dict(
      size = 12,
      color = z, # set color to an array/list of desired values
      colorscale = 'Viridis'
      )
    )
    layout = go.Layout(title = '3D Scatter plot')
    fig = go.Figure(data = [trace], layout = layout)
    fig.show()
    buff = io.BytesIO()
    plt.savefig(buff, format="PNG")
    img_str = base64.b64encode(buff.getvalue())


    return ""+str(img_str, 'utf-8') 
```

**Comment by mhsmith** [comment]
I can see several problems:

* You're calling the same function 12 times, so you'll just get the same image 12 times, unless you pass `i` as an argument and use it in `main`.

* You're doing every call in a  single loop in the button click handler. If the calls are slow, this will cause your app to stop responding. If the calls are fast, then all the images will get displayed at once. Either way, you won't get any animation effect.

Try something like this:
```
 btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                display(0);
            }

            private void display(int i) {
                    Log.d("Printing i value", String.valueOf(i));
                    PyObject pyo = py.getModule("volume");
                    PyObject obj = pyo.callAttr("main", i);
                    byte data[] = android.util.Base64.decode(String.valueOf(obj), Base64.DEFAULT);
                    bmp = BitmapFactory.decodeByteArray(data, 0, data.length);
                    iv.setImageBitmap(bmp);
                    if (i < 12) {
                        new Handler().postDelayed(() -> display(i+1), 1000);
                   }
           }
}
```

Then in Python:

```
def main(i):
    # Use `i` to generate a different image each time.
````

**Comment by deepik27** [comment]
Plotly graphs is not displaying in andriod studio, just its executing and i am not getting error please give me one solution how to intergrate plotly python file in andriod studio....
This is my java code..

package com.example.plotly;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;


import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Handler;
import android.util.Base64;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;

import com.chaquo.python.PyObject;
import com.chaquo.python.Python;
import com.chaquo.python.android.AndroidPlatform;
import com.google.android.material.bottomnavigation.BottomNavigationItemView;
import android.widget.Toast;
import android.os.Handler;
public class MainActivity extends AppCompatActivity {
    Button btn;
    ImageView iv;
    final Handler handler = new Handler();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        btn = (Button) findViewById(R.id.submit);
        iv = (ImageView) findViewById(R.id.image);


        //Now checking python is started or not
        if (!Python.isStarted())
            Python.start(new AndroidPlatform(this));

        final Python py = Python.getInstance();

        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Bitmap bmp = null;

                PyObject pyo = py.getModule("volume");
                //python object to load the script
                PyObject obj = pyo.callAttr("main");
                Log.d("printing", String.valueOf(obj));
                String str = obj.toString();
                byte data[] = android.util.Base64.decode(String.valueOf(obj), Base64.DEFAULT);
                bmp = BitmapFactory.decodeByteArray(data, 0, data.length);
                Log.d("Bitmap:", String.valueOf(bmp));
                iv.setImageBitmap(bmp);






            }
        });

    }
}



This is my python code 

import plotly.graph_objs as go
import io
import base64
import matplotlib.pyplot as plt
import numpy as np
def main():
    x = np.outer(np.linspace(-2, 2, 30), np.ones(30))
    y = x.copy().T # transpose
    z = np.cos(x ** 2 + y ** 2)
    trace = go.Surface(x = x, y = y, z =z )
    data = [trace]
    layout = go.Layout(title = '3D Surface plot')
    fig = go.Figure(data = data)
    fig.show()
    buff = io.BytesIO()
    plt.savefig(buff, format="PNG")
    img_str = base64.b64encode(buff.getvalue())


    return ""+str(img_str, 'utf-8') 


or should i use webview or something to display plotly graph in andriod studio please suggest me

**Comment by mhsmith** [comment]
If you're creating the image with plotly then you should save it with plotly, not matplotlib.

**Comment by deepik27** [comment]
Means I didnt got what u r telling to save in plotly

**Comment by mhsmith** [comment]
You're creating an image with plotly and then you're calling a matplotlib API to save it. I don't see how that could possibly work. Check the plotly documentation for instructions on how to export a plotly image.
