### ISSUE TITLE
I am not able to call and run my python script several times in a proper way.

### ISSUE THREAD

**Issue by alexcarnero97** [chaquo/chaquopy#484]
I am trying to use Chaquopy in order to execute a python script within my Android app. My application takes care of taking several photos until a certain condition is met, which is given by the python script. The python script receives and processes each of the images and finally predicts what type of object appears in them (out of two possible). The problem is that the python script only executes well with the first image that is passed to it, while with the following images it does not, and this I think is due to the fact that the PyObject variable has already been instantiated previously and it calls all the time to my prediction function without waiting for a new photograph to be taken, which I do not understand (I leave here the code that calls the python script):

        String result;

        while(!found) {
            takePicture();

            PyObject py = Python.getInstance().getModule("prediction");
            PyObject[] obj = new PyObject[1];
            obj[0] = py.callAttr("predict", currentPhotoPath);
            result = obj[0].toString();

            System.out.println(result);

            if (result.contains("turbine")) {
                found = true;
            }
        }

The error thrown is the following one:

```
2021-04-15 10:32:55.562 20510-20510/com.example.windturbinesai E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.windturbinesai, PID: 20510
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.windturbinesai/com.example.windturbinesai.PhotoActivity}: com.chaquo.python.PyException: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x78bb970680>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: com.chaquo.python.PyException: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x78bb970680>
        at <python>.PIL.Image.open(Image.py:2895)
        at <python>.keras_preprocessing.image.utils.load_img(utils.py:114)
        at <python>.prediction.predict(prediction.py:17)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.windturbinesai.PhotoActivity.start(PhotoActivity.java:63)
        at com.example.windturbinesai.PhotoActivity.onCreate(PhotoActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:8086)
        at android.app.Activity.performCreate(Activity.java:8074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
```

After the exception I go into my mobile's folder where pictures are saved and there is one picture taken without any data (it is empty), but it has been saved, so that's why I think the python script is being called before I can finish to take another photo, so everything is messed up here. I have already tried with different threads but it does not work well either.

My python script ends with a return statement (as you recommend in order to let a program finishes), but it seems like it does not wait the explicit call from my Java code. Is there a way to open and close the Python session for each of the times I want to run the script? I think there should be a better fix because I guess this solution would not be the best one in terms of efficiency.

**Comment by mhsmith** [comment]
Please post the following code, or at least a detailed explanation:

* What is `takePicture` doing, and how is `currentPhotoPath` assigned? Are you taking photos with the camera, or are you loading them from pre-existing files? 

* How is your `predict` function passing the image to keras `load_img`?

**Comment by mhsmith** [comment]
Are you sure it's executing well with the first image? Try adding some [Logcat](https://developer.android.com/studio/debug/am-logcat.html) calls, because `System.out.println` does nothing on Android.

**Comment by alexcarnero97** [comment]
I am taking the photos with the camera and the currentPhotoPath variable is assigned in the takePicture() workflow as shown below:

    // Creates an unique image file name
    private File createImageFile() throws IOException {
        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String imageFileName = "Backup_" + timeStamp;
        File storageDir = getExternalFilesDir(Environment.DIRECTORY_PICTURES);
        File image = File.createTempFile(imageFileName,".jpg", storageDir);

        // Save a file: path for use with ACTION_VIEW intents
        currentPhotoPath = image.getAbsolutePath();
        return image;
    }

    // Takes a picture and creates the file
    private void takePicture() {
        Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        // Ensure that there's a camera activity to handle the intent
        if (takePictureIntent.resolveActivity(getPackageManager()) != null) {
            // Create the File where the photo should go
            File photoFile = null;
            try {
                photoFile = createImageFile();
            } catch (IOException ex) {
                // Error occurred while creating the File
                ex.printStackTrace();
            }
            // Continue only if the File was successfully created
            if (photoFile != null) {
                Uri photoURI = FileProvider.getUriForFile(this,"com.example.android.fileprovider", photoFile);
                takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, photoURI);
                startActivityForResult(takePictureIntent, REQUEST_TAKE_PHOTO);
            }
        }
    }

This is my predict function:

    from tensorflow.keras.preprocessing.image import img_to_array, load_img
    from tensorflow.keras.models import load_model
    import numpy as np
    import pickle
    import cv2
    from os.path import dirname, join
    
    def predict(imagePath):
        # load our object detector and label binarizer from disk
        modedlfilename = join(dirname(__file__), "model.h5")
        model = load_model(modedlfilename)
        lbfilename = join(dirname(__file__), "lb.pickle")
        lb = pickle.loads(open(lbfilename, 'rb').read())
    
        # load the input image (in Keras format) from disk and preprocess it,
        # scaling the pixel intensities to the range [0, 1]
        image = load_img(imagePath, target_size=(224, 224))
        image = img_to_array(image) / 255.0
        image = np.expand_dims(image, axis=0)
    
        # predict the bounding box of the object along with the class label
        (boxPreds, labelPreds) = model.predict(image)
        (startX, startY, endX, endY) = boxPreds[0]
    
        # determine the class label with the largest predicted probability
        i = np.argmax(labelPreds, axis=1)
        label = lb.classes_[i][0]
    
        # load the input image (in OpenCV format) and grab its dimensions
        image = cv2.imread(imagePath)
        (h, w) = image.shape[:2]
    
        # scale the predicted bounding box coordinates based on the image dimensions
        startX = int(round(startX * w))
        startY = int(round(startY * h))
        endX = int(round(endX * w))
        endY = int(round(endY * h))
    
        bbox = [startX, startY, endX, endY]
    
        result = [label, bbox]
    
        return result

I am able to see the response from my predict function using System.out.println(), and yes, it is executing well with the first image. The problem appears when I try to call predict after I have already called it for the first time.

**Comment by mhsmith** [comment]
When using `ACTION_IMAGE_CAPTURE` you need to implement `onActivityResult` to be notified when the image is available. Please search for examples of this elsewhere.

**Comment by alexcarnero97** [comment]
Thank you!!
