### ISSUE TITLE
Failed to install any library

### ISSUE THREAD

**Issue by Ultramarine714** [chaquo/chaquopy#486]
Chaquopy version :
com.chaquo.python:gradle:9.1.0

build.gradle file :
apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.mandarin_tones_recognization"

        python {
            pip {
                install "numpy"
            }
        }

        sourceSets {
            main {
                python{
                    srcDirs = ["src/main/python"]
                }
            }
        }
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python{
            buildPython "/Applications/Python3.7/IDLE.app/Contents/MacOS/IDLE"
        }
    }

I don't know what reason cause this, it seems should not be capitalized 
> Task :mandarin_tones_recognization:preBuild UP-TO-DATE
> Task :mandarin_tones_recognization:preDebugBuild UP-TO-DATE
> Task :mandarin_tones_recognization:checkDebugManifest
> Task :mandarin_tones_recognization:generateDebugBuildConfig
> Task :mandarin_tones_recognization:compileDebugAidl NO-SOURCE
> Task :mandarin_tones_recognization:compileDebugRenderscript NO-SOURCE
> Task :mandarin_tones_recognization:extractPythonBuildPackages

> Task :mandarin_tones_recognization:generateDebugPythonRequirements FAILED
Error: option -S not recognized

USAGE: idle  [-deins] [-t title] [file]*
       idle  [-dns] [-t title] (-c cmd | -r file) [arg]*
       idle  [-dns] [-t title] - [arg]*

  -h         print this help message and exit
  -n         run IDLE without a subprocess (DEPRECATED,
             see Help/IDLE Help for details)

The following options will override the IDLE 'settings' configuration:

  -e         open an edit window
  -i         open a shell window

The following options imply -i and will open a shell:

  -c cmd     run the command in a shell, or
  -r file    run script from file

  -d         enable the debugger
  -s         run $IDLESTARTUP or $PYTHONSTARTUP before anything else
  -t title   set title of shell window

A default edit window will be bypassed when -c, -r, or - are used.

[arg]* are passed to the command (-c) or script (-r) in sys.argv[1:].

Examples:

idle
        Open an edit window or shell depending on IDLE's configuration.

idle foo.py foobar.py
        Edit the files, also open a shell if configured to start with shell.

idle -est "Baz" foo.py
        Run $IDLESTARTUP or $PYTHONSTARTUP, edit foo.py, and open a shell
        window with the title "Baz".

idle -c "import sys; print(sys.argv)" "foo"
        Open a shell window and run the command, passing "-c" in sys.argv[0]
        and "foo" in sys.argv[1].

idle -d -s -r foo.py "Hello World"
        Open a shell window, run a startup script, enable the debugger, and
        run foo.py, passing "foo.py" in sys.argv[0] and "Hello World" in
        sys.argv[1].

echo "import sys; print(sys.argv)" | idle - "foobar"
        Open a shell window, run the script piped in, passing '' in sys.argv[0]
        and "foobar" in sys.argv[1].

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mandarin_tones_recognization:generateDebugPythonRequirements'.
> Process 'command '/Applications/Python3.7/IDLE.app/Contents/MacOS/IDLE'' finished with non-zero exit value 2

**Comment by mhsmith** [comment]
`buildPython` should be the path to the actual Python executable, not IDLE.

**Comment by Ultramarine714** [comment]
Thanks for the reply! I am using the mac os, and i can run the script with simple main function, so i suppose the path is workable, but i run into problem when install library. you can see the error is "option -S is not recognized". I do not know what is that mean

**Comment by Ultramarine714** [comment]
Oh, i was wrong, i figure it out by changing the path, thanks!
