### ISSUE TITLE
install pythonnet failed

### ISSUE THREAD

**Issue by sos418** [chaquo/chaquopy#489]
#### Chaquopy version

9.1.0
#### Relevant parts of your build.gradle file

python: 3.9.0
ndk: abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
#### Describe your issue

Install **pythonnet** failed, error message: Chaquopy cannot compile native code

```
  building 'clr' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
  Command "/usr/local/bin/python3.9 -u -S -c "import setuptools, tokenize;__file__='/private/var/folders/z9/7tpfgb293lxbgx7y86zt1pcm0000gn/T/pip-install-51yqcgs_/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/z9/7tpfgb293lxbgx7y86zt1pcm0000gn/T/pip-wheel-ugtcw9wx --python-tag py3" failed with error code 1 in /private/var/folders/z9/7tpfgb293lxbgx7y86zt1pcm0000gn/T/pip-install-51yqcgs_/pythonnet/
ERROR: Failed to install pythonnet from https://files.pythonhosted.org/packages/f7/18/be276f27f649199563a59561623c0c008e72bbcb6ecb8b2ca0404a741ae1/pythonnet-2.5.2.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
```
<img width="971" alt="截圖 2021-05-01 下午2 47 56" src="https://user-images.githubusercontent.com/13904119/116774040-3b2ed380-aa8c-11eb-83bf-bd0196d75af3.png">

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but you can subscribe to this issue for any future updates. And if anyone else wants it too, please click the thumbs-up button above.

**Comment by mhsmith** [comment]
This package is for interfacing with the .NET CLR, so I don't see how it could be usable on Android. Even if you have a .NET installation on your development machine, there's no way you could access it from an app running in an Android emulator.

If there's some other way this package could be useful, please comment below and I may reopen the issue.
