### ISSUE TITLE
how to implement flask in android studio 

### ISSUE THREAD

**Issue by deepik27** [chaquo/chaquopy#492]
This is my python file 

```
import flask

app = flask.Flask(__name__)
app.config["DEBUG"] = True


@app.route('/', methods=['GET'])
def home():
    print ("Chaquopy api lauvhed0")
    return "<h8>Hello world</h8>"

if __name__ == '__main__':
    app.run()
```

How i can display hello world using chaquopy with flask in andriod studio emulator ?

**Comment by deepik27** [comment]
I have used webview in main activity.java file but it's not working can u tell me intergrate flask api in main activity.java file using chaquopy

**Comment by mhsmith** [comment]
From #493:

> i have a flask api code and integrated in andriod studio using chaquopy when i run andriod studio the local adresss host open google chrome in emulator, can you suggest me some ideas on this please it will be great help to me
>
> Actually i have ran python flask api file in visual studio and took that host address and wrote java code it worked, but what i need is python file also should be in android studio, how can i implement this please reply me

**Comment by mhsmith** [comment]
>I have used webview in main activity.java file but it's not working

I can't help you with such a vague description. What exactly did you do, and what exactly happened?

I assume `app.run` will start a webserver, so check the Flask documentation to find what address and port that server will run on, and point your webview at it.

Also, if `app.run` is a blocking function, you'll have to call it on a background thread to keep your app responsive. The thread can be created either in Java or Python.

**Comment by deepik27** [comment]
This is the python file 

import flask

app = flask.Flask(__name__)
app.config["DEBUG"] = True


@app.route('/', methods=['GET'])
def home():
    print ("Chaquopy api lauvhed0")
    return "<h8>Hello world</h8>"

if __name__ == '__main__':
    app.run()

the adrdress is 192.168.1.2:5000/

This address I used in webview but its not displayed

this is the mainactivity.java file is here 
============================

package com.example.webview_api;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.webkit.WebView;
import android.webkit.WebSettings;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        WebView webView = (WebView) findViewById(R.id.webView);
        webView.loadUrl("http://192.168.1.2:5000/");
        webView.getSettings().setAllowUniversalAccessFromFileURLs(true);


        webView.getSettings().setAllowFileAccessFromFileURLs(true);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setBuiltInZoomControls(true);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setDisplayZoomControls(false);
        webView.setVerticalScrollBarEnabled(true);
        webView.getSettings().setUseWideViewPort(true);
        webView.setHorizontalScrollBarEnabled(true);


    }
}


Question 1 : 

Actually how we should do when we use flask api in chaquopy  in andriod studio and how to  return the data to the mainactivity java file this is my doubt and i am new to this field so

**Comment by mhsmith** [comment]
> the adrdress is 192.168.1.2:5000/
>
> This address I used in webview but its not displayed

What is displayed? An error? A blank screen? And what happens if you visit the URL in Chrome on the same Android device?

According to the [Flask documentation](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.run), the default address is 127.0.0.1. Have you done anything to change that?

**Comment by deepik27** [comment]
I think you are not understanding my question, Actually u have showed us matplotlib example integration with andriod studio using chaquopy, like that only how can we implement flask api example integration with andriod studio using chaquopy how can we implement ?

**Comment by mhsmith** [comment]
Sorry, I've never used Flask myself, so I don't have any example.

**Comment by mhsmith** [comment]
However, if you search for "flask" in this issue tracker, you'll find some examples written by other users.
