### ISSUE TITLE
I have doubt using chaquopy in flask api

### ISSUE THREAD

**Issue by deepik27** [chaquo/chaquopy#493]
i have a flask api code and integrated in andriod studio using chaquopy when i run andriod studio the local adresss host open google chrome in emulator, can you suggest me some ideas on this please it will be great help to me

Actually i have ran python flask api file in visual studio and took that host address and wrote java code it worked, but what i need is  python file also should be in android studio, how can i implement this please reply me 

Thanks in advance

**Comment by mhsmith** [comment]
Please do not create multiple issues about the same thing, it will only slow down my response. I'll answer you in #492 later today.
