### ISSUE TITLE
How we can set license key & other dependency into the Android library module?

### ISSUE THREAD

**Issue by sw-tt-hasmukhbhadani** [chaquo/chaquopy#496]
We are going to use chaquopy library in our Android library module. As per your document, it says that add license key into the local.properties of the app side. But we want to use it in the library project, not on the app side. the reason behind this, we will use our library for multiple projects. How we can achieve this? Kindly provide suggestions.

At the same time, I want to add all kinds of chaquopy's dependency into the android library module rather than the top-level Gradle of the application so how I can do it? Please provide the solution for that as well.

Just for your kind information, we are using chaquopy v9.1.0.

Waiting for your prompt reply.

Thanks in advance.

**Comment by mhsmith** [comment]
> As per your document, it says that add license key into the local.properties of the app side.

If you're using Chaquopy in a library module, you should add the license key to the local.properties file of the project that contains the library, which might not be the same project that contains the app module. Sorry if that was unclear, I'll try to improve the wording on [the website](https://chaquo.com/chaquopy/license/).

> we will use our library for multiple projects. How we can achieve this? 

As [the website](https://chaquo.com/chaquopy/license/) says, when you build the library, you need to specify the ID of the app that it will be built into. If you want to use it in multiple apps, you'll have to build it multiple times and change the `chaquopy.applicationId` in local.properties each time.

> I want to add all kinds of chaquopy's dependency into the android library module rather than the top-level Gradle of the application so how I can do it? 

All the Chaquopy settings in build.gradle can be used in a library module in just the same way as an app module.

**Comment by sw-tt-hasmukhbhadani** [comment]
Thanks for the quick replay,

As per your suggestion, I have put all the dependencies into the module's build.gradle file but I am getting the below error.

_org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.chaquo.python'] was not found_

**Module's build.gradle**

_buildscript {
    repositories {
        google()
        jcenter()
        //Below maven is for Chaquo python lib
        maven { url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath "com.chaquo.python:gradle:9.1.0"
    }
}
plugins {
    id 'com.android.library'
    id 'com.chaquo.python'
}_

Let me know your feedback.

Thanks in advance.

**Comment by mhsmith** [comment]
As [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#basic-setup) says, the `buildscript` block doesn't go in the module build.gradle file, it goes in the project's top-level build.gradle file.
