### ISSUE TITLE
'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by Yashaswi-Anand** [chaquo/chaquopy#499]
if I execute python file in vs code then give desire output but in android  , it is not working and show "None type attribute error".
   
![Screenshot (10)](https://user-images.githubusercontent.com/68678601/118439660-06fe1880-b704-11eb-9906-0f9dd2402dcc.png)

def cvdata():
     iv='E:/Apps/KotlinApps/DigitPredictor/app/src/main/res/drawable/untitled.png'
    img = cv2.imread(iv,1)
    n=img.size
    return str(n)

**Comment by mhsmith** [comment]
An Android app can't directly access your development machine's filesystem, even if it's running on an emulator. The easiest way to load data files is to put them in the Python source directory, then follow the instructions in the ["data files"](https://chaquo.com/chaquopy/doc/current/android.html#android-data) section of the documentation.
