### ISSUE TITLE
Python-flint

### ISSUE THREAD

**Issue by joantyry** [chaquo/chaquopy#502]
Is python-flint (Fast Library for Number Theory )available for Chaquopy?

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but you can subscribe to this issue for any future updates. And if anyone else wants it too, please click the thumbs-up button above.

**Comment by joantyry** [comment]
Is it possible to add this package? I am working on a project which requires this package.

**Comment by mhsmith** [comment]
It doesn't look popular enough to justify us building it. But if you'd like to build it yourself, you could license our package build tool, which was used to build everything in our [native package repository](https://chaquo.com/pypi-7.0/). The cost of this tool is $250 -- this is separate to the license for Chaquopy itself. If you're interested in this, please [email us](https://chaquo.com/chaquopy/contact/) for more details.

From looking at python-flint, and the similar package flint-py, it looks like you'd have to build not only the Python package, but also the native libraries flint, arb, mpfr and mpir. I think it would be possible, but it could be a bit of work.

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be adding it in the foreseeable future. If anyone else is interested, please click the thumbs-up button above and post a comment, and I'll reopen the issue.

However, the package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add it to the public repository.
