### ISSUE TITLE
Beep sound not working

### ISSUE THREAD

**Issue by Vishvajeet590** [chaquo/chaquopy#503]
How can we add beep sound in python for chaquopy. Tried Libraires like SOX playsound  none of them worked. Even print('\a')  or   print('\007') are not working.

**Comment by mhsmith** [comment]
I'm not aware of any Python sound library which supports Android. So if you want to make sounds from Python code, you'll have to call one of the Android audio APIs directly, via the [Chaquopy Python API](https://chaquo.com/chaquopy/doc/current/python.html).

**Comment by Vishvajeet590** [comment]
Thanks. I did that only.
