### ISSUE TITLE
Error importing python requests library

### ISSUE THREAD

**Issue by Latouchay** [chaquo/chaquopy#511]
#### Chaquopy version
9.1

#### Python Version
3.8

#### Android Gradle Version
4.1.1

#### Describe your issue
I am getting a build error when trying to import requests. I receive the following error when building the project: Execution failed for task ':app:generateDebugPythonRequirements'.
> A problem occurred starting process 'command 'C:/Users/Lucas/AppData/Local/Programs/Python/Python38''. Please set buildPython to your Python executable path. See https://chaquo.com/chaquopy/doc/current/android.html#buildpython.

Here is my defaultConfig in gradle:

        python{
            pip{
                install "requests"
            }
            buildPython "C:/Users/Lucas/AppData/Local/Programs/Python/Python38"
        }

This build error only occurs when using the pip{install "requests"}, if I were to delete that line, the build error disappears. However, I require requests for my python script. Any idea what could be wrong?

**Comment by mhsmith** [comment]
`buildPython` should be set to the path of the actual python executable, not the directory that contains it.
