### ISSUE TITLE
Failed to install scikit-learn==0.20.2

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#512]
_Originally posted by @mdamaan08 in https://github.com/chaquo/chaquopy/issues/509#issuecomment-872456307_

Failed to install scikit-learn==0.20.2 from https://files.pythonhosted.org/packages/49/0e/8312ac2d7f38537361b943c8cde4b16dadcc9389760bb855323b67bac091/scikit-learn-0.20.2.tar.gz.

Please update the solution ASAP.

**Comment by mhsmith** [comment]
We have the following newer versions of scikit-learn, please use one of them instead:

* 0.22.1
* 0.23.2
* 0.24.1

**Comment by mdamaan08** [comment]
One of the NLP model was trained in scikit-learn==0.20.2 version.
Training code is missing,I have the requirement.txt and trained model with
.joblib extension.
To make that code running i need the above version!!

**Comment by mhsmith** [comment]
I know the [scikit-learn documentation](https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations) says that creating a model in one version of scikit-learn and loading on another isn't officially supported, but have you tried it anyway? And if it failed, what was the error message?

We won't build an old version of a package just for one person, but if you'd like to try building it yourself, you could license our package build tool, which was used to build the [scikit-learn wheels](https://chaquo.com/pypi-7.0/scikit-learn/) in our repository. It runs on Linux x86_64, and comes with full instructions, and I'll also include the build processes for all the versions of scikit-learn we've ever released. The price of the tool is $250 (this is separate to the license of Chaquopy itself). If you'd like to buy it, please [send us an email](https://chaquo.com/chaquopy/contact/).

As mentioned in #168, the scikit-learn documentation used to say "dumping a model on one architecture and loading it on another architecture is not supported". However, that's now changed to "pickled models should be portable across architectures assuming the same versions of dependencies and Python are used". But I don't know in what version of scikit-learn that was fixed. If it was later than 0.20.2, and your model was generated on x86_64, for example, then you still might not be able to load it on any architecture other than x86_64, even if the version numbers are the same.

One workaround might be to load the model file in version 0,20.2, on a machine with a compatible architecture, and then save it in a more portable file format. I have no personal experience of this, so I suggest you search the scikit-learn issue tracker for advice.

**Comment by Meesh011** [comment]
Failed to install scikit-learn from https://files.pythonhosted.org/packages/da/b4/5d7b9f64d2c3795ac37da3d8bc303be7950e575ec21ac7d0eb9de34fe0d5/scikit-learn-1.4.1.post1.tar.gz#sha256=93d3d496ff1965470f9977d05e5ec3376fb1e63b10e4fda5e39d23c2d8969a30.
 ->-> any solution to the above??

**Comment by mhsmith** [comment]
See #1115.
