### ISSUE TITLE
Failed install tensorflow 1.10.1 in chaquopy 9.1.0 

### ISSUE THREAD

**Issue by nhutthanh340** [chaquo/chaquopy#521]
#### Chaquopy version
com.android.tools.build:gradle:4.1.1
com.chaquo.python:gradle:9.1.0
#### Relevant parts of your build.gradle file
python 3.6.5
tensorflow==1.10.1
#### Describe issue
Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
![image](https://user-images.githubusercontent.com/36669308/127242179-56ad1921-738d-433a-925e-667e96165589.png)

**Comment by nhutthanh340** [comment]
I have the project Unity export to Android Studio. I have integrated project with chaquopy 6.3.0, it working but too slow startup (5-6s). So, i decide to choose chaquopy 9.1.0, it working perfect, but i do not install tensorflow 1.10.1 (my python project only working on python 3.6 and tensorflow 1.0 not tensorflow 2.0).
How can anyone help me, please?
Thanks

**Comment by mhsmith** [comment]
Sorry, we currently only provide TensorFlow 1.10.1 for Python 3.6, and TensorFlow 2.1.0 for Python 3.8.  You can see the corresponding Chaquopy versions [here](https://chaquo.com/chaquopy/doc/current/versions.html). Chaquopy 6.3.0 was the last version to come with Python 3.6, so the "cp36" packages in the `pypi-2.1` and `pypi-6.2` repositories cannot be used with newer versions.

The version of `buildPython` is not relevant here: that's only used to run pip, not to run your actual app.

So you'll have to either:

* Live with the slower performance of the older Chaquopy version, or
* [Migrate your TensorFlow 1 code to TensorFlow 2](https://www.tensorflow.org/guide/migrate). The `tensorflow.compat.v1` API is supposed to make this easy.
