### ISSUE TITLE
Failed to install pytesseract

### ISSUE THREAD

**Issue by Penguen-jpg** [chaquo/chaquopy#522]
#### Chaquopy version

com.chaquo.python:gradle:9.1.0
com.android.tools.build:gradle:4.1.1

#### Relevant parts of your build.gradle file
setuptools
Pillow
pytesseract

#### Describe your issue

![image](https://user-images.githubusercontent.com/69071861/127254841-935cd8ec-4e8c-45ab-9272-434cebabb7d4.png)
![image](https://user-images.githubusercontent.com/69071861/127254876-eede28d6-0d4b-48c4-98e6-766660cfa481.png)
![image](https://user-images.githubusercontent.com/69071861/127254898-1cbdfd5a-ae81-4c81-9e45-dfc6667cc06c.png)
![image](https://user-images.githubusercontent.com/69071861/127254925-c9edcc66-ca13-4f44-91e5-f4b32d463dce.png)

**Comment by mhsmith** [comment]
See #220, and please search for existing issues before creating new ones.
