### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find "libcrypto_chaquopy.so"

### ISSUE THREAD

**Issue by workhoust** [chaquo/chaquopy#524]
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dogen.usbcameradogen-o_5BJXEejE6VhkyZBtuisg==/base.apk"],nativeLibraryDirectories=[/data/app/com.dogen.usbcameradogen-o_5BJXEejE6VhkyZBtuisg==/lib/arm, /data/app/com.dogen.usbcameradogen-o_5BJXEejE6VhkyZBtuisg==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /oem/lib]]] couldn't find "libcrypto_chaquopy.so"`
```
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.chaquo.python.android.AndroidPlatform.loadNativeLibs(AndroidPlatform.java:242)
        at com.chaquo.python.android.AndroidPlatform.getPath(AndroidPlatform.java:109)
        at com.chaquo.python.Python.start(Python.java:50)
```

**Comment by mhsmith** [comment]
What is the version of com.chaquo.python:gradle in your app's top-level build.gradle file?

What devices does the problem occur on? And are there any other devices where the problem does NOT occur?

Have you tried running running Build > Clean Project, as mentioned at https://github.com/chaquo/chaquopy/issues/117#issuecomment-761181152?

**Comment by mhsmith** [comment]
If this is still a problem, please post the requested information and I'll reopen the issue.

**Comment by arvinsen** [comment]
I encountered this problem too,
version: "com.chaquo.python:gradle:8.0.1"
device: Amazon - KFTRWI,    Google Pixel 3 XL(once)
android verion: both android 9 with this two devices

**Comment by arvinsen** [comment]
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.PinusBungeana.FastVideo-C-7GfwN72Y0D7N1CitIOTg==/base.apk"],nativeLibraryDirectories=[/data/app/com.PinusBungeana.FastVideo-C-7GfwN72Y0D7N1CitIOTg==/lib/arm64, /system/lib64]]] couldn't find "libcrypto_chaquopy.so"    
Looking forward to your reply, thanks.

**Comment by mhsmith** [comment]
This may be related to https://github.com/chaquo/chaquopy/issues/117#issuecomment-761181152. What is the `abiFilters` line in your build.gradle file? 

And have you tried running Build > Clean Project in Android Studio, then reinstalling the app?

**Comment by arvinsen** [comment]
ndk { abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a' }
this is my abiFilters in build.gradle.

**Comment by mhsmith** [comment]
And have you tried running Build > Clean Project in Android Studio, then reinstalling the app?
