### ISSUE TITLE
pip install not working with chaquopy matplotlib example given in documentation.

### ISSUE THREAD

**Issue by sushmasrinivas57** [chaquo/chaquopy#525]
**#### Chaquopy version - 9.1.0**
**python version - 3.8.6**

Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting matplotlib
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pypi-7.0/matplotlib/
  
_****Could not find a version that satisfies the requirement matplotlib (from versions: )****_
No matching distribution found for matplotlib
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'py'' finished with non-zero exit value 1
 

BUILD FAILED in 30s
5 actionable tasks: 4 executed, 1 up-to-date

#### Describe your issue

Not able to install any python module. I want matplotlib as of now. But not able to install it. Tried with whl files also.TRied with and without build python option. Please help me with this
My python version is 3.8.6
Chaquopy version - 9.1.0

And here is my gradle file

 defaultConfig {
        applicationId "com.chaquo.myapplication"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        sourceSets {
            main {
                python {
                    srcDirs = ["src/main/python"]
                }
            }
        }

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {
           // buildPython "C:/Users/svanam/AppData/Local/Programs/Python/Python38/python.exe"
            pip {
                install "matplotlib"
            }
        }
    }

**Comment by mhsmith** [comment]
Are you able to visit https://pypi.org/ in a web browser on the same machine?

Does your Internet connection have a proxy or firewall which could be interfering?

**Comment by sushmasrinivas57** [comment]
Yes, I am able to visit [](https://pypi.org/ ) on my machine.
 My internet connection has proxy which might be causing the issue.
Please tell how to resolve that if we have proxy issues.

**Comment by mhsmith** [comment]
Try using the [`pip { options }`](https://chaquo.com/chaquopy/doc/current/android.html#requirements) setting to pass the [`--proxy`](https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server) option to pip.

**Comment by sushmasrinivas57** [comment]
I tried adding this proxy for pip install 

python {
           // buildPython "C:/Users/svanam/AppData/Local/Programs/Python/Python38/python.exe"
            pip {
                options "--proxy", "http://proxy-web.xxxx.com:80"
                options "--trusted-host", "files.pythonhosted.org"
                options "--trusted-host", "pypi.org"
                options "--trusted-host", "pypi.python.org"
                install "matplotlib"
            }
        }

And here is the build output 

Collecting matplotlib
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))': /pypi-7.0/matplotlib/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))': /pypi-7.0/matplotlib/
  Could not fetch URL https://chaquo.com/pypi-7.0/matplotlib/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='chaquo.com', port=443): Max retries exceeded with url: /pypi-7.0/matplotlib/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))) - skipping
  Downloading https://files.pythonhosted.org/packages/60/d3/286925802edaeb0b8834425ad97c9564ff679eb4208a184533969aa5fc29/matplotlib-3.4.2.tar.gz (37.3MB)
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/certifi/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!
    Couldn't find index page for 'certifi' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!
    No local packages or working download links found for certifi>=2020.06.20
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\svanam\AppData\Local\Temp\pip-install-rmw2fj4x\matplotlib\setup.py", line 258, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\setuptools\__init__.py", line 144, in setup
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\setuptools\__init__.py", line 139, in _install_setup_requires
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\setuptools\dist.py", line 717, in fetch_build_eggs
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\pkg_resources\__init__.py", line 782, in resolve
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\pkg_resources\__init__.py", line 1067, in best_match
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\pkg_resources\__init__.py", line 1079, in obtain
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\setuptools\dist.py", line 787, in fetch_build_egg
      File "C:\Users\svanam\Downloads\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\setuptools\command\easy_install.py", line 673, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('certifi>=2020.06.20')
    
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\svanam\AppData\Local\Temp\pip-install-rmw2fj4x\matplotlib\
    Edit setup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
      matplotlib: yes [3.4.2]
          python: yes [3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC
                      v.1927 64 bit (AMD64)]]
        platform: yes [win32]
           tests: no  [skipping due to configuration]
          macosx: no  [Mac OS-X only]
    
    
    ----------------------------------------
ERROR: Failed to install matplotlib from https://files.pythonhosted.org/packages/60/d3/286925802edaeb0b8834425ad97c9564ff679eb4208a184533969aa5fc29/matplotlib-3.4.2.tar.gz.
Failed to install matplotlib from https://files.pythonhosted.org/packages/60/d3/286925802edaeb0b8834425ad97c9564ff679eb4208a184533969aa5fc29/matplotlib-3.4.2.tar.gz.

**Comment by mhsmith** [comment]
If you found it necessary to use `--trusted-host` for pypi.org, then you'll probably have to do the same for chaquo.com as well.

**Comment by sushmasrinivas57** [comment]
python {
            pip {
                options "--proxy", "http://proxy-web.micron.com:80"
                options "--trusted-host", "files.pythonhosted.org"
                options "--trusted-host", "pypi.org"
                options "--trusted-host", "pypi.python.org"
                options "--trusted-host", "chaquo.com"
                install "matplotlib"
            }
        }

It's working now.Thank you so much for the support.
