### ISSUE TITLE
My android app is 336 mb while using chaquopy 

### ISSUE THREAD

**Issue by deepik27** [chaquo/chaquopy#530]
How i ca reduce the size of the mb, if i didnt use chaquopy it will be 25MB suppose if i use it increases to 336MB only simple camera bgr to gray conversion i did for that only it is increased suggest me ?

**Comment by mhsmith** [comment]
Your other issue said you were using TensorFlow, so both of the suggestions in the [FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#how-can-i-make-my-app-smaller) should be helpful.
