### ISSUE TITLE
Scipy==1.1.0 is not able to install in android studio

### ISSUE THREAD

**Issue by deepik27** [chaquo/chaquopy#532]
Hi, 

1) I want to install in scipy==1.1.0 version and my python version is 3.7.3 and i tired in 3.8 and 3.9 also but i am not able to install that version, suppose if i installed other version of scipy i am getting this error below i have attached the image and actually i want to import imresize, from scipy.misc import imresize and i tried with from scipy import misc and misc.imresize nothing is working 
![Screenshot_2021-08-16-15-14-10-057_com miui bugreport](https://user-images.githubusercontent.com/64435256/129562241-818d9b4b-c811-45ff-965f-1c8737d8efc8.jpg)

2) Can we create in android studio python virtual enviroment, in python virtual env it works this statement from scipy.misc import imresize

3) Suppose if i use this statement **"from skimage.transform import resize"** instead of this f**rom scipy.misc import imresize**,  this line is not working   result = **cv2.addWeighted(image,1,lane_image,1,0)**, i am getting error has 
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-eirhwqtr/opencv/modules/core/src/arithm.cpp:672: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'arithm_op'

**Comment by mhsmith** [comment]
`imresize` was [removed in SciPy version 1.3.0](https://docs.scipy.org/doc/scipy/release.1.3.0.html#scipy-interpolate-changes). The current version of Chaquopy only supports [version 1.4.1](https://chaquo.com/pypi-7.0/scipy/), but if you go back to Chaquopy 6.3.0 then you can choose [version 1.0.1 or 1.1.0](https://chaquo.com/pypi-2.1/scipy/).

> Can we create in android studio python virtual enviroment, in python virtual env it works this statement from scipy.misc import imresize

Only the packages listed in your build.gradle file's `pip` block are available to your app. Packages installed on your build machine will not have any effect.

> cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-eirhwqtr/opencv/modules/core/src/arithm.cpp:672: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'arithm_op'

This probably has nothing to do with Chaquopy, so please search for help elsewhere. If the same code works on other platforms but not on Chaquopy, please post the full stack trace and the relevant sections of your code.

**Comment by deepik27** [comment]
Ok thank you for your Guidance
