### ISSUE TITLE
Getting getModule​(@NotNull String name) response in delay in device sleep/killed mode

### ISSUE THREAD

**Issue by msh-nayan** [chaquo/chaquopy#533]
Hello, 
Greetings. Thanks for the Chaquopy library.

In my project requirement, I need to invoke Python script from my Android application. I've set alarm on a certain time & alarm is trigger on right time (even when the app is in killed mode). The problem, I'm having is that, when the application is in killed mode & alarm is trigger and then I invoke Python script (code is given below), then ".getModele(@NotNull String name)" does not returns immediately (when I wakes up device, then this method is executed)

```
if (!Python.isStarted()) {
    Python.start(new AndroidPlatform(context));
}
Log.e("TAG", "is_python_started : " + Python.isStarted());
Python python = Python.getInstance();
Log.e("TAG", "is_python_instance_null : " + (python == null));
PyObject pyObject = python.getModule("MODULE_NAME"));
Log.e("TAG", "is_pyObject_instance_null : " + (pyObject == null));
PyObject po = pyObject.callAttr(String key, Object... args);
Log.e("TAG", "is_po_instance_null : " + (po == null));
String poStr = po.toString();
Log.i(TAG, " value : " + poStr); 
```

The logs are I get is given below with the TIME 
**19/08/2021 10:05:27.593** >> is_python_started : true
**19/08/2021 10:05:27.595** >> is_python_instance_null : false
**19/08/2021 10:13:48.615** >> is_pyObject_instance_null : false
**19/08/2021 10:13:56.337** >> is_po_instance_null : false
**19/08/2021 10:13:56.343** >> value : "PROPER_RESPONSE_MODEL_AS_STRING"

As you see, `Python python = Python.getInstance()` is executed in **19/08/2021 10:05:27.595** but `PyObject pyObject = python.getModule("MODULE_NAME"))` is executed in **19/08/2021 10:13:48.615** (10:13 is the time when I woke up the device, i mean that time I turned on screen by pressing power button). 

is there anything in Chaquopy that it won't work when the device is in sleeping/killed mode? rather than getting immediate response, I'm getting response when I wake up the device.

Kindly response. 
Thanks & Regards

**Comment by mhsmith** [comment]
> is there anything in Chaquopy that it won't work when the device is in sleeping/killed mode?

Not as far as I'm aware. But I know that recent versions of Android have become a lot more aggressive about saving battery life by restricting what can happen when the device is asleep. So perhaps the amount of CPU or storage access required by the getModule call reached a limit and caused the app to be suspended until the device wakes up.

What method are you using to set the alarm? You might find the information in these pages useful:

* [Schedule tasks with WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager)
* [Guide to background processing](https://developer.android.com/guide/background)
* [Schedule repeating alarms](https://developer.android.com/training/scheduling/alarms) especially the mentions of "Doze mode"

**Comment by msh-nayan** [comment]
Thanks for the reply. 

I'm using `AlarmManager.setExactAndAllowWhileIdle(int type, long triggerAtMillis, PendingIntent operation)`

As I mentioned, alarm is trigger on the EXACT time (whether device is doze mode or app is in foreground/background) and I can catch it on `onReceive(Context context, Intent intent)` of `BroadcastReceiver` class. From that, I invoke my Python script but unfortunately (when the device is sleeping/screen is turned off) `.getModule("MODULE_NAME")` and `pyObject.callAttr(String key, Object... args)` is executed when the device wakes up.

I've set some other alarms and when those alarms are triggered, some other Google API (like nearby place API) is called and getting the response properly in every scenario.

**Comment by mhsmith** [comment]
Which version of Chaquopy are you using?

Which devices have you tested this with, and does it behave the same on all of them?

**Comment by msh-nayan** [comment]
I'm using **Chaquopy version 9.1.0**

I've tested on Huawei H-Mate 10 lite (Android version 8.0.0) and Redmi Note 5 (Android version 9)

on both device, getting the same behaviour.

**Comment by mhsmith** [comment]
Thanks for the information. I'd like to test this for myself: can you create a GitHub project with a minimal reproducible example?

**Comment by msh-nayan** [comment]
Thanks for the reply.

I'll create a GitHub project and will let you know.

**Comment by mhsmith** [comment]
If this is still a problem, please provide an example project as requested and I'll look into it.
