### ISSUE TITLE
Cannot install yfinance due to lxml prerequisite >4.5.1 where as chaquopy uses 4.4.2

### ISSUE THREAD

**Issue by trioli13** [chaquo/chaquopy#535]
#### Chaquopy version
9.1

#### Relevant parts of your build.gradle file
pip {
                install "numpy"
                install "yfinance"
                install "pandas"
            }

#### Describe your issue
When installing yfinance package, I have the below error. yfinance needs lxmx > 4.5.1 where as chaquopy uses 4.4.2 which is a 2019 version. How can I install a more recent lmxl version allowing to meet the prerequisites of yfinance?

Command "C:\Users\imber\AppData\Local\Programs\Python\Python38\python.exe -u -S -c "import setuptools, tokenize;__file__='C:\\Users\\imber\\AppData\\Local\\Temp\\pip-install-v5jhlxt9\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\imber\AppData\Local\Temp\pip-wheel-szwrulhw --python-tag py3" failed with error code 1 in C:\Users\imber\AppData\Local\Temp\pip-install-v5jhlxt9\lxml\
ERROR: Failed to install lxml>=4.5.1 from https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz (from yfinance).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Or try using one of the following versions, which are available as pre-built wheels: ['4.4.2'].
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
We can probably add a new version of lxml: I'll look into it and get back to you tomorrow.

**Comment by trioli13** [comment]
perfect. Thanks.

**Comment by mhsmith** [comment]
lxml version 4.6.3 is now available.
