### ISSUE TITLE
Could not find com.chaquo.python:target:2.7.10-2.

### ISSUE THREAD

**Issue by Waged** [chaquo/chaquopy#54]
Hi, I'm trying to use Chaquo  in a Mac Android studio from the code examples i found this error: 

    Could not find com.chaquo.python:target:2.7.10-2.
   Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/chaquo/python/target/2.7.10-2/target-2.7.10-2.pom
    https://dl.google.com/dl/android/maven2/com/chaquo/python/target/2.7.10-2/target-2.7.10-2-stdlib-     pyc.zip
    https://jcenter.bintray.com/com/chaquo/python/target/2.7.10-2/target-2.7.10-2.pom
    https://jcenter.bintray.com/com/chaquo/python/target/2.7.10-2/target-2.7.10-2-stdlib-pyc.zip
    https://chaquo.com/maven/com/chaquo/python/target/2.7.10-2/target-2.7.10-2.pom
    https://chaquo.com/maven/com/chaquo/python/target/2.7.10-2/target-2.7.10-2-stdlib-pyc.zip
Required by:
    project :

**Comment by mhsmith** [comment]
We didn't support using a pre-compiled Python standard library with Python 2.7.10.  I recommend you switch to [Python 2.7.15 (or preferably 3.6.5)](https://chaquo.com/chaquopy/doc/current/android.html#python-version). 

If for some reason you absolutely must use Python 2.7.10, you can try [disabling the compilation](https://chaquo.com/chaquopy/doc/current/android.html#bytecode-compilation), but note that this version has not been well-tested with the current version of Chaquopy and may have other bugs.
