### ISSUE TITLE
call superClass onStop() on application event onStop

### ISSUE THREAD

**Issue by PhilippeDou** [chaquo/chaquopy#540]
**The gradle version :** 

`    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.chaquo.python:gradle:6.0.0'`

**Implementation of onStop() call :**

       class MainActivity(static_proxy(AppCompatActivity)):
          def __init__(self):
             super(MainActivity, self).__init__()
           @Override(jvoid, [Bundle])
           def onCreate(self, state):
               AppCompatActivity.onCreate(self, state)
       
           @Override(jvoid, [])
           def onStop(self):
                **Here I have to add superClasse call**

When application is stopped or when an Intent Directory Choosser is called the python onStop() is correctly called. But the superclass should be called before make anything.
I have try 
       super.onStop()
       super().onStop()
       super(MainActivity, self).onStop()

For all of these cases I have an error : **'super' object has no attribute 'onStop'**

One solution would be to add the superclass call directly in MainActivity.java. But we can't add specific code (is overwrited during compilation).

Have you a solution to solve this problem ?

In advance best regards

**Comment by mhsmith** [comment]
As it says in [the documentation](https://chaquo.com/chaquopy/doc/current/python.html):

> To call through to the base class implementation of a method, use the syntax `SuperClass.method(self, args)`. Using `super` is not currently supported for Java methods, though it may be used in `__init__`.

For an example of this, see the [`onCreate`](https://github.com/chaquo/chaquopy/blob/35565ef4ce56492a5293cb7084559392f355b919/app/src/main/python/chaquopy/demo/ui_demo.py#L17) method in the demo app.
