### ISSUE TITLE
What is proguard rule for this lib

### ISSUE THREAD

**Issue by sw-tt-hasmukhbhadani** [chaquo/chaquopy#541]
We have already had a license key for this lib and implemented it into the project. We have used proguard in our project to secure our code.

Revied your documentation and git repository but not able to find proguard rules for this.

Kindly, provide proguard rules so we can add to the project.

Thanks in advance.

**Comment by mhsmith** [comment]
The Chaquopy plugin automatically adds its own ProGuard rules, so you don't need to do anything.
