### ISSUE TITLE
load model pickle

### ISSUE THREAD

**Issue by kunnncaqq** [chaquo/chaquopy#544]
```
f = open(join(dirname(__file__), 'ModelKNNF.pickle'))
import pickle
ModelKNNF.pickle = pickle.load(f)
```

'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

What do I have to do

**Comment by mhsmith** [comment]
Pickle files are binary, so you have to open the file in "rb" mode, as shown in the [pickle documentation](https://docs.python.org/3/library/pickle.html#examples).

**Comment by kunnncaqq** [comment]
when i read the file as rb
No such file or directory: 'ModelKNNF.pickle'

**Comment by kunnncaqq** [comment]
> Pickle files are binary, so you have to open the file in "rb" mode, as shown in the [pickle documentation](https://docs.python.org/3/library/pickle.html#examples).

when i read the file as rb
No such file or directory: 'ModelKNNF.pickle'

**Comment by kunnncaqq** [comment]
It is KNN models

**Comment by mhsmith** [comment]
_Originally posted by @kunnncaqq in https://github.com/chaquo/chaquopy/issues/546_

```
with open(''ModelKNNF.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    'ModelKNNF.pickle = pickle.load(f)
```

when i read the file as rb
No such file or directory: 'ModelKNNF.pickle'

**Comment by mhsmith** [comment]
You still need to use the `dirname(__file__)` technique, regardless of whether you're opening in binary mode or not.

Please don't create multiple issues for the same thing.

**Comment by kunnncaqq** [comment]
f = open(join(dirname(__file__), 'ModelKNNF.pickle'),'rb')
import pickle
KNNmodelf = pickle.load(f)

'list' object has no attribute 'predict'
What should I do?

**Comment by mhsmith** [comment]
I don't think that error has anything to do with the pickle loading code. Please search for the error on StackOverflow or Google and you'll find an answer.

**Comment by mhsmith** [comment]
Also, when posting code on GitHub, please use ` ``` ` to preserve the formatting, as shown [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
