### ISSUE TITLE
how to use Chaquopy transfer image data between kotlin and python

### ISSUE THREAD

**Issue by showkeyjar** [chaquo/chaquopy#548]
I have found that doc only contain Java API and Python API

but I can not found any that transfer image data between Kotlin and Python, 
how I can use those functions?
for example:
Kotlin -> Python

Kotlin

```
  private fun check(){
    val stream = ByteArrayOutputStream()   
    inputFace.compress(Bitmap.CompressFormat.PNG, 90, stream)    
    val py_image = stream.toByteArray()    
    val py: Python = Python.getInstance()    
    val pyobj: PyObject = py.getModule("report_lite").callAttr("gen_result", py_image)
  }
```

Python

```
  def gen_result(img):  
      img = np.array(img)  
      img_width = img.shape()[0]  
      img_height = img.shape()[1]  
      return jarray(jbyte)(img)
```

Python -> Kotlin

```
  var reportBitMap:Bitmap = Bitmap.createBitmap(pyobj.toJava(byte[].class)) ???
```

if those code right? or would you please provide a example?

**Comment by mhsmith** [comment]
Yes, that's roughly the correct approach. But you need to be careful to distinguish between arrays that contain raw bitmaps, versus arrays that contain encoded PNG files

if you're passing the image from Kotlin to Python as a PNG file, and you want to process it in Python as a bitmap, then you'll have to decode it using something like [`cv2.imdecode`](https://github.com/chaquo/chaquopy/issues/303#issuecomment-638155189).

Similarly, if you're passing an image from Python to Kotlin, you can either represent it as a raw 1-dimensional `int[]` array and pass it to `createBitmap`, or as a PNG file and pass it to `BitmapFactory.decodeByteArray`, as in [this example](https://github.com/chaquo/chaquopy-matplotlib).

**Comment by showkeyjar** [comment]
thanks for your reply, but I can't find how to send image data from kotlin to python.

I use these above codes, but throw python error:

com.chaquo.python.PyException: IndexError: tuple index out of range

**Comment by mhsmith** [comment]
I've already explained why your code won't work. You're passing the image from Kotlin to Python as a PNG file, so it's a 1-dimensional int8 array containing the compressed file, not a 2-dimensional array of pixels as your code seems to expect. 

Follow the link to `cv2.imdecode` above for an example of how to receive a PNG file correctly.

**Comment by showkeyjar** [comment]
ok, I fixed it, thanks again for your reply.

**Comment by haris-waqar123** [comment]
How can We send a list of images from kotlin to python to perform opencv operations ?

**Comment by mhsmith** [comment]
If you pass a Java array to a Python function, it will be received as an object that supports the standard Python sequence syntax as shown [here](https://chaquo.com/chaquopy/doc/current/python.html#arrays). 

Or if you pass a Java List, you can call the Java methods from Python, such as `size` and `get`.
