### ISSUE TITLE
Any alternatives for PyAudio?

### ISSUE THREAD

**Issue by gbdantoni** [chaquo/chaquopy#55]
The project I'm moving to Android requires PyAudio. Since there doesn't appear to be a version that runs on Android I'm planning to rewrite my code in Java to use the native Android audio capabilities, rather than calling PyAudio. I thought I'd check to see if anyone has any suggestions regarding this.

**Comment by mhsmith** [comment]
I'm not aware of any Python library that supports the Android audio API, so you will probably have to write something yourself. Chaquopy provides high-performance conversions between Java `byte[]` and Python `bytes` objects (search for "byte" on [this page](https://chaquo.com/chaquopy/doc/current/python.html)), so hopefully this will allow you to keep the bulk of your code in Python if that's what you want.
