### ISSUE TITLE
Failed to install jpegio

### ISSUE THREAD

**Issue by hjlogzw** [chaquo/chaquopy#553]
#### Chaquopy version
 chaquo 9.1

#### Devices or emulators where the issue happens
xiaomi M2006C3LC

#### Relevant parts of your code
Collecting Cython
  Using cached https://files.pythonhosted.org/packages/ec/30/8707699ea6e1c1cbe79c37e91f5b06a6266de24f699a5e19b8c0a63c4b65/Cython-0.29.24-py2.py3-none-any.whl
Collecting jpegio
  Using cached https://files.pythonhosted.org/packages/0b/12/8d4c0c165305c4ccd5f810e0ffe1fbda8e0345ceba4ce9b655be28057511/jpegio-0.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\AirForHj\AppData\Local\Temp\pip-install-3bc0j29p\jpegio\
      File "<string>", line 1, in <module>
      File "C:\Users\AirForHj\AppData\Local\Temp\pip-install-3bc0j29p\jpegio\setup.py", line 5, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'

#### Describe your issue
I want to install "jpegio", which need the "Cython" module.
 I do it this way  in build.gradle: 
 install "Cython"  
 install "jpegio"
But it did not work.
so what should I do ?

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be adding it in the foreseeable future.

However, the package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add it to the public repository.

If anyone else wants this package, please click the thumbs-up button above and post a comment, and I'll reopen the issue.

**Comment by mhsmith** [comment]
@IsakTheHacker: Thanks very much: I've built the new version and added it to our repository. 

Because this package was built against API level 21, it'll require Chaquopy 14.0.2 or later. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python`.
