### ISSUE TITLE
can't install KoNLPy library with cannot compile native code

### ISSUE THREAD

**Issue by HoWonJang** [chaquo/chaquopy#556]
when install "konlpy" in pip section  

ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/setup.py'"'"'; __file__='"'"'/private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-wheel-_mhipr0n --python-tag cp39
       cwd: /private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.9
  creating build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jcollection.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_classpath.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jio.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_pykeywords.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jproxy.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_gui.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/config.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jmethod.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/nio.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jstring.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/protocol.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/types.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/beans.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  ERROR: Command errored out with exit status 1:

  copying jpype/_jvmfinder.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/imports.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jcustomizer.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_core.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jthread.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jinit.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jarray.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jobject.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/dbapi2.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/pickle.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jclass.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jexception.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jpackage.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
  package init file 'jpype/_pyinstaller/__init__.py' not found (or not a regular file)
  creating build/lib.macosx-10.9-x86_64-3.9/jpype/_pyinstaller
  copying jpype/_pyinstaller/entry_points.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/_pyinstaller
  copying jpype/_pyinstaller/test_jpype_pyinstaller.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/_pyinstaller
  copying jpype/_pyinstaller/example.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/_pyinstaller
  copying jpype/_pyinstaller/hook-jpype.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/_pyinstaller
  copying jpype/_jio.pyi -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_core.pyi -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jcollection.pyi -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jthread.pyi -> build/lib.macosx-10.9-x86_64-3.9/jpype
  copying jpype/_jstring.pyi -> build/lib.macosx-10.9-x86_64-3.9/jpype
  running build_ext
  Call build extensions
  Using Jar cache
  copying native/jars/org.jpype.jar -> build/lib.macosx-10.9-x86_64-3.9
  Call build ext
  building '_jpype' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
  error: CCompiler.compile: Chaquopy cannot compile native code

  ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/setup.py'"'"'; __file__='"'"'/private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-wheel-_mhipr0n --python-tag cp39 Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/setup.py'"'"'; __file__='"'"'/private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-install-bc525oux/JPype1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/gd/14vt0mq135d6cmcv853mpv0c0000gn/T/pip-wheel-_mhipr0n --python-tag cp39 Check the logs for full command output.

ERROR: Failed to install JPype1 from https://files.pythonhosted.org/packages/57/4f/3cddc9b9cd892bbe098e5d48ed3a8aaa02dd3fa732612065fa6b0fab0062/JPype1-1.3.0.tar.gz (from duckling).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install JPype1 from https://files.pythonhosted.org/packages/57/4f/3cddc9b9cd892bbe098e5d48ed3a8aaa02dd3fa732612065fa6b0fab0062/JPype1-1.3.0.tar.gz (from duckling).

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python3'' finished with non-zero exit value 1

We have seen similar issues. However, there is no solution to the konlpy library, so I'm asking you again.
Please tell me the exact solution.
https://konlpy.org/en/latest/

**Comment by mhsmith** [comment]
Sorry, we still have no solution for this package. Please subscribe to #429 for future updates.
