### ISSUE TITLE
Getting Unable to open file error some some devices

### ISSUE THREAD

**Issue by msh-nayan** [chaquo/chaquopy#557]
Hello, 
Thanks for the library. 
We're using **paid** version of Chaquopy library (version **9.1.0**).

In our project, we've built a recommendation engine. We're using the following libraries (these libraries are added on app level gradle file)

```
python
{
       buildPython "/usr/bin/python3"
       buildPython "python3"
       pip {
             install "numpy"
             install "pandas"
             install "scikit-learn"
             install "tensorflow"
             install "h5py"
}
```

problem is for some devices, everything is working as expected but for devices we're getting the following error while invoking/executing Python scripts 

**Unable to open file (file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented')**

Devices that we're getting the above error 
Xiaomi Mi A3 (OS:11)
Oppo (OS: 11)

Devices that is working as expected our outcome (not getting above error)
Xiaomi Mi A2 (Os: 9)
Sony XperiaZ (OS: 9)
Huawei H-Mate 10 lite (OS : 8)

can you please help?
Thanks

**Comment by mhsmith** [comment]
Try setting `os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"` before running your code, as shown at https://github.com/h5py/h5py/issues/1804.

**Comment by msh-nayan** [comment]
Thanks for your support. 
Issue is fixed.
