### ISSUE TITLE
matplotlib.pyplot.specgram different spectrograms on native python vs chaquopy

### ISSUE THREAD

**Issue by kylevessPL** [chaquo/chaquopy#561]
matplotlib.pyplot.specgram generates different spectrogram images on python native vs chaquopy
Seems like chaqopy's native matplotlib version 3.1.2 generates kinda same but lower resolution ones.
Using librosa version 0.8.1 to load and resample audio file first.

**Steps to reproduce:**
```
x, sr = librosa.load(audio_path, mono=True, sr=16000)
plt.specgram(x, NFFT=2048, Fs=2, Fc=0, noverlap=128, cmap='inferno', sides='default',
             mode='default', scale='dB')
```
![python-native](https://user-images.githubusercontent.com/4037550/141459374-00f0673a-ebd5-4389-99e3-e135c2bc9e7c.png)
![chaquopy](https://user-images.githubusercontent.com/4037550/141459428-454f15f8-a1d7-4b11-800c-bce0cacf4d90.png)

**Comment by mhsmith** [comment]
Which version of matplotlib did you use to generate the higher-resolution image, and on which operating system?

What happens if you use matplotlib 3.1.2 on the same operating system? 

Did you use exactly the same code in both cases, including the code which saves the image to a file?

**Comment by kylevessPL** [comment]
The issue was with matplotlib 3.1.2 version, thanks for pointing out.
Finally managed to install 3.1.2 version on my machine (apparently couldn't install any 3.1.x before) to test the configuration.
In fact 3.1x matplotlib produces these lower res images, any 3.2.x or higher doesn't have this issue.
Is there any way to install latest 3.4.3 matplotlib version in chaquopy or should I just stick to 3.1.2 for now?
Any other than 3.1.2 chaquopy gives me _ ERROR: Command errored out with exit status 1:_

**Comment by mhsmith** [comment]
Currently Chaquopy only provides matplotlib version 3.1.2. 

If different versions produce different images, it's probably because they've changed the default settings of one of the functions you used. If you can pinpoint in which version it changed, you might be able to find an explanation in the matplotlib release notes. Otherwise, it might be worth asking a question on StackOverflow or the matplotlib issue tracker.

**Comment by kylevessPL** [comment]
Thank you very much for your help. Closing.
