### ISSUE TITLE
Unable to install pyhrv

### ISSUE THREAD

**Issue by JovankaMilosevic** [chaquo/chaquopy#568]
Hi, 
I've tried to install the [pyhrv](https://pyhrv.readthedocs.io/en/latest/_pages/start.html#installation) toolkit, but I got this error:

ERROR: Failed to install spectrum from https://files.pythonhosted.org/packages/3a/5c/7ab3e10bdff0ca2cea964dfb249929261074851fc65aef01e124e1d1bf44/spectrum-0.8.0.tar.gz (from pyhrv).

**Chaquopy version:**

`dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath "com.chaquo.python:gradle:9.1.0" 
    }`

**NDK and Python libraries and toolkits:**

`ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }`
`python {
            pip {
                install "numpy"
                install "neurokit2"
                install "nolds"
                install "pandas"
                install "datetime"
                install "six"
                install "matplotlib"
                install "scipy"
                install "biosppy"
                install "pyhrv"
                install "requests"
            }`

**Build log:**

Executing tasks: [:app:assembleDebug] in project D:\MoviWear_Co_Op_Fall2021\FallDetectionNew\mini6410-i2c-code

> Configure project :
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's shutdown in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.0.2/userguide/upgrading_version_6.html#jcenter_deprecation
	at build_b2fiziiupnlu28syn6m0ggguo$_run_closure1$_closure2.doCall(D:\MoviWear_Co_Op_Fall2021\FallDetectionNew\mini6410-i2c-code\build.gradle:4)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :app
Warning: This version of Chaquopy has not been tested with Android Gradle plugin versions beyond 4.1.1. If you experience problems, please edit the version of com.android.tools.build:gradle in your top-level build.gradle file. See https://chaquo.com/chaquopy/doc/current/versions.html.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting numpy
  Using cached https://chaquo.com/pypi-7.0/numpy/numpy-1.21.4-1-cp38-cp38-android_21_arm64_v8a.whl
Collecting neurokit2
  Using cached https://files.pythonhosted.org/packages/60/60/e95ca51edb08809d085b7af0cfc000b66a6d9826da85b888ead5f15b7eb9/neurokit2-0.1.5-py2.py3-none-any.whl
Collecting nolds
  Using cached https://files.pythonhosted.org/packages/67/28/60d734bb74181f3a36d685c63b18481789fd54d6c25124662e7195e2d5ed/nolds-0.5.2-py2.py3-none-any.whl
Collecting pandas
  Using version 1.3.2 (newest version is 1.3.4, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/pandas/pandas-1.3.2-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting datetime
  Using cached https://files.pythonhosted.org/packages/73/22/a5297f3a1f92468cc737f8ce7ba6e5f245fcfafeae810ba37bd1039ea01c/DateTime-4.3-py2.py3-none-any.whl
Collecting six
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting matplotlib
  Using version 3.1.2 (newest version is 3.5.0, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/matplotlib/matplotlib-3.1.2-1-cp38-cp38-android_21_arm64_v8a.whl
Collecting scipy
  Using version 1.4.1 (newest version is 1.7.3, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/scipy/scipy-1.4.1-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting biosppy
Collecting pyhrv
  Downloading https://files.pythonhosted.org/packages/84/37/ef1528358e938dd063faed41087a0274fc5b39517b2267018f9dca372e00/pyhrv-0.4.0-py3-none-any.whl (3.2MB)
Collecting requests
  Using cached https://files.pythonhosted.org/packages/92/96/144f70b972a9c0eabbd4391ef93ccd49d0f2747f4f6a2a2738e99e5adc65/requests-2.26.0-py2.py3-none-any.whl
Collecting chaquopy-libgfortran>=4.9 (from numpy)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libgfortran/chaquopy_libgfortran-4.9-0-py3-none-android_21_arm64_v8a.whl
Collecting chaquopy-openblas>=0.2.20 (from numpy)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-openblas/chaquopy_openblas-0.2.20-5-py3-none-android_21_arm64_v8a.whl
Collecting scikit-learn (from neurokit2)
  Using version 0.24.1 (newest version is 1.0.1, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/scikit-learn/scikit_learn-0.24.1-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting future (from nolds)
Collecting setuptools (from nolds)
  Using cached https://files.pythonhosted.org/packages/18/ad/ec41343a49a0371ea40daf37b1ba2c11333cdd121cb378161635d14b9750/setuptools-59.2.0-py3-none-any.whl
Collecting chaquopy-libcxx>=10000 (from pandas)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libcxx/chaquopy_libcxx-10000-0-py3-none-android_21_arm64_v8a.whl
Collecting pytz>=2017.3 (from pandas)
  Using cached https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.7.3 (from pandas)
  Using cached https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
Collecting zope.interface (from datetime)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/a0/34/895006117f6fce0b4de045c87e154ee4a20c68ec0a4c9a36d900888fb6bc/pyparsing-3.0.6-py3-none-any.whl
Collecting chaquopy-freetype>=2.9.1 (from matplotlib)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-freetype/chaquopy_freetype-2.9.1-1-py3-none-android_21_arm64_v8a.whl
Collecting chaquopy-libpng>=1.6.34 (from matplotlib)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libpng/chaquopy_libpng-1.6.34-1-py3-none-android_21_arm64_v8a.whl
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Using version 1.1.0 (newest version is 1.3.2, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/kiwisolver/kiwisolver-1.1.0-1-cp38-cp38-android_21_arm64_v8a.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl
Collecting shortuuid (from biosppy)
  Using cached https://files.pythonhosted.org/packages/22/1b/dda73524fc8dd5cd3b80adcc585a49b3f43f8889453d2ed96291b2fcc860/shortuuid-1.0.8-py3-none-any.whl
Collecting joblib (from biosppy)
  Using cached https://files.pythonhosted.org/packages/3e/d5/0163eb0cfa0b673aa4fe1cd3ea9d8a81ea0f32e50807b0c295871e4aab2e/joblib-1.1.0-py2.py3-none-any.whl
Collecting opencv-python (from biosppy)
  Using version 4.5.1.48 (newest version is 4.5.4.60, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/opencv-python/opencv_python-4.5.1.48-1-cp38-cp38-android_21_arm64_v8a.whl
Collecting bidict (from biosppy)
  Using cached https://files.pythonhosted.org/packages/f1/04/ac51cac8d2b792a8de216c775248a371bf1da25f11d919f3528975288e21/bidict-0.21.4-py3-none-any.whl
Collecting h5py (from biosppy)
  Using version 2.10.0 (newest version is 3.6.0, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/h5py/h5py-2.10.0-1-cp38-cp38-android_21_arm64_v8a.whl
Collecting spectrum (from pyhrv)
  Downloading https://files.pythonhosted.org/packages/3a/5c/7ab3e10bdff0ca2cea964dfb249929261074851fc65aef01e124e1d1bf44/spectrum-0.8.0.tar.gz (228kB)
Collecting idna<4,>=2.5; python_version >= "3" (from requests)
  Using cached https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/af/f4/524415c0744552cce7d8bf3669af78e8a069514405ea4fcbd0cc44733744/urllib3-1.26.7-py2.py3-none-any.whl
Collecting charset-normalizer~=2.0.0; python_version >= "3" (from requests)
  Using cached https://files.pythonhosted.org/packages/c8/27/141554fc0f42c05dd318fbb0be0e3e018da686544a3ff452762e49ccac58/charset_normalizer-2.0.8-py3-none-any.whl
Collecting threadpoolctl>=2.0.0 (from scikit-learn->neurokit2)
  Using cached https://files.pythonhosted.org/packages/ff/fe/8aaca2a0db7fd80f0b2cf8a16a034d3eea8102d58ff9331d2aaf1f06766a/threadpoolctl-3.0.0-py3-none-any.whl
Collecting chaquopy-libjpeg>=1.5.3 (from opencv-python->biosppy)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libjpeg/chaquopy_libjpeg-1.5.3-1-py3-none-android_21_arm64_v8a.whl
Collecting chaquopy-hdf5>=1.10.2 (from h5py->biosppy)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-hdf5/chaquopy_hdf5-1.10.2-1-py3-none-android_21_arm64_v8a.whl
Building wheels for collected packages: spectrum
  Running setup.py bdist_wheel for spectrum: started
  Running setup.py bdist_wheel for spectrum: finished with status 'error'
  Complete output from command C:\Users\Jovanka\AppData\Local\Programs\Python\Python39\python.exe -u -S -c "import setuptools, tokenize;__file__='C:\\Users\\Jovanka\\AppData\\Local\\Temp\\pip-install-jz9604ab\\spectrum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Jovanka\AppData\Local\Temp\pip-wheel-k0dhg0f7 --python-tag py3:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\cpp
  copying src\cpp\__init__.py -> build\lib.win-amd64-3.9\cpp
  creating build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\arma.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\burg.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\cholesky.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\correlation.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\correlog.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\covar.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\criteria.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\datasets.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\eigen.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\eigenfre.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\errors.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\io.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\levinson.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\linalg.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\linear_prediction.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\lpc.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\minvar.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\modcovar.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\mtm.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\periodogram.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\psd.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\spectrogram.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\toeplitz.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\tools.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\transfer.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\waveform.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\window.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\yulewalker.py -> build\lib.win-amd64-3.9\spectrum
  copying src\spectrum\__init__.py -> build\lib.win-amd64-3.9\spectrum
  creating build\lib.win-amd64-3.9\spectrum\data
  copying src\spectrum\data\__init__.py -> build\lib.win-amd64-3.9\spectrum\data
  copying src\spectrum\data\DOLPHINS.wav -> build\lib.win-amd64-3.9\spectrum\data
  copying src\spectrum\data\sunspot.dat -> build\lib.win-amd64-3.9\spectrum\data
  copying src\spectrum\data\sunspot_monthly.dat -> build\lib.win-amd64-3.9\spectrum\data
  running build_ext
  building 'spectrum.mydpss' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
  Command "C:\Users\Jovanka\AppData\Local\Programs\Python\Python39\python.exe -u -S -c "import setuptools, tokenize;__file__='C:\\Users\\Jovanka\\AppData\\Local\\Temp\\pip-install-jz9604ab\\spectrum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Jovanka\AppData\Local\Temp\pip-wheel-k0dhg0f7 --python-tag py3" failed with error code 1 in C:\Users\Jovanka\AppData\Local\Temp\pip-install-jz9604ab\spectrum\
ERROR: Failed to install spectrum from https://files.pythonhosted.org/packages/3a/5c/7ab3e10bdff0ca2cea964dfb249929261074851fc65aef01e124e1d1bf44/spectrum-0.8.0.tar.gz (from pyhrv).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
> Task :app:mergeDebugPythonSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:generateDebugPythonAppAssets UP-TO-DATE
> Task :app:generateDebugPythonLicenseAssets UP-TO-DATE
> Task :app:generateDebugPythonMiscAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:generateDebugPythonJniLibs UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'py'' finished with non-zero exit value 1
  

Thank you so much for your help!

**Comment by mhsmith** [comment]
`spectrum` is now available for Chaquopy, so both `hrv` and `pyhrv` can be installed.

**Comment by JovankaMilosevic** [comment]
Thank you very much!
