### ISSUE TITLE
Read frames from external USB camera using chaquopy

### ISSUE THREAD

**Issue by publioelon** [chaquo/chaquopy#569]
Hello, I've been getting around this lib and I have an external USB camera that uses [uvccamera library ](https://github.com/saki4510t/UVCCamera)to read frames from. The problem is the streaming part. There aren't any working solution for streaming USB camera frames from an android phone to a server, the current streaming options uses the native cameras from the android device.

I think if I was able to detect the device camera with chaquopy, I probably would be able to stream frames using sockets. I wonder if it's possible somehow to use chaquopy with uvccamera to read frames directly from the USB camera itself? 

I have tried reading USB devices connected to android and it returns an empty list

**Comment by mhsmith** [comment]
I don't know anything specifically about USB cameras. But unless it's rooted, Android doesn't usually allow direct access to any hardware devices. You have to go through the official Java or NDK APIs, and there are few if any Python libraries which have support for those. So I don't think Chaquopy would help you here.
