### ISSUE TITLE
Support for Web3 python library? (requires aiohttp)

### ISSUE THREAD

**Issue by SLong97** [chaquo/chaquopy#572]
Is there currently or will there be in the future any support for Web3's Python library in Chaquopy?
https://web3py.readthedocs.io/en/stable/

**Comment by mhsmith** [comment]
The current version of web3 requires `aiohttp<4,>=3.7.4.post0`, and there are no pure-Python wheels available within that range. We'll look into building some Android wheels for aiohttp. 

Meanwhile, you can work around it by using an older version of web3:

```
pip {
    install "web3==5.19.0"
}
```

**Comment by SLong97** [comment]
Thank you this worked, but when i try to import "from web3 import Web3" in my python script, i am getting "Unresolved reference" for both "web3" and "Web3", is this a common issue? do you know how to resolve this?

**Comment by mhsmith** [comment]
That message is harmless: see [this section](https://chaquo.com/chaquopy/doc/current/android.html#android-studio-plugin) of the documentation.

**Comment by SLong97** [comment]
Thanks very much for all the information you have provided.

**Comment by mhsmith** [comment]
`aiohttp` version 3.8.1 is now available for Chaquopy, so the current version of `web3` can be installed.
