### ISSUE TITLE
We want pycrypto to be installed from gradle

### ISSUE THREAD

**Issue by ihasib** [chaquo/chaquopy#573]
#### Chaquopy version

'com.chaquo.python:gradle:4.0.0'

#### Relevant parts of your build.gradle file

python {
            version "2.7.15"
            pip {
                install "pycrypto"
                install "pyasn1"
            }
 }

ndk {
            abiFilters "armeabi-v7a", "x86"
}

#### Describe your issue

Issue description:
Our python library is compatible for python 2.7
We roll back to chaquopy 4 to get it compatible without library
our library used a dependency named pycrypto. 
but during gradle syncing It shows following error 

How can we install pycrypto for the very chaquopy version?

Log:
Failed to install pycrypto from https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz. For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.

**Comment by mhsmith** [comment]
We never released `pycrypto` for Python 2.7, and we no longer support Python 2.7 so we won't be providing it now.

However, we did release `pycryptodome`, which is [mostly compatible](https://www.pycryptodome.org/en/latest/src/vs_pycrypto.html). Try changing your build.gradle file to use that instead.
