### ISSUE TITLE
msg's executing time is too long

### ISSUE THREAD

**Issue by Muhd-Faiq** [chaquo/chaquopy#575]
#### Chaquopy version

'com.chaquo.python:gradle:9.1.0'

#### Devices or emulators where the issue happens

I am using my android devices which realme 5 pro.

#### Describe your issue

After cloning your code from https://github.com/jaydangar/chaquopy_flutter and run it on my device, I try to execute command 'from deepface import DeepFace  DeepFace.stream()' , this command will download the library first then it will run the DeepFace.stream. But while downloading, it suddenly stop running and it print error message which stated below:

W/python.stderr(17710):  15%|█▌        | 82.8M/539M [00:05<00:28, 16.0MB/s]
W/python.stderr(17710):
E/ANR_LOG (17710): >>> msg's executing time is too long
E/ANR_LOG (17710): Blocked msg = { when=-15s378ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI } , cost  = 15378 ms
E/ANR_LOG (17710): >>>Current msg List is:
E/ANR_LOG (17710): >>>CURRENT MSG DUMP OVER<<<

**Comment by mhsmith** [comment]
chaquopy_flutter isn't our code, it's an unofficial plugin. I have no experience with Flutter, so I can only give general advice.

Are you sure your app has actually stopped? Or has it just displayed an [ANR](https://developer.android.com/topic/performance/vitals/anr) message?

If your Python code takes a long time, you should run it on a background thread to avoid blocking the UI. This could be created with the standard threading APIs in any language: Python, Java or Flutter.

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information and I'll reopen the issue.
