### ISSUE TITLE
pybalu

### ISSUE THREAD

**Issue by tomascortes** [chaquo/chaquopy#577]
Hi!
I'm trying to import the library [pybalu](https://github.com/computervision-xray-testing/pybalu) and getting the error: 
`Failed to install pybalu from https://files.pythonhosted.org/packages/15/10/1071f46dcd6e46cea479da0a47535e5b60d2083fc2fb38671e9c4d5f149f/pybalu-0.2.9.tar.gz.`

I asume because it has files .pyx inside to make some calculations. 
I can copy the functions that i need but they depend on one file exactly this.
https://github.com/computervision-xray-testing/pybalu/blob/master/pybalu/feature_extraction/haralick_utils.pyx

Im sorry if this the same as the answers using .so but what is the best way to import this functions? Im new to the concept of using pyx files.

Or other way to use the *.c files from the functions

**Comment by mhsmith** [comment]
.pyx files are Cython source code, so the package would need to be compiled into an Android-compatible wheel file.

This package doesn't look popular enough to justify us building it. But if you'd like to build it yourself, you could license our package build tool, which was used to build everything in our [native package repository](https://chaquo.com/pypi-7.0/). See https://github.com/chaquo/chaquopy/issues/175#issuecomment-778543307 for more details.

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by tomascortes** [comment]
Thanks!

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be building it in the foreseeable future.

However, the package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add it to the public repository.

If anyone else wants this package, please click the thumbs-up button above and post a comment, and I'll reopen the issue.
