### ISSUE TITLE
How can I stop a python function call?

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#58]
For example, I have run the following code:

PyObject info = function.call("book.txt");

If I want to stop or cancel the function call after I have run it, what should I do? Thanks.

**Comment by mhsmith** [comment]
Chaquopy runs Python within your main app process; there is no separate Python process. So your Python code will have to terminate itself, either by returning or throwing an exception.

The simplest technique is to make the function regularly check a variable and return when the variable is set. Then run the function in a background thread, and set the variable from the foreground thread when you want to interrupt it.

If you're unable to change the function to do this, then try using `PyThreadState_SetAsyncExc` to force the background thread to throw a Python exception, as shown [here](https://github.com/tongjinlv/matatacode-android/blob/ad46b0ad0bbd10aac954364a66af931d8b982971/app/src/main/python/hello.py). 

If you need even more isolation between the app and the Python code, you could try running Python in a separate process using the [`process`](https://developer.android.com/guide/topics/manifest/activity-element.html#proc) option in AndroidManifest.xml. There's an example of this in the [chaquopy-jupyter](https://github.com/chaquo/chaquopy-jupyter) repository. But this will significantly complicate your app.

**Comment by mhsmith** [comment]
Reopening as a reminder to move this to the FAQ.
