### ISSUE TITLE
Chaquopy licesnse verification failed

### ISSUE THREAD

**Issue by kdrkdrkdr** [chaquo/chaquopy#580]
This error occurs even though the charge.license is applied.
For your information, I received the license key by e-mail through the repository below.

https://github.com/kdrkdrkdr/test_chaquo

I would like to ask if it is possible to apply only a single repository.

#### Chaquopy version 10.0

Here is my opensource project that I applied chaquopy
https://github.com/kdrkdrkdr/novel_reader

#### Describe your issue
![image](https://user-images.githubusercontent.com/49074597/151689338-deda9cb7-74bd-4df2-8f95-2a798bae7e92.png)

**Comment by mhsmith** [comment]
Each open-source license key is only valid for a specific application ID. I've updated your license key to be valid for your new ID, `com.example.novel_reader`, so it should work the next time you build the app.

If you have any more problems with license keys, please contact me by email.
