### ISSUE TITLE
Getting ModuleNotFoundError: No module named '_ctypes' error while trying pip{ install "tensorflow==2.1.0" }

### ISSUE THREAD

**Issue by Mounika-coder** [chaquo/chaquopy#581]
####The version of com.chaquo.python:gradle is 10.0.1 and python is 3.8.11 

##Error

from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Failed to install termcolor>=1.1.0 from https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz (from tensorflow==2.1.0).
    For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
    Failed to install termcolor>=1.1.0 from https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz (from tensorflow==2.1.0).
    Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
There's probably something wrong with your Python installation. Try installing the newest version of Python 3.8 from [python.org](https://python.org/), and if necessary, use the [`buildPython`](https://chaquo.com/chaquopy/doc/current/android.html#buildpython) setting to configure Chaquopy to use it.

If that still doesn't work, please post the full build log.

**Comment by Mounika-coder** [comment]
Python 3.8.11 is probably the newest version, should I try installing python 3.10.2 version?

Below is the complete build log 

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting tensorflow==2.1.0
  Using cached https://chaquo.com/pypi-7.0/tensorflow/tensorflow-2.1.0-9-cp38-cp38-android_21_arm64_v8a.whl
Collecting termcolor>=1.1.0 (from tensorflow==2.1.0)
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
    ERROR: Command errored out with exit status 1:

     command: /usr/local/bin/python3.8 -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jqnzmg5g/termcolor/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jqnzmg5g/termcolor/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-jqnzmg5g/termcolor/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen zipimport>", line 259, in load_module
      File "/home/mounika/Documents/PRISM project/client3/app/build/generated/python/bp.zip/setuptools/__init__.py", line 20, in <module>
      File "<frozen zipimport>", line 259, in load_module
      File "/home/mounika/Documents/PRISM project/client3/app/build/generated/python/bp.zip/setuptools/dist.py", line 36, in <module>
      File "<frozen zipimport>", line 259, in load_module
      File "/home/mounika/Documents/PRISM project/client3/app/build/generated/python/bp.zip/setuptools/windows_support.py", line 2, in <module>
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: Failed to install termcolor>=1.1.0 from https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz (from tensorflow==2.1.0).
Failed to install termcolor>=1.1.0 from https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz (from tensorflow==2.1.0).

For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python3.8'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by mhsmith** [comment]
Since your Python executable is in `/usr/local`, I assume you built it yourself? If so, you must make sure all the necessary libraries and headers are available, otherwise some standard library modules won't work. Here are the packages you'll need on Debian. Other distributions will be similar:

* libbz2-dev
* libffi-dev 
* liblzma-dev 
* libsqlite3-dev 
* libssl-dev                       
* zlib1g-dev 

Once you've installed all of those, you'll have to rebuild and reinstall Python.

Of course, if your distribution has an official Python 3.8 build, it would be easier to just use that. Other versions of Python will also work, but this may reduce your app's startup speed, as described [here](https://chaquo.com/chaquopy/doc/current/android.html#bytecode-compilation).

**Comment by Mounika-coder** [comment]
Thank you, that really helped me, now I have successfully installed TensorFlow.
