### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kdrkdrkdr** [chaquo/chaquopy#586]
#### Describe your issue

![image](https://user-images.githubusercontent.com/49074597/153767626-638a91e6-56b5-414a-81a7-39db81e306eb.png)

I was using the Janome package, but the error that I couldn't find the file continues to occur.
The file definitely exists... Normal Python works well. Is there any solution?

Janome package is this way.
https://github.com/mocobeta/janome

My code is as follows.

from janome.tokenizer import Tokenizer
t = Tokenizer()
t.tokenize("text")

**Comment by mhsmith** [comment]
This package is trying to access its own Python source code files at runtime, But for efficiency, Chaquopy loads all Python modules directly from the APK, and doesn't unpack them as separate files. 

It looks like you can work around this by passing the following option:
```
t = Tokenizer(mmap=False)
```

**Comment by kdrkdrkdr** [comment]
Thanks! It's working properly!
