### ISSUE TITLE
How to set two Python code file paths at the same time

### ISSUE THREAD

**Issue by zhujianzhang** [chaquo/chaquopy#588]
I plan to store Python code in application and library at the same time. I need to access different Python paths respectively. How should I configure it?

**Comment by mhsmith** [comment]
If by "library" you mean an Android library module (AAR), then as it says [here](https://chaquo.com/chaquopy/doc/current/android.html#android-plugin), the Chaquopy plugin can only be used in one module in a project: either in the app module, or in exactly one library module.

However, within a module, you can add additional Python source directories using the `sourceSets` block, as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#android-source).

**Comment by zhujianzhang** [comment]
Thank you for your reply，I know how to set Python source directories.
But my problem now is App module and library module have a python source directories respectively.
That is, there are two Python source directories. Can this situation be supported?

**Comment by mhsmith** [comment]
Within the `sourceSets` block, you can have multiple `srcDir` lines.

**Comment by zhujianzhang** [comment]
I made the following attempts:
            sourceSets {
                main {
                    python {
                        srcDirs = ["src/main/python"]
                        srcDirs = ["src/main/python2"]
                    }
                }
            }
However, only python2 can be accessed, but the python folder cannot be accessed

**Comment by zhujianzhang** [comment]
Thank you for your patience in solving my problem
