### ISSUE TITLE
How to do livestream using camera

### ISSUE THREAD

**Issue by Lokkeshss** [chaquo/chaquopy#589]
Hi I'm developing face liveness detection application in android, where i have to pass video to python script to detect face liveness. Once face liveness is detected I can get the result back. But now concern is how to send live video from camera to python script.
Im using trial version of chaquopy now.

**Comment by mhsmith** [comment]
See ["Pass images to/from Python"](https://chaquo.com/chaquopy/doc/current/faq.html#faq-images) in the FAQ.
