### ISSUE TITLE
New purchased key not working

### ISSUE THREAD

**Issue by jdrichat** [chaquo/chaquopy#59]
I have included the new key, but the demo project now does not build. I removed the new key, and it still builds and runs as before. I have emailed what I have tried

Added in local.properties file, that is also in the home directory of the Gradle project; 
chaquopy.license=<“the license number”>

I also tried without the brackets, and before and after the two other lines that were already there.

**Comment by mhsmith** [comment]
There should be no brackets, and no quotation marks, just the key. The order of the lines doesn't matter.

**Comment by mhsmith** [comment]
If it still doesn't build, please say what the error is.

**Comment by jdrichat** [comment]
Thanks. It didbuild. That was a great help’
