### ISSUE TITLE
how to use sklearn to unpickle estimator LatentDirichletAllocation from version 1.0.2

### ISSUE THREAD

**Issue by showkeyjar** [chaquo/chaquopy#592]
W/python.stderr: /data/data/com.ml.projects.beautydetection/files/chaquopy/AssetFinder/requirements/sklearn/base.py:310: UserWarning: Trying to unpickle estimator LatentDirichletAllocation from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.

#### Chaquopy version

11.0.0

#### Devices or emulators where the issue happens

Pixel XL API 30

#### Relevant parts of your code

`python
model_file = join(dirname(__file__), "lda_skin.jb")
lda = load(model_file)
`

#### Describe your issue

rt.

**Comment by mhsmith** [comment]
It's only a warning, so your code might still work. If it doesn't work, try regenerating your model file with scikit-learn version version 0.24.1.
