### ISSUE TITLE
Question: Where does chaquo read py module?

### ISSUE THREAD

**Issue by Agono0** [chaquo/chaquopy#593]
I am trying to test the demo reply.py ....
And I put all files in assets folder(in the root folder) in my app
But iam still have this error
`com.chaquo.python.PyException: ModuleNotFound Error: No module named 'repl'
`
From this line ```
py.getModule("repl").callAttr("interact");```
I hope you get what I am talking about.
Thanks in advance.

**Comment by mhsmith** [comment]
Python modules should be placed in the `src/main/python` directory, as shown in the [documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-source) and all of the [examples](https://chaquo.com/chaquopy/doc/current/examples.html).

**Comment by mhsmith** [comment]
If you need more help, please create a GitHub project showing what you're trying to do, and post a link here.

**Comment by Agono0** [comment]
I am very sorry for the delay in responding.
First of all thanks for respon, I am not using Android studio 
I am using platform on android named (Sketchware) (without gradle)
But i make this possible to add the library in sketchware using the repo, and everything works .
Now where i can add py module and note that the demo apk in this repo (complied with Android studio) doesn't have python folder and everything found in assets folder.
How I can fix this ;(

**Comment by mhsmith** [comment]
> I am using platform on android named (Sketchware) (without gradle)
> But i make this possible to add the library in sketchware using the repo, and everything works .

I'm not familiar with Sketchware, so please explain exactly how you did this.

**Comment by Agono0** [comment]
First i have all lib `.so` inside `libs` folder including `libpython3.8.so` , and inside assets folder `assets/chaquopy` I have all `.imy` files to make this work...
My question is : how I can change the python module default read location (without gradle) to move it to assets Folder or read python module from internal storage of the device. 
Thanks very much for your reply 
I hope you understand me.

**Comment by mhsmith** [comment]
The file `app.imy` is a ZIP file, so you can put your Python files in there to build them into the APK.

Or if you want to load Python modules from the internal storage directory at runtime, you can add that directory to `sys.path` by doing something like this:

```
sys.get("path").callAttr("append", getFilesDir().toString())
```

**Comment by Agono0** [comment]
Okey, but i already include `app.imy` but this file is located in `assets/chaquopy/app.imy` but also nothing happens,  note that the same file is taken from demo.apk (builded with android studio) in demo.apk there's no python folder only chaquopy Folder with source folder are in assets.

**Comment by Agono0** [comment]
Now in my case thoes files found in `assets/chaquopy/utils`
![20220319_181801](https://user-images.githubusercontent.com/100796146/159129494-dee50827-b6ca-460e-b5ad-db222c98aae6.jpg)

Now how I can access them?

**Comment by Agono0** [comment]
@mhsmith Lol it works fine after I noticed that app.iml actually doesn't have the py module 😂😂.
Anyway , Thanks very much for your help And I also want to thank you for the great and wonderful library that you have made.

**Comment by Agono0** [comment]
@mhsmith 
Hey again 😅
I face a new error 
```java
Caused by: com.chaquo.python. PyException:  RecursionError: maximum recursion depth exceeded while calling a Python object 
```
when I call main.py
```python
def helloworld():
return "Hello world Chaquopy!"
```
my MainActivity code:
```java
PyObject main = py.getModule("chaquopy.utils.main").callAttr("helloworld");
text = main.toString();
```

The full error:
```java
FATAL EXCEPTION: main

Process: com.my.newproject14, PID: 32499

java.lang.RuntimeException:Unable to start activity ComponentInfo(com.my.newproject14/ com.my.newproject14.MainActivity): com.chaquo.python.PyException: RecursionError: maximum recursion depth exceeded while calling a Python object
at
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3139).
at
android.app.ActivityThread.handleLaunchActivity(Activ ityThread.java:3282)
at android.app.servertransaction.LaunchActivityItem.exec ute(LaunchActivityItem.java:78)
at
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at
android.app.servertransaction.TransactionExecutor.exe
cute(TransactionExecutor. java:68)
at
android.app.ActivityThreadSH.handleMessage (ActivityThread.java:1970)
at 
android.os.Handler.dispatchMessage (Handlerjava:186)

at
 android.os.Looper.loop(Looper.java:214)
at
android.app.ActivityThread.main(ActivityThread.java: 7156) at java.lang.reflect.Method.invoke(Native Method) at
com.android.internal.os.RuntimeInitŚMethodAndArgsCaller.run(RuntimeInit.java:494)
at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: com.chaquo.python. PyException:
RecursionError: maximum recursion depth exceeded while calling a Python object
at
<python>, java.android. importer.isdir (importer.py:884)
at
<python>.java.android.importer.<genexpr>(importer.py:
482)
at <python.java.android.importer.isdir (importer.py:482)
at
<python>.java, android.importer extract_dir(importer.py:459)
at
<python>.java, android. importer.extract_dir(importer.py:461)

at

<python>.java.android.importer.extract_dir(importer.p

y:461)

at

<python>.java.android.importer.extract_dir(importer.p

y:461)

at

<python.java.android.importer.extract_dir(importer.p

y:461)

at

<python.java.android. importer extract_dir(importer.p

Y:461)

at

<python.java.android.importer extract_dir(importer.p

y:461)

at

<python>.java.android. importer.extract_dir(importer.p

y:461)

at

<python>.java.android. importer.extract_dir(importer.p

y:461)

at

<python>.java.android. importer.extract_dir(importer.p

y:461)

at

<python.java.android.importer.extract_dir(importer.p

y:461)

at

<python>.java.android.importer extract_dir(importer.p

y:461)

at

<python>.java.android.importer.extract_dir(importer.p

y:461)

at

<python>.java.android.importer.extract_dir(importer.p

y:461)

at

<python>.java.android.importer.extract_dir(importer.p

y:461)

at

<python>.java.android.importer extract_dir(importer.p

y:461)

<python.java.android.importer.find_spec(importer.py?

408)

at

<python> importlib. bootstrap_external_get_spec(<fro zen importlib. _bootstrap_external>:1379) at <python importlib._bootstrap_external.find_spec(<fro

zen importlib. bootstrap_external> : 1407)

at <python>. 1mportlib. bootstrap..find_spec(<frozen

importlib. bootstrap> :914)

at

<python>> importlib. _bootstrap. find_and_load_unlocked

(<frozen importlib. bootstrap > :971)

at

<python importlib. bootstrap. find_and_load(<frozen

importlib. bootstrap>:991)

at <python>. importlib._bootstrap._god_import(<frozen

importlib. bootstrap>:1014)

at

<python> importlib. _bootstrap. call_with_frames_remov

ed(<frozen importlib._bootstrap>:219)

at

<python> importlib._bootstrap.find_and_load_unlocked (<frozen importlib. bootstrap>:961) at <python> importlib. bootstrap._find_and_load(<frozen

importlib. bootstrap>:991)

at <python> importlib. _bootstrap_gcd_import(<frozen

importlib. bootstrap>:1014) at <python> importlib._bootstrap._call_with_frames_remov ed(<frozen importlib. _bootstrap>:219) at

<python importlib._bootstrap. find_and_load_unlocked

(<frozen 1mportlib. bootstrap>:961) at

<python,importlib. _bootstrap. find_and_load (<frozen importlib. bootstrap> :991) at <python>. importlib. _bootstrap._god_import( importlib. bootstrap>:1014)

at <python> importlib. import_module(__init__.py 127)

<python>.importlib. bootstrap. find_and_load(<frozen

importlib. bootstrap :991)

at <python>importlib._bootstrap. god import (<frozen importlib. bootstrap>:1814) at <python>importlib. bootstrap. call_with_frames_remov ed(<frozen importlib. bootstrap-:219)

at

<python>.1mportlib. bootstrap_find_and_load_unlocked

(<frozen importlib. bootstrap>:961)

at

<python> Importlib. bootstrap. find_and_load(<frozen importlib. bootstrap>:991) at <python> importlib. bootstrap. ged import (<frozen importlib._bootstrap-:1014)

at <python>. importlib. import_module(__init__.py:127)

at

<python chaquopy_java.Java_com_chaquo_python_Python_

getModuleNative(chaquopy_java.pyx:155) at com.chaquo.python.Python.getModuleNative(Native Method) at com.chaquo.python. Python.getModule(Python.java:

84)

at

com.my.newproject14.MainActivity.initializeLogic (Main

Activity.java:111) at com.my.newproject14.MainActivity.onCreate (MainActivit y.java:75)

at android.app.Activity performCreate(Activity.java:

7335)

at android.app. Activity performCreate(Activity.java:

7326)

at android.app. Instrumentation.callActivityOnCreate(Inst rumentation.java: 1275) at

android.app.ActivityThread.performLaunchActivity (Acti

vityThread.java:3119)

... 11 more
```

**Comment by mhsmith** [comment]
Actually, I don't think we can support this kind of modification of the assets. And even if you can get it to work now, there's no guarantee that it'll keep working in future versions.

Instead, I suggest you try adding your modules to the the original source code, build it with Gradle, and then extract the resulting assets into your Sketchware app.

Or to avoid rebuilding your app every time you change your code, you might find it more convenient to modify `sys.path` as I mentioned above, and then upload the Python files with the [Device File Explorer](https://chaquo.com/chaquopy/doc/current/android.html#android-os).

**Comment by Agono0** [comment]
Okey it's fine 😔.
So I can't read py module from assets?
If yes, can i read from internal storage ?
Like this :
My py file path :
``` java
/storage/emulated/0/pythonfiles/main.py
```
And here `main.py` like code above : 
```python
def helloworld():
return "Hello world Chaquopy!"
```
Because I didn't get how to use`sys.path` , if you have example with code above this will be great
Thanks 💟

**Comment by mhsmith** [comment]
In recent Android versions, apps can't directly access `/storage/emulated` anymore. Try using the internal files directory (`getFilesDir`), like I said [here](https://github.com/chaquo/chaquopy/issues/593#issuecomment-1073032326).

**Comment by Agono0** [comment]
Okey,  thanks very much help 🙏 
Have a nice day .
