### ISSUE TITLE
kotlin bitmap lose color when return byteArray from python

### ISSUE THREAD

**Issue by showkeyjar** [chaquo/chaquopy#595]
I use chaquo call python and cut a image, then I return the cropped image from python

but I found this return byteArray to Bitmap has no color but bluish.

what's problem going on here?

#### Chaquopy version

11.0.0
#### Devices or emulators where the issue happens

pixel 2 pie 9.0
#### Relevant parts of your code

so I write the code in java:

```
var bytes = py.getModule("cut_img").callAttr("cut_one", encodingStr, jsonStr).toJava(ByteArray::class.java)
val cheekBitMap = BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
```

and write the code in python:
```
def cut_one(str_data, str_point):
    points = json.loads(str_point)
    print(type(points), points)
    decode_data = base64.b64decode(str_data)
    np_data = np.fromstring(decode_data, np.uint8)
    image = cv2.imdecode(np_data, cv2.IMREAD_UNCHANGED)
    cheek = cv2.resize(image , (80, 96), interpolation=cv2.INTER_LINEAR)
    pil_img = Image.fromarray(cheek)
    buff = io.BytesIO()
    pil_img.save(buff, format="PNG")
    return buff.getvalue()
```
#### Describe your issue

the cheekBitMap has no color but bluish.

**Comment by mhsmith** [comment]
OpenCV uses BGR color order, while Pillow and most other libraries use RGB. The simplest solution is probably to encode the image to PNG using OpenCV directly. Or if you must use Pillow, you'll have to convert between the two orders. You can find lots of examples of both of these approaches on Google or StackOverflow.

**Comment by showkeyjar** [comment]
thanks for your reply, I'll have a try.
