### ISSUE TITLE
Can we use Deep face Library in our Script in Chaqopy

### ISSUE THREAD

**Issue by Zaeem6100** [chaquo/chaquopy#597]
I was creating an app that uses face verification so I decide to use a deep face library to implement in facial detection. is it possible to use it on Chaqopy

**Comment by mhsmith** [comment]
If you mean https://pypi.org/project/deepface/ , the current version can be installed by following the instructions [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements). 

The functions which require direct access to the camera probably won't work, so you'd have to capture an image in Java/Kotlin and then pass it to Python for processing. But as far as I know, everything else should work.
