### ISSUE TITLE
Failed to compile to .pyc format: buildPython version 3.10.4 is incompatible

### ISSUE THREAD

**Issue by Zaeem6100** [chaquo/chaquopy#598]
I was Compiling 
pip{
                install "deepface"
            }

this gives me an error Failed to compile to .pyc format: build python version 3.10.4 is incompatible. See https://chaquo.com/chaquopy/doc/current/android.html#android-bytecode.

**Comment by Zaeem6100** [comment]
Issue Resolved by using 
pyc {
            src false
        }

**Comment by Gelassen** [comment]
I got this error ```Failed to compile to .pyc format: buildPython version 3.10.12 is incompatible```. I might turn off pyc compilation, but it would be good to know root cause of this issue and possible solution.

**Comment by mhsmith** [comment]
The error message contains a link which explains everything you need to know. Pay attention to what it says about the Python version.

**Comment by Gelassen** [comment]
@mhsmith , thank you, indeed error message is obvious. I faced with issue during migration from latest supported python version (3.8 -> 3.11). Could you please take a look on this? #939
