### ISSUE TITLE
Need help in adding chaquopy gradle plugin to react native android project

### ISSUE THREAD

**Issue by yashmaurya01** [chaquo/chaquopy#601]
Can someone guide me how to add the lines mentioned [here](https://chaquo.com/chaquopy/doc/current/android.html) to a react native project built using the native cli. The react native settings.gradle and build.gradle files don't match the format as mentioned in the chaquopy docs.
I'm new to react native and closing in on a project deadline which requires the use of chaquopy.

Help would really be appreciated.

**Comment by mhsmith** [comment]
Is your project using the previous `buildscript` and `apply` syntax? If so, you can find instructions in the [older version of the documentation](https://chaquo.com/chaquopy/doc/10.0/android.html#android-plugin).

**Comment by yashmaurya01** [comment]
Yeah, that fixed it. Thanks!
