### ISSUE TITLE
NEMO: please add cryptography version 3.4.7

### ISSUE THREAD

**Issue by ominfowave** [chaquo/chaquopy#609]
#### Chaquopy version
11.0.0

We have to use nemo version 3.13.3 in our project which has a dependency on cryptography version 3.4.7
Can you please add cryptography 3.4.7 in the chaquopy.

Ref: https://github-wiki-see.page/m/usnistgov/NEMO/wiki/Dependencies

**Comment by mhsmith** [comment]
This package pins all of its requirements to specific versions, so please try to deal with it as I explained in #607.
