### ISSUE TITLE
Sys arguments

### ISSUE THREAD

**Issue by EgorSigolaev** [chaquo/chaquopy#616]
How can I pass sys arguments while running python script?

For example, simple python script can be run as **python3 start.py -arg1  -arg2**. So python code to get these args like **sys.argv[1]**
Is it possible to pass sys args in Kotlin code?

**Comment by mhsmith** [comment]
Yes, you can do it like this in Java; Kotlin would be similar:
```java
PyObject sys = py.getModule("sys");
PyObject argv = sys.get("argv").asList();
argv.clear();
argv.add(PyObject.fromJava(""));  // Empty argv[0]
argv.add(PyObject.fromJava("-arg1"));
argv.add(PyObject.fromJava("-arg2"));
```

Then use `getModule` and `callAttr` to call your Python script.
