### ISSUE TITLE
The app size is too big for google play

### ISSUE THREAD

**Issue by showkeyjar** [chaquo/chaquopy#618]
I want publish my app to google play, but found it exceeded 150M bundle max size.

so I analyze the apk file, and found this result:

![image](https://user-images.githubusercontent.com/16154787/167065954-d757f459-351e-4485-8416-591212d8603a.png)

I'm wondering how to make it smaller?

#### Chaquopy version

11.0.0

#### Relevant parts of your build.gradle file

        ndk {
            // abiFilters "x86"  //debug
            abiFilters "armeabi-v7a", "arm64-v8a" //release
        }

        def beautyEnv = System.getenv('beauty')
        python {
            buildPython "${beautyEnv}python.exe"
            pip {
                install "opencv-python"
                install "tensorflow"
                install "scikit-learn"
                install "joblib"
            }
        }

#### Describe your issue

you can find that more than 90% size is used by chaquopy and python

**Comment by showkeyjar** [comment]
I was inspired by this issue: https://github.com/chaquo/chaquopy/issues/448
and I created a dynamic-feature module call "python", 
then I move those config to build.gradle in "python" model
`
plugins {
    id 'com.android.dynamic-feature'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}
android {
    compileSdk 31

    defaultConfig {
        minSdk 24
        targetSdk 31
        versionCode 1
        versionName "1.1.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            // abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"  //full
            // abiFilters "x86"  //debug
            abiFilters "armeabi-v7a", "arm64-v8a" //release
            // abiFilters "armeabi-v7a" //run
        }

        def beautyEnv = System.getenv('beauty')
        python {
            buildPython "${beautyEnv}python.exe"
            pip {
                install "opencv-python"
                install "tensorflow"
                install "scikit-learn"
                install "joblib"
            }
        }
    }

    sourceSets {
        main{
            // Python code dir
            python.srcDirs = ["../model_assets/src/main/assets/python"]
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(":app")
    implementation 'androidx.core:core-ktx:1.7.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation 'androidx.annotation:annotation:1.2.0'
}
`
but it run error:

Cannot query the value of property 'applicationId' because configuration of project ':python' has not completed yet.

how can I get go?

**Comment by mhsmith** [comment]
> Cannot query the value of property 'applicationId' because configuration of project ':python' has not completed yet.

Please post the full stack trace. To display it, click the “Build: failed” caption to the left of the message.

> `install "tensorflow"`

You can probably reduce the size and increase the speed of your app by switching to TensorFlow Lite. For instructions, see https://github.com/chaquo/chaquopy/issues/332#issuecomment-781480272.

**Comment by mhsmith** [comment]
If you use the Chaquopy plugin in an `application` or `library` module, then you'll be able to access the Chaquopy Java API from a `dynamic-feature` module. However, the plugin doesn't support being used in a `dynamic-feature` module directly.

Please try switching to TensorFlow Lite, as I mentioned in my previous comment. If it works, it'll solve all your app size problems and save you a lot of time in the long run.

Alternatively, Google Play supports releasing separate bundles for each ABI. See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size) for instructions.

**Comment by showkeyjar** [comment]
I tried those solutions but found the aab file is still more than 150M, 
and remove tensorflow, only keep scikit-lean and opencv, but it still 220M, 
so I highly recommended Chaquopy API to support dynamic-feature module.
because, it'll more and more python package to use.

**Comment by mhsmith** [comment]
> and remove tensorflow, only keep scikit-lean and opencv, but it still 220M,

I built an app with the following settings:

```
        pip {
            install "opencv-python"
            install "tflite-runtime"
            install "scikit-learn"
            install "joblib"
        }
```
```
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
```

... and the APK was only 86 MB. So you must be including something else large. Here are some ideas:

* Chaquopy doesn't create an `assets/python` directory. This must be something you've added yourself.
* Look further inside the `assets/chaquopy` directory. Here you'll find some .imy files. These are actually ZIPs, so you can extract and rename them, then explore inside them further.
  * `app.imy` contains  *everything* from your Python source code directories. If this file is too large, check whether there's anything unnecessary in those directories.
  * `requirements-*.imy` contains all of the `pip` requirements from your build.gradle file.

**Comment by showkeyjar** [comment]
ok, I'll have a try
