### ISSUE TITLE
Move Chaqoupy library out of Build folder

### ISSUE THREAD

**Issue by rpcd** [chaquo/chaquopy#62]
When a rebuild occurs the build directory gets removed and also removes the /app/build/generated/python/chaquopy_java.jar,  which causes a "Cannot open a library at ... " error ... re-locate the library to avoid ...
a work around:
I have to turn off python, rebuild to produce the build directory and then turn chaquopy back on

 this is the actual message:
Cannot open a library at 'FileMapping(from=/media/git-repos/NAME/app/build/generated/python/chaquopy_java.jar, to=/home/rpc/.gradle/caches/transforms-1/files-1.1/chaquopy_java.jar/0a758c1550db92a05c34ebdf616d8314/jetified-chaquopy_java.jar)'

**Comment by mhsmith** [comment]
Thanks, we'll definitely fix this in the next release.

What version of Python are you using in your app?

**Comment by rpcd** [comment]
Hi Malcolm,

We are using python 3.5.2

**Comment by mhsmith** [comment]
But what version are you using *[in your app](https://chaquo.com/chaquopy/doc/4.0/android.html#python-version)*?

**Comment by mhsmith** [comment]
Fixed in Chaquopy 5.0.0.

**Comment by rpcd** [comment]
:)

**Comment by rpcd** [comment]
Thank you ... confirm working correctly just now

**Comment by mhsmith** [comment]
Glad to hear it.
