### ISSUE TITLE
Please add json package/library

### ISSUE THREAD

**Issue by Finsday** [chaquo/chaquopy#621]
Hello can please upgrade pip or add JSON library to work with JSON files

ERROR: Could not find a version that satisfies the requirement json (from versions: none)

Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'intents.json'
        at <python>.test.<module>(test.py:7)

**Comment by Finsday** [comment]
> Hello can please upgrade pip or add JSON library to work with JSON files

**Comment by mhsmith** [comment]
`json` is part of the Python standard library, there's no need to install it.

To read data files from your source code directory, follow the instructions [here](https://chaquo.com/chaquopy/doc/current/android.html#android-data).
