### ISSUE TITLE
Install modules in runtime

### ISSUE THREAD

**Issue by m-anshuman2166** [chaquo/chaquopy#623]
I would like to have possibility of installing python modules in runtime, like there must be a class that installs python packages like pip does

**Comment by mhsmith** [comment]
You can install pip itself into your app just like any other package. However, pip isn't designed to be called programmatically within another program, so there may be a better choice. If you only need to installl a few Python files, then a simple HTTP download should be good enough.

Regardless of how you choose to download the modules, you should store them in a directory under [`os.environ["HOME"]`](https://chaquo.com/chaquopy/doc/current/android.html#android-os), and then add that directory to `sys.path` so you can import them.

Note that downloading executable code at runtime may be against the policies of some app stores.

**Comment by m-anshuman2166** [comment]
Actually I was working on a Python IDE project, installation of modules in runtime could be a useful feature

**Comment by m-anshuman2166** [comment]
@mhsmith finally succeeded but, just last question 

Since pip is async, how do i know when a specific module is installed

**Comment by m-anshuman2166** [comment]
Also what is path where modules are present (`maybe i could move downloaded stuff to that and make it work`)

**Comment by mhsmith** [comment]
> Since pip is async, how do i know when a specific module is installed

What do you mean by async? How exactly are you running pip?

> Also what is path where modules are present

You can control that with the [`--target`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-t) option.

**Comment by m-anshuman2166** [comment]
> > Since pip is async, how do i know when a specific module is installed
> 
> What do you mean by async? How exactly are you running pip?
> 

I mean that it may take time to download (`depending on net speed`)
My question is : how would I listen to the event when the specified module is installed

**Comment by mhsmith** [comment]
That depends on how you're running pip. For example, if you're installing modules by calling one of pip's internal functions, you can just wait until the function returns.

**Comment by mhsmith** [comment]
Unfortunately I think current versions of pip do a lot of their work in subprocesses, which won't work on Chaquopy because it doesn't provide a `python` executable. You may need to use a different packaging tool. 

Or for simple cases, you can just download a .whl file, unzip it into a directory under under [os.environ["HOME"]](https://chaquo.com/chaquopy/doc/current/android.html#android-os), and then add that directory to `sys.path`.

**Comment by mhsmith** [comment]
> for simple cases, you can just download a .whl file, unzip it into a directory under under [os.environ["HOME"]](https://chaquo.com/chaquopy/doc/current/android.html#android-os), and then add that directory to `sys.path`.

These steps can be assisted with libraries like [pypi-simple](https://pypi-simple.readthedocs.io/en/stable/) and [pypa/installer](https://installer.pypa.io/en/stable/).

I'm still not aware of any pure-Python library that can resolve dependencies, download wheels and install them, all within the calling process. If anyone can recommend one, please post a comment below.
