### ISSUE TITLE
Python 3.9 / 3.10

### ISSUE THREAD

**Issue by emanuele-f** [chaquo/chaquopy#624]
Any plan/eta to upgrade chaquopy to python 3.9 (or 3.10)? The [new mitmproxy release](https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md#15-may-2022-mitmproxy-810) now requires python 3.9 or above

**Comment by mhsmith** [comment]
We'll probably move to Python 3.10 in late 2022.

Meanwhile, it looks like the newest version of mitmproxy which will work with Chaquopy is 7.0.4, because 8.0.0 requires a newer version of `cryptography`.

**Comment by emanuele-f** [comment]
Oh great, hope to see it landing soon. Actually with some efforts I managed to build the [new crptography module](https://github.com/emanuele-f/chaquopy-wheels) and migrated the PCAPdroid mitm addon to version 8.0.0. Too bad they decided to update python just after the major release 😅

**Comment by mhsmith** [comment]
Thanks for letting me know. If you want to make a PR in the other repository for the new version of cryptography, then I'll be happy to build it and make it available to other Chaquopy users.

**Comment by emanuele-f** [comment]
I don't have a clean recipe for it, I had to manually cross compile python and add rust to the build environment

**Comment by mhsmith** [comment]
OK, no problem, I already did something similar when building `tokenizers`, so I'll probably add Rust support to the tool in the future.

**Comment by emanuele-f** [comment]
I renew my hopes for this project to become open source, closed source is doomed to waste valuable people time

**Comment by mhsmith** [comment]
@emanuele-f: As you may have noticed, Chaquopy is now open-source. See [here](https://chaquo.com/chaquopy/chaquopy-is-now-open-source/) for details.

**Comment by emanuele-f** [comment]
Yeah, that's great news! I hope this will attract new contributors and make the project grow even bigger!

**Comment by mhsmith** [comment]
Python 3.9 and 3.10 were added in Chaquopy 13.0.0: see [here](https://github.com/chaquo/chaquopy/issues/661#issuecomment-1304801515) for details.

**Comment by emanuele-f** [comment]
This is great, I will check it out!

As you already tag releases, please consider creating a Github Release with changelog as part of the release process, so that people can watch the repo and get notified whenever a new version is released 😉

**Comment by mhsmith** [comment]
Thanks, that's a good idea. I've created a release page for 13.0.0, and I'll add new ones for each future release.
