### ISSUE TITLE
Using Librosa To extract Features From Voice

### ISSUE THREAD

**Issue by HagarHossam38** [chaquo/chaquopy#625]
We working on Android app that take voice Input from user (using media recorder )and then extract some features from it using librosa
, How i can make librosa load this voice that already saved on mobile storage and extract features like mfcc
The pyhton code already working on python ide but it crash here

**Comment by mhsmith** [comment]
Please post the [full stack trace](https://stackoverflow.com/a/23353174) and the relevant sections of your code.

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information and I'll reopen the issue.
