### ISSUE TITLE
python-dateuil implementation

### ISSUE THREAD

**Issue by DedericoBruni** [chaquo/chaquopy#629]
Hi! I wanted to ask if its in plan to implement python-dateuil package on chaquopy. It would be really helpfull to handle dates!
Thank you

**Comment by mhsmith** [comment]
Assuming you mean python-dateutil, this is a pure-Python package so it should work with Chaquopy already. Add it to your app by following the instructions [here](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements).

If you have any problems, please post the details and I'll reopen the issue.
