### ISSUE TITLE
How to convert Pyobject into ByteBuffer

### ISSUE THREAD

**Issue by waffiqaziz** [chaquo/chaquopy#634]
I'm trying to get results from MFCC using librosa library and getting results in Pyobject format

_**preproccess.py**_
```
import librosa

def preprocess(file_path):

    maxlen = 22050


    signal, sample_rate = librosa.load(file_path)

    if len(signal) >= maxlen:
        signal = signal[:maxlen]

    MFCCs = librosa.feature.mfcc(signal, sample_rate, n_mfcc=13, n_fft=2048, hop_length=512)
    return MFCCs
```

Here's how I run the python code

```
fun mfcc(context: Context, path: String): PyObject? {
    if (!Python.isStarted()) {
      Python.start(AndroidPlatform(context))
      Log.i("Python", "python start")
    }
    val python = Python.getInstance()
    val pythonFile = python.getModule("preprocess")

    return pythonFile.callAttr("preprocess", path)
}
```

From there I want to use it in Tensorflow lite model, but the input must be a ByteBuffer, is there a way to convert it?

_**model.tflite**_
```
val model = ModelAudio.newInstance(context)

// Creates inputs for reference.
val inputFeature0 = TensorBuffer.createFixedSize(intArrayOf(1, 44, 13, 1), DataType.FLOAT32)
inputFeature0.loadBuffer(byteBuffer)  // here, I have to put the result of **preprocess.py**

// Runs model inference and gets result.
val outputs = model.process(inputFeature0)
val outputFeature0 = outputs.outputFeature0AsTensorBuffer

// Releases model resources if no longer used.
model.close()
```

Thank you..

**Comment by mhsmith** [comment]
`librosa.feature.mfcc` returns a NumPy array, so you can convert it as follows:
* Convert it to `bytes` in Python, as shown [here](https://chaquo.com/chaquopy/doc/current/python.html#python-array-convert).
* Return the `bytes` object from Python to Kotlin.
* Convert it to a `ByteArray` with `toJava`, as shown [here](https://github.com/chaquo/chaquopy/issues/595)
* Wrap the `byte[]` array in a `ByteBuffer`.

If this doesn't work as you expect, try logging some of the content of the array to see how it's encoded.

**Comment by waffiqaziz** [comment]
> `librosa.feature.mfcc` returns a NumPy array, so you can convert it as follows:
> 
> * Convert it to `bytes` in Python, as shown [here](https://chaquo.com/chaquopy/doc/current/python.html#python-array-convert).
> * Return the `bytes` object from Python to Kotlin.
> * Convert it to a `ByteArray` with `toJava`, as shown [here](https://github.com/chaquo/chaquopy/issues/595)
> * Wrap the `byte[]` array in a `ByteBuffer`.
> 
> If this doesn't work as you expect, try logging some of the content of the array to see how it's encoded.

Thank you very much, this worked for me. Very helpful 👍🏽
