### ISSUE TITLE
image to bitmap conversion

### ISSUE THREAD

**Issue by robotixdevteam** [chaquo/chaquopy#636]
Hi,
we are creating an app which deals with computer vision application where i have to send the image from java to python file and utilize the image data for preprocessing.As far i understood while searching that first we have to convert the image to bitmap then we have send that array to python. There we use numpy array to hold that bitmap array. I just want to know whether these are the steps to follow when we do image processing with respective opencv or not. If not we would like to have your help through a tutorial or any reference to help us do the same.

**Comment by mhsmith** [comment]
The easiest way is to convert the image to an in-memory PNG file, and then pass that as a byte array (Python `bytes`, Java `byte[]`, Kotlin `ByteArray`). The [chaquopy-matplotlib](https://github.com/chaquo/chaquopy-matplotlib) example shows how to do that in the Python-to-Java direction; the opposite direction would be similar.

**Comment by robotixdevteam** [comment]
we are struck at after we upload a python file in the app then we run that python file in the app in such a case will the byte array from the java can be send to that uploaded python file or not

**Comment by mhsmith** [comment]
Like any other Java/Kotlin object, you can pass a byte array to a Python function using `callAttr`, as shown [here](https://chaquo.com/chaquopy/doc/current/java.html). 

Then on the Python side, convert it by simply calling `bytes`, as shown [here](https://chaquo.com/chaquopy/doc/current/python.html#python-array-convert). You can then pass the `bytes` object to whatever Python image library you like.
