### ISSUE TITLE
Please add qiskit 0.36.2 the latest version.

### ISSUE THREAD

**Issue by lander-2113** [chaquo/chaquopy#643]
#### Chaquopy version
12.0.0

I am trying to make app with the help of qiskit. 

python {
            buildPython "C:\\Program Files\\python\\python3.8\\python.exe"

            pip {
                // A requirement specifier, with or without a version number:
                install "numpy"
                install "qiskit==0.36.2"
                install "matplotlib"

            }
        }

but it is giving error saying 'ERROR: Command errored out with exit status 1:'

I want help in installing it in an android app. Thank you!

**Comment by lander-2113** [comment]
I am installing qiskit like this

pip {
                // A requirement specifier, with or without a version number:
                install "numpy"
                install "qiskit==0.36.2"
                install "matplotlib"

            }

but it is giving error saying 'ERROR: Command errored out with exit status 1:'

I want help in installing it in an android app. Thank you!

**Comment by mhsmith** [comment]
Thanks for the report. As mentioned in #108, It looks like the last pure-Python version of qiskit was 0.7.0, so please give that a try if you haven't already.

We won't be updating this package in the near future, but I'll update this issue when we do. And if anyone else needs the new version, please click the thumbs up button above, and post a comment explaining why you need it.

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
It's been nearly a year and only one person has requested this package, so we won't be building it in the foreseeable future.

However, the package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add it to the public repository.

If anyone else wants this package, please click the thumbs-up button above and post a comment, and I'll reopen the issue.
