### ISSUE TITLE
Installation of SimpleItk

### ISSUE THREAD

**Issue by ratharva** [chaquo/chaquopy#644]
I am trying to get SimpleItk to work using Chaquopy but it is giving me an error saying "Failed to install SimpleITK from https://files.pythonhosted.org/packages/9a/80/e6b50299cf99f1df7dc20dd860a5ea105e3c901516bc3f5008353293ab13/SimpleITK-2.1.1.2.tar.gz."
Could this be resolved?

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently supported, but I'll update this issue if we add it in the future. And if anyone else wants it too, please click the thumbs-up button above.

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
It's been nearly a year and only one person has requested this package, so we won't be building it in the foreseeable future.

However, the package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add it to the public repository.

If anyone else wants this package, please click the thumbs-up button above and post a comment, and I'll reopen the issue.
