### ISSUE TITLE
skimage.feature peak_local_max function produce different result in chaquopy

### ISSUE THREAD

**Issue by eldon97** [chaquo/chaquopy#646]
#### Chaquopy version

11.0.0

#### Devices or emulators where the issue happens

real device and emulator

#### Relevant parts of your code

https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_peak_local_max.html

#### Describe your issue

chaquopy produce different result from this peak_local_max function. we can check if the result identical or not by saving the result to text like this code below, and compare it between result from the function executed in chaquopy and if executed natively using python in windows/linux machine.
````
from scipy import ndimage as ndi
from skimage.feature import peak_local_max
from skimage import data, img_as_float
import numpy

im = img_as_float(data.coins())

# image_max is the dilation of im with a 20*20 structuring element
# It is used within peak_local_max function
image_max = ndi.maximum_filter(im, size=20, mode='constant')

# Comparison between image_max and im to find the coordinates of local maxima
coordinates = peak_local_max(im, min_distance=20)

numpy.savetxt("coordinates.txt", coordinates)
````

**Comment by mhsmith** [comment]
I replaced the `savetxt` line with a `print` statement, and got exactly the same output on both Linux and Chaquopy:
```
[[276 111]
 [268 160]
 [264 324]
 [262 220]
 [259  73]
 [257 266]
 [255 131]
 [252 354]
 [246 179]
 [244 182]
 [214 280]
 [211 223]
 [199  81]
 [198  26]
 [190 137]
 [187 169]
 [186  58]
 [179 287]
 [173 320]
 [143 161]
 [142 201]
 [141  55]
 [140  90]
 [136 262]
 [132 353]
 [132 320]
 [131 292]
 [130 292]
 [130  26]
 [122 225]
 [119  65]
 [116 143]
 [108 293]
 [107 333]
 [ 71  92]
 [ 68 142]
 [ 66  26]
 [ 65 173]
 [ 64 117]
 [ 63 219]
 [ 61  63]
 [ 59 327]
 [ 56 295]
 [ 50 362]
 [ 46  88]
 [ 37 172]
 [ 34 213]
 [ 26 324]]
```

What numbers are you seeing?

**Comment by eldon97** [comment]
> I replaced the `savetxt` line with a `print` statement, and got exactly the same output on both Linux and Chaquopy:
> 
> ```
> [[276 111]
>  [268 160]
>  [264 324]
>  [262 220]
>  [259  73]
>  [257 266]
>  [255 131]
>  [252 354]
>  [246 179]
>  [244 182]
>  [214 280]
>  [211 223]
>  [199  81]
>  [198  26]
>  [190 137]
>  [187 169]
>  [186  58]
>  [179 287]
>  [173 320]
>  [143 161]
>  [142 201]
>  [141  55]
>  [140  90]
>  [136 262]
>  [132 353]
>  [132 320]
>  [131 292]
>  [130 292]
>  [130  26]
>  [122 225]
>  [119  65]
>  [116 143]
>  [108 293]
>  [107 333]
>  [ 71  92]
>  [ 68 142]
>  [ 66  26]
>  [ 65 173]
>  [ 64 117]
>  [ 63 219]
>  [ 61  63]
>  [ 59 327]
>  [ 56 295]
>  [ 50 362]
>  [ 46  88]
>  [ 37 172]
>  [ 34 213]
>  [ 26 324]]
> ```
> 
> What numbers are you seeing?

hmm, i get exactly the same output of yours in my android device using chaquopy. but in my machine, i get this different output. i have tried it in different desktop, using both windows and linux. it's all the same.
````
[[141  55]
 [142 201]
 [119  65]
 [ 71  92]
 [190 137]
 [214 280]
 [ 56 295]
 [143 161]
 [136 262]
 [130  26]
 [179 287]
 [122 225]
 [199  81]
 [140  90]
 [132 320]
 [ 65 173]
 [131 292]
 [116 143]
 [ 68 142]
 [ 64 117]
 [187 169]
 [ 37 172]
 [ 61  63]
 [ 59 327]
 [211 223]
 [ 50 362]
 [108 293]
 [ 46  88]
 [ 26 324]
 [132 353]
 [ 66  26]
 [ 63 219]
 [107 333]
 [198  26]
 [ 34 213]
 [186  58]
 [173 320]
 [262 220]
 [252 354]
 [257 266]
 [259  73]
 [255 131]
 [264 324]
 [276 111]
 [244 182]
 [268 160]]
````

**Comment by mhsmith** [comment]
It looks like this is a scikit-image version difference. On Linux, version 0.16.2 (the same as Chaquopy) gives the output from my comment, while the current version 0.19.3 gives the output from your comment.

I don't know enough about scikit-image to explain this, so I suggest you research elsewhere if you want to know why it changed. If the difference is causing a problem for your app, please post a comment on #509 explaining why.

**Comment by mhsmith** [comment]
As noted in #509, scikit-image version 0.18.3 is now available for Chaquopy, which gives the same output as 0.18.3.
