### ISSUE TITLE
I can't run a file with py extension

### ISSUE THREAD

**Issue by tellts** [chaquo/chaquopy#649]
Tablet with a diagonal of 10
Android 4.2
```
>>> os.system('python a1.py')
32512
```
The file a1.py contains the code
```
print('Hello')
```
But instead of the word Hello, numbers are displayed.

Previously before this, I entered the following commands:
```
>>> os.chdir('Python')
>>> os.listdir()
['a1.py', 'aq.py', 'as.py']
 
>>> import sys
 
>>> sys.version
'3.8.11 (default, Sep  6 2021, 17:21:11) \n[Clang 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c'
 ```

**Comment by mhsmith** [comment]
Chaquopy does not provide a `python` executable, but code in an external Python file can be run using one of the following methods:

* Use [`runpy.run_path`](https://docs.python.org/3/library/runpy.html#runpy.run_path); or
* Add the containing directory to `sys.path` and then `import` the module. Code can be run multiple times either by putting it in a function, or using [`importlib.reload`](https://docs.python.org/3/library/importlib.html#importlib.reload).

**Comment by tellts** [comment]
Thank you, this command works, only a long dictionary with possible values is displayed below as reference information. Can you please tell me how to change the command so that this dictionary is not displayed?

import runpy
runpy.run_path('a1.py',init_globals=None,run_name=None)

runpy.run_path("a1.py")

**Comment by mhsmith** [comment]
You could assign the return value of `run_path` to a variable, like this:
```
x = runpy.run_path("a1.py")
```
