### ISSUE TITLE
Support for installing rawpy?

### ISSUE THREAD

**Issue by jestontzh** [chaquo/chaquopy#65]
Hello, I am trying to install 'rawpy' using chaquopy

```
python {
            version "3.6.5"

            pip {
                install "rawpy==0.13.0"
                install "imageio==2.4.1"
                install "numpy==1.15.4"
            }
        }
```

It is a java compiler error:
```
ERROR: Failed to install rawpy==0.13.0 from https://files.pythonhosted.org/packages/8e/9f/d070940299b8087edbbd933727eb7573089709b44e3a6e9803b42e5f2ff4/rawpy-0.13.0.tar.gz. For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
```

Wondering if it's an issue with the rawpy library or is there a workaround I can do. 

Thanks!

**Comment by mhsmith** [comment]
rawpy depends on a native library, so we'd have to compile it. It's not highly ranked on PyPI, so it's not a priority at the moment. If anyone else wants it too, please subscribe to this issue and add a thumbs up. 

We would probably be willing to add it in return for a small payment: please [email us](https://chaquo.com/chaquopy/contact) if you're interested in this.

**Comment by sarthaksharma058439** [comment]
Hey i found this video it helps me alot in install and import package in android studio with chaquopy , hopefully this will helps you 

https://youtu.be/BDmB3EFy0Qg

**Comment by oszilevi** [comment]
Hello, is this problem still relevant? 
I am trying to use rawpy in studio, but have gotten the same issue as above, anything new I can try?
Thanks a lot.

**Comment by mhsmith** [comment]
rawpy still isn't available for Chaquopy, but we could build it for a fee of $150. Please [email us](https://chaquo.com/chaquopy/contact/) if you'd like to discuss this.

**Comment by mhsmith** [comment]
rawpy is now available for Chaquopy.
