### ISSUE TITLE
Public Distribution is Projibited

### ISSUE THREAD

**Issue by willor777** [chaquo/chaquopy#651]
Hi, 

I love your work. I am a Python programmer by heart, 6 weeks into Android Development. I enjoy writing apps that perform Financial Analysis. 

I just have a question about the Toast that pops up whenever i run an app with your library. It says this app was built with an Unlicensed copy of Chaquopy and is prohibited from distribution. 

I am just wondering what it would take to get a Licensed version of Chaquopy as i am interested in eventually publishing an app that runs Financial Analysis.

Thanks for your time.

**Comment by mhsmith** [comment]
To get a license key, please follow the instructions at https://chaquo.com/chaquopy/license/ .
