### ISSUE TITLE
update scikit-image to: 0.19.2

### ISSUE THREAD

**Issue by fsuper** [chaquo/chaquopy#652]
dear,
please update scikit-image package to the latest version, since some APIs like exposure.rescale_intensity already changes.

**Comment by mhsmith** [comment]
According to the [`rescale_intensity` documentation](https://scikit-image.org/docs/stable/api/skimage.exposure.html#skimage.exposure.rescale_intensity), that function was last changed in version 0.17. So please try the 0.18.3 build mentioned at https://github.com/chaquo/chaquopy/issues/509#issuecomment-1180982300, and let me know if it works for you.
