### ISSUE TITLE
Run a print statement from Python script that appears in the Logcat

### ISSUE THREAD

**Issue by pcanas** [chaquo/chaquopy#655]
I'd like to run a bunch of `print` statements throughout my Python codebase, and check their values during runtime.
Is there any way I could show the printed values via Android Studio's Logcat, similar to what `android.util.Log` does? Could you provide a working example?

**Comment by mhsmith** [comment]
This should [already work](https://chaquo.com/chaquopy/doc/current/android.html#sys). Have you tried it?

**Comment by pcanas** [comment]
It works, thanks for that.
