### ISSUE TITLE
blspy

### ISSUE THREAD

**Issue by BekzhanOmirzak** [chaquo/chaquopy#670]
#### Chaquopy version
12.0.1

#### Relevant parts of your code
WARNING: Requested blspy>=0.9 from https://files.pythonhosted.org/packages/b7/1d/c618a166b39413a3a382d26b64bd03b6d62d9c740f03f989a86e8d1600dc/blspy-1.0.14.tar.gz (from clvm), but installing version 0.0.0

WARNING: Requested blspy>=0.9 from https://files.pythonhosted.org/packages/b7/1d/c618a166b39413a3a382d26b64bd03b6d62d9c740f03f989a86e8d1600dc/blspy-1.0.14.tar.gz (from clvm), but installing version 0.0.0

Failed to install blspy>=0.9 from https://files.pythonhosted.org/packages/b7/1d/c618a166b39413a3a382d26b64bd03b6d62d9c740f03f989a86e8d1600dc/blspy-1.0.14.tar.gz (from clvm).

#### Describe your issue
I am importing clvm  and chia-dev-tools python modules in my android application, but I am facing this problem.

**Comment by mhsmith** [comment]
Thanks for the report. This package contains native components, so it would have to be built into a wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment and click the thumbs-up button above, and I'll reopen the issue.
