### ISSUE TITLE
E0F when reading a line

### ISSUE THREAD

**Issue by Hiluex** [chaquo/chaquopy#673]
```py
import sys
from os.path import dirname, join
from com.chaquo.python import Python


def main(CodeAreaData):
    file_dir = str(Python.getPlatform().getApplication().getFilesDir())
    filename = join(dirname(file_dir), 'file.txt')

    try:
        original_stdout = sys.stdout
        sys.stderr3
        sys.stdout = open(filename, 'w', encoding = 'utf8', errors="ignore")
        exec(CodeAreaData)
        sys.stdout.close()
        sys.stdout = original_stdout
        output = open(filename, 'r').read()
    except Exception as e:
        sys.stdout = original_stdout
        output = e
    return str(output)
```

how i can track the inputs of the script?

**Comment by mhsmith** [comment]
This code doesn't read anything from standard input, but I guess the code string you pass into the function does?

The [chaquopy-console](https://github.com/chaquo/chaquopy-console) example shows how to link an Android text box to the Python standard input. The key files are [PythonConsoleActivity.java](https://github.com/chaquo/chaquopy-console/blob/master/app/src/main/java/com/chaquo/python/utils/PythonConsoleActivity.java) and [console.py](https://github.com/chaquo/chaquopy-console/blob/master/app/src/main/python/chaquopy/utils/console.py).
