### ISSUE TITLE
How to install a program from a distribution kit in Android?

### ISSUE THREAD

**Issue by tellts** [chaquo/chaquopy#689]
Hello. I have a tablet with Android 4.2 and a diagonal of about 10. In recent months, I installed the latest version of Chaquopy, available at that time.
There is a program for creating a GUI https://pypi.org/project/remi/#files
Please tell me the exact command or several, if there is such an opportunity, to install from the distribution.
The author wrote that it should work on mobile devices and you need to install it so that the GUI works.

**Comment by mhsmith** [comment]
You can add this package to your app using the [`pip` block](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements) in your build.gradle file.
