### ISSUE TITLE
Saving the interpreter state in python

### ISSUE THREAD

**Issue by UtsaChattopadhyay** [chaquo/chaquopy#691]
We are using tflite models for our project, but whenever we are calling the python interface, everytime we need to load the models and do the inference, making the process slow. 
Is there any way or other means we can save the model state and load it once on the python side and use it for inference for other function calls.
Thanks.

**Comment by mhsmith** [comment]
If you're calling tflite via your own Python function, you could cache the loaded model in a global variable in the Python module. Or if you're calling it directly from Java, you could cache it in Java. Without seeing the relevant parts of your source code, it's impossible for me to be any more specific.

**Comment by UtsaChattopadhyay** [comment]
![tflite](https://user-images.githubusercontent.com/44424045/186863643-9f4e6500-ec13-41bb-80bc-7f93bcd660d0.PNG)
So this the code snippet here. So everytime we call main with a frame from java side, we are loading the tflite models under filename, pose_detector = Inference(filename) and calling detect_frame. 
The question was can this be done once and for the later calls from java side, we can directly use the detect_frame function from the saved models?
Thanks

**Comment by mhsmith** [comment]
You can either:
* Cache the models in a Python global variable, like I said; or
* Split your `main` function into one function that loads and returns the models, and another function that uses them. Then you can call the first function once from Java, save the return value in a Java variable, and pass it into the second function multiple times.

**Comment by UtsaChattopadhyay** [comment]
Split your main function into one function that loads and returns the models, and another function that uses them. Then you can call the first function once from Java, save the return value in a Java variable, and pass it into the second function multiple times.

This works thanks.
