### ISSUE TITLE
fail to build by using chaquopy v12.0

### ISSUE THREAD

**Issue by fsuper** [chaquo/chaquopy#692]
#### Describe your issue

[build_fail_log.txt](https://github.com/chaquo/chaquopy/files/9432381/build_fail_log.txt)

![image](https://user-images.githubusercontent.com/98015835/186885344-e33b6397-9cf8-48b5-b192-384ec9eaed70.png)

**Comment by fsuper** [comment]
Hi Dear,
Please help check how to solve this issue. you can find the build log. in the attached.

**Comment by mhsmith** [comment]
It looks like maven.aliyun.com only mirrors things on demand. When I first access a Chaquopy URL on that server, I get a 404 error, but then when I try again a few minutes later, it works.

So if you try repeating the build every few minutes, you might get a little further each time until it eventually completes.

If that doesn't work, you'll have to either use Maven Central directly, or make your own mirror as described [here](https://chaquo.com/chaquopy/doc/current/faq.html#faq-mirror).
