### ISSUE TITLE
Chaquopy can not read a file in the physical device

### ISSUE THREAD

**Issue by NeighborhoodCoding** [chaquo/chaquopy#694]
#### Chaquopy version

8.0.1

#### Devices or emulators where the issue happens
Samsung A80 physical device

#### Relevant parts of your code

**java code**
```
PyObject pyo = py.getModule("myscript");
PyObject obj = pyo.callAttr("main","/storage/self/primary/DCIM/demo.mp4");

```
**Python code(in the myscript.py**
```
def main(path):
    cap = cv2.VideoCapture(path)
```

#### Describe your issue

I have a video file, which is located in "/storage/self/primary/DCIM/demo.mp4"
So I want to read this file by a python code, so I just run the code.
In the python(Chaquopy), the 
`cap = cv2.VideoCapture(/storage/self/primary/DCIM/demo.mp4)`
will be actually executed...

But I got following error.

> 2022-08-29 18:44:16.074 16861-16861/com.example.chyface I/python.stdout: File read start, path: /storage/self/primary/DCIM/demo.mp4
> 2022-08-29 18:44:16.075 16861-16861/com.example.chyface I/python.stdout: cv2 read start
> 2022-08-29 18:44:16.076 16861-16861/com.example.chyface A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xaddff8b1 in tid 16861 (example.chyface), pid 16861 (example.chyface)

The above two line is just a result by print function in python(For debug purpose)
and last one line is main error.

> Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xaddff8b1 in tid 16861 (example.chyface), pid 16861 (example.chyface)

I doubt, maybe, Can Chaquopy not able to read a file in the physical device by a absolute path????

Thank you.

**Comment by mhsmith** [comment]
> Can Chaquopy not able to read a file in the physical device by a absolute path????

Of course it can, but apps can't read files in the /storage directory anymore on newer versions of Android, either in Python or in Java. See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-sdcard) for details.

Also, our OpenCV builds don't currently support mp4 files. For possible alternatives, see  #140.

**Comment by NeighborhoodCoding** [comment]
Thank you, chaquopy can read a file in a physical device

I'll close this issue, because it is OpenCV issue with mp4 files.

**Comment by halexandrino** [comment]
could please give the code sample to read a file in a physical device?

**Comment by mhsmith** [comment]
See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html), especially these sections:
* Read files in Python
* Read files from external storage
* Write files in Python
