### ISSUE TITLE
Can chaquo support xgboost 1.4.2 or newer version?

### ISSUE THREAD

**Issue by lyhzht2012** [chaquo/chaquopy#695]
#### Chaquopy version

12.0.1
#### Relevant parts of your build.gradle file

        python {
            pip {
                install "six"
                install "xgboost==1.4.2"
                install "numpy"
                install "pandas"
            }
        }
#### Describe your issue

* 
I need to use xgboost 1.4.2 version,but chaquo  only supports xgboost 1.1.1 version. However, the xgboost 1.1.1 version reports error, same as this issue https://github.com/chaquo/chaquopy/issues/571. 
When I try to configure "xgboost==1.4.2" in build.gradle,  there're compile errors. Thus, can chaquo provide official support for xgboost 1.4.2 or new version? 

Thanks a lot.

**Comment by mhsmith** [comment]
Please subscribe to #518 for updates on this issue, and see the discussion there for possible workarounds.
