### ISSUE TITLE
The Chaquopy service reports an error of 500

### ISSUE THREAD

**Issue by haover** [chaquo/chaquopy#697]
#### Chaquopy version
top-level build.gradle file：
buildscript {
    repositories {
        .......
        maven {url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.28-alpha'
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "com.chaquo.python:gradle:10.0.1"
    }
}
......

module build.gradle:

plugins {
    id 'com.android.library'
    id 'dagger.hilt.android.plugin'
    id 'com.chaquo.python'
}
android {
    compileSdkVersion 31
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 29
        ndk {
            abiFilters "arm64-v8a"
        }
        python {
            println "it's not Windows"
            buildPython "/usr/local/bin/python3"
            pip {
                install "numpy"
                install "opencv-python"
                install "scikit-image"
                install "scipy"
                install "matplotlib"
                install "src/main/python/thermalfun-0.0.1-0-cp38-cp38-android_21_arm64_v8a.whl"
            }
            pyc {
                src true
            }
        }
    }
}

android studio:
Android Studio Chipmunk | 2021.2.1 Patch 1

**error log:
Execution failed for task ':wdcservice:generateDebugPythonLicenseAssets'.
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
  <html><head>
  <title>500 Internal Server Error</title>
  </head><body>
  Internal Server Error
 
The server encountered an internal error or
  misconfiguration and was unable to complete
  your request.

  
Please contact the server administrator at 
   contact@chaquo.com to inform them of the time this error occurred,
   and the actions you performed just before this error.

  
More information about this error may be available
  in the server error log.

  Apache/2.4.38 (Debian) Server at chaquo.com Port 443

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.**

It has been running normally before, but today it suddenly fails to build APK

**Comment by androidscx** [comment]
We have the same problem

**Comment by mhsmith** [comment]
Thanks, we're looking into it. If anyone else has the same problem, please don't comment: just click the thumbs up button above.

**Comment by mhsmith** [comment]
Sorry about that, the problem has now been fixed.
