### ISSUE TITLE
version 10.0.1 build failed by ':app:generateDebugPythonLicenseAssets'

### ISSUE THREAD

**Issue by likenparklioo** [chaquo/chaquopy#698]
#### Chaquopy version
10.0.1

#### Relevant parts of your build.gradle file
com.chaquo.python:gradle:10.0.1

#### Describe your issue
My Android Studio Version is Android Studio Chipmunk | 2021.2.1 Patch 2

I got chaquopy license, but today(2022/08/31) when i build the project there is some error like this.

==========================================================================
```
Execution failed for task ':app:generateDebugPythonLicenseAssets'.
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
  <html><head>
  <title>500 Internal Server Error</title>
  </head><body>
  <h1>Internal Server Error</h1>
  
The server encountered an internal error or
  misconfiguration and was unable to complete
  your request.

  
Please contact the server administrator at 
   contact@chaquo.com to inform them of the time this error occurred,
   and the actions you performed just before this error.

  
More information about this error may be available
  in the server error log.

  <hr>
  <address>Apache/2.4.38 (Debian) Server at chaquo.com Port 443</address>
  </body></html>

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
==========================================================================

It's looks like license assets request is not work anymore.
I found this news [Chaquopy is now free and open-source, and all license restrictions have been removed.]
We don't want to upgrade version at this time , so we add the following line to your project’s local.properties file:
```
chaquopy.license=free
```

But it still not working.
How do i fix this issue. We still want to use verion 10.01. Is only way to fix this is upgrade to version 12.0.1 ?

Please help us thank you.

**Comment by androidscx** [comment]
today(2022/08/31)，We have the same problem，I suspect their server is down。

**Comment by mhsmith** [comment]
Sorry about that, the problem has now been fixed.
