### ISSUE TITLE
permission deny when open usb port

### ISSUE THREAD

**Issue by kk580kk** [chaquo/chaquopy#702]
#### Chaquopy version

    id 'com.chaquo.python' version '12.0.1' apply false

#### Devices or emulators where the issue happens

xiaomi pad 5
    com.chaquo.python.PyException: SerialException: [Errno 13] could not open port /dev/bus/usb/003/003: [Errno 13] Permission denied: '/dev/bus/usb/003/003'

#### Relevant parts of your code

import serial
ser2 = serial.Serial(PORT,9600 , timeout=1)

#### Describe your issue

try to open port  and read bytes from a usb hub。
return 'permission deny'

the device is already root and the app has the root .
already have request permission in manifest

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.hardware.usb.host"/>

and already request permission in code

and read bytes from usb port test in kotlin code is OK

**Comment by mhsmith** [comment]
> and already request permission in code
> and read bytes from usb port test in kotlin code is OK

Do you mean you're using [this API](https://developer.android.com/guide/topics/connectivity/usb/host)? That won't necessarily give you direct access to the device file: it might be routed through a system service.

> could not open port /dev/bus/usb/003/003

How do you know that's the correct device file?

> the device is already root and the app has the root

What do you mean by this? If the app was really running as root, I don't think it could get a "Permission denied" error. If you do have root shell access, then you might be able to work around this by changing the device file permissions. Though I wouldn't be surprised if access was also blocked by SELinux: if so, there will be some "avc" messages in the logcat.

> `<uses-permission android:name="android.hardware.usb.host"/>`

It probably won't affect your current problem, but according to [the documentation](https://developer.android.com/guide/topics/connectivity/usb/host), this should be `uses-feature`, not `uses-permission`.

**Comment by kk580kk** [comment]
> 

I don't know this [API](https://developer.android.com/guide/topics/connectivity/usb/host) before, I'll try it later.

Our project read from a serial port by ndk, and code wirte by C. 
The library code is [here](https://github.com/mutoukenji/SerialPortApi)

The file '/dev/bus/usb/003/003' is already set to 777, mean everyone can read it.
But I got an error ' [Errno 13] Permission denied: '/dev/bus/usb/003/003', so it is weird.

**Comment by mhsmith** [comment]
> I don't know this [API](https://developer.android.com/guide/topics/connectivity/usb/host) before

If you weren't using that API, then how were you accessing the device from Kotlin or Java?

> Our project read from a serial port by ndk, and code wirte by C.

Were you successful in accessing the serial port from C? If so, was the C code accessing the device file directly, or was it using some Android API?

Chaquopy runs Python code in the same process as the rest of your app, with exactly the same permissions. So if you can access a device file in C code, then you should be able to access it in Python.

**Comment by kk580kk** [comment]
> > I don't know this [API](https://developer.android.com/guide/topics/connectivity/usb/host) before
> 
> If you weren't using that API, then how were you accessing the device from Kotlin or Java?
> 
> > Our project read from a serial port by ndk, and code wirte by C.
> 
> Were you successful in accessing the serial port from C? If so, was the C code accessing the device file directly, or was it using some Android API?
> 
> Chaquopy runs Python code in the same process as the rest of your app, with exactly the same permissions. So if you can access a device file in C code, then you should be able to access it in Python.

this
> Chaquopy runs Python code in the same process as the rest of your app, with exactly the same permissions. So if you can access a device file in C code, then you should be able to access it in Python.

There two libraries, and pyserial is a public python libraries which has the error.

**Comment by kk580kk** [comment]
Question end!

After this:
```
nabu:/ # setenforce 0
nabu:/ # getenforce
Permissive
```

The error from 
`com.chaquo.python.PyException: SerialException: [Errno 13] could not open port /dev/bus/usb/003/003: [Errno 13] Permission denied: '/dev/bus/usb/003/003'`
to 
`serial.serialutil.SerialException: Could not configure port: (25, 'Inappropriate ioctl for device')`

Maybe I should submit an issue on [pyserial](https://github.com/pyserial/pyserial)
