### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by tellts** [chaquo/chaquopy#704]
Hello. Can you please tell me what are the simple ways to create a GUI for scripts designed to run on mobile devices?

**Comment by mhsmith** [comment]
See [this page](https://chaquo.com/chaquopy/doc/current/examples.html) for examples of both text-based and graphical apps.

Within the next few weeks we'll also be releasing Chaquopy support for [BeeWare](https://beeware.org/), which will allow you to write your GUI in Python as well.

**Comment by tellts** [comment]
Thanks for the replies. Are there any video tutorials on creating a program with the GUI? Is it possible to create a GUI using chaquopy-demo on the mobile device itself, while on a business trip, when there is no access to a computer?

**Comment by mhsmith** [comment]
> Are there any video tutorials on creating a program with the GUI? 

There are a few made by other people: just search for "chaquopy" on YouTube.

>  Is it possible to create a GUI using chaquopy-demo on the mobile device itself, while on a business trip, when there is no access to a computer?

Not at the moment, sorry. It's a great idea, and I hope someone makes a tool like this, but we won't have time to do it in the near future.
