### ISSUE TITLE
buildconfig from https://chaquo.com/chaquopy/doc/current/android.html

### ISSUE THREAD

**Issue by MomoSolaris8** [chaquo/chaquopy#706]
#### Describe your issue

Hello , frist thank your project , this is very helpful for me.
And I have an question about buildconfig , I use ubuntu operating system. 
And how can I give in this point config replace windows operating system using linux (ubuntu) 

defaultConfig {
    python {
        buildPython "C:/path/to/python.exe"
        buildPython "C:/path/to/py.exe", "-3.8"
    }
}

**Comment by mhsmith** [comment]
If you've installed Python with your operating system's package manager, then Chaquopy should find it automatically, and there's no need to include any `buildPython` lines.

Or if you want to use a different version of Python, you can install it with [pyenv](https://github.com/pyenv/pyenv) or [miniconda](https://docs.conda.io/en/latest/miniconda.html).

**Comment by MomoSolaris8** [comment]
thank for your recommendation !It is true, I do use the different version of python

**Comment by mhsmith** [comment]
OK, if you've installed a different version of Python, you can use it by either:
* Setting its location with a `buildPython` line; or
* Adding it to your PATH (e.g. using `pyenv global` or `conda activate`), and then running Gradle within that shell.
