### ISSUE TITLE
build-maven error

### ISSUE THREAD

**Issue by lex-geeker** [chaquo/chaquopy#708]
when I run the build-maven.sh by docker, create two images, like this
<img width="808" alt="image" src="https://user-images.githubusercontent.com/32827810/190110782-fe02993f-ff93-4fc0-9c8a-ac5514af1d42.png">
but the second chaquopy-target cannot run
I check the target-Dockerfile, it looks like donn't copy the shell to the docker images
lead to run the containers tips
<img width="594" alt="image" src="https://user-images.githubusercontent.com/32827810/190111396-1070552e-93cf-4afd-8825-2db5dc028b1c.png">

**Comment by mhsmith** [comment]
Yes, sorry, the build instructions and scripts are a bit out of date. We'll be improving them over the next month or so.

If you're interested in working on the Chaquopy plugin, you shouldn't be using the Docker build process anyway. Do this instead:
* Follow the setup instructions in product/README.md. Where it says "copy [sysroots] from another machine", you can do that by downloading the ZIPs from [here](https://repo.maven.apache.org/maven2/com/chaquo/python/target/3.8.13-1/) and then running `target/unpackage-target.sh`.
* Then open the `product` directory in Android Studio or IntelliJ.
