### ISSUE TITLE
Remove 32-bit ABIs (armeabi-v7a and x86)

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#709]
Here are the ABI statistics for Electron Cash, which was first released in 2018.

To find this in the Google Play console for your own app:
* Go to Reach and Devices > Overview (**NOT** "Statistics").
* Select time period at the top right.
* Scroll down and expand "ABI".

This includes devices which have the app installed and have been turned on within the last 30 days. 

![abis](https://user-images.githubusercontent.com/166954/192260218-4b0bd9d5-2f1e-464c-9767-eb46bd5df375.png)

Obviously there's a glitch with the "unreported" category, but if we exclude that category, 64-bit support over the last 12 months has risen from 82% to 86%. So we shouldn't remove 32-bit support yet, but we can probably do it in 1 or 2 years.

**Comment by mhsmith** [comment]
Google recently released the ["Pixel 7, the first 64-bit-only Android phone"](https://android-developers.googleblog.com/2022/10/64-bit-only-devices.html). However, at the end of the article they say "Please continue supporting 32-bit ABIs", because there are still plenty of low-end devices being released with 32-bit hardware.

**Comment by mhsmith** [comment]
64-bit support has now reached 92% of devices with known ABIs (81/88):

<img width="522" alt="Screenshot 2023-10-03 at 09 47 34" src="https://github.com/chaquo/chaquopy/assets/166954/3c21f921-8ed0-486a-b948-812705763c86">

@freakboy3742: So my proposal is that we omit Android 32-bit support when we add Python 3.12 and later, but maintain it for now in the existing versions (3.11 and earlier).

**Comment by freakboy3742** [comment]
Agreed that this approach seems reasonable. By the time 3.12 has any sort of serious adoption, 32 bit platforms will be even more marginal; given that we're about to start upstreaming changes, making a clean break sounds reasonable.

**Comment by IsakTheHacker** [comment]
Please don't stop supporting 32-bit ABIs!!! They are important for Wear OS. Not even the newest watches (Samsung Galaxy Watch 6 and Google Pixel Watch 2) support 64-bit ABIs.
![Screenshot from 2023-10-04 23-21-12](https://github.com/chaquo/chaquopy/assets/67378443/3d4494fb-5234-49cd-b7d6-cd72ecef860c)
![Screenshot from 2023-10-04 23-24-16](https://github.com/chaquo/chaquopy/assets/67378443/78ee3cab-f96f-409a-99ee-51d9b8513ab6)

**Comment by mhsmith** [comment]
Interesting – both of those CPUs are 64-bit capable, but I guess they've decided to ship a 32-bit OS to save RAM.

We're not removing 32-bit ABIs entirely, we just won't be including them in Python 3.12 or newer. But we'll keep 32-bit support in Python 3.11 and earlier for now, and probably right up until Python 3.11 is retired in 2027. Hopefully Android will be 64-bit only by then.

**Comment by IsakTheHacker** [comment]
That is great! Although it would be nice to have Python 3.12 be the last 32 bit version since it includes some pretty significant performance improvements: https://docs.python.org/3.12/whatsnew/3.12.html#optimizations

**Comment by mhsmith** [comment]
Implemented as discussed.

**Comment by mhsmith** [comment]
Yes.

**Comment by mhsmith** [comment]
Because those ABIs wouldn't be much use otherwise.

**Comment by IsakTheHacker** [comment]
"Much use"? What do you mean by that? The previous 32 bit packages built for 3.8, 3.9 and 3.10 will still be kept I am guessing so I don't get your point.

So to clarify, when we start building pip packages for 3.11 and 3.12, all 3.11 packages will also be built for 32 bit ABIs while 3.12 packages will only be built for 64 bit. Is that correct?

**Comment by mhsmith** [comment]
Yes, that's correct. I meant to say "those Python versions", sorry.

**Comment by mhsmith** [comment]
I mean, "those ABIs wouldn't be much use on Python 3.11".

**Comment by LillieH1000** [comment]
Honestly don't think this was a good idea for certain scenarios as Google and companies like Amazon are still releasing devices with 32bit abis for Android TV, such as the Google TV Streamer which has no support for arm64, so if anybody wanted to use this project for Android TV, they are limited on python versions.

**Comment by mhsmith** [comment]
Staying on Python 3.11 shouldn't be too much of an inconvenience at the moment. If this is still a factor in a couple of years, we may revisit it.
