### ISSUE TITLE
[Qustion] Chaquopy for bitmap input

### ISSUE THREAD

**Issue by NeighborhoodCoding** [chaquo/chaquopy#720]
I searched issue and FAQ, but seems no similar issues.

I got some bitmap in java, and want to run chaquopy with bitmap inputs.
How can I transfer bitmap input to chaquopy?

I searched some google, and they uses bitmap to str, and str to bitmap in both
but When I tried bitmap with 32bits(not 24bit) it looks some error exist in python.
Can I direct pass the bitmap? Or can I see some Reference or Docs? 

Thanks in advance.

**Comment by NeighborhoodCoding** [comment]
Add : I have some shape at python.

(At python,) cv2.imdecode has result with shape of 540 x 960 x 4

what is 4 comes from? I have bitmap(maybe 32bit) of 540 x 960 x 3...

**Comment by mhsmith** [comment]
>  it looks some error exist in python.

Please post the full error message, and the relevant sections of your code.

> what is 4 comes from? I have bitmap(maybe 32bit) of 540 x 960 x 3...

4 is probably the alpha channel.

**Comment by NeighborhoodCoding** [comment]
Thanks for your help!
It was alpha channel and I dropped the alpha channel to make RGB channel.

Thank you.
