### ISSUE TITLE
close chaquo

### ISSUE THREAD

**Issue by huazesi** [chaquo/chaquopy#722]
After the app runs for a period of time, I need to close chaquo and then restart chaquo, but I read the documentation and there is no way to close it, so I tried to assign the platform value to empty and then try to start it again, but restarting will report this error ValueError: <class '_frozen_importlib_external. PathFinder'> is not in list
Hope to give a way to completely shut down chaquo I need to restart after shutting down

**Comment by mhsmith** [comment]
Chaquopy doesn't provide any way to restart Python within the same process. Even if Python itself would support it, most native Python modules don't. So the only way to restart Python is to [restart your app's whole process](https://stackoverflow.com/questions/6609414). 

Why do you want to do this? If you can explain what you're trying to achieve, I may be able to suggest something easier and faster.

**Comment by hgwz8** [comment]
I need to make this apk with Chaquopy a plug-in for my other apk to dynamically load because Chaquopy can only start one python in the same process, which means I can only load one plug-in but I will make many plug-ins for my host app to dynamically load these plugins dex so I just want to stop a plugin's python to start a new plugin's python process

**Comment by hgwz8** [comment]
The plug-in ppp uses the dex file used by the Chaquopy host app to dynamically load the plug-in
The host app loads the plugin app. The plugin app and the host app will be the same process, which means that Chaquopy can only be started once and cannot be closed. That is to say, only one plugin can be started, but I have many plugins that need to be called in the host app. So I want to stop Chaquopy and load another plugin's Chaquopy

**Comment by hgwz8** [comment]
Is there a way to restart python without restarting the app

**Comment by mhsmith** [comment]
In that case, maybe the best solution is to access Chaquopy through a [service with a `process` attribute](https://developer.android.com/guide/topics/manifest/service-element#proc). That way, your user interface can be in one process, and Chaquopy can be in a separate process which you can restart independently whenever you want.

**Comment by baiwanzhou** [comment]
I tried to start Chaquopy with multiple threads, but I still get an error after I set Python.platform=null and start it again. Do you have a better solution? How to execute Chaquopy in a separate thread? Please give a solution

**Comment by baiwanzhou** [comment]
![image](https://user-images.githubusercontent.com/108533707/192746918-414c3362-03f8-46fd-90ba-95a57ac6b7a8.png)

**Comment by baiwanzhou** [comment]
![image](https://user-images.githubusercontent.com/108533707/192747369-c6e458f4-c3f6-4577-8cea-0f55a125d56c.png)

**Comment by mhsmith** [comment]
If you must restart Python (and if possible, I recommend you restructure your code so you don't have to), then you'll need to use a separate *process*, not a separate thread. See the link in my previous post, and read the Android documentation about services.
