### ISSUE TITLE
Chaquopy with Flutter

### ISSUE THREAD

**Issue by MukalDadhwal** [chaquo/chaquopy#726]
Hey,
I am developing a flutter application and wanted to run some python code from inside the application. From the [official python page] (wiki.python.org/moin/Android) I found your project and was wondering whether we can use it inside flutter framework as well.
The faq page on your website says it can be used with react native and all other frameworks which can let you add content to build.gradle file as well as call java methods, I guess flutter supports both. So, could you please guide how can we use it inside flutter or point out to some resources?

**Comment by mhsmith** [comment]
There's an unofficial Chaquopy Flutter plugin here: https://pub.dev/packages/chaquopy. You can either use it directly, or explore its [source code](https://github.com/jaydangar/chaquopy_flutter) to understand how it works and then use the same techniques in your own app.

**Comment by MukalDadhwal** [comment]
I have successfully implemented the code in my app thanks :)
