### ISSUE TITLE
Failure when installing scikit-learn >=1.1.0

### ISSUE THREAD

**Issue by eruditehassan** [chaquo/chaquopy#732]
#### Relevant parts of your code

```
python {
            buildPython "C:/Users/erudi/AppData/Local/Programs/Python/Python38/python.exe"
            pip {
                // A pip requirement specifier, with or without a version number:
                install "neurokit2"
                install "numpy == 1.17.3"
                install "scikit-learn >=1.1.0"
            }
        }
```

#### Describe your issue

Hi, 

I have to modify an application at a company I have recently joined. The application has several python libraries linked, among which **Scikit-learn** is causing problems when trying to run the app on an emulator (tried different emulators). The error I am receiving says that Scikit learn could not be installed because it requires numpy, while numpy is already installed and I made sure to explicitly put that in `pip {}` block as well.

The error I am receiving is shown below:

```
Collecting scikit-learn>=1.1.0
  Using cached https://files.pythonhosted.org/packages/10/ae/123b6d1fdb2fdb1aea6793abe33ed1bf19efd0a936d2f39040a5e99f402b/scikit-learn-1.1.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\erudi\AppData\Local\Programs\Python\Python38\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\erudi\\AppData\\Local\\Temp\\pip-install-no90mksm\\scikit-learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\erudi\\AppData\\Local\\Temp\\pip-install-no90mksm\\scikit-learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: C:\Users\erudi\AppData\Local\Temp\pip-install-no90mksm\scikit-learn\
    ERROR: Command errored out with exit status 1:

    Complete output (22 lines):
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "C:\Users\erudi\AppData\Local\Temp\pip-install-no90mksm\scikit-learn\setup.py", line 200, in check_package_status
        module = importlib.import_module(package)
      File "C:\Users\erudi\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'numpy'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\erudi\AppData\Local\Temp\pip-install-no90mksm\scikit-learn\setup.py", line 329, in <module>
        setup_package()
      File "C:\Users\erudi\AppData\Local\Temp\pip-install-no90mksm\scikit-learn\setup.py", line 303, in setup_package
        check_package_status("numpy", min_deps.NUMPY_MIN_VERSION)
      File "C:\Users\erudi\AppData\Local\Temp\pip-install-no90mksm\scikit-learn\setup.py", line 227, in check_package_status
        raise ImportError(
    ImportError: numpy is not installed.
    scikit-learn requires numpy >= 1.17.3.
    Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
    
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: Failed to install scikit-learn>=1.1.0 from https://files.pythonhosted.org/packages/10/ae/123b6d1fdb2fdb1aea6793abe33ed1bf19efd0a936d2f39040a5e99f402b/scikit-learn-1.1.2.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Or try using one of the following versions, which are available as pre-built wheels: ['0.22.1', '0.23.2', '0.24.1'].
Chaquopy: Exit status 1
Failed to install scikit-learn>=1.1.0 from https://files.pythonhosted.org/packages/10/ae/123b6d1fdb2fdb1aea6793abe33ed1bf19efd0a936d2f39040a5e99f402b/scikit-learn-1.1.2.tar.gz.
```

**Comment by mhsmith** [comment]
Thanks for the report. Chaquopy doesn't currently support scikit-learn 1.1.0 or later, but it supports several older versions, the newest of which is 0.24.1. See [the repository](https://chaquo.com/pypi-7.0/scikit-learn/) for a full list: hopefully one of those will work for you.

Or if you'd like to try building the new version yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). This package only required a small patch, so the update should not be too difficult. If you're successful, please make a pull request so we can add the new version to the public repository.

**Comment by eruditehassan** [comment]
Thank you for the explanation. On understanding this further, I found that the issue was actually being caused by **neurokit2** package, which installs a bunch of python libraries on its own. The latest version (currently 0.2.1) attempts to install scikit-learn version > 1.1.0 which is not supported by Chaquopy (as explained by @mhsmith). A quick fix is to downgrade the neurokit2 version to an earlier one. I downgraded it to 0.1.5 and it worked for me (just modifying the line `pip install "neurokit2"` to pip install `"neurokit2 == 0.1.5"`. Hopefully this explanation will be helpful for anyone else having the same problem.

**Comment by random-ship-it** [comment]
![image](https://user-images.githubusercontent.com/100432383/205694074-396ce45c-a59a-4a5f-8096-615bb48305ca.png)
Hello,

I have a similar problem, mlxtend is trying to install a scikit-learn version does is no supported.
It seems that downgrading the version might help, so can someone please tell me where i can find available versions.

**Comment by mhsmith** [comment]
You can find a list of old versions at https://pypi.org/project/mlxtend/#history. In this case, it looks like 0.19.0 is the most recent version that Chaquopy can install.

**Comment by random-ship-it** [comment]
It's working now and apparently it has to be python 3.8.
I appreciate the help!

**Comment by Flyfish233** [comment]
Hey everyone who still trying to use `scikit-learn` or `neurokit2`

You can manually build a new version yourself with instructions [here](https://github.com/chaquo/build-wheel); however, version `1.1.3` is the latest version the existing patch supports. So, if your requirements are up to 1.2+, you should modify the patch.

Below is a modified YAML for Python 3.9 targets still working well. I also tried the below versions all working well with the exsiting patch script:

- 1.0.2
- 1.1.0
- 1.1.3

```
package:
  name: scikit-learn
  version: "1.1.3"

requirements:
  build:
    - cython 0.29.24
  host:
    - chaquopy-openblas 0.2.20
    - numpy 1.23.3
    - scipy 1.6.3
```

**Comment by mhsmith** [comment]
Thanks very much: I've built scikit-learn 1.1.3 and added it to the public repository for Python 3.8 and 3.9. Later versions of Python will have to wait until they have a version of SciPy (#970).

If anyone needs a newer version of scikit-learn, see #878.
