### ISSUE TITLE
NoneType error while loading image 

### ISSUE THREAD

**Issue by SzymonSko** [chaquo/chaquopy#734]
Hello, I just tried to run my python script inside Android studio, and I'm facing the error: com.chaquo.python.PyException: TypeError: 'NoneType' object is not subscriptable

![image](https://user-images.githubusercontent.com/76167839/199040442-51ef80ad-c6dd-4a69-9285-17253ec5bb90.png)
so I assume it's about that line, which is working fine while running out of android studio

![image](https://user-images.githubusercontent.com/76167839/199040609-df362e7f-bdbd-4a31-a0b7-e22973592742.png)

**Comment by mhsmith** [comment]
To read data files from your source code directory, follow the instructions [here](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

**Comment by SzymonSko** [comment]
Thanks! Can u please help me with another, issue, I'm trying to save a jpg file but there is a problem with the directory, i couldn't find anything about it. 
![image](https://user-images.githubusercontent.com/76167839/199128337-97263aed-4ee7-46a1-87a1-33180d3b41c2.png)
![image](https://user-images.githubusercontent.com/76167839/199128310-2e23c852-f68e-4711-8e5c-1bee26bfb928.png)

**Comment by mhsmith** [comment]
An Android device or emulator can't directly write files to your desktop machine. Write to `os.environ["HOME"]` instead, as described [here](https://chaquo.com/chaquopy/doc/current/android.html#android-os).
