### ISSUE TITLE
[kociemba] run wrong

### ISSUE THREAD

**Issue by liangzilixueha** [chaquo/chaquopy#735]
#### Chaquopy version
12.0.1

#### Relevant parts of your build.gradle file
![图片](https://user-images.githubusercontent.com/85008631/199048149-e384387a-1c75-4a75-b018-97b5a4df883e.png)
![图片](https://user-images.githubusercontent.com/85008631/199048279-992c4954-edb9-454c-bafe-cf11da03c5e9.png)

#### Describe your issue
is kociemba unsupportable？i can‘t build it with “pip kociemba” but others can
just like 
![图片](https://user-images.githubusercontent.com/85008631/199048759-14603874-cfc5-4293-850d-9d0807310c5a.png)
👆👆👆👆it could work 👆👆👆
but 
![图片](https://user-images.githubusercontent.com/85008631/199049579-66100962-54b9-4b3c-9bb5-4661904e7267.png)
is anything i can do？

**Comment by mhsmith** [comment]
Thanks for the report. This package contains native components, so it would have to be built into a wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

**Comment by mhsmith** [comment]
It's been over a year, and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
