### ISSUE TITLE
Passing picture from java to python

### ISSUE THREAD

**Issue by SzymonSko** [chaquo/chaquopy#739]
Hi, I'm trying to figure out a way to:

Capture or choose a picture from the gallery,
Then use that image in my python script,
And display it on the phone, I was trying to use firebase([Errno 30] Read-only file system storage)
and information from [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-read) but it didn't work for me

**Comment by mhsmith** [comment]
There's an [FAQ entry](https://chaquo.com/chaquopy/doc/current/faq.html#faq-sdcard) with a full example of this. If you need help with an error, please post the [full stack trace](https://stackoverflow.com/a/23353174) and the relevant sections of your code.
