### ISSUE TITLE
Wechat QR code detector package missing?

### ISSUE THREAD

**Issue by dasavc** [chaquo/chaquopy#740]
I'd like to use Wechat QR code detector from the opencv-contrib. I've added to gradle:

```
 python {
            pip {
                install "opencv-contrib-python"
            }
       }
```

I can use the cv2 module, but it reports that wechat_qrcode_WeChatQRCode is not part of the cv2.cv2

If I understood well this package is not included in chaquopy? Any chance it would get included? I read that I can also create my own package, but I've never done this before - any hint at the level of complexity on this task?

**Comment by mhsmith** [comment]
See #620, and please search for existing issues before creating new ones.

This package required a medium-sized patch to build for Android, so building a new version may be difficult.
