### ISSUE TITLE
Chaquo Console app script files Directory

### ISSUE THREAD

**Issue by NigelKazembe** [chaquo/chaquopy#742]
I know that the Chaquo Console app reads .py files that are referenced in the project files (specifically under the python directory), however, is there a way for the app to read .py files that are stored in say for example the storage/emulated/0/Download folder and run their scripts?

**Comment by mhsmith** [comment]
As it says in [this FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-sdcard), you can't access the external storage folder directly in recent versions of Android, so adding it to `sys.path` won't work. However, by following the example in the FAQ, you can use the system file picker to get the content of any file, and then do whatever you want with that content, such as passing it to [`exec`](https://docs.python.org/3/library/functions.html#exec).
