### ISSUE TITLE
An issue with passing images from python to android 

### ISSUE THREAD

**Issue by SzymonSko** [chaquo/chaquopy#743]
Hi, I was trying to pass an image from my python script into Java, but I'm facing a problem with the byte array. What I mean is:
I'm trying to pass that image [as described](https://github.com/chaquo/chaquopy/issues/167) 
as I see python returns byte: 
![image](https://user-images.githubusercontent.com/76167839/200191624-fc1df083-1505-493b-a17a-f94af32d5305.png)
so I guess it should show anything
But my app is just a white screen.
Java code:
![image](https://user-images.githubusercontent.com/76167839/200191649-4a5b3b57-6529-4ce5-935a-3d626b024316.png)

**Comment by mhsmith** [comment]
You need to identify whether the problem is in:
* The image itself 
* Converting the image from Python to Java
* Displaying the image in Java

I suggest you test them one at a time in that order. So first, make your Python code [write the image to a file](https://chaquo.com/chaquopy/doc/current/android.html#android-os), and retrieve the file with the Device File Explorer. If it looks OK, try doing the same thing after the Python to Java conversion, and so on.

**Comment by SzymonSko** [comment]
So the thing is, the image itself is saving in the way I want it to be saved. I see byte array is passed to java but I guess it's a problem with that java part mentioned here
![image](https://user-images.githubusercontent.com/76167839/201364935-964563d1-68cc-4833-8c1a-b1b62042c124.png)

**Comment by mhsmith** [comment]
> the image itself is saving in the way I want it to be saved

But was the image ever actually correct on the Python side? That's what I suggested you test in my previous comment.

**Comment by SzymonSko** [comment]
Yep, the python part is working fine, I'm struggling with Java part

**Comment by mhsmith** [comment]
Then the next step would be to write the image to a file on the Java side, get it with the Device File Explorer, and see if it's correct.
* If the file written by Java is correct, then the problem isn't with Chaquopy but in the way you're displaying it, so you'll have to look for help elsewhere.
* If the file written by Java is not correct, then the bytes must be different between Python and Java. I can look into this if you provide the relevant code on the Python side, and an example of the data you're seeing on both sides.

You haven't mentioned what format this image is in. `decodeByteArray` requires an encoded image file like PNG or JPG. If you're dealing with a raw bitmap then you'd have to use something lower-level like [`createBitmap`](https://developer.android.com/reference/android/graphics/Bitmap#createBitmap(int[],%20int,%20int,%20int,%20int,%20android.graphics.Bitmap.Config)), though switching to PNG format would probably be easier.

**Comment by SzymonSko** [comment]
So what i tried:
     I tried to pass that image into java using tobytes(), i also tried to pass it as base64
     anyways the error is "Failed to create image decoder with message 'unimplemented' "

**Comment by SzymonSko** [comment]
So what i need is
OnClick button 
run scrip that opens photo (works)
same script edit photo(works)
at this moment i have my photo as array and need to pass it to java and set as ImageView

**Comment by mhsmith** [comment]
>I tried to pass that image into java using tobytes(),

Like I said, `decodeByteArray` can't read a raw bitmap. The easiest solution is to encode it to a PNG file before passing it to Java. For example, if you're using OpenCV, you can do that with `imencode`.
