### ISSUE TITLE
FileNotFoundError when accessing app-specific files despite using os.path.join(os.path.dirname(__file__), "filename.txt")

### ISSUE THREAD

**Issue by GoatseAdams** [chaquo/chaquopy#745]
As the title says, already checked #144 and docu.

#### Chaquopy version
13.0

#### Devices or emulators where the issue happens
Samsung Galaxy S10

#### Relevant parts of your code
```
from os.path import dirname, join
with open(join(dirname(__file__), fname)) as f:
    pass
```

#### Describe your issue
The app starts but soon crashes with FileNotFoundError. Adding a `print(os.listdir(dirname(__file__)))` also fails with the same error. 

In the documentation gets mentioned that (paraphr.) data files inside directories with an `__init__.py` need to have the module imported first, so this may be the issua at hand. How and where to import the module in order to access data files in the corresponding directory?

EDIT: To add to it, the same code works when invoked through an interpreter on my machine (Win 11, CPython, venv).

**Comment by mhsmith** [comment]
Please post the full stack trace, and the same for the `listdir` case.

> In the documentation gets mentioned that (paraphr.) data files inside directories with an `__init__.py` need to have the module imported first, so this may be the issua at hand. How and where to import the module in order to access data files in the corresponding directory?

To answer that I would need to know the layout of your source code, specifically:
* The path to the file containing this code
* The path to the data file you're trying to load
* The value of `fname`

**Comment by GoatseAdams** [comment]
Thank you very much for answering on such short notice.

> The path to the file containing this code

`./app/src/main/python/packagename/util/files_util.py`

Where `.` is the root directory of the Android Studio project.

> The path to the data file you're trying to load

1) `./app/src/main/python/packagename`

2) `./app/src/main/python/packagename/util`

3) `./app/src/main/python/assets`

N.B. the same file is copied on all three locations. The first two directories have an `__init__.py` file.

> The value of `fname`

1) `"../articles.txt"`

2) `"articles.txt"`

3) `"../../articles.txt"`

The same error message appears in all three cases.

I am momentarily not able to post the stack trace because I have no access to my computer. I will do that on Monday. Again, many thanks!

**Comment by mhsmith** [comment]
For performance reasons, Chaquopy doesn't extract .py files into separate files on the device: it reads them directly from the APK. So the only files that will exist under `AssetFinder/app` are those with names *other* than .py, and the only directories that will exist are the directories that contain those files.

So looking at your output with that in mind:

> FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.****.****/files/chaquopy/AssetFinder/app/packagename/util

This is probably because `packagename/util` doesn't contain anything except .py files.

> The same code when run from ./app/src/main/python/test.py with the fname as "articles.py" returns:

In this case you can see that articles.txt *does* exist, because it's a non-Python file. I'm not sure if articles.py was a typo for articles.txt, but if you did have a file of that name, it wouldn't be extracted, because it's a Python file. 

If you are actually trying to list and read Python files at runtime, you can use APIs like [`pkgutil.iter_modules`](https://docs.python.org/3/library/pkgutil.html#pkgutil.iter_modules) or [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html), both of which will work with Chaquopy's importer without requiring the Python files to actually exist on the filesystem.

**Comment by GoatseAdams** [comment]
That makes so much sense, than you for your answer.

So to recapitulate (if I understood you correctly),

1) don't put any non-python files inside package/module directories; it's bad practice

2) don't fret about `listdir()` not being able to list files in a folder if the folder contain no non-python files; on the other hand, `open()` on non-python files inside those directories should work

3) assets such as text files, databases and images that are to be sipped with and opened with Chaquopy Python can be placed inside of `./app/src/main/python` directory; one could even also use a helper function to fetch filenames from the default Android Studio assets folder (with a bunch of hard coded `../`) or make a resource fetcher class (overkill imho)

4) when and should one need to access those `.py` files, one should use `pkgutil.iter_modules` or `importlib.resources` (that should in the cast majority of cases be unnecessary)

So, the whole thing actually is a non-issue and can be closed?

P.S. you are right, I missspelled the `articles.txt`.

**Comment by mhsmith** [comment]
> 1. don't put any non-python files inside package/module directories; it's bad practice

No, I never said that. You can put them wherever you want, and it's generally clearer to put them in the same directory as the code that uses them.

> 2. don't fret about `listdir()` not being able to list files in a folder if the folder contains no non-python files; on the other hand, `open()` on non-python files inside those directories should work
> 3. assets such as text files, databases and images that are to be sipped with and opened with Chaquopy Python can be placed inside of `./app/src/main/python` directory; 

That's correct.

> one could even also use a helper function to fetch filenames from the default Android Studio assets folder (with a bunch of hard coded `../`) or make a resource fetcher class (overkill imho)

If you mean `app/src/main/assets`, that isn't extracted from the APK either, so it can only be accessed through the AssetManager. Basically, the only files you can access with this technique are non-Python files under `app/src/main/python`. 

> 4. when and should one need to access those `.py` files, one should use `pkgutil.iter_modules` or `importlib.resources` (that should in the vast majority of cases be unnecessary)

Yes, there are very few situations where you'd want to read a .py file as data, as opposed to simply importing it.

> So, the whole thing actually is a non-issue and can be closed?

Yes, as long as you've solved your problem.

**Comment by GoatseAdams** [comment]
Thank you for clearing this up.
