### ISSUE TITLE
k-means clustering model fitting is not working in Chaquopy

### ISSUE THREAD

**Issue by jyotiprajapati98** [chaquo/chaquopy#749]
I am trying to fit the k-means clustering model in Chaquopy but it is not working and not throwing any errors also. Please help me with that. The regression model fitting is working fine.

classpath "com.android.tools.build:gradle:4.2.1"
classpath "com.chaquo.python:gradle:13.0.0" 
I am using updated version

**Comment by jyotiprajapati98** [comment]
I am trying to fit the k-means clustering model in Chaquopy but it is not working and not throwing any errors also. Please help me with that. The regression model fitting is working fine.

**Comment by jyotiprajapati98** [comment]
I am implementing Adaptive_K_Value() method which will return the random k values from image.

```
def Adaptive_K_Value(image):
    
    print(image)
    data = image / 255.0  # use 0...1 scale
    print(data)
    data = data.reshape(image.shape[0] * image.shape[1], 3)
    print(data.shape)

    data = np.array(data)
    print(data)
    
    """
    data = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])
    #simple linear regression 
    X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
    y = np.dot(X, np.array([1, 2])) + 3
    reg = LinearRegression().fit(X, y)
    
    print(reg)
    reg.score(X, y)
    print(reg.score(X, y))
    """
    max_Dunn = float("-inf")
    min_DB = float("inf")
    max_Silhoutte = float("-inf")
    max_Calinski = float("-inf")

    ideal_k = k = 2

    while True:
        print("k = ", k + 1)
        reg = LinearRegression().fit(X, y)
    
        print(reg)
        reg.score(X, y)
        print(reg.score(X, y))
        kmeans = KMeans(n_clusters=k).fit(X)
        print("kmeans ",kmeans)
        print(data.shape)
        
        #kmeans.fit(data)
        print("fitted model ",kmeans)

        kmeans_labels = kmeans.labels_
        print(kmeans.labels_)
        print(kmeans.cluster_centers_)

        distances = pairwise_distances(data)
        Dunn = dunn(distances, kmeans_labels)
        print("Dunn Index kmeans =", Dunn)
        DB = davies_bouldin_score(data, kmeans_labels)
        print("DB Index kmeans =", DB)
        Silhoutte = silhouette_score(data, kmeans_labels)
        print('Silhouette Score kmeans=', Silhoutte)
        Calinski = metrics.calinski_harabasz_score(data, kmeans_labels)
        print('Calinski-Harabasz Index kmeans =', Calinski)

        count = 0
        if max_Dunn < Dunn:
            count += 1
        if min_DB > DB:
            count += 1
        if max_Silhoutte < Silhoutte:
            count += 1
        if max_Calinski < Calinski:
            count += 1
        if count < 2:
            break
        else:
            ideal_k = k
            k += 1
            max_Dunn = Dunn
            min_DB = DB
            max_Silhoutte = Silhoutte
            max_Calinski = Calinski

    print("\nOptimum K value =", ideal_k + 1)
    return ideal_k
```

**Comment by mhsmith** [comment]
Instead of duplicating this discussion, let's continue [on StackOverflow](https://stackoverflow.com/questions/74441930).

**Comment by jyotiprajapati98** [comment]
K-means is supported by Chaquopy or not ??

**Comment by jyotiprajapati98** [comment]
Hello,
I do not understand your concern, I have clearly mentioned all the errors
encountered, uploaded the code I'm using and asked a simple question if the
libraries and computation required for K- means works on Chaquopy or not,
if it doesn't I will have to figure out something else, I have been working
on this since a long time so I hope you help me out with an answer.

Best Regards

**Comment by mhsmith** [comment]
Chaquopy supports the entire scikit-learn API as far as I know, but there may be a difference in behavior depending on the scikit-learn version ([Chaquopy currently supports version 0.24.1](https://chaquo.com/pypi-7.0/scikit-learn/)).
