### ISSUE TITLE
call python method from java with a function/callback parameter from java

### ISSUE THREAD

**Issue by almaz1213** [chaquo/chaquopy#751]
Hi guys,

e.g. given a python module
```
class module1:
  
  def request(arg, callback):
    print('got arg', arg)
    if callable(callback):
      callback({"response": {"data": "OK"}})
```

how can i call the request method from java and obtain the resulted data from the method?

please, give an example with java code including the callback object in java.

thanks in advance

**Comment by mhsmith** [comment]
As it says [here](https://chaquo.com/chaquopy/doc/current/python.html#classes), you can use Python `()` syntax to call any Java object which implements a functional interface. There's an example in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-callback).

Or if you prefer, you can just pass any Java object to the Python function, and then call a method on it using normal Python syntax.

**Comment by almaz1213** [comment]
@mhsmith 
RE: "As it says [here](https://chaquo.com/chaquopy/doc/current/python.html#classes), you can use Python () syntax to call any Java object which implements a functional interface"

in our case the python module must be clear python that does not use java api.

RE: "There's an example in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-callback)"
 it doesn't clarify me.
 
 RE: "Or if you prefer, you can just pass any Java object to the Python function, and then call a method on it using normal Python syntax"
 
 could you provide an example in java, please? thanks

**Comment by almaz1213** [comment]
cool. thanks Malcolm!
