### ISSUE TITLE
Is it possible to implement my entire python code in chaquopy for Android Studio?

### ISSUE THREAD

**Issue by JaystonHayes** [chaquo/chaquopy#753]
I have made a face recognition system with attendance in python visual studio code that uses haar cascade and LBPH. Although I need to make it work for android studio instead of laptop/computers. Is there a way to implement this? I am new to chaquopy. I added snippets for the codes. For registration of the faces the system in visual studio takes 250 pictures of a single person after asking for the name and storing them in a dataset folder, in Android Studio I need to do the same thing for registration although what I have seen from youtube it is mostly manual input or taking pictures one by one using the camera button. I am sorry if I am asking too much since I really ran out of leads on implementing this.
![snip 1](https://user-images.githubusercontent.com/118749540/203086722-56d4541b-4213-4017-b4ce-31cb2c7a4990.png)
![snip 2](https://user-images.githubusercontent.com/118749540/203086738-d04ba157-a700-4e29-ae34-3373bd541a04.png)
![snip 3](https://user-images.githubusercontent.com/118749540/203086746-a29139ed-ee31-4964-bd7d-e1bfb4af2ffd.png)
![snip 4](https://user-images.githubusercontent.com/118749540/203086969-815af676-25b3-49d7-a2c0-9432e71704e1.png)

For face registration. 
![registerface1](https://user-images.githubusercontent.com/118749540/203088951-8f3fcac4-5d81-408b-a123-7af0c917f655.png)
![registerface2](https://user-images.githubusercontent.com/118749540/203088960-8724ddb3-1b2f-4269-9bb9-432a90a83cc7.png)
![registerface3](https://user-images.githubusercontent.com/118749540/203088967-a7b4d2da-e6a7-47fe-9e0c-6e55aab8dc9d.png)
![registerface4](https://user-images.githubusercontent.com/118749540/203088973-94430ee1-faaa-4535-b2c1-a35e4e93b13c.png)

For training of dataset.
![training1](https://user-images.githubusercontent.com/118749540/203089016-804e1759-e313-437d-9949-a5d62d2f6832.png)
![training2](https://user-images.githubusercontent.com/118749540/203089029-8049d197-d7c5-4118-96bb-49b4e0c6d74e.png)

Sorry if my english is bad.

**Comment by mhsmith** [comment]
If you're not familiar with Android programming, your easiest approach would be to keep it as a text-based app, using the [chaquopy-console](https://github.com/chaquo/chaquopy-console) example as a starting point. 

Unfortunately our Python OpenCV builds don't currently support accessing the camera, so you'd have to do that using one of the Android camera APIs. The simplest way is probably to use an Intent as shown [here](https://developer.android.com/training/camera/camera-intents).
