### ISSUE TITLE
time sleep and while loop not working for me

### ISSUE THREAD

**Issue by lamideag** [chaquo/chaquopy#759]
The problem is that when the user uses time sleep it will hang the time until the whole time expires and then print all the results at once
# my code python
``` python
import sys
from os.path import dirname, join
from java import jclass
import os
from io import StringIO
from os.path import join
from multiprocessing import Pool

def main(CodeAreaData):
    try:
            old_stdout = sys.stdout
            sys.stdout = mystdout = StringIO()
            exec(CodeAreaData) 

            sys.stdout = old_stdout
            output = mystdout.getvalue()
    except Exception as e:
        output = e

    return str(output)




```
# my code kotlin 
```kotlin
if (!Python.isStarted()) {
            Python.start(AndroidPlatform(this));
        }
val py = Python.getInstance()
val pyobj = py.getModule("myscript") //give python script name
val obj = pyobj.callAttr("main", editor.text.toString())

      



```

**Comment by mhsmith** [comment]
If your code takes a long time to run, you'll need to use a separate thread. I suggest you look at the [chaquopy-console](https://github.com/chaquo/chaquopy-console) example, which will deal with the threading details for you.

**Comment by lamideag** [comment]
use thread on file python or kotlin ?

**Comment by mhsmith** [comment]
You can create a thread using the standard threading APIs of either language, but I strongly recommend you look at the [chaquopy-console](https://github.com/chaquo/chaquopy-console) example first, if only for inspiration.
