### ISSUE TITLE
can not startActivity in chaqoupy

### ISSUE THREAD

**Issue by lamideag** [chaquo/chaquopy#762]
# my code python
```python
from java import jclass
activity =jclass("android.app.Activity")
Intent = jclass('android.content.Intent')
Uri = jclass('android.net.Uri')
intent = Intent()
intent.setAction(intent.ACTION_VIEW)
intent.setData(Uri.parse('http://kivy.org'))
activity.startAcivity(intent)
```
### return error
android.app.Activity.startActivity cannot be applied to (Intent): options are void android.app.Activity.startActivity(android.content.Intent), void android.app.Activity.startActivity(android.content.Intent, android.os.Bundle)

**Comment by mhsmith** [comment]
You're calling `startActivity` on the Activity *class*, but it's an instance method so it can only be called on an instance. You'll have to pass the instance over from Java or Kotlin. For example, if you called into Python from within an Activity class definition, then the instance will be `this`.
