### ISSUE TITLE
install airtest error,depend on opencv-contrib-python==4.5.1.48,depend on No module named 'skbuild'

### ISSUE THREAD

**Issue by BlackPigHe** [chaquo/chaquopy#767]
#### Chaquopy version

13

#### Relevant parts of your build.gradle file

defaultConfig {
        applicationId "com.chaquo.myapplication"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            buildPython "D:\\Program Files\\python3.8.10\\python.exe"
            buildPython "py", "-3.8"
            pip {
                version "3.8"
                options "--index-url", "https://pypi.tuna.tsinghua.edu.cn/simple", "--trusted-host", "pypi.tuna.tsinghua.edu.cn","-V"
                install "airtest==1.2.7"
            }
        }
    }

#### Describe your issue

无法正常加载opencv-contrib-python这个库，而我在本地直接使用pip是可以安装成功的
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-vj4encbz\opencv-contrib-python\setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'

详细的报错：
Collecting opencv-contrib-python==4.5.1.48
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/42/02/7b2fb0b81266aa3243dd8f392d48db1a206cc9a1856a14228e75c515616e/opencv-contrib-python-4.5.1.48.tar.gz (148.8MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Program Files\python3.8.10\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-z_wa3qhy\\opencv-contrib-python\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-z_wa3qhy\\opencv-contrib-python\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-z_wa3qhy\opencv-contrib-python\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-z_wa3qhy\opencv-contrib-python\setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    ----------------------------------------

**Comment by mhsmith** [comment]
The `--index-url` option removes all the default indexes, so if you want to use our Android OpenCV packages, you'll have to add back our index with the following line:
```
options "--extra-index-url", "https://chaquo.com/pypi-7.0/"
```
