### ISSUE TITLE
What is the best way to debug/tracing the Python code?

### ISSUE THREAD

**Issue by eldon97** [chaquo/chaquopy#768]
i'm always facing different result problem beetwen executing the code using windows machine and android device. the last time the issue occur because of difference of python library version that i use between those different machine. i wonder what is the best way to debug/tracing the Python code line by line to find where is the line that the root source of the issue is happening?

**Comment by mhsmith** [comment]
Unfortunately there's no easy way to attach a Python debugger to the app. But if you add some `print` lines to your code, you'll be able to see the output in the [Logcat](https://developer.android.com/studio/debug/am-logcat).

**Comment by mhsmith** [comment]
Update: there are some instructions in the [`debugger` directory](https://github.com/chaquo/chaquopy/tree/master/debugger) which may be useful, but they're several years old so I don't know whether they still work. If anyone tries them, please let me know how you get on.
