### ISSUE TITLE
Does chaquopy support installation of Image AI library?

### ISSUE THREAD

**Issue by acbz0805** [chaquo/chaquopy#77]
Hi, I am wondering is chaquopy supports installation of imageAI library?

**Comment by mhsmith** [comment]
Chaquopy supports all the dependencies listed in the [ImageAI README](https://github.com/OlafenwaMoses/ImageAI). You should just be able to add an [`install` line](https://chaquo.com/chaquopy/doc/current/android.html#requirements) for each of those dependencies, plus one for the ImageAI whl URL given there.

Reopen this issue if you have any problems.
