### ISSUE TITLE
Do I need to read images in the assets folder, everytime Chaquopy called?

### ISSUE THREAD

**Issue by saka3324** [chaquo/chaquopy#770]
I want to process images using OpenCV in Python code.
So I used chaquopy on Androidstudio.
It works fine, but performance is subtle.
I assume everytime chaquopy is called, the assets folder is opened and images are loaded.
Is this correct?
I want load and hold images the first time , something like "if img is None: img = cv2.imread()".
Is this possible?

Thank you.

**Comment by saka3324** [comment]
Sorry for bothering you with my poor English.
I'm new for java/kotlin, so this might be missing the point.
I want to somethig like this.

"""
// kotlin 

"""

**Comment by saka3324** [comment]
Sorry for bothering you with my poor English.
I'm new for java/kotlin, so this might be missing the point.
I want to somethig like this.
```
// kotlin
if (!Python.isStarted()) {
            Python.start(AndroidPlatform(requireContext()))
        }
val py = Python.getInstance()
val module = py1.getModule("pymodule") # I want to call "class pyclass↓" and make instance here

#loop----
while true:
    val result = module.callAttr( "function 1", ...)
-----------


// pymodule
class pyclass
  def __init__():
    img = cv2.imread()  # read image only when instance created

  def function1:
```

If doing like this, "img(Python)" is still alive when "module" is called, right?

Thank you.

**Comment by mhsmith** [comment]
I still don't really understand what you're asking. But here's how to create an instance of `pyclass` from Kotlin:
```
val pyc = module.callAttr("pyclass")
```
The class's `__init__` method will be run each time you do this.

And here's how to call a method on that instance:
```
pyc.callAttr("function1", "Hello")
```
So when and how `imread` is called is entirely up to you.
