### ISSUE TITLE
Must the scrip be run using asynchtask?

### ISSUE THREAD

**Issue by brahimaboutaleb** [chaquo/chaquopy#774]
#### Chaquopy version
. 13.0.0

#### Devices or emulators where the issue happens
 on device

#### Describe your issue

Must the scrip be run using asynchtask?
The script runs normal , but i noticed how it is a bit slow when i first start the app , and if i happen to be touching the screen while it is running the script , the app crashes and gives " Input dispatch ing timed out....server is not responding. Waited 5000ms for FocusEvent(hasfocus =true))"

To my understanding when i interact with the UI it sort of makes the scrip run out of memory to do its work.
If i don t click on the Ui the scrip runs normal and i have no issues.
How can i solve this in your opinion ?

Ps: I am new to programming , still learning

**Comment by mhsmith** [comment]
The app's main thread (the one where the system runs `onCreate`, `onStart`, etc) must be kept free in order for the UI to be responsive. So if you're running Python code that takes a long time, you should do that on a separate thread, which you can create either in Python or in Java.
