### ISSUE TITLE
Any way to do the same process in parallel in one python module.

### ISSUE THREAD

**Issue by takyq** [chaquo/chaquopy#782]
I want to parallelize processes written in python modules with an java executor service.

When I call the same py module from another java worker thread while the module is running, it does not return anything.

py = Python.getInstance()
module = py.getModule("pymodule")

If I want to run multiple python codes simultaneously, do I need to have the same number of "py"?

Thank you.

**Comment by Ojas1024** [comment]
Use threading in Android processes?

Doesn't that work?

**Comment by takyq** [comment]
I don't think so.
I want to do something like this.

```
lateinit : pyExecutor , module

if (!Python.isStarted()) {
            Python.start(AndroidPlatform(requireContext()))
        }
val py = Python.getInstance()
module = py.getModule("pymodule")

pyExecutor = Executors.newFixedThreadPool(5)
...
...
...
loop

pyExecutor.execute{
  val pyresult = module.callAttr( "Entry_point", img ).asList()
}
...
...
...
```

Processes within the loop does not overflow from the thread pool.
When the second call is performed, the first call is still in the middle of the process, so there is no completion of the first call same after that.
Does that mean that the first and second call is in the same py module?

**Comment by takyq** [comment]
I confirmed that get instance and getmodule are working in multiple threads if I try to do them in a loop, but the response seems to be very slow.

When two calls are made at the same time, the processing time, which was originally about 100 ms, is stretched out to about 4 seconds.

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information and I'll reopen the issue.
