### ISSUE TITLE
Failed to install openai

### ISSUE THREAD

**Issue by rafie-mehdi** [chaquo/chaquopy#783]
i use "python {
            pip{
                install "openai"

            }}" to install openai library but i get always this error
 Using cached https://files.pythonhosted.org/packages/37/37/eea5ae693a9f95c554ba7665e96a105425d6823782105f2317cb8a2bb8be/openai-0.26.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mehra\AppData\Local\Programs\Python\Python310\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mehra\\AppData\\Local\\Temp\\pip-install-s6bt817y\\openai\\setup.py'"'"'; __file__='"'"'C:\\Users\\mehra\\AppData\\Local\\Temp\\pip-install-s6bt817y\\openai\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: C:\Users\mehra\AppData\Local\Temp\pip-install-s6bt817y\openai\
    Complete output (39 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mehra\AppData\Local\Temp\pip-install-s6bt817y\openai\setup.py", line 3, in <module>
        setup()

**Comment by mhsmith** [comment]
This is an instance of #715, which was fixed in Chaquopy 14.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python`.
