### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by botbahlul** [chaquo/chaquopy#784]
My app crashed on EMULATOR Pixel 2 API 25 and on REAL DEVICE Android Q API 29 when applying textview.append() or textview.setText() methode from python script but running well on EMULATOR Nexus 5X API 29

Here's my code from android java part

                    if (!canceled && mediaURI != null && sourceCopy != null) {
                        PyObject pyObjsrtFileTranslated = py.getModule("autosrt").callAttr("transcribe", src, dst, sourceCopy, textview_debug);
                        if (pyObjsrtFileTranslated != null) {
                            srtFileTranslated = pyObjsrtFileTranslated.toString();
                        }
                    }

and here's the code from python script that I called :

def transcribe(src, dest, filename, textView_debug):
    textView_debug.setText("Running python script...")

So the problem is every time I call textview.setText() or textview.append() from pyhton, the logcat shows that warning message AND MOST OF THE TIME WILL LEAD TO CRASHED especially if I use setText() or append() over and over

For now to avoid crashes, I must split python codes in smaller functions but still crashed occasionally

Is there any better way to call setText() or append() from python without having this issue? Something like 

                        runOnUiThread(new Runnable() {
                                          @Override
                                          public void run() {

                                          }
                                      });

I've tried using this :

class R(dynamic_proxy(Runnable)):
        def run(self):
            textView_debug.setText("Copy created at :\n " + filename + "\n")
activity.runOnUiThread(R())

but it didn't work
It said :
com.chaquo.python.PyException: NotImplementedError: com.chaquo.python.PyProxy._chaquopyGetDict is abstract and cannot be called

I need to call setText() or append() to show the running progress of python script in REAL TIME

I've also tried using Threads from android java part to monitor the progress of python script but it didn't work too

Here's my complete codes from my repo : 
https://github.com/botbahlul/android-autosrt

TIA

**Comment by botbahlul** [comment]
Here's my complete codes from my repo : 
https://github.com/botbahlul/autosrt

**Comment by botbahlul** [comment]
Never mind..
It seems that the problem occurred if setText()/append() being called to fast
Adding time.sleep(1) before setText()/append() solved the issue

**Comment by mhsmith** [comment]
> com.chaquo.python.PyException: NotImplementedError: com.chaquo.python.PyProxy._chaquopyGetDict is abstract and cannot be called

This approach should work without any need to call `time.sleep`, so this may indicate a bug in Chaquopy. Can you post the full stack trace of this error, please?

**Comment by mhsmith** [comment]
Continued in #788.
