### ISSUE TITLE
Fastest way to convert Jarray to Numpy array.

### ISSUE THREAD

**Issue by saka3324** [chaquo/chaquopy#785]
I would like to pass the results of inference done in Adroid to the Chaquopy module in Jarray format.
The size of jarray is [1,36,8400] and [1,36,640,640].
This is the method I am currently taking.

```
#In Java code
 val postprocess = pymodule.callAttr(
                    "nms",
                    jarray1,
                    jarray2)

#In Python code
 
j1 = np.array(jarray1)
j2 = np.array(jarray2)

torch_j1 = torch.from_numpy(j1.astype(np.float32))
```

I spent the most time on this data conversion in the python module.
When the python module receives the jarray, does it directly refer to the original location?

Any good ways to speed up the conversion?
Thank you.

**Comment by mhsmith** [comment]
> When the python module receives the jarray, does it directly refer to the original location?

Yes. 

But when you convert it to a numpy array, a copy will be made. This should be very fast for 1-dimensional arrays. But multi-dimensional Java arrays are actually many different objects, e.g. if you run `new int[1][36][640][640]`, then you actually have 23,040 arrays of `int[640]`, each of which must be copied separately.

So if possible, it would be more efficient to pass the data to Python in a 1-dimensional Java array, and then reshape it after converting to a NumPy array.
