### ISSUE TITLE
Defective OpenSSL Version Error by Google Play Dashboard on x86_64 libssl_chaquopy.so

### ISSUE THREAD

**Issue by gubatron** [chaquo/chaquopy#789]
<img width="888" alt="Screenshot 2023-01-31 at 10 43 21 AM" src="https://user-images.githubusercontent.com/163977/215840844-9a613a95-d138-44f0-965b-996fdc58fdd7.png">

**Comment by mhsmith** [comment]
See #727, and please search for existing issues before creating new ones.

**Comment by gubatron** [comment]
For anyone reading this, the solution is:

>This issue was fixed in Chaquopy 14.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of com.chaquo.python.
