### ISSUE TITLE
how to build py file to so file

### ISSUE THREAD

**Issue by lex-geeker** [chaquo/chaquopy#810]
I want to package the py file into a. so file. I have checked the question many times, but I still don't know how to operate it
server/ypi is already installed
The folder "pypi/packages/test/" is created. There are "setup.py" and "a.py" in the directory
I want to compile "a.py" into ".so" file. How to operate arm64-v8a type? Is use meta.xml? Thanks

**Comment by mhsmith** [comment]
Follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi), and base your recipe on the [cython-example](https://github.com/chaquo/chaquopy/tree/master/server/pypi/packages/cython-example).

**Comment by lex-geeker** [comment]
Thanks for taking care of that
