### ISSUE TITLE
cannot pip install Octave / oct2py

### ISSUE THREAD

**Issue by MomoSolaris8** [chaquo/chaquopy#818]
**Ｈello，First of all, thank you for your creation！**

I want to do an image transformation in chaquopy (https://en.wikipedia.org/wiki/B-spline). But I can't install octave in pip, how can I fix it?

My operating system is ubuntu
python version is the default python 3.8
**I need to pass an image to python code via java to do image processing. In this image processing I need to import ocatve (oct2py)**

plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.example.demo15'
    compileSdk 33

    defaultConfig {

        applicationId "com.example.demo15"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {
            version "3.8"
            pip {
                install "dlib"
                install "opencv-contrib-python-headless"
                install "pillow"
                install "numpy"
                install "pywavelets"
                install "python-math"
                install "scipy"
                install "opencv-python"
                **install  "octave"**

            }

        }

plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
    id 'com.chaquo.python' version '13.0.0' apply false
}
![Bildschirmfoto vom 2023-03-02 11-23-21](https://user-images.githubusercontent.com/13085793/222401628-0604c0db-7b00-4e4d-92e1-82f3feee1a51.png)

**Comment by mhsmith** [comment]
The recommended package for calling Octave from Python appears to be called `oct2py`, not `octave`. `oct2py` can be installed successfully, but it currently fails to import because of #820. 

We'll fix #820 in the next version of Chaquopy. However, it looks like Octave is a compiled component, so it will still have to be built separately. And if it depends on calling an executable, as [this](https://github.com/Calysto/octave_kernel) implies, then it will also be blocked by #605.

**Comment by MomoSolaris8** [comment]
Thanks for your quick answer

**Comment by mhsmith** [comment]
It's been over a year, and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
