### ISSUE TITLE
Python.getInstance().getModule("youtube_dl.bootstrap")  Unable to create object after running

### ISSUE THREAD

**Issue by webyouling** [chaquo/chaquopy#82]
module = Python.getInstance().getModule("youtube_dl.bootstrap") Unable to create object after running

phone：SHARP AQUOS Xx
system version ：5.0.2

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.chaquo.python.PyObject com.chaquo.python.PyObject.callAttr(java.lang.String, java.lang.Object[])' on a null object reference

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information.
