### ISSUE TITLE
There are a lot of Python dependency and it makes my app bundle size up to more than 150MB which is the size limit of app bundle in play store

### ISSUE THREAD

**Issue by eldon97** [chaquo/chaquopy#829]
#### Chaquopy version

14.0.2

#### Relevant parts of your build.gradle file
                install "numpy"
                install "opencv-python"
                install "scipy"
                install "scikit-image"
                install "imutils"
                install "backcall==0.2.0"
                install "certifi==2022.12.7"
                install "charset-normalizer==2.1.1"
                install "colorama==0.4.6"
                install "cycler==0.11.0"
                install "decorator==5.1.1"
                install "fonttools==4.38.0"
                install "gitdb==4.0.10"
                install "GitPython==3.1.29"
                install "idna==3.4"
                install "ipython==7.34.0"
                install "jedi==0.18.2"
                install "joblib==1.2.0"
                install "matplotlib"
                install "matplotlib-inline"
                install "packaging==22.0"
                install "pandas"
                install "parso==0.8.3"
                install "pickleshare==0.7.5"
                install "Pillow"
                install "prompt-toolkit==3.0.36"
                install "psutil"
                install "Pygments==2.13.0"
                install "pyparsing==3.0.9"
                install "python-dateutil==2.8.2"
                install "pytz==2022.6"
                install "PyYAML"
                install "requests==2.28.1"
                install "scikit-learn"
                install "seaborn==0.12.1"
                install "six==1.16.0"
                install "smmap==5.0.0"
                install "threadpoolctl==3.1.0"
                install "torch"
                install "torchvision"
                install "tqdm==4.64.1"
                install "traitlets==5.7.0"
                install "typing_extensions==4.4.0"
                install "urllib3==1.26.13"
                install "wcwidth==0.2.5"
                install "tflite-runtime"

#### Describe your issue

I use abi filters only x86 and my app size is over than 150mb which is 180mb precisely. i check it's because there are a lot of python dependencies that i use, if i remove all of them my app size is around 40mb which is the python dependencies take 140mb. are there some way to reduce it or split the python dependencies using asset delivery, feature delivery, or something else?

**Comment by mhsmith** [comment]
We don't currently support Google Play's asset delivery or anything similar, so you'll somehow have to make the APK smaller. Here are some ideas:
* I can confirm that these requirements add up to 140 MB, but 40 MB for the rest of the app seems quite large. Chaquopy itself shouldn't be responsible for more than 10 MB of that. Are there any non-Python components you could remove?
* I don't think Google Play would accept an x86-only app, because they now require all apps to support 64-bit. Could you switch to arm64-v8a instead? That reduces the requirements size to 135 MB in my tests.
* Otherwise, you'll have to actually remove some requirements. To see which ones are taking the most space, build your app and then look in the `build/pip` directory.

**Comment by mhsmith** [comment]
I haven't used asset delivery, so I don't know how difficult it is to use. After installing the asset, you'd probably still have to extract the model to a file on the device before your Python code can load it. So downloading it from your own server might be simpler, if you already have a server available.

**Comment by eldon97** [comment]
> I haven't used asset delivery, so I don't know how difficult it is to use. After installing the asset, you'd probably still have to extract the model to a file on the device before your Python code can load it. So downloading it from your own server might be simpler, if you already have a server available.

okay thanks, i think i will use that approach
