### ISSUE TITLE
Loading python scripts from android device storage

### ISSUE THREAD

**Issue by pramodgobburi3** [chaquo/chaquopy#830]
Hello,

I'm trying to build an application that will download python scripts from a remote server and saves them to the device storage and then execute the scripts. Is this possible with chaquopy?

Thanks

**Comment by mhsmith** [comment]
Yes: you should store them in a directory under [`os.environ["HOME"]`](https://chaquo.com/chaquopy/doc/current/android.html#android-os), and then add that directory to sys.path so you can import them.
