### ISSUE TITLE
Failed to install pycryptodomex==3.17 

### ISSUE THREAD

**Issue by enakhi** [chaquo/chaquopy#845]
#### Chaquopy version
14.0.2

#### Relevant parts of your build.gradle file
        python {
            version "3.8"
            pip {
                install "matplotlib"
                install "instagrapi"
            }
        }

#### Describe your issue
It failed to complete the build.
I got this error :
Failed to install pycryptodomex==3.17 from https://files.pythonhosted.org/packages/3d/07/cfd8f52b9068877801317d26dc7225e19421bc659e1395d2cd6933b1a351/pycryptodomex-3.17.tar.gz#sha256=0af93aad8d62e810247beedef0261c148790c52f3cd33643791cc6396dd217c1 (from instagrapi).

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/807#issuecomment-1416727724.
