### ISSUE TITLE
Failed to install tokenizers!=0.11.3,<0.14,>=0.11.1

### ISSUE THREAD

**Issue by pro3k** [chaquo/chaquopy#848]
#### Describe your issue

In Android Studio 7.4 

ERROR: Failed to install tokenizers!=0.11.3,<0.14,>=0.11.1 from https://files.pythonhosted.org/packages/29/9c/936ebad6dd963616189d6362f4c2c03a0314cf2a221ba15e48dd714d29cf/tokenizers-0.13.3.tar.gz#sha256=2e546dbb68b623008a5442353137fbb0123d311a6d7ba52f2667c8862a75af2e (from transformers).

I think This error ` error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib` failed with code 101` got because of tokenizers.

**Comment by mhsmith** [comment]
See #607, and in future please search the existing issues before creating new ones.
