### ISSUE TITLE
Support for PyNaCl?

### ISSUE THREAD

**Issue by atoms118** [chaquo/chaquopy#85]
Requires native code to be compiled

**Comment by mhsmith** [comment]
We'll have a look and get back to you.

**Comment by atoms118** [comment]
This issue may be of some help: https://github.com/pyca/pynacl/issues/510

**Comment by mhsmith** [comment]
PyNaCl 1.3.0 is now available.

**Comment by atoms118** [comment]
Thank you so much!

**Comment by atoms118** [comment]
Hm, I am still getting this error while building:
```
ERROR: Chaquopy: can't happen: requirement pycparser from https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (from cffi>=1.4.1->PyNaCl) is still not a wheel.
```

**Comment by atoms118** [comment]
Nevermind, so sorry, it was just an issue on my end. Thanks again for the incredible support!
