### ISSUE TITLE
How to know when function in python done?

### ISSUE THREAD

**Issue by MinHieu2006** [chaquo/chaquopy#850]
I use the lastest version of chaquopy (14.0).
In my java file , I call
```
 py = Python.getInstance();
 pyboj = py.getModule("chatgpt");
 obj = pyboj.callAttr("main",message);
```
In my python file ,  I use:
```

def main(message) -> str:
    prompt_list: list[str] = ['Bạn nói tiếng việt và chỉ trả lời bằng tiếng việt']

    user_input: str = message
    response: str = get_bot_response(user_input, prompt_list)
    respense = fixed(response)
    return (fixed(f' {response}'))
```
I find out that chaquopy is multi-threading. So I don't know when main() function done?

Is there any solution to this? Thank you!

**Comment by mhsmith** [comment]
Chaquopy *supports* multi-threading, but it won't create any threads by itself. The `callAttr` method will block until the `main` function is done.

**Comment by mintheinwin** [comment]
Hi MinHieu how you get this solution. Can share your idea? I

**Comment by mhsmith** [comment]
The simplest solution is:
* Create a background Java thread
* Call the Python function on the background thread
* When it returns, notify the UI thread using [`Handler.post`](https://developer.android.com/reference/android/os/Handler#post(java.lang.Runnable)) or [`MutableLiveData.postValue`](https://developer.android.com/reference/androidx/lifecycle/MutableLiveData#postValue(T)).
