### ISSUE TITLE
torch.jit.load raises RuntimeError: [enforce fail at inline_container.cc:222] . file not found

### ISSUE THREAD

**Issue by pro3k** [chaquo/chaquopy#852]
#### Chaquopy version
com.chaquo.python:gradle:14.0.2

#### Android Gradle plugin version
com.android.tools.build:gradle:7.4.0
and Gradle Version --> 7.5

#### Relevant parts of code
model = torch.jit.load(homeopath + "torch_lite_model.ptl") 

#### Issue
I want to read the "torch_lite_model.ptl" file but got an error:
com.chaquo.python.PyException: RuntimeError: [enforce fail at inline_container.cc:222] . file not found: torch_lite_model/version

I run the project on Python version 3.11 and it executed fine but when I tried to run the project module on android studio got this error. 
Android Studio uses the Chaquopy library which uses Python version 3.8. What to do to use Chaquopy Python version 3.11?

**Comment by mhsmith** [comment]
Chaquopy currently only supports PyTorch on Python 3.8. Your actual issue is probably with the path you're passing to `load`. Try using a path relative to `__file__`, as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

**Comment by pro3k** [comment]
I tried in this way: 

# Get the directory of the current script
current_dir = os.path.dirname(os.path.abspath(__file__))

# Define the relative path to the torch lite model file
torch_lite_model_path = os.path.join(current_dir, "torch_lite_model.ptl")

# Load the torch lite model using the relative path
torch_lite_model = torch.jit.load(torch_lite_model_path, map_location=torch.device('cpu'))

# Load the TorchScript model
model = torch.jit.load(torch_lite_model_path)

but got the same as the previous one.

**Comment by pro3k** [comment]
I tried in this way:

Get the directory of the current script
current_dir = os.path.dirname(os.path.abspath(file))

Define the relative path to the torch lite model file
torch_lite_model_path = os.path.join(current_dir, "torch_lite_model.ptl")

Load the torch lite model using the relative path
torch_lite_model = torch.jit.load(torch_lite_model_path, map_location=torch.device('cpu'))

Load the TorchScript model
model = torch.jit.load(torch_lite_model_path)

but got the same as the previous one.

**Comment by pro3k** [comment]
I have found the solution. The (.ptl) files I have is developed in different versions from Chaquopy's Torch version. I developed that file according to the Torch version of Chaquopy and the error was solved.

Torch version that I used before is `1.13.1`

Chaquopy's preferred Torch version is `1.4.1` and `1.8.1`
