### ISSUE TITLE
Update Packages 

### ISSUE THREAD

**Issue by Kira-Kitsune** [chaquo/chaquopy#853]
I was wondering if possible to update the following packages to these versions (or add that version), I need these version for my project and they aren't downloading from pythonhosted.org probably.

| Package | Version | 
|---------|---------|
| scipy   | 1.10.1  | 
| numpy   | 1.23.5  | 
| pandas  | 2.0.0   |

**Comment by mhsmith** [comment]
If you look under https://chaquo.com/pypi-7.0/, you'll see that we have newer versions of NumPy and Pandas for Python 3.9 and 3.10. You can use them by changing the [Python version of your app](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

However, these versions are not quite as new as the ones you asked for. If this is a problem for you, please explain why.

Unfortunately we don't have SciPy for Python 3.9 and 3.10, for the reason given in #648.
