### ISSUE TITLE
Chaquopy problem with brew for macos

### ISSUE THREAD

**Issue by kareematif186** [chaquo/chaquopy#856]
@mhsmith 
The issue was discussed before but it does not work for me , I use Chaquopy with macos with brew python 

#### Chaquopy version

--------------------------------------------------------------------------
using   chaquopy: ^0.0.19

#### Relevant parts of your build.gradle file
--------------------------------------------------------------------------
Thats my gradle : 
apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.2.2"
        classpath "com.chaquo.python:gradle:14.0.2"
    }
}
//
//plugins {
//    id 'com.android.application'
//    id 'com.chaquo.python'
//}

android {
    compileSdkVersion 33

    defaultConfig {

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

        python {
           buildPython "/opt/homebrew/opt/python@3.8/bin/python3.8"
            //version "3.10.9"

            //  buildPython "/opt/homebrew/Caskroom/miniforge/base/bin/python"

            //"C:\\Users\\salma\\AppData\\Local\\Programs\\Python\\Python38\\python.exe"
            //buildPython "C:\\Users\\kareem\\AppData\\Local\\Programs\\Python\\Python38\\python.exe", "-3.8"
            pip {
                //install "scripts"
                //install "scipy"
                install "numpy"
                install "keras.models"
                install "pyaxmlparser"
                install "androguard"
                //install "pyrebase"
                //  specify any other package to install.
            }

            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "com.application.app"     // whatever the name
            minSdkVersion 21
            targetSdkVersion 32
            multiDexEnabled true
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
        }

        aaptOptions {
            noCompress 'tflite'
            noCompress 'lite'
        }

    }

    flutter {
        source '../..'
    }

}
--------------------------------------------------------------------------

#### Describe your issue
----------------------------------
error I got :

![Screenshot 2023-04-15 at 5 24 41 AM](https://user-images.githubusercontent.com/88941146/232180695-a856c912-bba4-43d6-b993-f34b11704d7f.png)

**Comment by mhsmith** [comment]
This error was previously discussed in #405, which should have been fixed in Chaquopy 9.1.0. 

You've closed the issue, so did you manage to solve the problem? If so, how?

**Comment by kareematif186** [comment]
I was using buildscript in the Gradle for the app level so changing the version was not working, I noticed it and changed it for the Gradle in the project level and it works!
