### ISSUE TITLE
How to write a file inside python function?

### ISSUE THREAD

**Issue by wyh5625** [chaquo/chaquopy#86]
How can I write a file in python's function? I have tried directly open a new file for writing in python method, but the new file doesn't exist after android call python's method. It's said that python package is not a seperate file, it's loaded from apk asset in runtime. So the file operation doesn't work. I tried to set "extractPackages" in gradle which can read the resource of device, but it can't write or save any data to the device. Is there any method to write a file and save it inside python methods?

**Comment by mhsmith** [comment]
In which directory are you attempting to write the file? The recommended location would be the app's files directory, which you can find using `os.environ["HOME"]`.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and give more details.
