### ISSUE TITLE
pip install too big app

### ISSUE THREAD

**Issue by jvallsgm** [chaquo/chaquopy#865]
Hi, 

I'm using some little parts of packages (as numpy, scipy, pandas...). The app builded is too big. I read "How can I make my app smaller?" but the problem is that I need a little functions of this some packages. Then I cannot remove them from pip. 

Is there a way to use certain parts of packages (from X import Y), without having to install the whole package (and the packages dependent on it)?

Thanks!

**Comment by mhsmith** [comment]
If you want to know what's taking up the space, you can look under your app's build/pip directory. However, we don't currently have any way to remove specific folders from the build, and modifying that directory will simply cause pip to run again. So I don't have any suggestions beyond what's in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size).

**Comment by jvallsgm** [comment]
Ok thanks!
