### ISSUE TITLE
socket module does not have if_nametoindex method

### ISSUE THREAD

**Issue by Kotlinlife** [chaquo/chaquopy#870]
#### Devices or emulators where the issue happens
Any device

#### Relevant parts of your code
import socket
socket.if_nametoindex()

#### Describe your issue
The contained exception was: module 'socket' has no attribute 'if_nametoindex'

**Comment by mhsmith** [comment]
The NDK's include/net/if.h indicates that the underlying libc function isn't available until API level 24:
```c
if __ANDROID_API__ >= 24
struct if_nameindex* if_nameindex(void) __INTRODUCED_IN(24);
void if_freenameindex(struct if_nameindex* __ptr) __INTRODUCED_IN(24);
#endif /* __ANDROID_API__ >= 24 */
```

Since we currently compile Python against API level 21, the `socket.if_...` functions won't be available. I'll add this to the documentation.

What do you need this function for?

**Comment by Kotlinlife** [comment]
@mhsmith  Thanks for answer. I need this functions to wrap some python protocol library(reticulum) in kotlin. How can I fix it?

**Comment by mhsmith** [comment]
That depends on how the library uses the function. You might be able to get away with a minimal implementation like this:

```python
import socket

def if_nametoindex(if_name):
    raise OSError("not implemented")

socket.if_nametoIndex = if_nametoindex
```

Or if the library needs the function to return real information, perhaps you could implement it using ctypes to call the underlying libc function.

**Comment by mhsmith** [comment]
Adding to the next milestone because it's better for these functions to return OSError as documented, rather than NameError, which user code is unlikely to catch.

**Comment by Kotlinlife** [comment]
Thanks a lot!
