### ISSUE TITLE
web3 and bitarray

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#871]
_Originally posted by @Lokuslick in https://github.com/chaquo/chaquopy/issues/868#issuecomment-1538377289_

Hey @mhsmith Thanks for the help. But another issue popped out. 
When I ran the app it is getting the python file from my py module as expected.
I am using web3 package which has to be installed in the py module in the above repository (Have updated the above repo code). When I try to use the below block of installing a package I am getting the compilation error attached below.

**build.gradle**
```
python {
            pip {
                install "web3"
            }
        }
```
**Compilation error**
> Failed to install bitarray<3,>=2.4.0 from https://files.pythonhosted.org/packages/82/30/68a3ee41e6abbb521a3418fb25a7755127a1d6bf4604028bb404f833b2fc/bitarray-2.7.3.tar.gz#sha256=f71256a32609b036adad932e1228b66a6b4e2cae6be397e588ddc0babd9a78b9 (from eth-account>=0.8.0->web3).

![image](https://user-images.githubusercontent.com/33567165/236838538-fc19b2dc-d138-4e0b-986c-358b33af5fd4.png)

**Comment by mhsmith** [comment]
Chaquopy does support bitarray, but our current version is too old for this requirement.

If you'd like to try building a newer version yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). This package required no patches, so the update should not be too difficult. And if you're successful, please make a pull request so we can add the new version to the public repository.

If anyone else needs a new version of this package, please click the thumbs up button above, and post a comment explaining why you need it.

**Comment by mhsmith** [comment]
Alternatively, you may be able to work around this by using older versions of web3 and eth-account which are compatible with our current bitarray version . The following combination should be valid:
```
                install "web3==5.28.0"
                install "eth-account==0.5.7"
```

But when I tried to build this, I got several warnings about conflicting requirements from other eth-... packages. There's probably a solution to this, but unfortunately Chaquopy's current version of pip doesn't have the new resolver, so it can't solve it automatically.

**Comment by B3nac** [comment]
Hey @mhsmith I can give building a new version the ole college try! My project https://github.com/TheLootBox-xyz/TheLootBoxWallet requires the newer version while building for Android so without it I can only build for desktop with briefcase. 

```bash
ERROR: Failed to install bitarray>=2.4.0 from https://files.pythonhosted.org/packages/2d/08/e6b51b0456becc0db01e969d6e1c4542094bde0a7bbb197834f94b18332a/bitarray-2.7.6.tar.gz#sha256=3807f9323c308bc3f9b58cbe5d04dc28f34ac32d852999334da96b42f64b5356 (from eth-account>=0.8.0->web3->-r requirements.txt (line 3)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
```
I just completed refactoring so I could use briefcase for desktop builds so I'll be reviewing the Chaquopy package building instructions soon-ish.
