### ISSUE TITLE
Support for install Zbar

### ISSUE THREAD

**Issue by hhhai0304** [chaquo/chaquopy#88]
I'm using Pyzbar 0.1.7.

Pyzbar is a python wrapper of Zbar shared library and Zbar itself comes with python by default in Windows but other OS is not... I need Zbar to use Pyzbar...

I try to install Zbar using Chaquopy but failed.
Wondering if would be possible to get support for installing Zbar library?

Thank you so much!

**Comment by mhsmith** [comment]
Thanks for the request. It's not a priority at the moment, but we would probably be willing to add it in return for a small payment: please [email us](https://chaquo.com/chaquopy/contact/) if you're interested in this.

If anyone else wants this package too, please subscribe to this issue and add a thumbs up.

**Comment by mhsmith** [comment]
Let's leave it open in case other people have the same question.

**Comment by sarthaksharma058439** [comment]
Hey i found this video it helps me alot in install and import package in android studio with chaquopy , hopefully this will helps you 

https://youtu.be/BDmB3EFy0Qg

**Comment by mhsmith** [comment]
pyzbar is now available for Chaquopy.
