### ISSUE TITLE
Weird Bug In Chaquopy Realted To Saving Video Using CV2 In Android With Chaquopy

### ISSUE THREAD

**Issue by Ansh24816** [chaquo/chaquopy#883]
def create_video(processed_frames, output_path, fps):
    print("STARTING create_video ")
    width, height = processed_frames[0].size
    fourcc = cv2.VideoWriter_fourcc(*'mp4v') 
    os.chdir(os.environ['HOME'])
    output_Path = os.getcwd()
    output_path =  os.path.join(os.environ['HOME'], "abc.mp4")
    out = cv2.VideoWriter(output_Path, fourcc, fps, (width, height))
    for frame in processed_frames:
        rgb_frame = cv2.cvtColor(np.array(frame), cv2.COLOR_RGB2BGR)
        out.write(rgb_frame)
    print("DONE create_video ")
    out.release()
    
in this sample code , it executes successfully , but there is no output video in the target section when running in android  , where same code works perfectly in Python idle like Pycharm ,

**Comment by Ansh24816** [comment]
![pythonProject](https://github.com/chaquo/chaquopy/assets/106660200/fd14b4f1-5128-4109-a09f-275af4304a59)


this is the original method which works perfectly fine in python idle like PyCharm.

**Comment by Ansh24816** [comment]
Any Helpful Suggestions will be appreciated Sir.

**Comment by mhsmith** [comment]
Sorry, Chaquopy's OpenCV builds do not currently support reading or writing video files. Please subscribe to #140 for any updates on this.
