### ISSUE TITLE
The library ddddocr cannot be compiled

### ISSUE THREAD

**Issue by 5tiaowu** [chaquo/chaquopy#888]
https://pypi.org/project/ddddocr/
The ddddocr library cannot be compiled, please support
![image](https://github.com/chaquo/chaquopy/assets/108533707/d64b2eb7-d39c-4216-99c9-46c6da02c8c7)

**Comment by mhsmith** [comment]
See #216, and please search for existing issues before creating new ones.

**Comment by 5tiaowu** [comment]
How exactly do I compile it myself, that is, do I need to compile this model to my phone?

**Comment by mhsmith** [comment]
Sorry, I don't know anything about this except what's in #216.
