### ISSUE TITLE
Is there any plan to implement pyts

### ISSUE THREAD

**Issue by jklee157** [chaquo/chaquopy#891]
Hello I'm struggling on  grampian angular field for CNN, but I cant find GAF on Android.
hopefully, pyts could be seen in this library.

Thank you.

**Comment by mhsmith** [comment]
`pyts` is a pure-Python package, but the current version requires `scipy>=1.8.1`, which we don't yet support (#648). Instead, try using the previous version, `pyts==0.12.0`.
