### ISSUE TITLE
Lower minimum API level to 14

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#897]
It would be really nice if the minimum API level for Chaquopy could match that of AndroidX (14). According to this [chart](https://chaquo.com/chaquopy/doc/current/versions.html), support for the older SDKs was only recently dropped. What is the reason for this? Is it not feasible to support these old Android versions because of technical reasons or was support simply dropped because of the small userbase?

**Comment by mhsmith** [comment]
The main reason is that before API level 21, Android was missing several functions from its C library, which made it significantly more difficult to build Python, OpenSSL, and many Python packages.

Google publishes [this data](https://dl.google.com/android/studio/metadata/distributions.json) showing the Android versions of devices which connect to Google Play. As you can see, devices older than API level 21 make up less than 2% of the total, so I don't think this limit will significantly harm the usefulness of your app.

If you really need to support older Android versions, you can always use an older version of Chaquopy.

**Comment by IsakTheHacker** [comment]
Okay I understand, that sounds reasonable. But using an older version of Chaquopy is probably not the best thing to do either as it is constantly getting improved. Also if I am going to use the newest version of Chaquopy that supports API level 15, won't I miss out on the new packages added to https://chaquo.com/pypi-13.1/ or would it be possible to backport new packages such as miniaudio to old Chaquopy versions?

One more question, why did you choose minimum API level 15 when you started this project? It just seems like an odd version to me. I think the minimum for both Google Play and AndroidX is 14 now, so why 15?

Finally, what is the lowest version that could ever be supported by Chaquopy (in a fork ofcourse) based on the limits of the Android system? I have some old devices at home running Froyo (API level 8) that I think could have good use of my app

**Comment by mhsmith** [comment]
> would it be possible to backport new packages such as miniaudio to old Chaquopy versions?

64-bit packages should already be compatible with older Chaquopy versions, because our minimum API level for 64-bit ABIs was always 21. 

To use 32-bit packages with Chaquopy versions older than 13.0, you can try building them against API level 16 by passing the `--api-level` argument to build-wheel.

> why did you choose minimum API level 15 when you started this project?

I don't remember why it was originally 15, but soon afterwards we increased it to 16 because we moved to a newer version of the Android NDK for which that was the minimum version.

> what is the lowest version that could ever be supported by Chaquopy (in a fork ofcourse) based on the limits of the Android system? I have some old devices at home running Froyo (API level 8) that I think could have good use of my app

I've never tried anything older than 15, but I think you would find older versions progressively more difficult.

**Comment by mhsmith** [comment]
For further discussion of the minimum API level, see https://github.com/chaquo/chaquopy/pull/1375#issuecomment-3591607766.
