### ISSUE TITLE
Can't build Maven or Server/PyPi from Docker

### ISSUE THREAD

**Issue by pasdeloup** [chaquo/chaquopy#899]
Hey,
I need to rebuild my packages (Numba, Numpy and others) for Python 3.9 and using some precise versions, so I'm trying to install all the building environment but I encounter a lot of small issues and wonder if I don't do something wrong :thinking: ?

 * `base.dockerfile` the requested version of Debian has been archived so the apt sources need to be updated to : 
```
-RUN echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
+RUN printf "deb http://archive.debian.org/debian stretch main\ndeb-src http://archive.debian.org/debian stretch main\ndeb http://archive.debian.org/debian stretch-backports main\ndeb http://archive.debian.org/debian-security stretch/updates main\ndeb-src http://archive.debian.org/debian-security stretch/updates main\n" > /etc/apt/sources.list 
```
* `server/pypi/build-wheel.py` : line 172 `sum()` use the Python 3.8 syntax and so don't work with the default 3.7 installed in the Docker, I had to tweak the Dockerfile to use pyenv and force 3.8

* `build-maven.sh` : couldn't make it work yet
`docker build -t chaquopy-target target` doesn't build the toolchains as `build-all.sh` is not executed (and the source is not copied either)

**Comment by mhsmith** [comment]
The Dockerfiles in the repository have not been updated to match the recent changes in the build system. We may fix this in the future, but meanwhile, it's easiest to just ignore Docker and follow the instructions in [the README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md).

**Comment by pasdeloup** [comment]
Ok thanks!
