### ISSUE TITLE
Python folder is empty and understanding how to call a python script within the application

### ISSUE THREAD

**Issue by jeffmorr** [chaquo/chaquopy#90]
Hello,

I have two main questions. one is dealing with the initial setup of integrating Python with AndroidStudio. When I click Make Project of my Android Studio application, the python folder that is created within my app/src/main/ directory is empty. I have Python30 installed on C:/Python30/python.exe. This is what my app.build.gradle looks like 

```
apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'

android {
    compileSdkVersion 28
    defaultConfig {
        ndk{
            abiFilters "arm64-v8a"
        }
        applicationId "com.example.androidwebserver"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments "-DANDROID_STL=c++_shared"
            }
        }
        python {
            //buildPython "C:/Python30/python.exe"
            pip {
                install "scipy==1.1.0"
                install "scikit-learn==0.19.1"
            }
            pyc {
                stdlib true
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    // If you want Gradle to package prebuilt native libraries
    // with your APK, modify the default source set configuration
    // to include the directory of your prebuilt .so files as follows.
    sourceSets {
        main {
            jniLibs.srcDirs 'libnode/bin/'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

I tried using the manual buildPython setting but that seems to give an error (probably because it's already installed on my machine). So any help on this would be appreciated!

My second question is dealing with just understanding how Chaquopy works in general. I have a MainActivity that is written in Java, is it possible for me to call a Python script from that Java activity file and if so how do I do that? Or do I have to rewrite the Java activity file in python? 

Thanks for any help!

**Comment by mhsmith** [comment]
> I tried using the manual buildPython setting but that seems to give an error

If your "Python30" really is Python 3.0, then that is way too old.  buildPython need to be at least Python 3.4.

Or if that's not the problem, please post the error message.

> I have a MainActivity that is written in Java, is it possible for me to call a Python script from that Java activity file

Of course, and here are some examples:
* https://github.com/chaquo/chaquopy/blob/master/app/src/main/java/com/chaquo/python/demo/JavaDemoActivity.java
* https://github.com/chaquo/chaquopy-console

**Comment by mhsmith** [comment]
If you still have a problem, please reopen and give details.
