### ISSUE TITLE
Fail to find joblib model file

### ISSUE THREAD

**Issue by KimiaHO** [chaquo/chaquopy#900]
A model must be loaded with joblib format. the model file is present in python package in android studio. How the model is loaded in python:
`        svc_model = load('VT_VF_model.joblib')
`
This error occurs:
`FileNotFoundError: [Errno 2] No such file or directory: 'VT_VF_model.joblib'
        at <python>.joblib.numpy_pickle.load(numpy_pickle.py:650)`
Is it possible to run these models in chaquopy? or should it only be tflite format?
Thank you in advance

**Comment by mhsmith** [comment]
See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#filenotfounderror). And please read the issue template in future: it's there to save you time.
