### ISSUE TITLE
how to Implement pip installation

### ISSUE THREAD

**Issue by lex-geeker** [chaquo/chaquopy#902]
#### Chaquopy version
14.0.2

#### Relevant parts of your build.gradle file
```
python {
            buildPython project["buildPython"]
            pip {
                version "3.8"
                install "chaquopy-libjpeg"
                install "chaquopy-freetype"
            }
        }
```
#### Describe your issue
For example, I installed the dependencies required by pillow in advance. I downloaded and decompressed the pillow through whl to achieve the import of Pillow, but an error was reported when it ran, indicating "dlopen failed: library "libjpeg_chaquopyopy.so" not found", how do I find" libjpeg_chaquopyopy.so"

**Comment by mhsmith** [comment]
There's no need to do any of this manually. Just write `install "pillow"`, and pip will handle everything automatically.

**Comment by lex-geeker** [comment]
> There's no need to do any of this manually. Just write `install "pillow"`, and pip will handle everything automatically.

I know the operation you said, but I want to implement online installation. For example, my APP does not have this library and I want to install pillow online

**Comment by mhsmith** [comment]
OK, please post the full stack trace.

And also explain why you're doing it this way, when building the library in your app is so much easier.

**Comment by lex-geeker** [comment]
> OK, please post the full stack trace.
> 
> And also explain why you're doing it this way, when building the library into your app is so much easier.

I put pillow in my home, and I run this code

"from PIL import Image"

But it suggests
./java/android/importer.py
ImportError at line 619 of source string: dlopen failed: library "libjpeg_chaquopy.so" not found
But I already have libjpeg_chaquopy.so installed and I don't know where to put this so or how to load it properly

The reason for this is because I want to implement a dependent online installation like pip

**Comment by mhsmith** [comment]
Sorry, this isn't going to work. You can load pure-Python code at runtime by adding it to `sys.path`, but packages like Pillow with native-compiled .so files will only work if they're built into the app.

**Comment by xiaoPyTool** [comment]
> Sorry, this isn't going to work. You can load pure-Python code at runtime by adding it to `sys.path`, but packages like Pillow with native-compiled .so files will only work if they're built into the app.

But after I unzipped the requests package in the same way
The code is as follows
import requests

Report an error
No module named 'urllib3'
ModuleNotFoundError at line 20 of source string: No module named 'urllib3'
I have added sys.path, but it seems that sys.path does not work?

**Comment by lex-geeker** [comment]
> Sorry, this isn't going to work. You can load pure-Python code at runtime by adding it to `sys.path`, but packages like Pillow with native-compiled .so files will only work if they're built into the app.

But after I unzipped the requests package in the same way
The code is as follows
import requests

Report an error
No module named 'urllib3'
ModuleNotFoundError at line 20 of source string: No module named 'urllib3'
I have added sys.path, but it seems that sys.path does not work?

**Comment by mhsmith** [comment]
Please post the relevant code, including how you're downloading it, unzipping it, adding it to sys.path, and how you're running the "source string".

**Comment by mhsmith** [comment]
If you still need help, please provide the requested information, and I'll reopen the issue.
