### ISSUE TITLE
Failed to install grpcio from flwr 

### ISSUE THREAD

**Issue by pro3k** [chaquo/chaquopy#906]
#### Chaquopy version
**'14.0.2'**

#### Relevant parts of the build.gradle file
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {

            buildPython "C:/Python38/python.exe"

            pip {
                options "--upgrade", "pip"
                install "gensim"
                install "numpy"
                install "pandas"
                install "openpyxl"
                install "scikit-learn"
                install "torch==1.8.1"
                install "transformers==4.15.0"
                install "tokenizers"
                install "flwr"
            }

            pyc {
                src false
            }
        }

#### Issue
To fulfil my requirements, I want to install "**flwr**" model to my Python environment on an Android device. 

Failed to install grpcio!=1.52.0,<2.0.0,>=1.48.2 from https://files.pythonhosted.org/packages/ee/d6/62ea04e71abe92406baf8fbe25daee5e90d45571206b8e93c4812ea958b6/grpcio-1.56.0.tar.gz#sha256=4c08ee21b3d10315b8dc26f6c13917b20ed574cdbed2d2d80c53d5508fdcc0f2 (from flwr).

**Comment by mhsmith** [comment]
See #873, and please search for existing issues before creating new ones.

**Comment by pro3k** [comment]
When I try to install `grpcio` with the specified version `1.48.2` from the last error that I mentioned in the above issue. I got this line ` ASM Builds for BoringSSL currently not supported on: win-amd64` in the Build Output. What is the meaning of this line? Can I able to work with `flwr` in the Windows system? And how to work with it?

**Comment by mhsmith** [comment]
As #873 says, try using `flwr==0.18.0`.
