### ISSUE TITLE
System storage fills up after several deployments

### ISSUE THREAD

**Issue by Benoit-W** [chaquo/chaquopy#911]
Hello, I am using Chaquopy and i have got a strange storage issue.

When i am coding on Android Studio and deploying my app on my simulated device, the system storage (which is not accessible as i know) fills up at the same time as the Apps storage. If i deploy it many times, the application storage don't decrease , but the system one will. It lead to a loss of spaces on my phone :/ .
The same issue appears when i uninstall the app, only the App storage will increase, not the system storage.

I had the same issue on my personnal phone and has to reset it totally because of this. 

Does someone could help me to find where the problem could be ?

**Comment by mhsmith** [comment]
Which devices does this happen on, with which Android versions?

What exactly do you mean by "the system storage" and "the application storage", and how are you measuring each one? Please include before and after screenshots.

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information, and I'll reopen the issue.
