### ISSUE TITLE
scikit-image

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#92]
If you're interested in using this package with Chaquopy, please subscribe to this issue and add a thumbs up.

**Comment by nonsobiose** [comment]
This package isn't part of the packages listed on your site.
https://chaquo.com/pypi-2.1/

**Comment by mhsmith** [comment]
scikit-image is now available. To access its example data, you'll currently have to add the following line to the `python` block in your `build.gradle`:

```
extractPackages "skimage.data", "skimage.io"
```

This will be added as a default in the next release of Chaquopy.
