### ISSUE TITLE
How to convert python's NumPy type to Java's OnnxTensorLike type

### ISSUE THREAD

**Issue by 5tiaowu** [chaquo/chaquopy#922]
I moved the onnxruntime to android now and it works fine now the problem is 

         ort_inputs = {'input1': np.array([image]).astype(np.float32)}
         ort_outs = self.__ort_session.run(None, ort_inputs) 

python calls our java method 

     public Result run(Map<String, ? extends OnnxTensorLike> inputs) throws OrtException {
         return this.run(inputs, this.outputNames);
     }

This will report an error because the type does not match. How to convert python's NumPy type to Java's OnnxTensorLike type

![image](https://github.com/chaquo/chaquopy/assets/108533707/455121b0-1aab-48a1-ae61-0df52e90f79f)
![image](https://github.com/chaquo/chaquopy/assets/108533707/7c386d8c-41d0-425a-8cda-267bcce32bf4)
![image](https://github.com/chaquo/chaquopy/assets/108533707/b420ff45-d0aa-48c5-9fe8-336e5cf06d20)
![image](https://github.com/chaquo/chaquopy/assets/108533707/06fb7d24-5d34-4e08-91a1-02b43f09853c)

**Comment by mhsmith** [comment]
Sorry for the slow reply. I'm not familiar with ONNX, but you'll probably need to use one of the [`createTensor`](https://onnxruntime.ai/docs/api/java/ai/onnxruntime/OnnxTensor.html) functions.
