### ISSUE TITLE
are 50MB of chaquopy assets correct?

### ISSUE THREAD

**Issue by albaspazio** [chaquo/chaquopy#925]
#### Chaquopy version
14.0.2

#### Relevant parts of your build.gradle file
        ndk {
            abiFilters  "arm64-v8a" 
        }
        python {
            pip {
                install "matplotlib"
                install "adopy"
            }
        }
#### Describe your issue
my release apk contains 50MB of chaquopy assets.
requirements-common.imy    47.5 MB
stdlib-common.imy                2.8MB
stdlib-arm64-v8a.imy             1.4MB
and more.....

is it ok? 
thanks
Alberto

**Comment by mhsmith** [comment]
Adopy depends on some large packages including SciPy and Pandas, and matplotlib is also fairly large, so I don't think an  app with these requirements can be made any smaller.

The .imy files are actually ZIPs, so you can rename and unpack them if you want to see exactly what's taking up the space.
