### ISSUE TITLE
How to convert Python's numpy array to Java Byte Array?

### ISSUE THREAD

**Issue by AniketKumarSingh123456789** [chaquo/chaquopy#926]
I'm working on image processing with opencv, numpy, pillow and cython

I'm trying to pass the result (a numpy array) from Python to Java and converting the result into byte array

And i encountered this error:

**java.lang.ClassCastException: cannot convert ndarray object to  bytes**

How to convert Python's numpy array to Java Byte Array?

**Comment by mhsmith** [comment]
Please post the relevant parts of your code.

**Comment by AniketKumarSingh123456789** [comment]
1.  A portion from **imgprocess.pyx**

**#cython: c_string_type=unicode, c_string_encoding=utf8**
import cv2, numpy as np
from PIL import Image, ImageFilter
from libcpp.string cimport string
cimport cython, numpy as cnp

cnp.import_array()

def emboss(string file_name):
    img = Image.open(file_name)
    res = img.filter(ImageFilter.EMBOSS)
    return np.asarray(res)



2. **setup.py**

from distutils.core import setup
from Cython.Build import cythonize
import numpy
from setuptools import setup, find_packages, Extension
from setuptools.command.build_ext import build_ext


extensions = [Extension( 
    name="imgprocess",
    sources=['imgprocess.pyx'],
    language='c++' ), ]

setup(
    name="imgprocess",
    version='1.0.0',
    include_package_data=True,
    include_dirs=[numpy.get_include()],
    ext_modules = cythonize(extensions))

3. **build.gradle**

pip {
                install "numpy-1.19.5-0-cp38-cp38-android_21_arm64_v8a.whl"
                install "opencv_python-4.5.1.48-1-cp38-cp38-android_21_arm64_v8a.whl"
                install "Pillow-8.4.0-0-cp38-cp38-android_21_arm64_v8a.whl"
                install "imgprocess-1.0.0-0-cp38-cp38-android_21_arm64_v8a.whl"
            }

4. A portion from **MainActivity.java**

Python python;

if (!Python.isStarted()) {
            Python.start(new AndroidPlatform(MainActivity.this));
        }
python = Python.getInstance();
PyObject imgprocess= python.getModule("imgprocess");
PyObject pyObject = imgprocess.callAttr("emboss", "test.png");

byte[] bytes;
bytes = pyObject.toJava(byte[].class);


 runOnUiThread(() -> {
                            photoEditorView.getSource().setImageBitmap(BitmapFactory.decodeByteArray(bytes, 0, bytes.length));

});

**Comment by AniketKumarSingh123456789** [comment]
Please reply sir @mhsmith  it's been a week.

**Comment by mhsmith** [comment]
Sorry for the slow reply.

`BitmapFactory.decodeByteArray` expects an image file, not a raw bitmap. So if you change your Python code to encode the image as a PNG file, and return it as a `bytes` object, then your Java code should work without modification.

**Comment by mhsmith** [comment]
For a similar example, see https://github.com/chaquo/chaquopy-matplotlib

**Comment by AniketKumarSingh123456789** [comment]
Encoding the image as JPEG is better than encoding it as PNG, it takes less time to process.

Thank you sir @mhsmith for your support.
