### ISSUE TITLE
Update aiohttp

### ISSUE THREAD

**Issue by 0cothucluc** [chaquo/chaquopy#927]
I'm integrating langchain into chaquopy, it built successfully but show the error

#### Chaquopy version

14.0.2

#### Relevant parts of your code

``` defaultConfig {
        applicationId "com.example.xxxx"
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        sourceSets{
            main{
                python.srcDir "src/main/python"
            }
        }
        python {
            version "3.8"
            pip {
                install "matplotlib"
                install "openai"
                install "langchain"
            }
        }
```

**Error**
```
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python3'' finished with non-zero exit value 1
```

**Comment by mhsmith** [comment]
The error I received from langchain is:
```
  error: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install aiohttp<4.0.0,>=3.8.3 from https://files.pythonhosted.org/packages/d6/12/6fc7c7dcc84e263940e87cbafca17c1ef28f39dae6c0b10f51e4ccc764ee/aiohttp-3.8.5.tar.gz#sha256=b9552ec52cc147dbf1944ac7ac98af7602e51ea2dcd076ed194ca3c0d1c7d0bc (from langchain).
```

As you can see [here](https://chaquo.com/pypi-7.0/aiohttp/), the newest version of aiohttp we currently have is 3.8.1, so you'll have to use an older version of langchain:
```
                install "openai"
                install "langchain==0.0.79"
                install "charset-normalizer<3.0"
```

If this is too old for you, please explain why.

**Comment by 0cothucluc** [comment]
after changing the langchain version, I still have above errors

**Comment by mhsmith** [comment]
The cause might be obvious from the full build log. You can view it by clicking on the "Build ... failed" caption to the left of the error message. If you still don't understand it, please post the log here.

**Comment by mhsmith** [comment]
If this is still a problem, please post the requested details, and I'll reopen the issue.

**Comment by thuanDDKeego** [comment]
I want to use the newer version of LangChain, but I met this issue.
Failed to install numexpr<3.0.0,>=2.8.4 from https://files.pythonhosted.org/packages/85/d0/411a1fac79c7cd56978318b28a7effd8fa56c0056e1878cf41185a0d693c/numexpr-2.8.6.tar.gz#sha256=6336f8dba3f456e41a4ffc3c97eb63d89c73589ff6e1707141224b930263260d (from langchain===0.0.180).

**Comment by mhsmith** [comment]
Let's use this issue to track updating aiohttp, and discuss numexpr in #975.

If you'd like to try building a newer version of this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the new version to the public repository.

If anyone else needs a new version of this package, please click the thumbs up button above, and post a comment explaining why you need it.

**Comment by mhsmith** [comment]
Sorry for the slow reply.

**Comment by IsakTheHacker** [comment]
I also need aiohttp 3.8.3 or newer because a package I depend on needs it. I can't use older versions of that package because I need the functionality provided by the latest version!

**Comment by mhsmith** [comment]
Can you be more specific about which package, which version and which functionality?
