### ISSUE TITLE
Compilation on migration from Python version "3.8" -> "3.11"

### ISSUE THREAD

**Issue by Gelassen** [chaquo/chaquopy#939]
#### Chaquopy version
```id("com.chaquo.python") version "14.0.2" apply false```

#### Relevant parts of your build.gradle file
Module ```:chaquolib```
```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}

android {
    namespace 'io.github.gelassen.chaquopylib'
    compileSdk 33

    defaultConfig {
        applicationId "io.github.gelassen.chaquopylib"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            // you may also import only some of them
        }
        python {    // this is not recognized in kts builds !!!
            version "3.11"
//            version "3.8"
            pip {
                install "matplotlib"
            }
            pyc {
                src false
            }
        }

    }

/*    sourcesJar {
        duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
    }*/

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
/*    implementation "androidx.core:core-ktx:1.9.0" */
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.google.android.material:material:1.9.0"
    implementation 'org.jetbrains.kotlin:kotlin-reflect:1.7.20'
}
```

#### Describe your issue
I try to run my code with the most recent Python version. With Python version 3.8 I am able to compile code, with Python 3.11 I get this error: 
```
Caused by: org.gradle.api.InvalidUserCodeException: Entry bootstrap.imy is a duplicate but no duplicate handling strategy has been set.
```
Duplicates during merge are know for me and in case of manifest it would look like this: 
```
android {
    packagingOptions {
        pickFirst "META-INF/MANIFEST.MF"
        // exclude "META-INF/MANIFEST.MF"
    }
}
```
, but for this issue it is clear yet how it should be solved. 

Sample code to reproduce the issue:
```
$ git clone https://github.com/Gelassen/chaquopy-integration.git
$ git checkout choir/python-version
```

**Comment by Gelassen** [comment]
I was able to run code with the latest python version with the latest but[ not-released-yet version of chaquopy](https://chaquo.com/chaquopy/doc/15.0/android.html). 

However, I am getting ```TypeError: 'MainActivity$testPythonModule$Params1' object is not subscriptable```, but it is seems to be just pure python related  issue.

**Comment by mhsmith** [comment]
> Sample code to reproduce the issue:
> 
> ```
> $ git clone https://github.com/Gelassen/chaquopy-integration.git
> $ git checkout choir/python-version
> ```

Your project has a couple of structural problems:

* You're using the `com.android.application` plugin in both modules, with one depending on the other. The second module should be using the `com.android.library` plugin instead.
* You're using the `com.chaquo.python` plugin in multiple modules, which is [not supported](https://chaquo.com/chaquopy/doc/current/android.html#android-plugin).

Also, we don't currently have matplotlib for Python 3.11, only for 3.8, 3.9 and 3.10.

> However, I am getting `TypeError: 'MainActivity$testPythonModule$Params1' object is not subscriptable`, but it is seems to be just pure python related issue.

If you need help on that, please create a separate issue with a full stack trace and the relevant sections of your code.

**Comment by Gelassen** [comment]
@mhsmith , thank you. Where can I look on al supported packages/modules? 

Regarding issue, I have rolled back to use chaquopy directly, without wrapper. Similar calls gives different errors. Also call a simple ```sum_func``` from a class gives strange error, but a call to the same ```sum_func``` out of the class works fine. I will prepare an issue in next ten minutes.

**Comment by Gelassen** [comment]
Also I am interested to know what should be done to have python package/module by chaquopy? At this moment I need support of ```transformers``` and ``ckip-transformers``` to run [this classifiers](https://gist.github.com/Gelassen/e8e40cb79b87bc4144c1ed71dc902aed). May be I could help with it. 

[https://pypi.org/project/transformers/](https://pypi.org/project/transformers/)
[https://pypi.org/project/ckip-transformers/](https://pypi.org/project/ckip-transformers/)

**Comment by mhsmith** [comment]
> Where can I look on all supported packages/modules?

Our native-compiled packages are all listed here:
* https://chaquo.com/pypi-7.0/
* https://chaquo.com/pypi-13.1/

As well as these packages, Chaquopy also supports most pure-Python packages on [PyPI](https://pypi.org/).

> At this moment I need support of `transformers` and ``ckip-transformers```

We don't support the current version of `transformers`, but you can try an older version as shown at https://github.com/chaquo/chaquopy/issues/608#issuecomment-1107441743.

**Comment by Gelassen** [comment]
I am closing issue, because I was able to build and run the most recent version of chaquopy despite its alfa version.
