### ISSUE TITLE
Cannot delay sound play on Android.

### ISSUE THREAD

**Issue by leaffeather** [chaquo/chaquopy#941]
I uses beeware/toga and I want to play sound on Android. I refer to an existing topic https://stackoverflow.com/questions/74120614/how-to-play-sound-in-an-android-app-created-by-beeware-using-python but it causes an exception **sample 1 not ready**and no sound is played. I refer to some websites and the conclusion is that the sound has not completely loaded into the memory but .play method has already executed. There are two methods to deal with it:
(1) Directly set a delay. This is not a good idea because the larger the time interval, the more obvious the lag, and the smaller the time interval, the more the loop. 
(2) Set a soundPool.setOnLoadCompleteListener() method. I refer to https://www.android-doc.com/reference/android/media/SoundPool.OnLoadCompleteListener.html and try to change into python code. Here is my code:
`python

        from android.media import AudioManager, SoundPool
        
        soundPool = SoundPool(5, AudioManager.STREAM_MUSIC, 0)
        
        soundId = soundPool.load(filedir, 1)
        
        class OnLoadCompleteListener(SoundPool.OnLoadCompleteListener):
        
            def __init__(self, callback):
        
                self.callback = callback
        
            def onLoadComplete(self, soundPool, sampleId, status):
        
                self.callback(soundPool, sampleId, status)
        
        onLoadCompleteListener = OnLoadCompleteListener(lambda soundPool, sampleId, status: soundPool.play(sampleId, 1, 1, 1, 0, 1.0))
        
        soundPool.setOnLoadCompleteListener(onLoadCompleteListener)

`
But this code will cause a problem **Java classes can only be inherited using static_proxy or dynamic_proxy** and no sound will play. How to solve this problem?

**Comment by mhsmith** [comment]
To implement a Java interface, use the dynamic_proxy feature as shown [here](https://chaquo.com/chaquopy/doc/current/python.html#dynamic-proxy).
