### ISSUE TITLE
Do not put the compiled folder in assets and load it locally

### ISSUE THREAD

**Issue by 5tiaowu** [chaquo/chaquopy#944]
Can you not put the chaquo folder in assets? I want to load the sd card locally and load the compiled folder because every hot update in the app has to load a large volume

**Comment by mhsmith** [comment]
See #382.

**Comment by 5tiaowu** [comment]
> See #382.

I don't want to reload python, I just want to put the compiled folder chaquo on the sd card instead of putting it in assets

**Comment by mhsmith** [comment]
It's basically the same approach: 
* Put the code you're updating in a directory on the device. The app's `files` directory is the easiest option.
* In the app's main code (built into the assets), include something which adds that directory to `sys.path` and then imports from it.
* When the code you're updating has changed, either reload it as shown in #382, or just restart the app.

**Comment by 5tiaowu** [comment]
> It's basically the same approach: 
> 
> * Put the editable code in a directory on the device. The app's `files` directory is the easiest option.
> 
> * In the app's main code (built into the assets), include something which adds that directory to `sys.path` and then imports from it.
> 
> * When the editable code has changed, either reload it as shown in [#382](https://github.com/chaquo/chaquopy/issues/382), or just restart the app.

Isn’t the compiled folder a chaquo folder? In the assets folder, I copied it to the local directory of the sd card. Then how should I load this folder? Can you give me some code reference? What should I write?

**Comment by mhsmith** [comment]
What exactly did you copy?

**Comment by 5tiaowu** [comment]
> What exactly did you copy?

My purpose is simply to load from the local instead of running assets. I copied the chaquo folder generated by compilation to /storage/chaquopy. Now I want to load it from the local, but this folder is composed of some files that do not belong to py. load

**Comment by 5tiaowu** [comment]
> What exactly did you copy?

![image](https://github.com/chaquo/chaquopy/assets/108533707/47f2ea74-a3cc-4d99-a31a-dec5adee0f34)

**Comment by 5tiaowu** [comment]
> What exactly did you copy?

It is this folder. This folder is stored under assets by default. Chaquo also loads this folder from assets to run py, but I want to copy this folder to the local SD card to load instead of running assets.

**Comment by mhsmith** [comment]
Those files can only be loaded from the assets. So if you want to update your Python code without reinstalling the whole app, you'll have to use the approach I described in my previous comments.
