### ISSUE TITLE
Changing python internal lib source code does not take any effect

### ISSUE THREAD

**Issue by EVRICA** [chaquo/chaquopy#946]
Hi Chaquopy team!

I wonder, from where does Chaquopy imports standard (internal, like asyncio) libraries for python?
And does Chaquopy updates this python "imported libs list" every time I build my kotlin app?

Because I stuck in situation where I need to change asyncio lib source code,
I change it, and my app runs like nothing was changed at all :/
(But these (my) changes in asyncio lib are noticeable when I run python code separately)
It looks like Chaquopy imports libs NOT from PATH, but from another place?...

What is this "place"?

(OS: Windows)

**Comment by mhsmith** [comment]
Why do you need to change the asyncio source code: what are you trying to achieve?

Which files, classes and functions are you changing?

And where are you finding those files currently?

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information, and I'll reopen the issue.
