### ISSUE TITLE
Error reported when using the requests library

### ISSUE THREAD

**Issue by shengyuansir** [chaquo/chaquopy#948]
Error reported when using the requests library：<model * from '/data/data/.../*.pyc'>
Can I support the use of the requests library

**Comment by mhsmith** [comment]
See the FAQ answers about [accessing the Internet](https://chaquo.com/chaquopy/doc/current/faq.html#no-address-associated-with-hostname) and [writing files](https://chaquo.com/chaquopy/doc/current/faq.html#faq-write). Then if you still need help, please post the [full stack trace](https://stackoverflow.com/a/23353174).

**Comment by mhsmith** [comment]
If you still need help, please post the requested information, and I'll reopen the issue.
