### ISSUE TITLE
ERROR: Failed to install scikit-learn

### ISSUE THREAD

**Issue by RahulMvr2824** [chaquo/chaquopy#950]
#### Chaquopy version
"com.chaquo.python:gradle:14.0.2"

#### Relevant parts of your build.gradle file

ndk {
            abiFilters  "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            //   abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            pip {
                
                install "numpy"
                install "matplotlib"
                install "scipy"
                install "reportlab"
                install "scikit-learn"
                install "pandas"
                install "heartpy"
                install "scikit-image"
                install "neurokit2"
                install "biosppy"
            }
        }
#### Describe your issue

When trying to install Scikit-learn installation getting failed. here's the complete log

> error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 ERROR: Command errored out with exit status 1: command: 'C:\Users\venka\AppData\Local\Programs\Python\Python311\python.exe' 'D:\RNProjects\InnoVital_Project1\InnoVital\android\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\venka\AppData\Local\Temp\tmp0_1ewkoy' cwd: C:\Users\venka\AppData\Local\Temp\pip-install-gwh7m95_\scikit-learn Complete output (30 lines): Partial import of sklearn during the build process. Traceback (most recent call last): File "D:\RNProjects\InnoVital_Project1\InnoVital\android\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 280, in <module> main() File "D:\RNProjects\InnoVital_Project1\InnoVital\android\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 263, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\RNProjects\InnoVital_Project1\InnoVital\android\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel return hook(metadata_directory, config_settings) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\venka\AppData\Local\Temp\pip-build-env-5jrcodxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel self.run_setup() File "C:\Users\venka\AppData\Local\Temp\pip-build-env-5jrcodxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script) File "C:\Users\venka\AppData\Local\Temp\pip-build-env-5jrcodxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup exec(code, locals()) File "<string>", line 626, in <module> File "<string>", line 620, in setup_package File "<string>", line 554, in configure_extension_modules File "C:\Users\venka\AppData\Local\Temp\pip-install-gwh7m95_\scikit-learn\sklearn\_build_utils\__init__.py", line 46, in cythonize_extensions basic_check_build() File "C:\Users\venka\AppData\Local\Temp\pip-install-gwh7m95_\scikit-learn\sklearn\_build_utils\pre_build_helpers.py", line 73,m(code) File "C:\Users\venka\AppData\Local\Temp\pip-install-gwh7m95_\scikit-learn\sklearn\_build_utils\pre_build_helpers.py", line 31, in compile_test_program ccompiler.compile( File "C:\Users\venka\AppData\Local\Temp\pip-build-env-5jrcodxe\site\chaquopy_monkey.py", line 56, in compile chaquopy_block_native("CCompiler.compile") File "C:\Users\venka\AppData\Local\Temp\pip-build-env-5jrcodxe\site\chaquopy_monkey.py", line 87, in chaquopy_block_native raise DistutilsPlatformError("{}: {}".format(prefix, CHAQUOPY_NATIVE_ERROR)) distutils.errors.DistutilsPlatformError: CCompiler.compile: Chaquopy cannot compile native code ---------------------------------------- ERROR: Failed to install scikit-learn>=1.0.0 from https://files.pythonhosted.org/packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz#sha256=8be549886f5eda46436b6e555b0e4873b4f10aa21c07df45c4bc1735afbccd7a (from neurokit2). For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues. Chaquopy: Exit status 1 FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:generateDebugPythonRequirements'. > Process 'command 'py'' finished with non-zero exit value 1 To view full details in Android Studio: * Click the 'Build: failed' caption to the left of this message. * Then scroll up to see the full output. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 1m 53s.

**Comment by mhsmith** [comment]
See #732, where someone else was also trying to use neurokit2.
