### ISSUE TITLE
15.0 release?

### ISSUE THREAD

**Issue by dbnicholson** [chaquo/chaquopy#958]
I see 15.0.0 was [tagged](https://github.com/chaquo/chaquopy/releases/tag/15.0.0) a few weeks ago, but as far as I can tell it hasn't been published. Do you have a timeline for making an official release? The fixes I'm really interested were merged after 15.0.0, though.

**Comment by mhsmith** [comment]
Version 15.0.0 hasn't been fully tested, but you can still use it by following the instructions [here](https://github.com/chaquo/chaquopy/issues/934#issuecomment-1683205265). I'm planning to make an official 15.0.1 release within the next few weeks.

**Comment by tim4tech** [comment]
Any progress on this? Looking to use Gradle 8+ and don't want to stop using this awesome lib!

**Comment by mhsmith** [comment]
Chaquopy 15.0.1 has now been released.
