### ISSUE TITLE
Problems setting up in Gradle 8.0

### ISSUE THREAD

**Issue by BentiGorlich** [chaquo/chaquopy#959]
#### Chaquopy version
14.0.2

#### Relevant parts of your build.gradle file
```
android {
    namespace = "de.bentigorlich.mozillattsenginewrapper"
    compileSdk = 33

    defaultConfig {
        applicationId = "de.bentigorlich.mozillattsenginewrapper"
        minSdk = 26
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }

        ndk {
            abiFilters.add("armeabi-v7a")
            abiFilters.add("arm64-v8a")
            abiFilters.add("x86")
            abiFilters.add("x86_64")
        }

        python {
            version "3.8"
            pip {
                install "TTS"
            }
        }
    }
}
```

#### Describe your issue

Hi, I am completely new to chaquopy and tried to create a new project and set it up. I followed the instructions on the homepage and tried to copy some things from the `chaquopy-matplotlib` example. However I got stuck very fast with the ndk section, because the offical docs from android studio say the same as your examples and instructions, but my AndroidSutdio build complained instantly, so I copied something from Stackoverflow which you can see above. I don't know whether it is correct, but the build didn't complain anymore. Now I added the stuff to add the python package in which I am interested and got these errors:

> e: /home/benni/Dokumente/git/mozillattsenginewrapper/app/build.gradle.kts:29:25: Unexpected tokens (use ';' to separate expressions on the same line)
e: /home/benni/Dokumente/git/mozillattsenginewrapper/app/build.gradle.kts:24:31: Unresolved reference: ABI_FILTERS
e: /home/benni/Dokumente/git/mozillattsenginewrapper/app/build.gradle.kts:27:9: Unresolved reference: python
e: /home/benni/Dokumente/git/mozillattsenginewrapper/app/build.gradle.kts:28:13: Unresolved reference: pip
e: /home/benni/Dokumente/git/mozillattsenginewrapper/app/build.gradle.kts:29:17: Unresolved reference: install

I did sync the build with my previous config which was working. I don't really have a clue as to what I am supposed to be doing, so any help is appreciated.

**Comment by mhsmith** [comment]
To use Chaquopy in a KTS file you'll need to use a pre-release version. See [here](https://github.com/chaquo/chaquopy/issues/934#issuecomment-1683205265) for instructions.

**Comment by BentiGorlich** [comment]
Yeah I just noticed that. Thanks for the quick comment. Recreated the project with groovy dsl and use Java. Didn't want to use Kotlin anyway :sweat_smile:
