### ISSUE TITLE
No python interpreter

### ISSUE THREAD

**Issue by Azhan-Aathir** [chaquo/chaquopy#96]
It shows no python interpreter is added to the module

**Comment by mhsmith** [comment]
I assume you're getting this message from the Python Community Edition plugin. Only a few features of this plugin will work properly in Android Studio. Most of the IDE assistance will be unavailable, but the build process should still work fine.

**Comment by Azhan-Aathir** [comment]
Then, is Chaquopy different from python community edition??

**Comment by mhsmith** [comment]
Yes, Chaquopy is a plugin for the Gradle build system, which mosly runs independently of the Android Studio IDE. It hasn't been fully integrated with the Python IDE plugin, but some basic IDE features will still work, including syntax highlighting and navigation within a single module.
