### ISSUE TITLE
creating onCompletionListener for MediaPlayer

### ISSUE THREAD

**Issue by nevahid** [chaquo/chaquopy#965]
hi, i'm working on a project using chaquopy. I'm writing code in python to play videos in a VideoView in android. everything works fine, i just need to implement OnCompletionListener like below (but in python):

```
mPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
    public void onCompletion(MediaPlayer mp) {
        doSomeThing()
    }
}); 
```

i'm just so confused on how to write this listener. i tried this, but no success:

```
onCompListener = MediaPalyer.OnCompletionListener():
      @Override(jvoid, [MediaPalyer])
      def onCompletion(self, mp):
           doSomeThing()
videoview.setOnCompletionListener(
      onCompListener
      )
```

**Comment by nevahid** [comment]
i was wandering around examples of chaqopy and after reviewing the deme, i wrote down this code for my problem:

```
class MyMediaPlayer(static_proxy(MediaPlayer)):
    @Override(jvoid, [MediaPalyer])
    def onCompletion(self, mp):
		class Listener(dynamic_proxy(MediaPlayer.OnCompletionListener)):
            def __init__(self, mp):
                super(Listener, self).__init__()
```
is it correct? and how can i use it as in `setOnCompletionListener`? thanks

**Comment by mhsmith** [comment]
`MediaPlayer.OnCompletionListener` is an interface, so it can be implemented using `dynamic_proxy` as shown [here](https://github.com/chaquo/chaquopy/blob/14.0.2/demo/app/src/main/python/chaquopy/demo/ui_demo.py#L101).

**Comment by nevahid** [comment]
thank you very much. i wrote this code:
```
class onCompListener(dynamic_proxy(MediaPlayer.OnCompletionListener)):
      def __init__(self):
        super(Listener, self).__init__()
      def onCompletion(self):
        Toast.makeText(androidContext,str(len(allclips)),Toast.LENGTH_LONG).show()
```

but i got errer: "Cannot convert DynamicProxyClass object to android.media.MediaPlayer$OnCompletionListener"
and this is how i used the class
```
videoView.setOnCompletionListener(onCompListener)
```

**Comment by mhsmith** [comment]
You've edited your last comment so it's no longer using consistent names, but as it stands you should be doing `videoView.setOnCompletionListener(Listener())`, i.e. pass a Listener *object*, not the Listener *class*.

And since the `__init__` method isn't doing anything, you can delete it if you want.

**Comment by nevahid** [comment]
WOW! i don't know how i missed that, thank you very much. it is solved, everything works fine now. 🙏🙏
