### ISSUE TITLE
How to parse data Hashmap list from java android to python and Python to java?

### ISSUE THREAD

**Issue by mintheinwin** [chaquo/chaquopy#973]
I'm trying to parse data with Hashmap object list from JavaAndroid to Python and get return data Hashmap object list from python on Android Java. I'm not sure how to get it? Any have idea on call method. I'm not found in document how to parse Hashmap data from java to python and from python to java. Please Help.

        Map<PyObject,PyObject> mapParam=new HashMap<>();
        mapParam.put(PyObject.fromJava(1),PyObject.fromJava("a"));
        mapParam.put(PyObject.fromJava(2),PyObject.fromJava("b"));
        mapParam.put(PyObject.fromJava(3),PyObject.fromJava("c"));
        Map<PyObject,PyObject> pyObjectPyObjectMap= python.getModule("hello").callAttr("print_listKey",mapParam).asMap();

def print_listKey(data):
    # Traversing Java’s Map object
    return data

Error Log.
 java.lang.UnsupportedOperationException: 'HashMap' object has no attribute '__contains__'

**Comment by mhsmith** [comment]
As the message says, the HashMap class doesn't have a method called `contains`, which I assume you've included somewhere in the body of `print_listKey`. You probably want to use [`containsKey`](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#containsKey-java.lang.Object-) instead.

In future, when asking for help with your code, please actually post the code, and the full stack trace.
