### ISSUE TITLE
"Ninja is required" to run ZPdesu/Barbershop

### ISSUE THREAD

**Issue by lemontechnology73** [chaquo/chaquopy#974]
#### Relevant parts of your build.gradle file

python {
                pip{
                    install "ninja"
}
}

#### Describe your issue
 I am installing ninja but i got the following issue

 Failed building wheel for ninja

Could not build wheels for ninja which use PEP 517 and cannot be installed directly

Process 'command 'C:\Users\Admin\AppData\Local\Programs\Python\Python38\python.exe'' finished with non-zero exit value 1

**Comment by mhsmith** [comment]
Ninja is a build tool, so it would probably be useless within an Android app. Are you trying to install it because you actually want some other package? If so, please let me know which one.

**Comment by lemontechnology73** [comment]
thank you so much for your response I am new to python side I am trying to use following library
https://github.com/ZPdesu/Barbershop

**Comment by mhsmith** [comment]
Please post the full stack trace.

**Comment by mhsmith** [comment]
And since this GitHub repository is not pip-installable (having no pyproject.toml or setup.py file), please explain exactly how you added it to your app, and which other packages you installed with it.

**Comment by lemontechnology73** [comment]
I added the python project files into python directory of my android project.

**Comment by mhsmith** [comment]
Do you mean you copied the entire repository into your Python source directory?

I also need to know:
* The full stack trace
* Which other packages you installed into your app, either by copying them into your Python directory or adding them to the `pip` block of your build.gradle file.

**Comment by mhsmith** [comment]
If this is still a problem, please post the requested information, and I'll reopen the issue.
