### ISSUE TITLE
install langchain met error caused by numexpr

### ISSUE THREAD

**Issue by thuanDDKeego** [chaquo/chaquopy#975]
I want to use Vertex AI by Langchain, and the oldest version that supports it is 0.0.180. The newest version I can use without the error below is 0.0.128. It hasn't supported Vertex AI.
#### Chaquopy version 
14.0.2

#### Relevant parts of your build.gradle file

```groovy
plugins {
  ...
  id 'com.chaquo.python'
}

android {
  ...
    ndk {
    abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
    }
    python {
        buildPython "C:/Users/ducth/AppData/Local/Programs/Python/Python38/python.exe"
        pyc {
            src true
        }
        pip {
            install "openai"
            install "langchain===0.0.180"
            install "charset-normalizer<3.0"
       }
    }
}
```

#### Error
```
Failed to install numexpr<3.0.0,>=2.8.4 from https://files.pythonhosted.org/packages/85/d0/411a1fac79c7cd56978318b28a7effd8fa56c0056e1878cf41185a0d693c/numexpr-2.8.6.tar.gz#sha256=6336f8dba3f456e41a4ffc3c97eb63d89c73589ff6e1707141224b930263260d (from langchain===0.0.180).
```

**Comment by mhsmith** [comment]
numexpr contains native components, so it would have to be built into a wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

To install the current version of langchain will also require a newer version of aiohttp (#927).

**Comment by mhsmith** [comment]
Actually, there's already an open issue for numexpr, so please subscribe to #498 instead.
