### ISSUE TITLE
importlib.resources.files(__package__) api does not work 

### ISSUE THREAD

**Issue by pax0r** [chaquo/chaquopy#977]
#### Describe your issue
For some reason I can't get the `importlib.resources.files(__package__)` to work. In my case this is used by external library `jsonschema` but I was able to reproduce this in my own code as well.  By documentation this should return some Traversable with files in given module. `jsonschema` library is using it to load some `.json` files inside the package directory.

In Chaquopy each call to `importlib.resources.files(__package__)` returns `importlib._adapters.DegenerateFiles.Path` which means it cannot read files from package dir.

According to this comment: https://github.com/chaquo/chaquopy/issues/745#issuecomment-1313294553 it should work

#### Chaquopy version
`id 'com.chaquo.python' version '14.0.2' apply false`

#### Devices or emulators where the issue happens
Tested on emulator only, but I think it does not matter

#### Relevant parts of your code
```
from importlib import resources

print('==================', resources.files(__package__))
```
Should shown a `Traversable` with files from package, istead it shows  `importlib._adapters.DegenerateFiles.Path` 

I have tried both with package mentioned in `extractPackages` and not.

**Comment by mhsmith** [comment]
It looks like implementing the new `importlib.resources` API automatically gives you support for the old one, but not vice versa:
```
Python 3.10.6 (main, Sep 17 2022, 20:08:30) [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315df on linux
The current application context is available in the variable 'context'.
>>> import chaquopy
>>> from importlib import resources
>>> resources.files("chaquopy")
<importlib._adapters.DegenerateFiles.Path object at 0x7667af327eb0>
>>> root = _
>>> list(root.iterdir())
[]
>>> list(resources.contents("chaquopy"))
['__init__.py', 'test', 'utils']
```

Thanks for the report. We'll fix this in the next version of Chaquopy.

**Comment by mhsmith** [comment]
Since the new `importlib.resources` API was introduced in Python 3.9, you can probably fix any related issues in third-party packages by downgrading your app to Python 3.8.

**Comment by pax0r** [comment]
I've managed to patch 3rd party lib by myself but I can't wait for fix in Chaquopy ;) 

I've seen that in Python < 3.9 it uses https://pypi.org/project/importlib-resources/ for this task but I haven't tested it on Android.

**Comment by mhsmith** [comment]
The [importlib documentation](https://docs.python.org/3/library/importlib.resources.abc.html) says:

> Loaders that wish to support resource reading are expected to provide a method called get_resource_reader(fullname) which returns an object implementing this ABC’s interface. If the module specified by fullname is not a package, this method should return [None](https://docs.python.org/3/library/constants.html#None). An object compatible with this ABC should only be returned when the specified module is a package.

As of Python 3.12, I think this is incorrect, because `importlib.resources.files` can accept a module as well as a package, and to make that work, it's depending on the standard importers to always return an object whether they're passed a module or a package. In the common case, it returns an importlib.resources.readers.FileReader, which constructs the path simply by stripping off the last component of the module's path, whether it's `__init__.py` or anything else.
