### ISSUE TITLE
Please add package umbral to chaquopy

### ISSUE THREAD

**Issue by akhilspillai** [chaquo/chaquopy#98]
Please add umbral package to your repository. I would like to use it with [NuCypher](https://www.nucypher.com/)

**Comment by mhsmith** [comment]
umbral itself is a pure-Python package so it doesn't need to be added to the repository, but it looks like it requires some hash algorithms which we don't currently support. I'll look into this and get back to you.

**Comment by akhilspillai** [comment]
Thanks for taking a look.

**Comment by mhsmith** [comment]
OK, this requires OpenSSL 1.1, which will be included in the next release of Chaquopy. However, that probably won't be for a few weeks, so I've made a pre-release build available. To use it, edit your app's top-level `build.gradle` file as follows:

* Change `https://chaquo.com/maven` to `https://chaquo.com/maven-test`.
* Change the version number of `com.chaquo.python` to `6.2.0`.

Please give this a try and let me know how you get on.

**Comment by akhilspillai** [comment]
It seems to be working fine. I did not get enough time to test but as far as I can see everything seems fine. Thanks a lot for your effort. Really appreciate it.

**Comment by mhsmith** [comment]
If you're using the above pre-release, please now switch to the released version, 6.2.1:

* Change https://chaquo.com/maven-test back to https://chaquo.com/maven.
* Change the version number of com.chaquo.python to 6.2.1.

The pre-release will be removed in 2 weeks.

**Comment by mhsmith** [comment]
The pre-release build has now been removed: see the previous comment for what to do if you're still using it.
