### ISSUE TITLE
Chaquopy cannot compile native code PyClipper

### ISSUE THREAD

**Issue by Rudransh1996** [chaquo/chaquopy#982]
#### Chaquopy version
  classpath 'com.chaquo.python:gradle:14.0.2'

#### Relevant parts of your build.gradle file
running build_ext
  building 'pyclipper._pyclipper' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install pyclipper from https://files.pythonhosted.org/packages/1b/3d/e5b5ff36b24f3fc9b962a68ce4f6932ab698b8ba860261f402be37b85d17/pyclipper-1.3.0.post5.tar.gz#sha256=c0239f928e0bf78a3efc2f2f615a10bfcdb9f33012d46d64c8d1225b4bde7096.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
  error: CCompiler.compile: Chaquopy cannot compile native code

Failed to install pyclipper from https://files.pythonhosted.org/packages/1b/3d/e5b5ff36b24f3fc9b962a68ce4f6932ab698b8ba860261f402be37b85d17/pyclipper-1.3.0.post5.tar.gz#sha256=c0239f928e0bf78a3efc2f2f615a10bfcdb9f33012d46d64c8d1225b4bde7096.

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/rudransh.sharma/python.exe'' finished with non-zero exit value 1

#### Describe your issue
While building my project I'm getting this error Chaquopy cannot compile native code for the library pyclipper which I believe is used in the easyocr library I'm using in the Python code. 
On the website, it's mentioned that this native package isn't built yet. I want to know if there's any walkaround for this.

**Comment by Rudransh1996** [comment]
Collecting kiwisolver>=1.0.1
  Using cached https://chaquo.com/pypi-7.0/kiwisolver/kiwisolver-1.1.0-1-cp38-cp38-android_16_armeabi_v7a.whl (57 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.43.0-py3-none-any.whl (1.0 MB)
Collecting setuptools
  Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
Building wheels for collected packages: PyYAML, ninja, pyclipper
  Building wheel for PyYAML (PEP 517): started
  Building wheel for PyYAML (PEP 517): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-6.0.1-cp38-cp38-win_amd64.whl size=45377 sha256=0e5515107ab66f963c8af3cdc7cc5010019fe2a1205366944db8bd19b168b13a
  Stored in directory: c:\users\rudransh.sharma\appdata\local\chaquopy\pip\cache\wheels\77\54\77\68b3079bd1d88cb070513c3935d9f7e32c70ad69368375308d
  Building wheel for ninja (PEP 517): started
  Building wheel for ninja (PEP 517): finished with status 'error'

**Comment by mhsmith** [comment]
See #584, and in future please search for existing issues before creating new ones.
