### ISSUE TITLE
Unable to install onnxruntime

### ISSUE THREAD

**Issue by lemontechnology73** [chaquo/chaquopy#985]
I am trying to install [rembg ](https://github.com/danielgatis/rembg)library through

```
 defaultConfig{
            python {
                pip{
                    install "rembg"

                }
            }
        }
```

When i build the app it gives me an error

> ERROR: Could not find a version that satisfies the requirement onnxruntime (from rembg) (from versions: none)
> ERROR: No matching distribution found for onnxruntime (from rembg)
> Could not find a version that satisfies the requirement onnxruntime (from rembg) (from versions: none)
> 
> No matching distribution found for onnxruntime (from rembg)
> 
> Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
See #216, and in future please search for existing issues before creating new ones.
