### ISSUE TITLE
Huggingface Transformer->safetensor->rust->pysam(Issue in pysam)

### ISSUE THREAD

**Issue by SahinMjks** [chaquo/chaquopy#989]
#### Chaquopy version
14.0.2  Gradle Version 8.0.0 Python version 3.8

#### Relevant parts of your build.gradle file
defaultConfig {

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        python {
            version "3.8"
        }
        sourceSets{
            main{
                python.srcDir "src/main/python"
            }
        }
#### Describe your issue
Complete output (42 lines):
   pysam: cython is available - using cythonize if necessary
   pysam: htslib mode is shared
   pysam: HTSLIB_CONFIGURE_OPTIONS=None
   pysam: (env) CC=Chaquopy_cannot_compile_native_code
   pysam: (sysconfig) CFLAGS=-Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g
   pysam: (sysconfig) LDFLAGS=-arch x86_64 -g
  checking for gcc... Chaquopy_cannot_compile_native_code

**_Please Help me here otherwise i can't able to use huggingface any model/ tokenizer._**

**Comment by mhsmith** [comment]
Please post the complete build log, and the `pip` section of your build.gradle file.

**Comment by mhsmith** [comment]
If you're trying to use `transformers`, see https://github.com/chaquo/chaquopy/issues/607#issuecomment-1643676510.
