### ISSUE TITLE
com.chaquo.python.PyException: _MultiThreadedRendezvous:

### ISSUE THREAD

**Issue by pro3k** [chaquo/chaquopy#990]
#### Chaquopy version
id 'com.chaquo.python' version '14.0.2' apply false

#### Devices or emulators where the issue happens
Original Android devices

#### Relevant parts of your code
    # Start client
    def client_fn() -> None: # this will called by server which runs locally in the andiord devices
    trainloader, testloader, model = load_data()

    client = FlowerClient(model, trainloader, testloader)
    print("client fn called from python side")
    fl.client.start_numpy_client(server_address="18.218.5.183:8080", client=client) # same here local address is running

#### Describe your issue
I am trying to train my model using server files from the mentioned server address. I got an error while trying to train my model using chaqopy library in android. 

When I run the file after the first installation of an app it throughs an error:
INFO flower 2023-10-09 14:14:31,160 | connection.py:102 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flower 2023-10-09 14:14:31,163 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flower 2023-10-09 14:14:31,166 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flower 2023-10-09 14:14:31,530 | connection.py:39 | ChannelConnectivity.TRANSIENT_FAILURE
DEBUG flower 2023-10-09 14:14:31,761 | connection.py:121 | gRPC channel closed
com.chaquo.python.PyException: _MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1696841071.528737274","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1696841071.528713890","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>

And then I tried again it throughs an error:
com.chaquo.python.PyException: AttributeError: get_properties

When I redirect to suggested error it spot this line of my code
`**fl.client.start_numpy_client(server_address="18.218.5.183:8080", client=client) # same here local address is running**`

**Comment by mhsmith** [comment]
Does your app have the [INTERNET permission](https://stackoverflow.com/q/2378607)?

**Comment by pro3k** [comment]
Yes, definitely.

**Comment by mhsmith** [comment]
Please post the full stack traces of both the exceptions you mentioned.

**Comment by mhsmith** [comment]
But before you do that, if possible try running the code on a different platform than Android. If it fails in the same way, then the problem has nothing to do with Chaquopy.

**Comment by pro3k** [comment]
I already tried and ran the whole script on Ubuntu and Window and it worked perfectly. After that, I started to create and run on the Android platform.

**Comment by mhsmith** [comment]
OK, then please post the full stack traces of both the exceptions you mentioned.

**Comment by mhsmith** [comment]
If you still need help, please post the requested information, and I'll reopen the issue.
