### ISSUE TITLE
Update compile sdk version?

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#992]
Would it be possible to update the compile sdk version from 30 to 34 in product/buildSrc/src/main/java/com/chaquo/python/internal/Common.java or does that break something?

**Comment by mhsmith** [comment]
It probably wouldn't break anything, but why would you want to do it? Code compiled against an old version will still work on a new version. 

And this setting is only for compiling Chaquopy itself. Each individual app is free to use whatever compileSdkVersion and targetSdkVersion it wants.

**Comment by mhsmith** [comment]
OK, if you create a PR for this, and everything works, I'll be happy to merge it.

You might be interested in #936 as well.

**Comment by sainathkishoremrinc12** [comment]
Update for flutter sdk?? I think it's 14 months ago update for sdk happens

**Comment by IsakTheHacker** [comment]
In what way is flutter related to chaquopy?

**Comment by mhsmith** [comment]
There's an unofficial [Chaquopy plugin for Flutter](https://pub.dev/packages/chaquopy). Unfortunately its author has abandoned it, and I don't have time to take it over myself.

If you're having errors with that plugin related to SDK versions, see https://github.com/jaydangar/chaquopy_flutter/issues/47#issuecomment-1656936687.
