### ISSUE TITLE
Package request: pydantic-core

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#995]
I need the pydantic package for my app which depends on the native pydantic-core package written in Rust. I have tried following [the guide](https://github.com/emanuele-f/chaquopy/blob/cryptography-wheel/README_cryptography_39.md) for building Cryptography version 39 and read this [issue](https://github.com/chaquo/chaquopy/issues/657). It is hard to understand exactly what I need to do to set up Rust support when there is no official documentation. For example, do I need to cross-compile Python as described [here](https://github.com/emanuele-f/chaquopy/blob/cryptography-wheel/README_cryptography_39.md#python-cross-compilation) or is that specific to the Cryptogaphy package?

**Comment by Saeppo** [comment]
This worked for me.

python {
            version 3.8
            pip {
                install "pydantic<2"
            }
 }

**Comment by caarmen** [comment]
> This worked for me.
> 
> python { version 3.8 pip { install "pydantic<2" } }

Would like to be able to use pydantic 2. Some libs seem to require it (ex: ariadne-codegen: https://github.com/mirumee/ariadne-codegen/pull/186 )

**Comment by mhsmith** [comment]
For further discussion of pydantic version 2, see #1017.
